### PR TITLE
[CI][VSTS] Fix needed in ESRP landed in the prod feed so we can use it now.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Failures should be fixed after https://github.com/xamarin/xamarin-macios/pull/10495

**Review by rolfbjarne — APPROVED** [review]

**Comment by mandel-macaque** [comment]
rebase job created but you did nothing @vs-mobiletools-engineering-service2 !!!

**Pull request merged**
