### PR TITLE
[Make.config] Bump for Xcode 9.4 beta 2

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by spouliot** [comment]
The failure makes sense, since `readonly` was added in b2

```diff
-@property (nonatomic, getter=isActive) BOOL active;
+@property (nonatomic, assign, readonly, getter=isActive) BOOL active;
```

**Comment by VincentDondain** [comment]
@spouliot ok can we merge with this failing test? It'll be fixed in my next ClassKit PR.

**Comment by spouliot** [comment]
@VincentDondain yes

**Comment by VincentDondain** [comment]
Ok merging, this will be fixed in next PR, I'll paste a link when it's up.

**Comment by VincentDondain** [comment]
Build issue should be fixed in https://github.com/xamarin/xamarin-macios/pull/4020

**Pull request merged**
