### PR TITLE
Force mac-binding-projec to build non-parallel

### PR DESCRIPTION
**Pull request by chamons**
- Try to fix https://bugzilla.xamarin.com/show_bug.cgi?id=50634
- Unable to reproduce locally
- Increases build time from about 20s to 60s :(

### CODE REVIEW

**Comment by chamons** [comment]
Anyone have a better idea on this? I wrote a shell script to run the make 500 times in a row (with and without a clean in between) and could not reproduce.

**Comment by rolfbjarne** [comment]
This won't do anything, because make is already running in non-parallel mode:

>  		make[5]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.

**Comment by rolfbjarne** [comment]
Ideas:

* Call `ld` directly instead of using `libtool`. Passing -v to libtool gave me this:

    /Applications/Xcode82.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -arch_multiple -arch x86_64 -dylib -dynamic -all_load -force_cpusubtype_ALL -no_arch_warnings -macosx_version_min 10.9 obj/SimpleClass.o -framework Cocoa -lSystem -o bin/SimpleClassDylib.dylib

which I guess should be using `xcrun:

    xcrun ld -arch_multiple -arch x86_64 -dylib -dynamic -all_load -force_cpusubtype_ALL -no_arch_warnings -macosx_version_min 10.9 obj/SimpleClass.o -framework Cocoa -lSystem -o bin/SimpleClassDylib.dylib

* Re-compile the source instead of linking the .o:

    clang -shared ../common/mac/SimpleClass.m -o obj/SimpleClassDylib.dylib -std=gnu99 -mmacosx-version-min=10.9 -framework Cocoa -lSystem

**Comment by chamons** [comment]
Let me try rewriting it to recompile the source idea (different PR).

**Pull request closed without merging**
