### PR TITLE
Update Messaging and HotRestart versions

### PR DESCRIPTION
**Pull request by japarson**
We need to update the `System.Diagnostics.Tracer` package to version `2.1.0-alpha` due to an issue with the `ChecksumAlgorithm` property of older versions.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This looks good. That said, why are you targeting the `xcode14.3` branch? That branch isn't used anymore.

**Comment by japarson** [comment]
> This looks good. That said, why are you targeting the `xcode14.3` branch? That branch isn't used anymore.

We are still using this branch in XamarinVS: https://github.com/xamarin/XamarinVS/blob/main/.ios-external

**Review by rolfbjarne — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by japarson** [comment]
@rolfbjarne Is it safe to merge this PR? I don't think the failing test is related to my change.

**Comment by rolfbjarne** [comment]
@japarson looks good, but I'd like @emaf's approval too

**Review by emaf — APPROVED** [review]

**Comment by dalexsoto** [comment]
@japarson will you also do this in main at some point? Looks like we will need this also in .NET 7 and .NET 8 at some point after discussing with @emaf.

**Pull request merged**
