### PR TITLE
Bump Xcode version to beta 2

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
Don't merge, current results are incorrect as the wrong Xcode version was installed (beta1 in beta2 directory).

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
