### PR TITLE
[ReplayKit] Use protocols instead of models in API.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@spouliot you changed one API to use model instead of protocol here: 6ea6fe47 - do you remember why? It seems strange to me to use models instead of protocols here.

**Comment by spouliot** [comment]
Likely a copy/paste from sharpie as the selector (and API signature) changed and I missed the type/protocol type :(

**Comment by spouliot** [comment]
I think we can get introspection to checks for `[Model]` decorated types in API signatures.

**Comment by spouliot** [comment]
approved for stable (#etl)

**Pull request merged**
