### PR TITLE
[QuickLook] Update based on quicklookui feedback

### PR DESCRIPTION
**Pull request by rachelkang**
Fix things I missed in https://github.com/xamarin/xamarin-macios/pull/12337/files

as per feedback in https://github.com/xamarin/xamarin-macios/pull/12389#discussion_r686081738

### CODE REVIEW

**Review by spouliot — APPROVED** [review]
👍

**Review by stephen-hawley — APPROVED** [review]

**Comment by rachelkang** [comment]
test failure is unrelated https://github.com/xamarin/maccore/issues/2414

**Review by rolfbjarne — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by rachelkang** [comment]
@mandel-macaque could you help me figure out the test failures? in particular, this one seems odd:

[FAIL] GHIssue8342(Unauthorized,"mandel","12345678","","") : Status not ok
Tests run: 2299 Passed: 2282 Inconclusive: 16 Failed: 1 Ignored: 68

**Comment by mandel-macaque** [comment]
@rachelkang that is a network test, I'm merging the PR since is unrelated, I have created issue https://github.com/xamarin/maccore/issues/2493 to track it.

**Comment by rachelkang** [comment]
@mandel-macaque ok, gracias!

**Pull request merged**
