### PR TITLE
[tests][monotouch] More adjustments for iOS10 related failures/changes

### PR DESCRIPTION
**Pull request by spouliot**
- some might be Apple bugs and need to be reverted later

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
