### PR TITLE
[dotnet] Add support for LinkDescription items.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Also use the LinkDescription item group instead of a custom one
(_BundlerXmlDefinitions), since there's no need for the custom one.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
UhoItsB0rken!

**Review by stephen-hawley — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

 * link sdk/iOS Unified 64-bits - simulator/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2379
 * link sdk/iOS Unified 64-bits - simulator/Release [dotnet]: https://github.com/xamarin/maccore/issues/2379
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: https://github.com/xamarin/maccore/issues/2380
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (all optimizations) [dotnet]: https://github.com/xamarin/maccore/issues/2380
 * [xUnit] Mono SystemCoreXunit Part 2/tvOS - simulator/Debug: https://github.com/xamarin/maccore/issues/2384
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): https://github.com/xamarin/maccore/issues/2378

**Pull request merged**
