### PR TITLE
Bump VSMac to 8.1.0.2742 to fix msbuild issues

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@VincentDondain heh thanks. silly typo 😬

**Comment by radical** [comment]
If it does, then great. Else I will be debugging on this PR itself, since I can't reproduce this locally at all!

**Comment by radical** [comment]
The `Test Report` page (https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10329/Test_20Report/):

```
Problem accessing /job/xamarin-macios-pr-builder/10329/Test_20Report/index.html. Reason:

    Not Found
```

@VincentDondain any idea what might be wrong here?

**Comment by rolfbjarne** [comment]
Test failure is unrelated

* Xtro: https://github.com/xamarin/maccore/issues/1742

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-2

**Pull request merged**
