### PR TITLE
[preview.7] Added Hot Restart support into the SDK (#12293)

### PR DESCRIPTION
**Pull request by mauroa**
- Added Hot Restart support for net6
- Added Hot Restart content into the Windows iOS pack

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]
We'll need to make sure we can actually change Preview 7 anymore at this point.

If we are shipping the .NET MAUI workload in Visual Studio, we already have the bits and Preview 7 is closed.

**Review by jonathanpeppers — APPROVED** [review]
I think this was resolved over email.

I'll let @dalexsoto have final decision here, thanks.

**Review by dalexsoto — APPROVED** [review]
Yup, we will try to get this in for P7

**Comment by dalexsoto** [comment]
Known unrelated issue -> https://github.com/xamarin/maccore/issues/2304

**Pull request merged**
