### PR TITLE
[msbuild] Teach _StripAssemblyIL task to support inputs with duplicate file names but different paths

### PR DESCRIPTION
**Pull request by chamons**
- Fixes https://github.com/xamarin/xamarin-macios/issues/13526
- F#, along with some other cases, have files to publish that have the same filename but different folder
- The most obvious example being resources assemblies: cs/FSharp.Core.resources.dll vs de/FSharp.Core.resources.dll
- I naively copied all files into one directory ignoring path, which does not work here at all
- DestinationSubPath seems to be set unconditionally by ResolvePackageAssets but #msbuild suggested not assuming it was always there (https://github.com/dotnet/sdk/blob/0fc72ddb758dd136182972c2aea1d504ea046cfd/src/Tasks/Common/ItemUtilities.cs#L126-L128)
- So use DestinationSubPath when it is around, else fall back to the old Filename + Extension
- Since there are now subdirectories inside stripped folder, extend MakeDir to cover all file's Directory path
- Tested by hand with FSharpiOSCoolApp (.NET), I can extend an auto test if desired

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]
Looks good, would be nice to have the msbuild tests call the failing app or similar in our CI, specially with f# since we have a tendency to forget about it.

**Comment by rolfbjarne** [comment]
> * Tested by hand with FSharpiOSCoolApp (.NET), I can extend an auto test if desired

We already have a test case that runs into this:

https://github.com/xamarin/xamarin-macios/issues/13526#issuecomment-991256782

**Review by rolfbjarne — APPROVED** [review]

**Comment by chamons** [comment]
FYI @emaf - Waiting on XVS review an a clean test run.

**Review by emaf — APPROVED** [review]

**Comment by praeclarum** [comment]
Hi, I'm running into this now with preview 11. I wonder if you can guess at a workaround?

**Comment by chamons** [comment]
Yep, setting EnableAssemblyILStripping will work around  it @praeclarum, or you could patch Xamarin.Shared.Sdk.targets  locally (or try a newer build), but that might get complicated.

**Pull request merged**
