### PR TITLE
[CryptoTokenKit] Bind this framework. Fixes #7876.

### LINKED ISSUE #7876: Support for CryptoTokenKit
Are there any plans when Xamarin.Mac supports the new CryptoTokenKit API. Currently we have to build with Sharpie.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/7876.

### CODE REVIEW

**Comment by dotMorten** [comment]
woah! This is awesome ❤️

**Review by haritha-mohan — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Marking as do-not-merge for now, let's see if we can get #20591 in first so that we can mark CryptoTokenKit as preview API.

**Review by mandel-macaque — COMMENTED** [review]
@rolfbjarne  should we also update: https://github.com/xamarin/xamarin-macios/blob/1ce1d31ade39497f81e0cc92d1228492e631bdac/tests/monotouch-test/ObjCRuntime/EveryFrameworkSmokeTest.cs#L29

**Comment by rolfbjarne** [comment]
> @rolfbjarne should we also update:
> 
> https://github.com/xamarin/xamarin-macios/blob/1ce1d31ade39497f81e0cc92d1228492e631bdac/tests/monotouch-test/ObjCRuntime/EveryFrameworkSmokeTest.cs#L29

The change in NSObject.mac.cs is what needs to be done:

https://github.com/xamarin/xamarin-macios/pull/20587/files#diff-4e3e24f9db24f570d3277c4391153c6591f327e5b016bfff705b085c4df20440R114

**Review by dalexsoto — APPROVED** [review]

**Pull request merged**
