### PR TITLE
Remove the watch-mono repository, and use a single mono repository.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Still keeping some of the logic so that it's easy to switch back if we wish
to.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
MSBuild/iOS tests timed out.

build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
Now it's an actual _build_ failure:

    /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/watchbcl/libtool: line 11629: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/watchbcl/mono/mini/mono: No such file or directory
    /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/watchbcl/libtool: line 11629: exec: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/watchbcl/mono/mini/mono: cannot execute: No such file or directory
    make[11]: *** [../../class/lib/build/mscorlib.dll] Error 126

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
Nice checks (in case we need to re-enable this)

**Comment by rolfbjarne** [comment]
Now it failed due to a jenkins bug (discussed on Slack)

> stderr: error: pathspec 'external/ModernHttpClient' did not match any file(s) known to git.

**Comment by rolfbjarne** [comment]
build

**Pull request merged**
