### PR TITLE
[CI][VSTS] Continue on profiles failure.

### PR DESCRIPTION
**Pull request by mandel-macaque**
We want to continue and generate the pkgs, the failure of this step only
results in failing tests.

fixes: https://github.com/xamarin/maccore/issues/2376

### CODE REVIEW

**Comment by mandel-macaque** [comment]
re-triggering, there is a missbehaving bot.

**Review by spouliot — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Pull request merged**
