### PR TITLE
[Localization] Temporarily Stop OneLocBuild from making PRs

### PR DESCRIPTION
**Pull request by tj-devel709**
The 'isCreatePRSelected' is responsible for creating the PR. 
Turning it to false should stop OneLocBuild from creating PRs.

The only thing I am not sure of and would like to know from reviewers is:
the rest of the inputs are used for creating the PRs. If we are not creating a PR, 
I am not sure if Yaml will complain about these additional unused inputs
```isAutoCompletePrSelected: false
    prSourceBranchPrefix: 'locfiles'
    repoType: gitHub
    gitHubPatVariable: '$(GitHub.Token)'
    packageSourceAuth: patAuth
    patVariable: '$(OneLocBuild--PAT)'

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Please rebase with main to fix the issues.

**Review by mandel-macaque — APPROVED** [review]

**Comment by tj-devel709** [comment]
> Please rebase with main to fix the issues.

Thank you for doing this!

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
yellow dots are due to the outage we had yesterday. Test failures are unrelated. Merging because this is consuming resources in the CI that it should not.

**Pull request merged**
