### PR TITLE
[CI][VSTS] Add trigger for xcode branches.

### PR DESCRIPTION
**Pull request by mandel-macaque**
fixes: https://github.com/xamarin/maccore/issues/2355

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
is there a way to build any PR if it comes from project maintainers and have external contributors PR's built only if we approve? If not, is there an issue filled for that?

**Review by tj-devel709 — APPROVED** [review]

**Comment by mandel-macaque** [comment]
This is something I have talked with mbond, we need to set the triggers better, but might be that VSTS is not considered for this scenario 😞

**Comment by dalexsoto** [comment]
@mandel-macaque can you make an issue so we do not forget? we really need a way to make this work

**Pull request merged**
