### PR TITLE
Unify code for executing processes.

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Create a simple Xamarin.Utils.Execution class that can handle all our
  process execution needs:
    * Captures or streams stdout/stderr (in UTF8).
    * Supports async
    * Supports a timeout
    * Does not depend on any other source file we have, only uses BCL API.
* Have the execution helper classes from mtouch/mmp
  (Xamarin.BundlerDriver.RunCommand) and the tests
  (Xamarin.Tests.ExecutionHelper) use this new class.
* Some simplifications were made:
    * All API that took a string array for the environment now takes a
      Dictionary<string, string>.
    * The Driver.RunCommand methods were split out to a separate file. This
      file also contains a Verbosity field, which is conditioned on not being
      in mtouch nor mmp, which makes including this file from other projects
      simpler (such as bgen - in particular bgen was modified to use this
      Verbosity field instead of its own).

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* [NUnit] Mono Mac OS X BCL tests group 2: https://github.com/xamarin/maccore/issues/2127
* monotouch-test/watchOS 32-bit: https://github.com/xamarin/maccore/issues/581

**Comment by mandel-macaque** [comment]
Ignore device tests failures, look like the testing pipeline picked up this pr.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8848/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8848/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.9'' 🔥

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8848/3//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8848/3//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.157.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/xamarin.ios-13.21.1.157.pkg)
* [xamarin.mac-6.21.1.157.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/xamarin.mac-6.21.1.157.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8848.157+sha.e45dfcbbd.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8848.196+sha.e45dfcbbd.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/jenkins-results/apicomparison/api-diff.html) (no change)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-8848/3/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8848/e45dfcbbdc92fb3cd31fb0f3e59da5b6a3030fd3/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 183 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
</details>

**Comment by rolfbjarne** [comment]
Test failure are unrelated

* monotouch-test: https://github.com/xamarin/maccore/issues/1265
* macOS 10.9: https://github.com/xamarin/maccore/issues/2221

**Pull request merged**
