### PR TITLE
[msbuild] Don't replace * by bundle id in entitlements (#1147)

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes bug #46298: Xamarin seems to replace asterisk with bundle id in Entitlements.plist file
  https://bugzilla.xamarin.com/show_bug.cgi?id=46298

The CompileEntitlementsTaskBase logic is still good wrt TeamIdentifierPrefix, AppIdentifierPrefix and CFBundleIdentifier
replacements but asterisks that represent wildcards shouldn't be replaced. Note that Apple doesn't do it in Xcode either.

* [msbuild/test] Add CompileEntitlementsTaskTests

Makes sure that for a given Entitlement.xcent and provisioning profile in input and output the right thing.

These tests also cover the changes made in https://github.com/xamarin/xamarin-macios/pull/1147/commits/e32efb0310c44f9dc15fc8fae71d269971bbb668
in response to bug #46298 (https://bugzilla.xamarin.com/show_bug.cgi?id=46298).

### CODE REVIEW

**Comment by rolfbjarne** [comment]
It looks like your changes doesn't build:

> TaskTests/CompileEntitlementsTaskTests.cs(10,38): error CS0115: `Xamarin.iOS.Tasks.CustomCompileEntitlements.GetMobileProvision(Xamarin.MacDev.MobileProvisionPlatform, string)' is marked as an override but no suitable method found to override

**Comment by jstedfast** [comment]
I don't think this is correct. At least *some* values need to have the `*` replaced by the bundle id, but based on the bug report, it is clear that we can't just blindly do that substitution.

**Comment by VincentDondain** [comment]
I haven't seen Xcode replace any `*` value, when the bundle id is need it's written explicitly.

**Comment by jstedfast** [comment]
It seems that over time, Xcode has phased out the use of `*` to mean "replace this value with the bundle identifier" (which it used to mean originally). This might be because they found a need to use an actual wildcard character as the feature set has expanded. I *have* noticed that Xcode has gotten more explicit in its use of variables such as `$(TeamIdentifierPrefix)` and `$(IdentifierPrefix)`, so this seems at least plausible to me.

**Pull request merged**
