### PR TITLE
Try to fix build of PR #31

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
That solved the build issue.

There's one breaking change in the API:

    Type Changed: System.Net.Http.NSUrlSessionHandler

    Removed property:

    	public bool DisableCaching { get; set; }

and it seems that the properties from `HttpCLientEx.cs` (with a `partial` type for `NSUrlSessionHandler`)

* `AllowAutoRedirect` and
* `Credentials`

are no longer honoured, so they will be broken as the PR currently stands.

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@nberardi QA tests failed as the new implementation hangs while running one of our sample: https://github.com/xamarin/monotouch-samples/tree/master/HttpClient

I'll have a look again later, but we're busy with WWDC/Xcode8 right now - in case you want to see what's going :)

**Comment by nberardi** [comment]
@spouliot I will have a look.  Can I have access to the test procedures or script so that I can run in the same way the automated tests run?

**Comment by nberardi** [comment]
I have been able to reproduce the hang on the HTTPS request.  Is that what you are also seeing?

**Comment by nberardi** [comment]
@spouliot I merged this with PR #31 if you want to close in favor of the original PR.

**Comment by mandel-macaque** [comment]
Closing this as https://github.com/xamarin/xamarin-macios/pull/932 landed with the same changes and extra fixes :)

**Pull request closed without merging**
