### PR TITLE
Import tests.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Tests are running here: https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-tests-import

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
That last file was already added for another project, `tests/introspection/EnvironmentVariable.cs`
It might not be the best location, but it should be inside the `tests` directory

**Comment by spouliot** [comment]
It looks like some failures (e.g. link sdk) are due to using the _just copied_ tests and not the versions already moved in `xamarin-macios`.

**Comment by rolfbjarne** [comment]
I've removed the duplicated `EnvironmentVariable.cs` file now.

linksdk build failure was a missing file (.dll, so `git add` didn't add it by default).

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
