### PR TITLE
[msbuild] Fixed Condition for CalculateCodesignAppBundleInputs

### PR DESCRIPTION
**Pull request by jstedfast**
CodesignAppBundle was not being executed because the inputs were empty.

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59379

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Lots of test failures like this:

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets: error : Error executing task EmbedMobileProvision: Required property 'ProvisioningProfile' not set.

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
The monotouch-test/tvOS simulator test crashes with:

> Exception Type:        EXC_CRASH (Code Signature Invalid)

and did for two builds (I've never seen this crash before).

This suggests the problem is with the PR (since the PR also changes signing-related code).

**Comment by jstedfast** [comment]
Thanks Rolf, I'll try to dig into this.

**Comment by jstedfast** [comment]
build

**Comment by jstedfast** [comment]
@rolfbjarne Looks like the failures are now in some bindings and not msbuild related. Can you confirm my reading of the failures?

**Comment by rolfbjarne** [comment]
build

**Comment by jstedfast** [comment]
Test Result (36 failures / +36)KeyChainTest.Add_CertificateKeyChainTest.AddQueryRemove_IdentityKeyChainTest.CheckIdKeyChainTest.SecItemAdd_IdentityKeyChainTest.Add_CertificateKeyChainTest.AddQueryRemove_IdentityKeyChainTest.CheckIdKeyChainTest.SecItemAdd_IdentityKeyChainTest.Add_CertificateKeyChainTest.AddQueryRemove_IdentityShow all failed tests >>>
--

**Comment by rolfbjarne** [comment]
@jstedfast those test failures are real, and were introduced in this PR.

**Comment by rolfbjarne** [comment]
Reverting in PR #2944.

**Comment by rolfbjarne** [comment]
It seems monotouch-test is signed now, which might be causing those failures.

**Pull request merged**
