### PR TITLE
[system-dependencies] Add support for installing the expected CoreSimulator.framework version.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This works around FB6149048: "Xcode 11 beta 1 breaks older simulators in Xcode 10.2."

Ref: https://trello.com/c/bqkONZFo/142-fb6149048-xcode-11-beta-1-breaks-older-simulators-in-xcode-102

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.10', Running XM tests on '10.10', Running XM tests on '10.11', Running XM tests on '10.13', Running XM tests on '10.9', Running XM tests on '10.9'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6275/1//console)
✅ Packages: [xamarin.ios-12.15.0.222.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6275/d4f5886396451a418efc15e7c6e35e9f9d06c40c/1/package/xamarin.ios-12.15.0.222.pkg) [xamarin.mac-5.15.0.222.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6275/d4f5886396451a418efc15e7c6e35e9f9d06c40c/1/package/xamarin.mac-5.15.0.222.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6275/d4f5886396451a418efc15e7c6e35e9f9d06c40c/1/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-6275/1//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at d4f58863
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 1.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 2.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 3.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 4.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 6.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/generated/
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib.csproj
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-6275/1/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6275/d4f5886396451a418efc15e7c6e35e9f9d06c40c/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 166 tests passed.</summary>

## Failed tests

 * apitest/Mac Classic/NonSystem: BuildFailure
 * dont link/Mac Classic/All: BuildFailure
 * introspection/Mac Classic/Modern: BuildFailure
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
 * MSBuild tests/iOS: Failed (Execution failed with exit code 1)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6275/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6275/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6275/2//console)
✅ Packages: [xamarin.ios-12.15.0.226.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6275/a0c93c9b1cb0a101be836b7631e1c48bb5a68f3d/2/package/xamarin.ios-12.15.0.226.pkg) [xamarin.mac-5.15.0.226.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6275/a0c93c9b1cb0a101be836b7631e1c48bb5a68f3d/2/package/xamarin.mac-5.15.0.226.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6275/a0c93c9b1cb0a101be836b7631e1c48bb5a68f3d/2/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-6275/2//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at a0c93c9b
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 1.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 2.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 3.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 4.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 6.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/generated/
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib.csproj
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6275/a0c93c9b1cb0a101be836b7631e1c48bb5a68f3d/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>6 tests failed, 165 tests passed.</summary>

## Failed tests

 * apitest/Mac Classic/NonSystem: BuildFailure
 * dont link/Mac Classic/All: BuildFailure
 * introspection/Mac Classic/Modern: BuildFailure
 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
 * MSBuild tests/iOS: Failed (Execution failed with exit code 1)
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* \*/Mac Classic/\*: https://github.com/mono/mono/issues/14875
* MSBuild tests/iOS: https://github.com/mono/mono/issues/14876
* monotouch-test/watchOS 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/581
* introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): https://github.com/xamarin/maccore/issues/581

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-2

**Pull request merged**
