### PR TITLE
[msbuild] Always codesign libraries and frameworks

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes issue #3289

### CODE REVIEW

**Comment by spouliot** [comment]
@jstedfast It's **very** late to request a backport so it needs justifications (impact) to decide to move forward (or not). c.c. @rolfbjarne

**Comment by rolfbjarne** [comment]
@spouliot I thought this would affect device builds as well (Gouri says it happens in both simulator and on device), but I can only reproduce it in the simulator, which makes it much less serious.

Also there's a fairly simple workaround: add `--mono=static` to the additional mtouch arguments in all projects' (both executable and extensions) additional mtouch arguments (this workaround would not be ideal for device builds, since the app size would grow significantly, but for the simulator it doesn't matter), so in the end I don't think this is needed for d15-6, given how late it is (but it might be nice to get it fixed in a service release).

**Comment by jstedfast** [comment]
It shouldn't affect device builds because device builds always required a CodeSigningKey whereas for Simulator, it didn't.

**Comment by mohakbarokar** [comment]
Hi @jstedfast;

Th build provided for this PR is failed. Can you please provide a new build?

**Comment by rolfbjarne** [comment]
@mohakbarokar the build succeeded, it was the tests that failed (the reporting is broken though).

**Comment by mohakbarokar** [comment]
This PR is tested on Build : https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5920&host_id=392&revision_id=927710

& the breakpoint is hitting for TvServiceExtension.

Screencast Link: http://www.screencast.com/t/diqDm05DB6s

Observation: Breakpoint again points to same line number even after the execution is continued

We can merge the PR for this fix

**Comment by spouliot** [comment]
Clearing milestone (as per discussions above). It does not affect devices and there's a workaround for simulators. If needed we'll revise for SR.

**Comment by GLjackyvaswani** [comment]
Can you please provide a new build to test the above PR.

**Comment by spouliot** [comment]
Too late/risk to change msbuild stuff for 15.6
We'll re-evaluate for a service release

**Comment by spouliot** [comment]
re-opened for SR1

**Comment by parasAmbhore** [comment]
I have tested this issue on build info : https://gist.github.com/parasAmbhore/4b1d903e98e4ca361248728e58e268c7
and issue is not reproducible here.
The issue is Resolved - Fix Tested now, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/578197

The Screen-recording and IDE logs are attached on the work-item 
This PR is approved

**Pull request merged**
