### PR TITLE
bump maccore for classic deprecation

### PR DESCRIPTION
**Pull request by joelmartinez**
The changes from https://github.com/xamarin/maccore/pull/650

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This is building on [wrench](https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5958&host_id=392&revision_id=930062) too, so `do-not-merge` until results are back from wrench.

**Comment by dalexsoto** [comment]
It seems it failed :/

[7:50:36] Time Elapsed 00:00:13.3166980
[7:50:36] Making all in docfixer-ios
[7:50:36] make[6]: *** No rule to make target `Xamarin.iOS.dll', needed by `docfixer.exe'.  Stop.
[7:50:36] make[6]: *** Waiting for unfinished jobs....

**Comment by joelmartinez** [comment]
Hmm, that target was removed in another recent commit on that makefile by someone else. I guess it probably just needs to be re-added

**Comment by rolfbjarne** [comment]
Wrench built fine now, so this looks good.

I'll wait for wrench to complete (tests are still executing) until merging, just in case.

**Comment by rolfbjarne** [comment]
@joelmartinez the `test-docs` step on wrench fails with:

```
mono --debug document-generated-code.exe temp.dll ../../../xamarin-macios/../ios-api-docs
-> core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null <-
-> mscorlib <-
here
-> monotouch.BindingAttributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null <-
WHAT
Failed

Unhandled Exception:
System.IO.FileNotFoundException: monotouch.BindingAttributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  at IKVM.Reflection.Universe.Load (System.String refname, IKVM.Reflection.Module requestingModule, System.Boolean throwOnError) [0x000fa] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Universe.cs:759 
  at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl (IKVM.Reflection.Metadata.AssemblyRefTable+Record& rec) [0x0009f] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Reader/ModuleReader.cs:594 
  at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef (System.Int32 index) [0x0004b] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Reader/ModuleReader.cs:577 
  at IKVM.Reflection.Reader.ModuleReader.ResolveType (System.Int32 metadataToken, IKVM.Reflection.IGenericContext context) [0x000e9] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Reader/ModuleReader.cs:460 
  at IKVM.Reflection.Module.ResolveType (System.Int32 metadataToken, IKVM.Reflection.Type[] genericTypeArguments, IKVM.Reflection.Type[] genericMethodArguments) [0x00025] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Module.cs:459 
  at IKVM.Reflection.Module.ResolveType (System.Int32 metadataToken) [0x00005] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Module.cs:426 
  at IKVM.Reflection.Reader.ModuleReader.GetMemberRef (System.Int32 index, IKVM.Reflection.Type[] genericTypeArguments, IKVM.Reflection.Type[] genericMethodArguments) [0x00107] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Reader/ModuleReader.cs:865 
  at IKVM.Reflection.Reader.ModuleReader.ResolveMethod (System.Int32 metadataToken, IKVM.Reflection.Type[] genericTypeArguments, IKVM.Reflection.Type[] genericMethodArguments) [0x00066] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Reader/ModuleReader.cs:769 
  at IKVM.Reflection.Module.ResolveMethod (System.Int32 metadataToken) [0x00005] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/Module.cs:467 
  at IKVM.Reflection.CustomAttributeData.get_Constructor () [0x0003a] in /Users/builder/data/lanes/5958/cf893e37/source/xamarin-macios/external/mono/external/ikvm/reflect/CustomAttributeData.cs:576 
  at Attributes+<HasAttribute>c__AnonStorey1.<>m__0 (IKVM.Reflection.CustomAttributeData x) [0x00001] in /Users/builder/data/lanes/5958/cf893e37/source/maccore/tools/docfixer/document-generated-code.cs:1194 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/AnyAll.cs:38 
  at Attributes.HasAttribute (System.Collections.Generic.IList`1[T] attrs, System.String name) [0x0001b] in /Users/builder/data/lanes/5958/cf893e37/source/maccore/tools/docfixer/document-generated-code.cs:1194 
  at DocumentGeneratedCode.Main (System.String[] args) [0x001cb] in /Users/builder/data/lanes/5958/cf893e37/source/maccore/tools/docfixer/document-generated-code.cs:998 
```

it looks like something is still looking for Classic binaries.

**Comment by joelmartinez** [comment]
@rolfbjarne ok, let me take a look at what DGC is doing, to see why it might be looking for that attribute/file

**Comment by joelmartinez** [comment]
Hmm, well, it seems like `temp.dll` has a reference to that which IKVM then attempts to resolve ... so next step is to figure out what `temp.dll` is ...

**Comment by joelmartinez** [comment]
```temp.dll: $(MACIOS_BINARIES_PATH)/ios-compat-temp.dll
	cp $< $@```

@rolfbjarne looks like `temp.dll` **is** `ios-compat-temp.dll`. I'm digging further, but do you have any insight into what these assemblies are for?

**Comment by rolfbjarne** [comment]
@joelmartinez IIRC they're used to get the API to generate documentation stubs for. Can you try this and see if it works: https://gist.github.com/rolfbjarne/1d08203bb1bcd35c97439848f71570d5?

**Comment by joelmartinez** [comment]
It _seems_ like the jenkins build failure might be unrelated?

```
Build step 'Publish xUnit test result report' changed build result to FAILURE
```
And towards the end of the CI's console output:
```
29428 tests run, 672 skipped, 9 failed.'
```

**Comment by joelmartinez** [comment]
@rolfbjarne any indication if this build failure is caused by these docs changes specifically, or whether it's an unrelated build failure with the unit tests? Does wrench have any other clues as to the cause (there's no link to the build from here)?

**Comment by joelmartinez** [comment]
ahh, great news! thanks for your help in getting this PR through @rolfbjarne! 🎉

**Pull request merged**
