### PR TITLE
[introspection] Update according to changes that seem to have occurred in macOS 10.15.2.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7567/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7567/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.15', Running XM tests on '10.15'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7567/2//console)
✅ Packages: 
* [xamarin.ios-13.15.0.117.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/package/xamarin.ios-13.15.0.117.pkg)
* [xamarin.mac-6.15.0.117.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/package/xamarin.mac-6.15.0.117.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.15 failed: Xamarin.Mac tests on macOS 10.15 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-7567/2/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-7567/8d2c0f659d4ed61d049955a30e928e6d2f9674a0/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>7 tests failed, 157 tests passed.</summary>

## Failed tests

 * [NUnit] Mono BCL tests group 1/iOS Unified 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono BCL tests group 2/iOS Unified 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono BCL tests group 3/iOS Unified 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono BCL tests group 4/iOS Unified 32-bits - simulator/Debug: Crashed
 * mscorlib/iOS Unified 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono BCL tests group 6/iOS Unified 32-bits - simulator/Debug: Crashed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* macOS 10.15/xammac tests: Fixed in #7546.
 * [NUnit] Mono BCL tests group 1/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * [NUnit] Mono BCL tests group 2/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * [xUnit] Mono BCL tests group 3/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * [xUnit] Mono BCL tests group 4/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * mscorlib/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * [xUnit] Mono BCL tests group 6/iOS Unified 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/2085
 * monotouch-test/watchOS 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/581

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-5

**Comment by spouliot** [comment]
@monojenkins backport xcode11.3

**Pull request merged**
