### PR TITLE
[makefile] Fix 'buildinfo' branch name on jenkins

### LINKED ISSUE #4674: [Makefile] Incorrect 'HEAD' word used as branch for xcode10 pkg
Our packages from the xcode10 branch have an incorrect "branch" when looking at the version information from VSMac.

See:

```
Xamarin.iOS
Version: 11.99.3.243 (Visual Studio Enterprise)
Hash: 347f472b0
Branch: HEAD
Build date: 2018-08-21 04:53:44-0400
```

This comes from that code: https://github.com/xamarin/xamarin-macios/blob/5995833903a99a310803cd64a505c5464e42c09e/Makefile#L54-L58

### PR DESCRIPTION
**Pull request by VincentDondain**
- Jenkins knows the branch name $(BRANCH_NAME) which Wrench didn't.
- Fixes #4674: [Makefile] Incorrect 'HEAD' word used as branch for xcode10 pkg.
  (https://github.com/xamarin/xamarin-macios/issues/4674)

### CODE REVIEW

**Comment by ekene90** [comment]
Earn

**Comment by rolfbjarne** [comment]
Test failures are due to https://github.com/xamarin/maccore/issues/961, merging with origin that contains potential fix to see if it's really fixed (and also get a build with a package, to verify this fix).

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4703/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4703/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4703/43ad626cd87d5738cc25ef6db27a9565903537f5/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4703/43ad626cd87d5738cc25ef6db27a9565903537f5/2/jenkins-results/apicomparison/index.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4703/43ad626cd87d5738cc25ef6db27a9565903537f5/2/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
This looks good:

```shell
$ mtouch --version
mtouch 11.99.3.551 (PR-4703: 43ad626c)

$ mmp --version
mmp 4.99.3.671 (PR-4703: 43ad626c)
```

**Pull request merged**
