### PR TITLE
[net][coregraphics] Match native strings representation for structs

### PR DESCRIPTION
**Pull request by spouliot**
* Use the native `NSStringFrom*` API so we can, eventually, use the
native code to parse them from `NSString` and also ensure increased
compatibility with any code that expects the native string representation

* Add unit tests for `ToString` methods

Also use [`System.HashCode`](https://docs.microsoft.com/en-us/dotnet/api/system.hashcode?view=net-6.0) to generate the hash code

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
xtro says:

    ?unknown-entry? !missing-pinvoke! NSStringFromCGAffineTransform is not bound in '/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromCGPoint is not bound in '/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromCGRect is not bound in '/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromCGSize is not bound in '/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromPoint is not bound in 'macOS-Foundation.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromRect is not bound in 'macOS-Foundation.ignore'
    ?unknown-entry? !missing-pinvoke! NSStringFromSize is not bound in 'macOS-Foundation.ignore'
    Sanity check failed (7)
    make[2]: *** [.stamp-dotnet-classify] Error 7

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Red tests are unrelated:

* monotouch-test/Mac [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2197
* monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2443

**Pull request merged**
