### PR TITLE
[ShazamKit] Update bindings for Xcode 14.0 beta 1&2&3&4

### PR DESCRIPTION
**Pull request by tj-devel709**

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Sim installer failed like never before. Lets re-run the tests.

**Comment by tj-devel709** [comment]
image
Xtro passes locally. Will update branch and run tests here again

**Comment by tj-devel709** [comment]
Intro Failures unrelated in regards to WebKit

**Pull request merged**
