### PR TITLE
Merge d15-8 into xcode 10

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by VincentDondain** [comment]
Lol this PR cracked up. The real comments start from this one (:

**Comment by VincentDondain** [comment]
Added `do-not-merge` as things might break (still rebuilding the world locally) but it can already be reviewed.

**Comment by VincentDondain** [comment]
https://gist.github.com/VincentDondain/e63fce9dca2efaa1803c772d9298b73c when doing a `make` in `external/mono/sdks`. The 32 bit bits need to be built using Xcode 9.4.

**Comment by VincentDondain** [comment]
Blocked by https://github.com/mono/mono/issues/10100

**Comment by rolfbjarne** [comment]
This PR should not be squashed, only merged (otherwise any future blame will blame Vincent for any modified lines 😄)

**Comment by VincentDondain** [comment]
Ok so it seems a bunch of tests are failing because we cannot build 32 bit projects? https://gist.github.com/VincentDondain/e0fe885cfaad33d6b6090eab18967972

^ That's when building `msbuild/tests/MyWatch2Container/MyWatch2Container.sln` for Device|Release.

**Comment by VincentDondain** [comment]
The rest of the tests are failing because of some issues with MonoTouch.Dialog (can't repro locally).

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
* watchOS/LLVM tests are failing because mono's 2018-02 branch doesn't have the fix for https://github.com/mono/mono/issues/9318
* All tvOS tests failed due to some issue trying to find MonoTouch.Dialog-1 sources (still diagnosing this one)
* A mmp test (Xamarin.MMP.Tests.RegistrarTests.SmokeTest) is failing due to trying to compile a 32-bit executable.
* System.Xml.Linq/Mac/Full fails to compile due to a namespace conflict (new framework/namespace in xcode10).

**Comment by rolfbjarne** [comment]
Test failure is a known issue: https://github.com/xamarin/maccore/issues/951

**Pull request merged**
