### PR TITLE
Bump [watch-]mono to get more API removal for watchOS.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by spouliot** [comment]
LGTM but I think it also needs (it can be a separate PR) adjustments in `src/ObjCRuntime/RuntimeOptions.cs` which, right now, seems to use `MONOTOUCH_WATCH` (which is unlike other files) and could be further simplified now

**Comment by rolfbjarne** [comment]
`src/ObjCRuntime/RuntimeOptions.cs` uses `MONOTOUCH_WATCH` because it's compiled into System.Net.Http.dll, which uses the defines from the mono repository (which in this case is `MONOTOUCH_WATCH`).

OTOH I guess the whole class is redundant for watchOS though, since there's never more than one valid value for any of the options it controls.

**Comment by spouliot** [comment]
ok, that can (and should) be optimized in a future PR

**Comment by rolfbjarne** [comment]
@spouliot there's only one failure now, the one about ServicePointManager I mentioned on Slack:

> [FAIL] HttpClientHandlerTest.NSUrlSession : System.PlatformNotSupportedException : System.Net.ServicePointManager is not supported on the current platform.

**Comment by spouliot** [comment]
@rolfbjarne great, so we're one (mono) bump away form a green build :)

**Pull request merged**
