### PR TITLE
[d16-1][xharness] Multiple cherry picks to make device tests green

### PR DESCRIPTION
**Pull request by VincentDondain**
This PR contains backport and new fixes that only affect the tests (no logic changed).
Sometimes https://github.com/xamarin/xamarin-macios/issues/4723 is hit (random).
Backporting fixes to an old mono branch wasn't possible so a couple mono tests were completely skipped, note: they are fixed in master.

### CODE REVIEW

**Comment by VincentDondain** [comment]
Various device tests were reported in this PR but you can also monitor: https://github.com/xamarin/xamarin-macios/commits/d16-1-xharness-cherry-picks

**Comment by mandel-macaque** [comment]
@VincentDondain failures look like we might missing some ignores, or that the tests are diff since I think @akoeplinger did some fixes on the mono side.

**Comment by VincentDondain** [comment]
@mandel-macaque just 1 failure now and it's one I never saw (random): http://xamarin-storage/jenkins/xamarin-macios/d16-1-xharness-cherry-picks/c4e3bbfa52de73f6495dd7105d33d3f80e987bc3/2643030/device-tests/jenkins-results/tests/index.html

**Comment by VincentDondain** [comment]
Looks like we don't yet have a fix for the 1 remaining device issue: https://github.com/xamarin/maccore/issues/1010 so this PR seems good to go! (:

**Pull request merged**
