### PR TITLE
[Tests] Fix cecil tests ensuring that missing MarshalAs is present.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Added the marshaling attr and a test to ensure it is ok.

fixes: https://github.com/xamarin/maccore/issues/2519

### CODE REVIEW

**Comment by chamons** [comment]
UniChar is documented return value - https://developer.apple.com/documentation/corefoundation/1542730-cfstringgetcharacteratindex?language=objc

UniChar is typedef'ed as unsigned short - https://developer.apple.com/documentation/foundation/unichar?language=objc

**Review by chamons — APPROVED** [review]
Approved, but given the possibility of MarshalAs ruining our day I'd like @rolfbjarne review at least after landing if nothing else.

**Review by rolfbjarne — APPROVED** [review]
I fixed the test, and found more issues, and fixed those as well. So I guess I'm mostly approving my own code here 😁

**Comment by mandel-macaque** [comment]
Unrelated failure: https://github.com/xamarin/maccore/issues/2521

**Pull request merged**
