### PR TITLE
[mmp] Fix symbol name for 32-bit Objective-C classes. Fixes #58861.

### PR DESCRIPTION
**Pull request by rolfbjarne**
https://bugzilla.xamarin.com/show_bug.cgi?id=58861

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
@chamons I've added a test now.

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
@rolfbjarne @chamons please check why `Xamarin.MMP.Tests.MMPTests.Unified_WithStaticNativeRef_32bit` failed, thanks!

**Comment by chamons** [comment]
@rolfbjarne changed tests/mac-binding-project/Makefile so it is likely not an intermittent failure.

**Comment by rolfbjarne** [comment]
Test failure is unrelated (xammac test failure due to bug #[58394](https://bugzilla.xamarin.com/show_bug.cgi?id=58394)).

**Pull request merged**
