### PR TITLE
Rename any *OSX_SDK_VERSION variables to *MACOS_SDK_VERSION.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This makes it easier to iterate over all the *_SDK_VERSION variables in
template code, because they're all named using the standard platform names we
use elsewhere.

### CODE REVIEW

**Review by chamons — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2414).

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2414).

**Pull request merged**
