### PR TITLE
[msbuild] Implemented GetFiles and GetFullPath tasks to fix the vs build

### PR DESCRIPTION
**Pull request by jstedfast**
Hopefully fixes https://bugzilla.xamarin.com/show_bug.cgi?id=53410

### CODE REVIEW

**Comment by emaf** [comment]
I think using %(FullPath) could still be an issue (here https://github.com/xamarin/xamarin-macios/blob/8003e41291aa8cf81138dffadacdcaeb559505cc/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets#L389)

And I'm not sure if it's safe to use %(Directory) (here https://github.com/xamarin/xamarin-macios/blob/8003e41291aa8cf81138dffadacdcaeb559505cc/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets#L385)

@kzu can you confirm? ^

Anyway, the changes look good to me

**Comment by josegallardo** [comment]
We need a Wrench lane from https://github.com/xamarin/xamarin-macios/tree/msbuild-vs-fixes to get a bundle, and be able to bump XVS to this `msbuild-vs-fixes` branch.
That way we can add additional fixes if needed into either `XamarinVS` or `xamarin-macios`.

I've created already a `iosbuild-53410` branch on `XamarinVS` and pointed to the tip of this branch.
Once we have a bundle I'll setup a lane and get a build for verification.

**Comment by rolfbjarne** [comment]
@josegallardo Wrench lane: https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-msbuild-vs-fixes

**Comment by kzu** [comment]
Indeed, the two places @emaf mentioned won't work.  %(Directory) in particular won't work on Windows either, since it's lacking the %(RootDir) so it won't clean up anything. The paths need to be relative in order to be properly removed on Windows *and* Mac appropriately from MSBuild on Windows.

**Comment by jstedfast** [comment]
I'm working on a GetDirectories task to solve the %(Directory) usage and clean up that mess of XML that all it really does is get a list of *.dSYM dirs.

**Comment by jstedfast** [comment]
Okay, there are now no %(FullPath) or %(Directory) usages anywhere.

**Pull request merged**
