### PR TITLE
[DON'T MERGE]: Martin CI Testing

### PR DESCRIPTION
**Pull request by baulig**
This is to test the `System.Net.Http` from CoreFX on iOS and xammac.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-7279/1//console) 🔥

**Comment by baulig** [comment]
It fully built locally this time, let's see how it's doing on CI.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#3)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-7279/3//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/4//console)
    ⚠️ Mono built from source

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/5/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/5/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/5//console)
    ⚠️ Mono built from source

**Comment by mandel-macaque** [comment]
build

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/6/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/6/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/6//console)
    ⚠️ Mono built from source

**Comment by baulig** [comment]
Okay, we're slowly making progress here ....

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/7/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/7/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/7//console)
    ⚠️ Mono built from source

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/8/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/8/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/8//console)
    ⚠️ Mono built from source

**Comment by baulig** [comment]
I'll squash this into a nicer PR with some decent commit message and stuff.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7279/10/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7279/10/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-7279/10//console)
🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-7279/10//console) 🔥

**Comment by baulig** [comment]
I'm going to close this because a new PR will be up shortly with some new writeup, I'm currently writing the commit message.

**Pull request closed without merging**
