### PR TITLE
Remove the Visual Studio dependency.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Remove our dependency on Visual Studio. Use the 'dotnet-t4' tool instead of
invoking the t4 tool embedded in Visual Studio.

Fixes this build error after installing VS Mac 2022:

> Cannot open assembly '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe': No such file or directory.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by spouliot** [comment]
nice! that makes another process uses arm64 on apple silicon Macs 😄

**Review by tj-devel709 — APPROVED** [review]

**Pull request merged**
