### PR TITLE
[d16-0] Bump Xamarin.MacDev to get fix for #5277.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Commit list for xamarin/Xamarin.MacDev:

* xamarin/Xamarin.MacDev@44e90a2 Keys in property list dictionaries aren't necessarily unique. Fixes xamarin-macios#5277. (#39) (#41)
* xamarin/Xamarin.MacDev@c81c625 Get rid of spurious <ItemGroup>
* xamarin/Xamarin.MacDev@d1d3fa4 Remove packagerefs. Leads to unintended problems (see discussion https://github.com/xamarin/md-addins/pull/3946) (#38)

Diff: https://github.com/xamarin/Xamarin.MacDev/compare/179f7201bd719a54f16ff5d359da9879ccef1405...44e90a202c1bb5b6d8b4f30f8b06091545faa145

Fixes https://github.com/xamarin/xamarin-macios/issues/5277.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5284/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5284/1//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/1/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/1/jenkins-results/apicomparison/api-diff.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 0 tests skipped, 282 tests passed.</summary>

## Failed tests

 * MSBuild tests/iOS: Failed (Execution failed with exit code 24)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 6)
</details>

**Comment by rolfbjarne** [comment]
Test failures were due to https://github.com/xamarin/xamarin-macios/issues/5277#issuecomment-448162023. I've fixed the bots according to the workaround, and re-scheduled a build.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5284/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5284/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5284/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/2/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/2/jenkins-results/apicomparison/api-diff.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/2/jenkins-results/generator-diff/index.html) (no change)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5284/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5284/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-5284/3//console) 🔥

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5284/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5284/4//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/4/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/4/jenkins-results/apicomparison/api-diff.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/4/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5284/3d97aa5d1da01dc1348f23d1cdaf1e0874ad21a8/4/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 0 tests skipped, 282 tests passed.</summary>

## Failed tests

 * [NUnit] Mono MonoParallelTests/watchOS - simulator/Debug: Crashed
 * MSBuild tests/iOS: Failed (Execution failed with exit code 2)
</details>

**Comment by rolfbjarne** [comment]
Test failures are known issues:

* MonoParallelTests/watchOS: https://github.com/xamarin/maccore/issues/581
* MSBuild tests/iOS: https://github.com/xamarin/xamarin-macios/issues/5252

**Pull request merged**
