### PR TITLE
[msbuild] Fixed msbuild logic to properly codesign watchos2 intents e…

### PR DESCRIPTION
**Pull request by jstedfast**
…xtensions

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55316

### CODE REVIEW

**Comment by jstedfast** [comment]
Build

**Comment by jstedfast** [comment]
The tvOS simulator test keeps failing, but not sure why.

**Comment by spouliot** [comment]
The first time it was watchOS/fsharp [1], not tvOS [2]. If it's a known issue, that did not stop the tests from running, you just have to mention the bug report in the PR (or file one for a new, unrelated issue).

[1] https://jenkins.mono-project.com/view/Xamarin.MaciOS/job/xamarin-macios-pr-builder/3571/Test_Report/
[2] https://bugzilla.xamarin.com/show_bug.cgi?id=52538

**Comment by jstedfast** [comment]
@spouliot d'oh, yea, sorry - watchos/fsharp test first, tvos second.

**Pull request merged**
