### PR TITLE
[msbuild] Only use File.GetLastWriteTimeUtc

### PR DESCRIPTION
**Pull request by VincentDondain**
Instead of just using File.GetLastWriteTime.
Fixes bug #51694: Use File.GetLastWriteTimeUtc not File.GetLastWriteTime
https://bugzilla.xamarin.com/show_bug.cgi?id=51694

### CODE REVIEW

**Comment by jstedfast** [comment]
LGTM 👍

**Comment by VincentDondain** [comment]
Seems a test needs to be fixed.

**Comment by VincentDondain** [comment]
@spouliot this is iOS/Mac actually

**Comment by jstedfast** [comment]
The UnpackLibraryResources bug fix should fix the failing test.

👍

**Comment by VincentDondain** [comment]
Yea works locally now, thanks @jstedfast for the troubleshooting help!

**Comment by VincentDondain** [comment]
Unrelated build failure (MT1008), added here: https://bugzilla.xamarin.com/show_bug.cgi?id=50419

**Pull request merged**
