### PR TITLE
[Maccore] Bump to pick CI fixes.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Commits:

* Remove Vincent as a code owner https://github.com/xamarin/maccore/commit/87e165fdbb207bc8a0eb46a8e9abb83ec058bb07
* [CI][VSTS] Add information when the external tool fails. https://github.com/xamarin/maccore/commit/0dfeb85ff607f6d0bb4063de4f4b91c4161b8e55

Full diff: https://github.com/xamarin/maccore/compare/55a700bb5ba3c092f511075d479d82ecb10fa5fe..0dfeb85ff607f6d0bb4063de4f4b91c4161b8e55

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated.

* link sdk/iOS Unified 64-bits - simulator/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2379
* link sdk/iOS Unified 64-bits - simulator/Release [dotnet]: https://github.com/xamarin/maccore/issues/2379
* monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: https://github.com/xamarin/maccore/issues/2380
* monotouch-test/iOS Unified 64-bits - simulator/Debug (all optimizations) [dotnet]: https://github.com/xamarin/maccore/issues/2380
* introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): https://github.com/xamarin/maccore/issues/2378

**Pull request merged**
