### PR TITLE
[registrar] Fix casing of PDFKit's header path. Fixes #59965.

### PR DESCRIPTION
**Pull request by rolfbjarne**
https://bugzilla.xamarin.com/show_bug.cgi?id=59965

### CODE REVIEW

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
* MTouch test failure is unrelated and fixed with PR #2849.
* MMP test failure is known and already fixed in master (bug #[59539](https://bugzilla.xamarin.com/show_bug.cgi?id=59539))

**Comment by antongdn** [comment]
Do I need Xcode 9.1 to get this fix? When/how will this be available in a release, stable or beta? Thanks!

**Comment by rolfbjarne** [comment]
@antongdn this will be in stable just after Xcode 9.1 is released to stable. We'll most likely release preview releases before that, but I don't have any dates yet.

**Comment by antongdn** [comment]
@rolfbjarne Ok, I see. Thanks!

**Pull request merged**
