### PR TITLE
[tests][mono-native] Adjust logic which is causing tests to fail on tvOS.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes this when running on tvOS using dylibs:

> [FAIL] Introspection.CheckSymbols : dlsym() not found mono_native_initialize()

Now:

* If on iOS, we'll always have the `mono_native_initialize` symbol, because the symbol is used in P/Invoke in a user assembly (the test assembly itself), and mtouch will make the AOT-compiled code use dlsym for P/Invokes in user assemblies (and when using dlsym we can't (native) strip away the symbol).
* If on watchOS or tvOS, we'll have the symbol when we're loading `mono_native_initialize` from a dylib. If loading `mono_native_initialize` from a static library, we can (native) strip away the symbol because mtouch will make the AOT-compiled P/Invoke use a static reference to the native symbol, and thus the `mono_native_initialize` symbol will not be present in the executable.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
For reference, sample failing on device: http://xamarin-storage/jenkins/xamarin-macios/master/2326e87bd5ae74f0055cf31e58b3fcbdf0c3da79/2564813/device-tests/jenkins-results/tests/index.html

**Comment by akoeplinger** [comment]
FWIW this was added after discussion in https://gitter.im/xamarin/xamarin-macios?at=5c6c10947667931e2fc89e57.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5877/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5877/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5877/1//console)
✅ Packages: [xamarin.ios-12.11.0.317.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/package/xamarin.ios-12.11.0.317.pkg) [xamarin.mac-5.11.0.317.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/package/xamarin.mac-5.11.0.317.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/2718eae0dc4f18e2c1bd2d87b68af41d29ff7cd4/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 230 tests passed.</summary>

## Failed tests

 * [NUnit] Mono SystemTransactionsTests/watchOS - simulator/Debug: Crashed
</details>

**Comment by spouliot** [comment]
The linked discussion mention that tvOS/watchOS are different (direct calls) and the current test treats those platform differently -> all good, so why the change ?

**Comment by rolfbjarne** [comment]
I've looked into this, and found the following:

The original fix for this issue was https://github.com/xamarin/xamarin-macios/commit/fa3878391fba56c90271c0125c3bffc0744bf75f. The confusing part is that it adds two conditions, one #if and one `MonoNativeConfig.LinkMode != MonoNativeLinkMode.Static`. The second condition is the one that fixed the actual issue, and the #if changed the asserts to be incorrect.

I've now remade this PR so that the code:

* If on iOS, we'll always have the `mono_native_initialize` symbol, because the symbol is used in P/Invoke in a user assembly (the test assembly itself), and mtouch will make the AOT-compiled code use dlsym for P/Invokes in user assemblies (and when using dlsym we can't (native) strip away the symbol).
* If on watchOS or tvOS, we'll have the symbol when we're loading `mono_native_initialize` from a dylib. If loading `mono_native_initialize` from a static library, we can (native) strip away the symbol because mtouch will make the AOT-compiled P/Invoke use a static reference to the native symbol, and thus the `mono_native_initialize` symbol will not be present in the executable.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5877/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5877/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5877/2//console)
✅ Packages: [xamarin.ios-12.11.0.318.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/package/xamarin.ios-12.11.0.318.pkg) [xamarin.mac-5.11.0.318.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/package/xamarin.mac-5.11.0.318.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/08f78672fc4c9252611ed8eb8378715bd348a3c5/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 0 tests skipped, 226 tests passed.</summary>

## Failed tests

 * mono-native-compat/tvOS - simulator/Debug: Failed
 * mono-native-unified/tvOS - simulator/Debug: Failed
 * mono-native-compat/watchOS - simulator/Debug: Failed
 * mono-native-unified/watchOS - simulator/Debug: Failed
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS - simulator/Debug: Crashed
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5877/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5877/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5877/3//console)
✅ Packages: [xamarin.ios-12.11.0.319.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/package/xamarin.ios-12.11.0.319.pkg) [xamarin.mac-5.11.0.319.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/package/xamarin.mac-5.11.0.319.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5877/7d68a3af12bdc326d6e31ed91bca42cc952adcec/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 230 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS - simulator/Debug (static registrar): Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failure is unrelated:

* monotouch-test/watchOS: https://github.com/xamarin/maccore/issues/581

**Pull request merged**
