### PR TITLE
[xtro] Exclude some frameworks that cause issues with sharpie on macOS 10.15

### PR DESCRIPTION
**Pull request by spouliot**
Also merge new `MPSNDArray` into its parent `MetalPerformanceShaders`
and use a `SortedSet` to avoid ending up with both `PdfKit` and `PDFKit`

### CODE REVIEW

**Comment by spouliot** [comment]
note: can be safely applied before bumping Xcode

**Comment by spouliot** [comment]
```
2019-06-04 17:38:44.853 mlaunch[65916:52271889] -[SimDevice registerNotificationHandler:]: unrecognized selector sent to instance 0x7feceee06ea0
Failed to launch the simulator: NSInvalidArgumentException: -[SimDevice registerNotificationHandler:]: unrecognized selector sent to instance 0x7feceee06ea0
error MT1008: Failed to launch the simulator: NSInvalidArgumentException: -[SimDevice registerNotificationHandler:]: unrecognized selector sent to instance 0x7feceee06ea0
```

**Comment by spouliot** [comment]
`66 tests failed, 0 tests' device not found, 29 tests passed.`
@rolfbjarne was that typo fix not backported to `d16.2` before the branch ?

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
failures related to https://github.com/mono/mono/issues/14875

**Comment by rolfbjarne** [comment]
> @rolfbjarne was that typo fix not backported to `d16.2` before the branch

No, it wasn't.

**Comment by spouliot** [comment]
failures are mix of known

* msbuild path issue mono/mono#14875
* NSData/https xamarin/maccore#1725

**Pull request merged**
