### PR TITLE
[src] Include netstandard20 System.Drawing types in Xamarin.WatchOS.dll.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by marek-safar** [comment]
The change is missing `Color` and `KnownColor` types

**Comment by rolfbjarne** [comment]
OK, I'll have a look.

**Comment by marek-safar** [comment]
@rolfbjarne I already made a patch for that https://github.com/marek-safar/xamarin-macios/commit/01e3a93c70155342662161c3f310e59922ad7351

**Comment by rolfbjarne** [comment]
OK, that looks good, can you make a PR for it?

**Comment by marek-safar** [comment]
sure

**Pull request merged**
