### PR TITLE
[InputMethodKit] Remove existing code for InputMethodKit.

### PR DESCRIPTION
**Pull request by rolfbjarne**
No InputMethodKit bindings are included in the build, so just remove the
bindings we have, since it's confusing to have code we don't build/use.

See also https://github.com/xamarin/xamarin-macios/issues/7487.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Comment by ShikiSuen** [comment]
Is there any instructions for how to bind this module and make it work?
The missing of InputMethodKti support makes it impossible to use C# to write an input method for macOS.

**Comment by rolfbjarne** [comment]
> Is there any instructions for how to bind this module and make it work?

You could probably create a binding project and bind the APIs you need that way.

**Comment by ShikiSuen** [comment]
@rolfbjarne I was told (years ago) that IMK is not the supported case:
image
https://github.com/xamarin/xamarin-macios/issues/16070#issuecomment-1255580906

However, I just found an interesting article:
https://debruyn.dev/2016/creating-a-xamarin.ios-binding-project-for-dummies/
I'll try it to see whether it works well.

**Comment by ShikiSuen** [comment]
@rolfbjarne I have tried creating a project here.

1. Create a new "Bindings Library" project in VS mac v17.6.9.
2. Use Sharpie to extract headers by the following command:
```bash
sharpie bind -output Binding -sdk macosx -scope /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Versions/A/Headers/ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Versions/A/Headers/IMKCandidates.h /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Versions/A/Headers/IMKInputController.h /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Versions/A/Headers/IMKServer.h /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Versions/A/Headers/InputMethodKit.h -c -Ibuild/Headers -arch arm64
```
3. Copy the contents of the extracted file above to replace the content of the `ApiDefinition.cs` file in the newly created project.
4. Add a native reference for this file:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework
```

Now the things get stucked at this step:
image

I uploaded the project to this repo:
https://github.com/ShikiSuen/InputMethodKitBinding-CSharp

Could you please show me some further steps I should do?

**Comment by rolfbjarne** [comment]
> Could you please show me some further steps I should do?

You can't reference the `InputMethodKit` namespace with a `using` clause, because you're basically creating it yourself.

So instead of:

```cs
using InputMethodKit;

[Static]
[Verify(ConstantsInterfaceAssociation)]
partial interface Constants {
[...]
```

do:

```cs
namespace InputMethodKit {
    [Static]
    [Verify(ConstantsInterfaceAssociation)]
    partial interface Constants {
```

**Comment by ShikiSuen** [comment]
@rolfbjarne Thank you for mentioning that. I pushed the commit of this fix.

Now the rest problems are summarized as follows:
```
ApiDefinition.cs(242,6): warning CS0618: 'MacAttribute' is obsolete: 'Use [Introduced|Deprecated|Obsoleted|Unavailable] attributes with PlatformName.'
ApiDefinition.cs(43,6): warning CS0618: 'MacAttribute' is obsolete: 'Use [Introduced|Deprecated|Obsoleted|Unavailable] attributes with PlatformName.'
ApiDefinition.cs(49,6): warning CS0618: 'MacAttribute' is obsolete: 'Use [Introduced|Deprecated|Obsoleted|Unavailable] attributes with PlatformName.'
BTOUCH : error BI0002: bgen: Could not compile the API bindings.
ApiDefinition.cs(28,25): error CS0246: The type or namespace name 'IIMKServerProxy' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(183,34): error CS0246: The type or namespace name 'IIMKStateSetting' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(183,52): error CS0246: The type or namespace name 'IIMKMouseHandling' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(11,4): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(11,4): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(56,4): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(56,4): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(11,11): error CS0103: The name 'ConstantsInterfaceAssociation' does not exist in the current context
ApiDefinition.cs(56,11): error CS0103: The name 'ConstantsInterfaceAssociation' does not exist in the current context
ApiDefinition.cs(55,4): error CS0579: Duplicate 'Static' attribute
ApiDefinition.cs(31,5): error CS0246: The type or namespace name 'NativeHandle' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(186,5): error CS0246: The type or namespace name 'NativeHandle' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(35,5): error CS0246: The type or namespace name 'NativeHandle' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(239,5): error CS0308: The non-generic type 'NSObject' cannot be used with type arguments
ApiDefinition.cs(239,14): error CS0246: The type or namespace name 'IMKTextInput' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(39,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(39,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(39,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(202,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(202,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(202,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(207,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(207,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(207,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(101,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(101,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(101,13): error CS0103: The name 'StronglyTypedNSArray' does not exist in the current context
ApiDefinition.cs(224,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(224,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(224,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(230,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(230,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(230,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(45,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(45,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(45,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
ApiDefinition.cs(51,6): error CS0246: The type or namespace name 'VerifyAttribute' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(51,6): error CS0246: The type or namespace name 'Verify' could not be found (are you missing a using directive or an assembly reference?)
ApiDefinition.cs(51,13): error CS0103: The name 'MethodToProperty' does not exist in the current context
```

Also, regarding the Availability attribute, should I fix it as follows?
```
// Before:
[Mac(10, 7)]
// After:
[Introduced(PlatformName.MacOSX, 10, 7)]

```

**Comment by rolfbjarne** [comment]
> The type or namespace name 'NativeHandle'

This needs a `using ObjCRuntime;` at the top of the file.

> The type or namespace name 'VerifyAttribute'

Verify if the generated code is correct, then remove the attribute.

> Also, regarding the Availability attribute, should I fix it as follows?

Since this is just for yourself, the easiest would be to just delete them all.

**Comment by ShikiSuen** [comment]
@rolfbjarne Thank you for your response.

The `using ObjCRuntime;` is already there. I managed to fix the NativeHandle by introducing:
```
#if !NET
using NativeHandle = System.IntPtr;
#endif
```

I'll troubleshoot this further. Looks like one or more IMK internal headers are missed in the Sharpie command.

**Comment by ShikiSuen** [comment]
I finally made it. This works fine even if the native reference is pointed to "/System/Library/Frameworks/InputMethodKit.framework".

The ApiDefinition.cs is now written as follows:

```csharp
using System;

using AppKit;
using Foundation;
using ObjCRuntime;
using CoreGraphics;

#if !NET
using NativeHandle = System.IntPtr;
#endif

namespace InputMethodKit {
[BaseType(typeof(NSObject))]
interface NSObject_IMKServerProxy {
  // extern const NSString * IMKModeDictionary;
  [Export("IMKModeDictionary")]
  NSString IMKModeDictionary { get; }

  // extern const NSString * IMKControllerClass;
  [Export("IMKControllerClass")] NSString IMKControllerClass { get; }

  // extern const NSString * IMKDelegateClass;
  [Export("IMKDelegateClass")] NSString IMKDelegateClass { get; }
}

// @interface IMKServer : NSObject <IMKServerProxy>
[BaseType(typeof(NSObject))]
interface IMKServer : NSObject_IMKServerProxy {
  // -(id)initWithName:(NSString *)name bundleIdentifier:(NSString *)bundleIdentifier;
  [Export("initWithName:bundleIdentifier:")]
  NativeHandle Constructor(string name, string bundleIdentifier);

  // -(id)initWithName:(NSString *)name controllerClass:(Class)controllerClassID delegateClass:(Class)delegateClassID;
  [Export("initWithName:controllerClass:delegateClass:")]
  NativeHandle Constructor(string name, Class controllerClassID, Class delegateClassID);

  // -(NSBundle *)bundle;
  [Export("bundle")]
  NSBundle Bundle { get; }

  // -(BOOL)paletteWillTerminate __attribute__((availability(macos, introduced=10.7)));
  [Introduced(PlatformName.MacOSX, 10, 7)][Export("paletteWillTerminate")] bool PaletteWillTerminate { get; }

  // -(BOOL)lastKeyEventWasDeadKey __attribute__((availability(macos, introduced=10.7)));
  [Introduced(PlatformName.MacOSX, 10, 7)][Export("lastKeyEventWasDeadKey")] bool LastKeyEventWasDeadKey { get; }
}

partial interface Constants {
  // extern const NSString * kIMKCommandMenuItemName;
  [Export("kIMKCommandMenuItemName")]
  NSString kIMKCommandMenuItemName { get; }

  // extern const NSString * kIMKCommandClientName;
  [Export("kIMKCommandClientName")] NSString kIMKCommandClientName { get; }
}

// @interface IMKServerInput (NSObject)
[BaseType(typeof(NSObject))]
interface NSObject_IMKServerInput {
  // -(BOOL)inputText:(NSString *)string key:(NSInteger)keyCode modifiers:(NSUInteger)flags client:(id)sender;
  [Export("inputText:key:modifiers:client:")]
  bool InputText(string @string, nint keyCode, nuint flags, NSObject sender);

  // -(BOOL)inputText:(NSString *)string client:(id)sender;
  [Export("inputText:client:")]
  bool InputText(string @string, NSObject sender);

  // -(BOOL)handleEvent:(NSEvent *)event client:(id)sender;
  [Export("handleEvent:client:")]
  bool HandleEvent(NSEvent @event, NSObject sender);

  // -(BOOL)didCommandBySelector:(SEL)aSelector client:(id)sender;
  [Export("didCommandBySelector:client:")]
  bool DidCommandBySelector(Selector aSelector, NSObject sender);

  // -(id)composedString:(id)sender;
  [Export("composedString:")]
  NSObject ComposedString(NSObject sender);

  // -(NSAttributedString *)originalString:(id)sender;
  [Export("originalString:")]
  NSAttributedString OriginalString(NSObject sender);

  // -(void)commitComposition:(id)sender;
  [Export("commitComposition:")]
  void CommitComposition(NSObject sender);

  // -(NSArray *)candidates:(id)sender;
  [Export("candidates:")]
  NSObject[] Candidates(NSObject sender);
}

// @protocol IMKStateSetting
/*
  Check whether adding [Model] to this declaration is appropriate.
  [Model] is used to generate a C# class that implements this protocol,
  and might be useful for protocols that consumers are supposed to implement,
  since consumers can subclass the generated class instead of implementing
  the generated interface. If consumers are not supposed to implement this
  protocol, then [Model] is redundant and will generate code that will never
  be used.
*/
[Protocol]
interface IMKStateSetting {
  // @required -(void)activateServer:(id)sender;
  [Abstract]
  [Export("activateServer:")]
  void ActivateServer(NSObject sender);

  // @required -(void)deactivateServer:(id)sender;
  [Abstract]
  [Export("deactivateServer:")]
  void DeactivateServer(NSObject sender);

  // @required -(id)valueForTag:(long)tag client:(id)sender;
  [Abstract]
  [Export("valueForTag:client:")]
  NSObject ValueForTag(nint tag, NSObject sender);

  // @required -(void)setValue:(id)value forTag:(long)tag client:(id)sender;
  [Abstract]
  [Export("setValue:forTag:client:")]
  void SetValue(NSObject value, nint tag, NSObject sender);

  // @required -(NSDictionary *)modes:(id)sender;
  [Abstract]
  [Export("modes:")]
  NSDictionary Modes(NSObject sender);

  // @required -(NSUInteger)recognizedEvents:(id)sender;
  [Abstract]
  [Export("recognizedEvents:")]
  nuint RecognizedEvents(NSObject sender);

  // @required -(void)showPreferences:(id)sender;
  [Abstract]
  [Export("showPreferences:")]
  void ShowPreferences(NSObject sender);
}

// @protocol IMKMouseHandling
/*
  Check whether adding [Model] to this declaration is appropriate.
  [Model] is used to generate a C# class that implements this protocol,
  and might be useful for protocols that consumers are supposed to implement,
  since consumers can subclass the generated class instead of implementing
  the generated interface. If consumers are not supposed to implement this
  protocol, then [Model] is redundant and will generate code that will never
  be used.
*/
[Protocol]
interface IMKMouseHandling {
  // @required -(BOOL)mouseDownOnCharacterIndex:(NSUInteger)index coordinate:(NSPoint)point
  // withModifier:(NSUInteger)flags continueTracking:(BOOL *)keepTracking client:(id)sender;

  [Abstract]
  [Export("mouseDownOnCharacterIndex:coordinate:withModifier:continueTracking:client:")]
  bool MouseDownOnCharacterIndex(nuint index, CGPoint point, nuint flags, ref bool keepTracking, NSObject sender);

  // @required -(BOOL)mouseUpOnCharacterIndex:(NSUInteger)index coordinate:(NSPoint)point withModifier:(NSUInteger)flags
  // client:(id)sender;
  [Abstract]
  [Export("mouseUpOnCharacterIndex:coordinate:withModifier:client:")]
  bool MouseUpOnCharacterIndex(nuint index, CGPoint point, nuint flags, NSObject sender);

  // @required -(BOOL)mouseMovedOnCharacterIndex:(NSUInteger)index coordinate:(NSPoint)point
  // withModifier:(NSUInteger)flags client:(id)sender;
  [Abstract]
  [Export("mouseMovedOnCharacterIndex:coordinate:withModifier:client:")]
  bool MouseMovedOnCharacterIndex(nuint index, CGPoint point, nuint flags, NSObject sender);
}

// @interface IMKInputController : NSObject <IMKStateSetting, IMKMouseHandling>
[BaseType(typeof(NSObject))]
interface IMKInputController : IMKStateSetting, IMKMouseHandling {
  // -(id)initWithServer:(IMKServer *)server delegate:(id)delegate client:(id)inputClient;
  [Export("initWithServer:delegate:client:")]
  NativeHandle Constructor(IMKServer server, NSObject @delegate, NSObject inputClient);

  // -(void)updateComposition;
  [Export("updateComposition")]
  void UpdateComposition();

  // -(void)cancelComposition;
  [Export("cancelComposition")]
  void CancelComposition();

  // -(NSMutableDictionary *)compositionAttributesAtRange:(NSRange)range;
  [Export("compositionAttributesAtRange:")]
  NSMutableDictionary CompositionAttributesAtRange(NSRange range);

  // -(NSRange)selectionRange;
  [Export("selectionRange")]
  NSRange SelectionRange { get; }

  // -(NSRange)replacementRange;
  [Export("replacementRange")] NSRange ReplacementRange { get; }

  // -(NSDictionary *)markForStyle:(NSInteger)style atRange:(NSRange)range;
  [Export("markForStyle:atRange:")] NSDictionary MarkForStyle(nint style, NSRange range);

  // -(void)doCommandBySelector:(SEL)aSelector commandDictionary:(NSDictionary *)infoDictionary;
  [Export("doCommandBySelector:commandDictionary:")]
  void DoCommandBySelector(Selector aSelector, NSDictionary infoDictionary);

  // -(void)hidePalettes;
  [Export("hidePalettes")]
  void HidePalettes();

  // -(NSMenu *)menu;
  [Export("menu")]
  NSMenu Menu { get; }

  // -(id)delegate;
  // -(void)setDelegate:(id)newDelegate;
  [Export("delegate")] NSObject Delegate { get; set; }

  // -(IMKServer *)server;
  [Export("server")] IMKServer Server();

  // -(id<IMKTextInput,NSObject>)client;
  [Export("client")]
  IMKTextInput Client();

  // -(void)inputControllerWillClose __attribute__((availability(macos, introduced=10.7)));
  [Introduced(PlatformName.MacOSX, 10, 7)]
  [Export("inputControllerWillClose")]
  void InputControllerWillClose();

  // -(void)annotationSelected:(NSAttributedString *)annotationString forCandidate:(NSAttributedString
  // *)candidateString;
  [Export("annotationSelected:forCandidate:")]
  void AnnotationSelected(NSAttributedString annotationString, NSAttributedString candidateString);

  // -(void)candidateSelectionChanged:(NSAttributedString *)candidateString;
  [Export("candidateSelectionChanged:")]
  void CandidateSelectionChanged(NSAttributedString candidateString);

  // -(void)candidateSelected:(NSAttributedString *)candidateString;
  [Export("candidateSelected:")]
  void CandidateSelected(NSAttributedString candidateString);
}

[BaseType(typeof(NSObject))]
interface IMKTextInput {
  // @required -(struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
  [Abstract]
  [Export("firstRectForCharacterRange:actualRange:")]
  CGRect FirstRectForCharacterRange(NSRange arg1, ref NSRange arg2);

  // @required -(NSString *)stringFromRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
  [Abstract]
  [Export("stringFromRange:actualRange:")]
  string StringFromRange(NSRange arg1, ref NSRange arg2);

  // @required -(NSString *)uniqueClientIdentifierString;
  [Abstract]
  [Export("uniqueClientIdentifierString")]
  string UniqueClientIdentifierString { get; }

  // @required -(id)supportsProperty:(unsigned int)arg1;
  [Abstract]
  [Export("supportsProperty:")] NSObject SupportsProperty(uint arg1);

  // @required -(int)windowLevel;
  [Abstract]
  [Export("windowLevel")]
  int WindowLevel { get; }

  // @required -(NSString *)bundleIdentifier;
  [Abstract][Export("bundleIdentifier")] string BundleIdentifier { get; }

  // @required -(id)supportsUnicode;
  [Abstract][Export("supportsUnicode")] NSObject SupportsUnicode { get; }

  // @required -(void)selectInputMode:(NSString *)arg1;
  [Abstract]
  [Export("selectInputMode:")] void SelectInputMode(string arg1);

  // @required -(void)overrideKeyboardWithKeyboardNamed:(NSString *)arg1;
  [Abstract]
  [Export("overrideKeyboardWithKeyboardNamed:")]
  void OverrideKeyboardWithKeyboardNamed(string arg1);

  // @required -(NSArray *)validAttributesForMarkedText;
  [Abstract]
  [Export("validAttributesForMarkedText")]
  NSObject[] ValidAttributesForMarkedText { get; }

  // @required -(NSDictionary *)attributesForCharacterIndex:(unsigned long long)arg1 lineHeightRectangle:(struct CGRect
  // *)arg2;
  [Abstract]
  [Export("attributesForCharacterIndex:lineHeightRectangle:")] NSDictionary AttributesForCharacterIndex(
      ulong arg1, ref CGRect arg2);

  // @required -(long long)characterIndexForPoint:(struct CGPoint)arg1 tracking:(long long)arg2 inMarkedRange:(char
  // *)arg3;
  [Abstract]
  [Export("characterIndexForPoint:tracking:inMarkedRange:")]
  long CharacterIndexForPoint(CGPoint arg1, long arg2, ref CGRect arg3);
  // @required -(long long)length;
  [Abstract]
  [Export("length")]
  long Length { get; }

  // @required -(NSAttributedString *)attributedSubstringFromRange:(struct _NSRange)arg1;
  [Abstract]
  [Export("attributedSubstringFromRange:")] NSAttributedString AttributedSubstringFromRange(NSRange arg1);

  // @required -(struct _NSRange)markedRange;
  [Abstract]
  [Export("markedRange")]
  NSRange MarkedRange { get; }

  // @required -(struct _NSRange)selectedRange;
  [Abstract][Export("selectedRange")] NSRange SelectedRange { get; }

  // @required -(void)setMarkedText:(id)arg1 selectionRange:(struct _NSRange)arg2 replacementRange:(struct
  // _NSRange)arg3;
  [Abstract]
  [Export("setMarkedText:selectionRange:replacementRange:")] void SetMarkedText(NSObject arg1, NSRange arg2,
                                                                                NSRange arg3);

  // @required -(void)insertText:(id)arg1 replacementRange:(struct _NSRange)arg2;
  [Abstract]
  [Export("insertText:replacementRange:")]
  void InsertText(NSObject arg1, NSRange arg2);
}

}

```

**Comment by ShikiSuen** [comment]
@rolfbjarne Hi, could you please tell me how to stop VS from attemping to copy the InputMethodKit.framework into the built app bundle. This copying behavior is not allowed on macOS 11 and later due to some internal changes in macOS.

image

**Pull request merged**
