### PR TITLE
Cherry pick XM Full Netstandard fixes to 15.5

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Comment by spouliot** [comment]
@chamons please look at test failures - maybe another back port is needed since it's working from master ?

**Comment by chamons** [comment]
Task "Exec"
		Using task Exec from Microsoft.Build.Tasks.Exec, Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
		Executing: make -j8 -C ../../tests/test-libraries
		Environment variables being passed to the tool:
		make: error: unable to find utility "make", not a developer tool or in PATH

@rolfbjarne is this https://github.com/xamarin/xamarin-macios/commit/ee91b95c1984a598aee0447ab23a89b1be98de23#diff-b61a6d542f9036550ba9c401c80f00ef ?

**Comment by spouliot** [comment]
@chamons it might be because bots were being updated with Xcode 9.1

**Comment by spouliot** [comment]
build

**Pull request merged**
