### PR TITLE
[mediaplayer] Update up to Xcode 9.2 beta 2

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by VincentDondain** [comment]
@spouliot is this related to some bug? What's the reason for that change?

**Comment by spouliot** [comment]
@VincentDondain that's for matching Xcode9.2 header files

**Comment by VincentDondain** [comment]
Of course... sorry was doing something else and didn't even read the title of the PR (:

**Comment by dalexsoto** [comment]
iOSApiTypoTest.ApiTypoTest.TypoTest -> mea culpa, getting fixed in PR #2995

**Pull request merged**
