### PR TITLE
[CI] Fix wrong fwd labels.

### PR DESCRIPTION
**Pull request by mandel-macaque**
We are trying to join the json rather than the collection of strings.
$tag is a collection we can join.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]
join all the things!

**Comment by mandel-macaque** [comment]
152 tests thanks to the bcl, so it is a success :)

**Comment by mandel-macaque** [comment]
Do not backport to xcode12.5 since I did a commit in the merge PR with this change.

**Pull request merged**
