### PR TITLE
[Harness] If we cannot connect over tcp use Console.Out as the writer.

### PR DESCRIPTION
**Pull request by mandel-macaque**
If we could not connect to the host via tcp, set the writer to be
Console.Out which will fix the NRE and will report the test run in the
runlogs.

Fix only applies to tvOS and iOS since neither watchOS or MacOS use the tcp connection.

fixes: https://github.com/xamarin/xamarin-macios/issues/8130

### CODE REVIEW

**Comment by mandel-macaque** [comment]
@spouliot branch is in origin already.

**Comment by mandel-macaque** [comment]
build

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8235/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8235/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Running XM tests on '10.14'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8235/2//console)
✅ Packages: 
* [xamarin.ios-13.19.0.386.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8235/1aa16455056ab8d426a6c938d257b3e3a96d6bad/2/package/xamarin.ios-13.19.0.386.pkg)
* [xamarin.mac-6.19.0.386.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8235/1aa16455056ab8d426a6c938d257b3e3a96d6bad/2/package/xamarin.mac-6.19.0.386.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/1aa16455056ab8d426a6c938d257b3e3a96d6bad/2/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-8235/2//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/1aa16455056ab8d426a6c938d257b3e3a96d6bad/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 180 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>
🔥 [Xamarin.Mac tests on 10.14 failed: null](https://jenkins.internalx.com/job/macios/job/PR-8235/2/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8235/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8235/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8235/3//console)
✅ Packages: 
* [xamarin.ios-13.19.0.397.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/package/xamarin.ios-13.19.0.397.pkg)
* [xamarin.mac-6.19.0.397.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/package/xamarin.mac-6.19.0.397.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/jenkins-results/apicomparison/api-diff.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8235/cca2113ee987750810de84e9bcde8bdada0f38be/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 183 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Pull request merged**
