### PR TITLE
[xcode12.5] Bump for Xcode 12.5 RC

### PR DESCRIPTION
**Pull request by spouliot**
and add the few new bindings added in the SDKs

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Of course, we have an infra problem with the network :/

**Review by dalexsoto — APPROVED** [review]
❤️

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
