### PR TITLE
[CI][VSTS] The pkg of the tests fail because there is a path not longer found.

### PR DESCRIPTION
**Pull request by mandel-macaque**
fixes: https://github.com/xamarin/maccore/issues/2363

### CODE REVIEW

**Comment by mandel-macaque** [comment]
@rolfbjarne I'm not sure about this fix. I used to run the make in the yaml pipeline and worked then it stopped. Did we change a path in the test generation? Maybe with the catalist work?

**Review by rolfbjarne — APPROVED** [review]
This regressed when apitest was merged into xammac_tests, so this is the correct fix.

**Pull request merged**
