### PR TITLE
[dotnet] Fix MSBuild syntax.

### PR DESCRIPTION
**Pull request by rolfbjarne**
For some reason .NET 6 does not like spaces in certain places:

    MSB4259: Unexpected space at position "32" of condition [...]

So just remove them.

### CODE REVIEW

**Review by chamons — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
wow 😱

**Review by whitneyschmidt — APPROVED** [review]
🥇

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]
lol

**Review by emaf — APPROVED** [review]

**Comment by rolfbjarne** [comment]
For the record, this is an MSBuild bug: https://github.com/dotnet/msbuild/issues/5863

**Pull request merged**
