### PR TITLE
[msbuild] Make codesigned output files relative, and don't list directories.

### PR DESCRIPTION
**Pull request by rolfbjarne**
When XVS creates output/stamp files on Windows, the paths must be relative,
because otherwise XVS will append the full macOS path to the current Windows
directory and get garbage.

XVS also expects only files as output, so don't return any directories.

Fixes part of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1505990/.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by mauroa — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* mmptest/macOS/Debug: https://github.com/xamarin/maccore/issues/2560
* MTouch tests/NUnit: #14601, #14604.

**Comment by rolfbjarne** [comment]
This change works, but it's not complete (there are other tasks that return output directories). I'll merge this one, and keep working on the other ones.

**Pull request merged**
