### PR TITLE
[devops] Make sure BUILD_REVISION is set to something during the build.

### PR DESCRIPTION
**Pull request by rolfbjarne**
We have logic that depend on this variable to determine whether we're in CI or not.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* introspection tests: https://github.com/xamarin/maccore/issues/2596
* monotouch tests: https://github.com/xamarin/xamarin-macios/pull/15423 and https://github.com/xamarin/maccore/issues/2558
* mtouch tests: https://github.com/xamarin/xamarin-macios/pull/15422

**Comment by rolfbjarne** [comment]
The hotrestart app is signed now:

Screen Shot 2022-07-08 at 19 43 16

**Review by chamons — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Pull request merged**
