### PR TITLE
Fixed issue with code signing when using multiple AdditionalAppExtensions

### PR DESCRIPTION
**Pull request by wojciech-kulik**
I discovered that there is still some issue with code signing of app extensions when using more than one `AdditionalAppExtensions` section in `csproj`.

It turned out that `msbuild` is trying to codesign both extensions using the same entitlements.

To fix it I moved the path to the entitlements file from `PropertyGroup` section (which is static and causes issues in this case) into `ItemsGroup`.

I also mentioned about this issue here: https://github.com/xamarin/xamarin-macios/issues/9458#issuecomment-703891928

### CODE REVIEW

**Review by chamons — APPROVED** [review]
This looks reasonable to me, but I'll wait on @rolfbjarne and @emaf 's review tomorrow.

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
Thanks for the contribution!

**Comment by wojciech-kulik** [comment]
> This looks reasonable to me, but I'll wait on @rolfbjarne and @emaf 's review tomorrow.

Great, I'm not `msbuild` expert, so let's better wait to confirm the fix :)

**Review by dalexsoto — APPROVED** [review]

**Review by whitneyschmidt — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by juepiezhongren** [comment]
does this have anything to do with clip apps?

**Review by rolfbjarne — APPROVED** [review]
This looks good to me (it's explained in the section about batching in MSBuild: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-batching?view=vs-2019)

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by chamons** [comment]
Waiting on review from XVS

**Review by emaf — APPROVED** [review]

**Comment by chamons** [comment]
Thanks again for the contribution!

**Comment by dalexsoto** [comment]
@monojenkins backport xcode12.2

**Pull request merged**
