### PR TITLE
[msbuild] Skip reference assemblies passed to mtouch

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes issue #3199: Could not AOT the assembly System.Runtime.CompilerServices.Unsafe.dll (MT3001)
  (https://github.com/xamarin/xamarin-macios/issues/3199)
- Test case: https://www.dropbox.com/s/kxt3isgzn74nq35/Issue3199.zip?dl=0

Problem
=======

Given a Nuget Package added via the "package reference" mechanism and the said package having netstandard `lib` **and** `ref` folders;
MTouch was getting reference assemblies and was trying to AOT them. This resulted in an error as those assemblies are only facades.

Solution
========

Skipping the assemblies that have `/ref/` in their path seems like the simplest and yet most functional solution to the problem.

As it turn out, there is some logic already in place that copies the `lib` assemblies to the destination folder. It seems equivalent to marking them as "Local Copy".
What this does is that it makes those assemblies available to msbuild via `@(ReferenceCopyLocalPaths)`. This gives us the opportunity to safely remove the `ref` assemblies from `@(ReferencePath)`.

*Note: `mtouch` is getting the assemblies to reference via a combination of `@(ReferencePath)` and `@(ReferenceCopyLocalPaths)`.*

### CODE REVIEW

**Comment by rolfbjarne** [comment]
What does Xamarin.Android do in this case? It seems they should have the same problem (so we should also implement the same solution).

**Comment by jstedfast** [comment]
I agree with @spouliot and @rolfbjarne makes a good suggestion. We should see what Android does and try to solve it the same way.

I'm also concerned that `/ref/` might appear in customer's paths, so filtering on that seems wrong.

**Comment by VincentDondain** [comment]
Filtering on `/ref/` was a bit optimistic I realize (:

Now I'm not sure copying what Xamarin.Android did is our best option (here's the [PR](https://github.com/xamarin/xamarin-android/pull/1356) for reference).

1. One important discovery I made is that the full version of the assembly is automatically copied by msbuild and ends up in `@(ReferenceCopyLocalPaths)`. See [gist](https://gist.github.com/VincentDondain/4bffc499126134f4649199ed8515220a#file-gistfile1-txt-L2878-L2882) with `_CopyFilesMarkedCopyLocal ` target. So mtouch gets the reference assembly from `@(ReferencePath)` (that I hoped to filter out) and the full version from `@(ReferenceCopyLocalPaths)`.
2. The XA patch is complex and if there is a change in the nuget json format (oh, there will...) it won't work (even if it falls back to the current behavior).

My next steps are:

- Investigate why we get the `/lib/` version of the assembly from Copy (msbuild).
- Talk to interested parties (#msbuild and friends) to know if people have better ideas on how this should be handled.

**Comment by spouliot** [comment]
The `\lib\` version seems to be an **input** to the Copy task.

```
Target "_CopyFilesMarkedCopyLocal" in file "/Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets":
  Using "Copy" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "Copy"
    Copying file from "/Users/vidondai/.nuget/packages/system.runtime.compilerservices.unsafe/4.4.0/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll" to "bin/iPhone/Debug/System.Runtime.CompilerServices.Unsafe.dll".
  Done executing task "Copy".
```

We need to figure out how that (`\lib\`) path/file became something known inside `msbuild` since some code was able to infer the `\lib\` version existence (and requirement) somehow...

The task name `_CopyFilesMarkedCopyLocal` is *weird* before the logs hints it is not a `CopyLocal`

```
        This reference is not "CopyLocal" because at least one source item had "Private" set to "false" and no source items had "Private" set to "true".
```

see https://gist.github.com/VincentDondain/4bffc499126134f4649199ed8515220a#file-gistfile1-txt-L2552

so it's unclear *why* it was copied ?!? 

Note that the Private = false was for `ref` not `lib` so that might be the reason, however the logs are silent about that transition :(

**Comment by VincentDondain** [comment]
Argh and we have an other problem that's not even covered by this PR's "fancy workaround".

See test case: https://www.dropbox.com/s/btb6rzb636pnutf/Issue3199Test2.zip?dl=0

In this new test case the iOS project references a netstandard class library, which references a Nuget Package (System.Runtime.CompilerServices.Unsafe) but the app does **NOT** reference that package directly.

In this specific case mtouch will fail with `MTOUCH : error MT2101: Can't resolve the reference '!!1& System.Runtime.CompilerServices.Unsafe::As(!!0&)', referenced from the method 'System.Void LibWithPackage.Class1::Test()' in 'System.Runtime.CompilerServices.Unsafe, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.` as it doesn't have a reference to `System.Runtime.CompilerServices.Unsafe.dll`.

Therefore the mechanism where the `\lib\` version of the package's dll is copied to `@(ReferenceCopyLocalPaths)` only happens if the main app references the package directly.

Full build log: https://gist.github.com/VincentDondain/3a067c97e7f034a2a5c542dc6d3d7072

**Comment by VincentDondain** [comment]
Here is a gist where I output the content of different msbuild variables: https://gist.github.com/VincentDondain/38073e31f5bba95e4520bcffa35f03a6. That helps understand the latest commit.

**Comment by VincentDondain** [comment]
No this doesn't solve part B discussed in my comment here: https://github.com/xamarin/xamarin-macios/pull/3791#issuecomment-375349342 (aka "iOS project references a netstandard class library, which references a Nuget Package (System.Runtime.CompilerServices.Unsafe) but the app does NOT reference that package directly") but it fixes netstandard packages with `/lib/` and `/ref/` added to the main iOS app project.

**Comment by VincentDondain** [comment]
@rolfbjarne yes, trying right now to build the test case I attached from our tests but I'm failing on restore the nugget package for now.

**Comment by VincentDondain** [comment]
Ok so it looks like adding a proper msbuild test for this issue is currently not possible (or very very hard / hacky).

See https://bugzilla.xamarin.com/show_bug.cgi?id=53164.

Our msbuild tests are in fact still using `xbuild` and @radical is trying to move them to msbuild. Because the test case for this issue is using NugetPackages added via "PackageReference" it needs msbuild. `xbuild` cannot "restore" nor is using the right `ResolveAssemblyReferences` target (that feeds csc with the right assemblies).

I think we should merge this issue before getting the test (filled issue https://github.com/xamarin/xamarin-macios/issues/3810 to remember we should add it).

**Comment by spouliot** [comment]
@VincentDondain can't you just add the nuget/code ito monotouch-test (not the msbuild tests) until then ? that would fail when we build it for device

**Comment by VincentDondain** [comment]
@spouliot good idea, I just added that with my latest commit. Without this PR's fix we'd get a build error when building `monotouch-test`.

It's not as if the test itself is testing anything though but it's still a good way to know if we regress.

**Comment by spouliot** [comment]
👍

**Comment by VincentDondain** [comment]
See last comment of this PR https://github.com/xamarin/xamarin-macios/pull/3817#issuecomment-376680991.

I tried to run the tests with msbuild but it is still currently blocked on https://bugzilla.xamarin.com/show_bug.cgi?id=53164.

Without msbuild and `/restore` we can't restore the NuGet package added via PackageReference therefore we can't have the monotouch-test I tried to add (nor can we have an msbuild test).

In addition to the aforementioned bug we're also tracking the addition of the proper msbuild test for this here: https://github.com/xamarin/xamarin-macios/issues/3810

**Pull request merged**
