### PR TITLE
Improve UIScreen Capture() support for complex views

### PR DESCRIPTION
**Pull request by christianhelle**
The current UIScreen Capture() method doesn't support complex views with multiple CA Layers (for example iCarousel). The changes here are in use in our apps in the AppStore with over half a million daily active users and no one has ever reported a bug regarding it. I kept the original code for backward compatibility as [drawViewHierarchyInRect:afterScreenUpdates:](https://developer.apple.com/reference/uikit/uiview/1622589-drawviewhierarchyinrect) was introduced in iOS 7.0. My changes were based from https://developer.apple.com/library/content/qa/qa1817/_index.html

Screenshot using original Capture() implementation:
Alt text

Screenshot using the changes in this pull request:
Alt text

The images above are from an app with a screen using iCarousel with 8 items containing both images and texts. I used the UIScreen Capture() method to capture this screen before opening another screen where I show it as the background image. 

I unfortunately had to crop out the rest of the image due to corporate reasons, but the images provided above are enough to illustrate the problem. I can provide a video of the problem if needed as long as this video is not shared with the general public

### CODE REVIEW

**Comment by rolfbjarne** [comment]
approve

**Comment by christianhelle** [comment]
Thanks for the input @rolfbjarne, I'll fix the styling issue you pointed out. 

I'm pretty sure that the method [drawViewHierarchyInRect:afterScreenUpdates:](https://developer.apple.com/reference/uikit/uiview/1622589-drawviewhierarchyinrect) was introduced in iOS 7.0 since it states that in the documentation page. If I didn't include the original implementation then calling `Capture()` would fail on older iOS versions. 

I'm fine with replacing the old implementation but I wanted to tread carefully since this is my first time contributing to the product I thought I should consider backwards compatibility

**Comment by christianhelle** [comment]
I updated my changes based on the comments by @rolfbjarne

**Comment by rolfbjarne** [comment]
Test failures are unrelated (watchOS/System test failures filed as bug #[47167](https://bugzilla.xamarin.com/show_bug.cgi?id=47167)).

**Comment by rolfbjarne** [comment]
Thanks!

**Comment by mandel-macaque** [comment]
Looking at this PR, we should also test that the UIView.Capture added in commit 7c51c3b7b805b3c5bbf9485ed9be62c835729c4c

@rolfbjarne what do you think? 
@christianhelle do you have an example I could use for testing?

**Pull request merged**
