### PR TITLE
[mtouch] Show MT0091 as a warning if we're using the dynamic registrar.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Even if using an Xcode older than the bindings we're shipping, everything
might just happen to work when using the dynamic registrar, so downgrade the
MT0091 error to a warning in that case (and cross fingers, because things
might still break).

Hopefully this makes it easier when using older Xcodes, because the typical
scenario of Sim+DontLink and Dev+LinkSdk/LinkAll will now just work (if the
app developer also crosses fingers piously and sacrifies the appropriate
amount of pizza to the proper deity).

Reference: https://trello.com/c/wP3Pcb1q/692-targeting-older-xcodes-without-enabling-managed-linking

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This won't break currently working scenarios, but it might continue to fail for some people, but in more confusing ways (thus we end up with some happy customers and some even more confused customers).

**Comment by rolfbjarne** [comment]
git clone failure 😞

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
git clone failure 😞

**Comment by rolfbjarne** [comment]
build

**Comment by chamons** [comment]
This also appears to fix https://bugzilla.xamarin.com/show_bug.cgi?id=58977

**Comment by rolfbjarne** [comment]
We decided to not do this for now.

**Pull request closed without merging**
