### PR TITLE
[spritekit] Add nullability to (generated and manual) bindings

### PR DESCRIPTION
**Pull request by spouliot**
See [HOWTO](https://github.com/xamarin/xamarin-macios/wiki/Nullability)

### CODE REVIEW

**Comment by spouliot** [comment]
```
20:31:23 make[2]: *** [downloads/maccat-release-Darwin-dfbfe5eed1992905b0dac80a8dc7d6f1f9647735.7z] Error 92
20:31:23 make[1]: *** [.stamp-download-mono] Error 2
```
file seems to exists ?!?

**Comment by spouliot** [comment]
build

**Comment by dalexsoto** [comment]
What's up with you and the bots @spouliot ?

**Comment by spouliot** [comment]
@dalexsoto it's reciprocal 🤖 😒

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Pull request merged**
