### PR TITLE
[homekit] Update watchOS API availability for Xcode 8.3

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes xtro tests.

### CODE REVIEW

**Comment by VincentDondain** [comment]
Ran introspection-watchos tests on `3.1.3` Apple Watch device, see: https://gist.github.com/VincentDondain/f615571ddedd6c3aa770ccb85e0f265f

Failures are not related to the newly available APIs.

**Comment by VincentDondain** [comment]
build

**Comment by spouliot** [comment]
@dalexsoto see results above - the Contacts API changes seems to have missing/incorrect availability attributes.

**Comment by dalexsoto** [comment]
Noted, will fix them, thanks for the heads up

**Comment by VincentDondain** [comment]
Unrelated test failures:
iOS Unified 32 bit - https://bugzilla.xamarin.com/show_bug.cgi?id=52162

**Pull request merged**
