### PR TITLE
[CoreText] Add support for Xcode13 beta1.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Added the invokes to be ignored as with macOS.

### CODE REVIEW

**Review by spouliot — COMMENTED** [review]
why not implement them ?

if not, then don't label as `highlight` since it will go out in release notes without anything new in the release

**Comment by mandel-macaque** [comment]
@spouliot We ignored them in mac OS for a reason, no one has requested them. I am just following what we did in macOS. (I've removed the label.)

**Comment by spouliot** [comment]
> We ignored them in mac OS for a reason,

Yes, the API were not available cross-platform, so of limited use (unless someone provided a use case).

**Comment by mandel-macaque** [comment]
@spouliot issues is, I have not found any sample from apple or any example on how to use the API. I an add it if you want, should not be too much work.

**Review by dalexsoto — APPROVED** [review]
I am fine ignoring them for now and if someone needs it we can always add it later

**Pull request merged**
