### PR TITLE
[UIKit] UIGestureRecognizer's custon OnDispose method needs to queue the actual operation on the main thread

### PR DESCRIPTION
**Pull request by migueldeicaza**
Proposed fixed for:

https://github.com/xamarin/xamarin-macios/issues/5388

### CODE REVIEW

**Comment by migueldeicaza** [comment]
The problem is that by the time it hits the main thread, the handle will have been cleared.

The Dispose() implementation just injects the result of the Dispose attribute, before calling Dispose(disposing).   So there would be a potential race where the finalizer queue would run first, and release the handle, so our handle would be pointing to garbage.

That is why I took the ref, and then released it manually.

**Comment by rolfbjarne** [comment]
Do we really need to call `RemoveTarget` when `Dispose` is called from the GC? Won't things be freed anyway when the object is freed on the native side?

**Comment by migueldeicaza** [comment]
The hook is executed for all Dispose() kinds of invocations.   I do not think it harms to keep it.

**Comment by VincentDondain** [comment]
I think this PR broke this test:

```
GestureRecognizerTest
	[FAIL] GestureRecognizerTest.NoStrongCycles :   Any finalized
  Expected: True
  But was:  False

		  at MonoTouchFixtures.UIKit.GestureRecognizerTest.NoStrongCycles () [0x001ce] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/monotouch-test/UIKit/GestureRecognizerTest.cs:81 
		  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
		  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.7.0.62/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

**Pull request merged**
