### PR TITLE
[watchos][gamekit] Enable GameKit on watchOS

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build (to get beta 3 results)

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
superseded by #452

**Pull request closed without merging**
