### PR TITLE
[XM] Teach XM to add fobjc-runtime=macosx to clang 64-bit builds

### PR DESCRIPTION
**Pull request by chamons**
- As requested by Rolf here https://bugzilla.xamarin.com/show_bug.cgi?id=42889

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
LGTM but did we have a test case ? i.e. what's the origin of that bug report

**Comment by dalexsoto** [comment]
This got me curious and found this nice blog post about it, might not actually answer Sebastien's question but it is a great explanation http://www.sealiesoftware.com/blog/archive/2009/01/27/objc_explain_Non-fragile_ivars.html

**Comment by chamons** [comment]
@spouliot The origin was @rolfbjarne saying "hey we should do this" with the bug. Beyond that, we had some issues with the static registrar getting angry about various things not showing up in the header, but nothing definitive that I know enough to test against.

**Comment by spouliot** [comment]
@chamons sounds like it should go into cycle8 too

**Comment by chamons** [comment]
Good call @spouliot. I thought I had already made a card, but was mistaken - https://trello.com/c/u9CNwxse/97-xm-compile-with-non-fragile-runtime-for-64-bit

**Pull request merged**
