### PR TITLE
[mono] bump mono/2019-08

### PR DESCRIPTION
**Pull request by lewurm**
New commits in mono/mono:

* mono/mono@a0e7f9eaf2e [2019-08] [arm64_32] make "Debug Mode" work on Watch series 4 with --interpreter (#16886)
* mono/mono@6275840a7f8 Rename bundle identifier for the various Mono.frameworks we create for Xamarin.iOS. Fixes xamarin/xamarin-macios#7005. (#16901)
* mono/mono@25f60932839 [corlib] Fix building nunit-lite twice (#16895)
* mono/mono@7ec17ba1be9 [2019-08] [android sdk] Add aprofutil tool (#16884)
* mono/mono@f755f3b5391 [metadata] Fix leaks when handling a few attributes (#16850)
* mono/mono@5f9a2db39b0 [2019-08] Fix infrequent hangs in test-runner. (#16854)
* mono/mono@f31f5ea1f1b [2019-08] [threads] do not convert NULL thread name (#16828)
* mono/mono@20308e6f874 [aot] Do not wrap tool_prefix path when calling strip (#16820)
* mono/mono@cecda47c489 [aprofutil] Add -p and -f options
* mono/mono@824cc12ac3f Bump to mono/corefx@e79cf5b
* mono/mono@b77dc06a7e7 [aprofutil] Install the tool correctly (#16112)
* mono/mono@1848d78d60f [aotprof-tool] Initial import of AOT profiler tool (#15384)
* mono/mono@da0086e3042 [2019-08] Add RenamedEvent* to FSW sources from CoreFX (#16756)
* mono/mono@0297b21b030 [msbuild][roslyn] Bump msbuild and roslyn to pull in new versions (#16768)
* mono/mono@40631e3b9e3 [2019-08] [aot] move method_addresses to data.rel.so section to avoid text relocations (#16751)
* mono/mono@68b77674e20 Vtable [i] can be null so this should be check before use it. Fixes #16712
* mono/mono@4a0b4f41ede [mini] publish global patches after JitInfo has been added
* mono/mono@7a1f63fde68 [debugger][android] It was not initialising seq_points on MonoCompile on Android, so when was compiling dynamic methods, seq_points wasn't created and we got the assert when try to single step.

Diff: https://github.com/mono/mono/compare/29b1ac19c961b959a09097dbc0fe4cd567cc5298..a0e7f9eaf2e10fb3fa9d55b8ef651256a42ebb7e

### CODE REVIEW

**Comment by lewurm** [comment]
> 16:31:40 [0x70001195a000:] EXCEPTION handling: System.Xml.XmlException: Root element is missing.

is this a known issue?

**Comment by spouliot** [comment]
@lewurm that's normally because there's no (xml) results available - and the real cause happened earlier (e.g. crash, timeout)

**Comment by rolfbjarne** [comment]
> @lewurm that's normally because there's no (xml) results available - and the real cause happened earlier (e.g. crash, timeout)

It could also be that the test whose results we're trying to parse hasn't completed yet.

We run xharness.exe with `--trace=E:all`, which means that every exception will be printed to stdout, even if handled.

**Comment by lewurm** [comment]
bumped again, added:
* mono/mono@70d6903 [2019-08] [merp] Use a separate program as the hang supervisor. (#16900)
* mono/mono@4bff2b6 [offsets-tool] Install clang into the user-specific python directory.
* mono/mono@81894ec Implement WriteCore and ReadCore in DeflateStream
* mono/mono@bfbf823 [ci] Remove more XCODE32_DIR usages (#16964)
* mono/mono@ce01b20 Add net_4.8.xml to EXTRA_DIST and bump binary-reference-assemblies again
* mono/mono@7a587d7 Add .NET 4.8 reference assemblies (#16912)
* mono/mono@35e454a [sdks] Remove the mac32 build. (#16936)
* mono/mono@75eb342 [2019-08] [System] Make FileSystemWatcher backend non-static (#16926)
* mono/mono@5881981 [2019-08] [mini] Add missing membars when initializing rgctx entries (#16909)
* mono/mono@6290b6c Temporarily disable embedded ppdb data decompression (#16911)

**Comment by VincentDondain** [comment]
Thanks @lewurm, we're in no rush to merge this for now so I think it's good we're running tests on HEAD for now.

**Comment by lewurm** [comment]
good to merge?

**Comment by lewurm** [comment]
Actually, not good to merge:
```
 Xamarin.MMP.Tests.CodeStrippingTests.ExplictStripOption_ThirdPartyLibrary_AndWarnsIfSo(True,True): lipo usage did not match expectations
Expected: True
But was: False

Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(null,False,True): Did not contain two archs
Expected: 2
But was: 1

Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(True,True,True): Debug lipo usage did not match expectations
Expected: True
But was: False

Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(False,False,False): Did not contain two archs
Expected: 2
But was: 1
```

this is probably due to 

mono/mono@35e454a [sdks] Remove the mac32 build. (#16936)

**Comment by rolfbjarne** [comment]
This bump was included in #7044, so this PR is now redundant.

**Pull request closed without merging**
