### PR TITLE
[package] Remove creation of files/symlinks under /Developer

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by spouliot** [comment]
hopefully fix (at least help) install on 10.15

**Comment by mandel-macaque** [comment]
@spouliot We should add a fixes https://github.com/xamarin/xamarin-macios/issues/6504 

Which is one of the two issues we have with the .pkg atm.

**Comment by chamons** [comment]
@monojenkins backport to d16-3

**Comment by chamons** [comment]
@monojenkins backport to d16-2

**Pull request merged**
