### PR TITLE
[msbuild] Don't try to find frameworks in a directory that doesn't exist.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Check if the .app has a Frameworks directory before trying to iterate over any
*.framework directories it may have.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Comment by mandel-macaque** [comment]
failure is cataastrophic, and unrelated to the PR

**Review by mandel-macaque — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2154)

**Pull request merged**
