### PR TITLE
[Harness] Refactor RunDeviceTask.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Move most/all of the logic to a helper class so that it later can be
used in the CLI.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Like others, as a draft to simplify reviews.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.11', Running XM tests on '10.13', Running XM tests on '10.14', Running XM tests on '10.12', Running XM tests on '10.10', Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.11 failed (apitest)

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8386/2//console)
✅ Packages: 
* [xamarin.ios-13.21.0.53.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/f7163b5ecabfc48796fdbc5e6ba48a248157c928/2/package/xamarin.ios-13.21.0.53.pkg)
* [xamarin.mac-6.21.0.53.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/f7163b5ecabfc48796fdbc5e6ba48a248157c928/2/package/xamarin.mac-6.21.0.53.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/f7163b5ecabfc48796fdbc5e6ba48a248157c928/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/f7163b5ecabfc48796fdbc5e6ba48a248157c928/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/f7163b5ecabfc48796fdbc5e6ba48a248157c928/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/2/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.10', Running XM tests on '10.13', Running XM tests on '10.12', Running XM tests on '10.14', Running XM tests on '10.9', Running XM tests on '10.11', Running XM tests on '10.11'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8386/3//console)
✅ Packages: 
* [xamarin.ios-13.21.0.55.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/package/xamarin.ios-13.21.0.55.pkg)
* [xamarin.mac-6.21.0.55.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/package/xamarin.mac-6.21.0.55.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/3/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/d41a92818eaa8f41be969f6cff010dd5ed197406/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 184 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 2)
</details>

**Comment by mandel-macaque** [comment]
Mac OS X failures are unrelated: https://github.com/xamarin/xamarin-macios/issues/8395

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.11', Running XM tests on '10.10', Running XM tests on '10.14', Running XM tests on '10.9', Running XM tests on '10.12', Running XM tests on '10.13', Running XM tests on '10.13'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8386/4//console)
✅ Packages: 
* [xamarin.ios-13.21.0.58.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/package/xamarin.ios-13.21.0.58.pkg)
* [xamarin.mac-6.21.0.58.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/package/xamarin.mac-6.21.0.58.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8386/4/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8386/af9f269412065a965175bfba6789cf318adf4e9e/4/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 184 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 2)
</details>

**Comment by mandel-macaque** [comment]
mmptests and mac failures are unrelated.

**Pull request merged**
