### PR TITLE
[tests] Wrench has mono 4.6 and it requires an explict reference to System.Core to compile introspection tests

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build again (failures likely related to bots being updated to a newer Xcode beta)

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
failure due to beta5 being removed from the bots

**Pull request merged**
