### PR TITLE
[Mac] Update numerous availability tags from 10.12.1 to 10.12.2

### PR DESCRIPTION
**Pull request by timrisi**
From a 10.12.2 beta diff that was never implemented.

We're waiting to merge after the xcode8.3 branch has been merged back into master to try to avoid making that merge any harder than it has to be.

### CODE REVIEW

**Comment by spouliot** [comment]
This can now be merged (without causing conflicts with xcode8.3)

**Comment by timrisi** [comment]
Build

**Comment by timrisi** [comment]
Build

**Comment by timrisi** [comment]
Build

**Comment by timrisi** [comment]
Build

**Comment by spouliot** [comment]
@timrisi the build fails with 
```
17:19:42 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/src/appkit.cs(13683,0): error CS1028: Unexpected processor directive (no #if for this #else)
17:19:42 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/src/appkit.cs(13685,0): error CS1028: Unexpected processor directive (no #if for this #endif)
17:19:43 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/src/appkit.cs(13683,0): error CS1028: Unexpected processor directive (no #if for this #else)
17:19:43 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/src/appkit.cs(13685,0): error CS1028: Unexpected processor directive (no #if for this #endif)
```

Please always review logs on failures (before asking bots to build again) and file bugs (or fix) as appropriate.

**Comment by timrisi** [comment]
Yah I saw that in the last build.  There were several that failed with git issues before hand.

**Pull request merged**
