### PR TITLE
[net8.0] Updated Xamarin.Messaging and added Merq to ILMerge

### PR DESCRIPTION
**Pull request by mauroa**
- Updated Messaging to 1.9.59: includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.
- Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging
- Added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging

### CODE REVIEW

**Comment by dalexsoto** [comment]
@mauroa do we need this for .NET 8 Preview 2?

**Review by dalexsoto — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Closing, this will be a part of #17711.

**Pull request closed without merging**
