### PR TITLE
[linker] Remove more and earlier some attributes

### PR DESCRIPTION
**Pull request by spouliot**
* `[Model]` and `[Native]` are not needed at runtime if the dynamic
   registrar is removed

* Removing (and storing) the attributes earlier make it's possible for
  them not to be marked. IOW the attribute type itself (and not just the
  decorations) can be removed.

```diff
--- /var/folders/w_/zfvfxj_x3nbd8wlj9p4ck3xc0000gn/T/appcompare/diffcustomtooloutput/Microsoft.iOS.dll.a.text	2022-02-28 10:57:57.000000000 -0500
+++ /var/folders/w_/zfvfxj_x3nbd8wlj9p4ck3xc0000gn/T/appcompare/diffcustomtooloutput/Microsoft.iOS.dll.b.text	2022-02-28 10:57:57.000000000 -0500
@@ -43,14 +43,6 @@
 		{
 		}
 	}
-	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface)]
-	public sealed class ModelAttribute : Attribute
-	{
-		[MethodImpl(8)]
-		public ModelAttribute()
-		{
-		}
-	}
 	public sealed class You_Should_Not_Call_base_In_This_Method : Exception
 	{
 		[MethodImpl(8)]
@@ -584,11 +576,6 @@
 				return (Type)/*Error near IL_0001: Stack underflow*/;
 			}
 		}
-
-		[MethodImpl(8)]
-		public ProtocolAttribute()
-		{
-		}
 	}
 	[AttributeUsage(AttributeTargets.Interface, AllowMultiple = true)]
 	public sealed class ProtocolMemberAttribute : Attribute
@@ -1248,7 +1235,6 @@
 		}
 	}
 	[Register("Microsoft_iOS__UIKit_UIApplicationDelegate", false)]
-	[Model]
 	public class UIApplicationDelegate : NSObject, INativeObject, IDisposable
 	{
 		[MethodImpl(8)]
@@ -1270,7 +1256,6 @@
 		}
 	}
 	[Flags]
-	[Native]
 	public enum UIControlState : ulong
 	{
 		Normal = 0x0uL,
@@ -2931,14 +2916,6 @@
 			return (NativeHandle)/*Error near IL_0001: Stack underflow*/;
 		}
 	}
-	[AttributeUsage(AttributeTargets.Enum)]
-	public sealed class NativeAttribute : Attribute
-	{
-		[MethodImpl(8)]
-		public NativeAttribute()
-		{
-		}
-	}
 	public struct NativeHandle : IEquatable<NativeHandle>
 	{
 		private readonly IntPtr handle;
```

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
A few tests fails to build with:

>ILLink : MacOSX error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/tmp-test-dir/link all93/link all.csproj]
>ILLINK : error MM2362: The linker step 'Registrar' failed during processing: Object reference not set to an instance of an object. [/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/tmp-test-dir/link all93/link all.csproj]

* link all / Mac [dotnet] / Release: [build-Mac-20220228_121731.txt.zip](https://github.com/xamarin/xamarin-macios/files/8159900/build-Mac-20220228_121731.txt.zip)
* monotouch-test / iOS Unified 64-bits - simulator / Release (all optimizations) [dotnet]
* monotouch-test /tvOS - simulator / Release (all optimizations) [dotnet]

**Review by mandel-macaque — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by rolfbjarne** [comment]
I've been looking into this, and it's a lot trickier than it looks for various reasons, so I'll be closing this.

There's a tentative follow-up in #20224.

**Pull request closed without merging**
