### PR TITLE
[msbuild] Set $(CscDebugFileExt) also, whenever overriding $(CscToolExe)

### PR DESCRIPTION
**Pull request by radical**
This should fix issue: https://github.com/NuGet/Home/issues/3516

### CODE REVIEW

**Comment by jstedfast** [comment]
Looks good to me

**Comment by kzu** [comment]
@joj do you envision this being a problem for XVS? I don't think so, but I'd like to confirm

**Comment by spouliot** [comment]
@kzu is @joj around ? I'd like to merge that before we branch c9 so it gets more testing. thanks!

**Comment by joj** [comment]
We're not using that item as far as I know. Debug uses a completely different mechanism and pdb2mdb looks for mdb files and converts them. That said, I cannot guarantee this will not break us. I say, let's merge and we'll fix it if it breaks.

**Comment by kzu** [comment]
nudge @joj to try this out after a bump, to see if anything broke?

**Pull request merged**
