### PR TITLE
[msbuild] Emit a build error when CFBundleIdentifier is null/empty

### PR DESCRIPTION
**Pull request by jstedfast**
The logic that attempted to auto-calculate a CFBundleIdentifier for the Info.plist if it was missing has been around since the days of MonoTouch 1.0 but it realistically serves no purpose and can instead be a source of confusion if that code path is actually hit.

Instead, when this value is missing, fail the build. This is the only way to force the user to provide a valid CFBundleIdentifier for their app.

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59572

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Will both VS and VSfM will set the CFBundleIdentifier when creating new projects?

**Comment by jstedfast** [comment]
VSfM does, but I don't know about VS - but I suspect they do (otherwise that would be broken).

**Comment by emaf** [comment]
VS does it as well, all the new projects have a default CFBundleIdentifier based on the project name.

**Comment by jstedfast** [comment]
Seems that the build error was an error uploading build artifacts?

**Comment by spouliot** [comment]
@jstedfast there's no uploading artifacts from Jenkins 
The issue came from watchOS simulator failing to load
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5157/Test_Report/
known issue -> https://bugzilla.xamarin.com/show_bug.cgi?id=55719

**Comment by rolfbjarne** [comment]
@GouriKumari FYI this will likely cause several samples to fail to build with an error like this:

> [sample] does not define CFBundleIdentifier

This needs to be fixed in each sample by adding a CFBundleIdentifer to the sample's Info.plist.

**Pull request merged**
