### PR TITLE
[CI] Fix API diff uploads since they broke when we wanted to continue on failure.

### PR DESCRIPTION
**Pull request by mandel-macaque**
AZP yaml variables vs parameter is hard. The template ignores the settings of the run time variables resulting in skipping the upload and we later have urls that point nowhere. Latests comment in the commit shows we fixed this.

### CODE REVIEW

**Review by spouliot — APPROVED** [review]
I'm beginning to think that there should be absolutely no logic inside the yaml files.
IOW only variables and constants (no condition)
The rest should be calling scripts (shell, csx) that can be tested independently and returns `0` or fail

**Comment by mandel-macaque** [comment]
@spouliot problem.. here is the logic to execute yaml steps, there is no way around that :/

**Comment by spouliot** [comment]
> @spouliot problem.. here is the logic to execute yaml steps, there is no way around that :/

@mandel-macaque then the human race is doomed :( maybe AI will be able to figure it out once we're out of the way

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@spouliot is so bad that we started sharpliner ;)

**Pull request merged**
