### PR TITLE
[UIKit] Correct nullability attributes for parts of UIKit

### PR DESCRIPTION
**Pull request by rpendleton**
These changes correct some of the nullability attributes for the UIKit bindings. Although UIKit has several hundred lines of xtro-sharpie ignores related to nullability, this PR only fixes a few of them.

I wasn't sure where to draw the line, but in the end, I essentially fixed most of `UIViewController` and all of `UITableView` and `UICollectionView`. These classes were the ones that led to the most `// ReSharper disable` comments being added in my team's codebase, and/or that led to crashes being introduced by devs following ReSharper's suggestions to remove "unnecessary" null-checks.

These changes were largely based on the instructions given by @spouliot in [#6154](https://github.com/xamarin/xamarin-macios/issues/6154#issuecomment-620014843). However, I noticed the xtro-sharpie ignore files have been duplicated in the `api-annotations-dotnet` directory since then, so I updated the .ignore and .todo files in that directory as well.

If the process has changed since that comment was written, I can make any additional changes that are needed.

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]
This looks great! Thanks!

**Comment by rolfbjarne** [comment]
> These changes were largely based on the instructions given by @spouliot in [#6154](https://github.com/xamarin/xamarin-macios/issues/6154#issuecomment-620014843). However, I noticed the xtro-sharpie ignore files have been duplicated in the `api-annotations-dotnet` directory since then, so I updated the .ignore and .todo files in that directory as well.

That's correct, since spouliot wrote those instructions, we have a different set if xtro files for the .NET assemblies, and you'll have to remove the same entries from those files as well. I've updated the instructions in that comment accordingly.

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by chamons** [comment]
Looks like some of the CI choked on the build:

```##[error]We stopped hearing from agent VSM-XAM-35.BigSur.arm64. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610```

@mandel-macaque - Can this go in? I _think_ that's signing stuff and this is fine, but I'm out of the loop here.

**Comment by mandel-macaque** [comment]
Results seem ok, but I have merge with main and will re-trigger a build.

**Comment by rolfbjarne** [comment]
Great work! Thanks a lot!

**Pull request merged**
