### PR TITLE
[Xcode11] [carplay] Updates for beta 5

### PR DESCRIPTION
**Pull request by whitneyschmidt**

### CODE REVIEW

**Comment by spouliot** [comment]
why was this closed ? I can't see another PR with the changes (which mostly look correct, once xtro data is updated)

**Comment by spouliot** [comment]
@whitneyschmidt so looking at a recent PR you can see that the API is still missing
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/11096/Test_20Report/

You should have the same result by running xtro locally.

**Comment by whitneyschmidt** [comment]
@spouliot - this should be good to go once build/test validation comes back. I checked xtro results locally :) Don't look at the commit history...

**Comment by dalexsoto** [comment]
Yup better than doing it manually like some time ago :)

**Pull request merged**
