### PR TITLE
Fix mmp rebuild logic to detect mmp failures and rebuild

### PR DESCRIPTION
**Pull request by chamons**
- https://bugzilla.xamarin.com/show_bug.cgi?id=46508

Since we were previously looking for the .exe instead of the launcher, mmp
failures would come back as good and we wouldn't rebuild. What we want
to do is look for the native launcher, which we perviously were doing wrong.

### CODE REVIEW

**Comment by chamons** [comment]
@jstedfast Could you review? See if XI has a similar bug?

**Comment by spouliot** [comment]
Tests don't compile

```
20:50:50 src/MMPTest.cs(487,2): error CS1525: Unexpected symbol `}', expecting `)' or `,'
20:50:50 src/MMPTest.cs(487,3): error CS1002: ; expected
20:50:50 
	Task "Csc" execution -- FAILED
```

**Comment by chamons** [comment]
Bah. It's what I get for doing a "fast" clean merge/resolve...

**Comment by chamons** [comment]
This needs to hit C9 when landed.

**Comment by rolfbjarne** [comment]
build

**Comment by chamons** [comment]
Hmm. That passed locally. I'll take a look.

**Comment by spouliot** [comment]
The failure seems related to using 10.12 API on the jenkins bots (that are still on 10.11).

**Comment by chamons** [comment]
@spouliot No, those tests are unrelated to this PR (did we just bump xcode's on the bots)?

In any case, that was the static registrar thing I mentioned on Monday and during on 1-on-1. I'm working up fix now.

**Comment by chamons** [comment]
https://github.com/xamarin/xamarin-macios/pull/1164 has that fix.

**Comment by chamons** [comment]
build

**Comment by jstedfast** [comment]
LGTM

**Pull request merged**
