### PR TITLE
[msbuild] Force-Init AppleSdkSettings in DetectSdkLocationsTaskBase

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59756

### CODE REVIEW

**Comment by VincentDondain** [comment]
Agreed, I approved the fix itself because it does fix the issue you reported but I very much agree this code needs a cleanup (:
That can be done either in this PR or in a subsequent PR.

**Comment by jstedfast** [comment]
Those changes will all require changes to the IDE's as well which is a lot more work. I wanted to avoid additional work beyond what would easily fix this problem for your MSBuild needs.

**Comment by abock** [comment]
It helps, but if you make `Init` public, you can no longer rename it. Given that `Init` was private before, I do not see why this should not be done now.

Removing `Changed` is a completely separate topic as has been said, if the IDEs are in fact using it.

Similarly, I do not see why removing the dead/commented out code could not be done now. Or at least reference the bugs/PRs in question as comments.

**Comment by jstedfast** [comment]
Init() seems fine to me as a public name until we find a way of using an instance instead of a static class.

**Comment by abock** [comment]
Except for the part where it's intended/okay to call it multiple times. Seems odd, but at this point I will just stop caring.

**Comment by rolfbjarne** [comment]
We already have bug #[15041](https://bugzilla.xamarin.com/show_bug.cgi?id=15041) to add support for specifying the Xcode location using a MSBuild variable; it sounds like a good idea to do the static->instance cleanup at the same time.

IOW it seems this PR is a workaround that's good enough until then.

**Pull request merged**
