### PR TITLE
[XM] Fix static registrar under Xcode 8.2 with another hack

### PR DESCRIPTION
**Pull request by chamons**
- Generalized the hack a bit. If we continue to need them
we can make it more data driven

### CODE REVIEW

**Comment by chamons** [comment]
Pretty trivial fix, but Static Registrar is your area @rolfbjarne could you review?

**Comment by spouliot** [comment]
If correct this should be backported to `xcode8.2` since this is the last issue blocking green builds on that branch.

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
The problem is that the TouchBar APIs should have gone into the xcode8.2 branch, not master.

master is still using Xcode 8.1, which is why this is failing.

**Comment by rolfbjarne** [comment]
BTW the patch itself looks fine 👍

**Comment by chamons** [comment]
Build

**Pull request merged**
