### PR TITLE
Update Xamarin.Messaging to 1.8.0

### PR DESCRIPTION
**Pull request by jknaudt21**

### CODE REVIEW

**Review by emaf — APPROVED** [review]

**Comment by dalexsoto** [comment]
@emaf can this change go into `release/7.0.1xx-xcode14-rc2` (17.4) and `release/6.0.4xx-xcode14`? Since Xcode 14.1 will include main changes.

**Review by dalexsoto — CHANGES_REQUESTED** [review]
Wait for @emaf response before merging

**Review by rolfbjarne — APPROVED** [review]

**Comment by emaf** [comment]
@dalexsoto No, this is for 17.5 so we should hold this one if main is still 17.4

**Comment by mauroa** [comment]
Closing in favor of https://github.com/xamarin/xamarin-macios/pull/16281

**Pull request closed without merging**
