### PR TITLE
Bump mono to 2019-08@528103728fc2aedb7b6062e11255d39a0ed3f31c to add missing NS2.1 APIs

### PR DESCRIPTION
**Pull request by akoeplinger**
See https://github.com/mono/mono/issues/17064.

The 2019-08 version of the fix adds a new assembly with NS2.1 APIs that we stubbed out in 2019-06: System.Data.DataSetExtensions.dll

Commit diff: https://github.com/mono/mono/compare/d8441deead62b3af591c6daefb5013b09ef1ab8b...528103728fc2aedb7b6062e11255d39a0ed3f31c

### CODE REVIEW

**Comment by akoeplinger** [comment]
This needs to be ported to all branches that use mono 2019-08.

**Comment by mandel-macaque** [comment]
@VincentDondain please do the backport needed for this to be in all 2019-08 related branches since you are the albert.

**Comment by akoeplinger** [comment]
@mandel-macaque yes there should be a corresponding test dll.

**Comment by VincentDondain** [comment]
@monojenkins backport to d16-4

**Comment by dalexsoto** [comment]
Failures are due to [FAIL] UrlProtocolTest.RegistrarTest : DidReceiveData is failing because of user agent sniffing on microsoft.com will be fixed by https://github.com/xamarin/xamarin-macios/pull/7154

**Pull request merged**
