### PR TITLE
Add Windows support for building Xamarin.Mac

### PR DESCRIPTION
**Pull request by joj**
@rolfbjarne @jstedfast @mandel-macaque This is the same as PR 77, but separated in 3 commits. I also added the new file to the make, so no further effort should be required. Please review by commit. Reviewing as a PR will be identical to the last one (with all the adds and deletes), but as separate commits you'll only get the differences.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
That's _much_ easier to review 😄

And from my side this looks good.

**Comment by jstedfast** [comment]
Looks good!

**Comment by joj** [comment]
Excellent! I'll wait for confirmation from Jenkins and then ping you for a merge :)

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by jstedfast** [comment]
```
15:39:29 Tasks/DetectSdkLocations.cs(6,36): error CS0246: The type or namespace name `DetectSdkLocationsTaskBase' could not be found. Are you missing `Xamarin.iOS.Tasks' using directive?
15:39:29 Tasks/EmbedProvisionProfile.cs(6,39): error CS0246: The type or namespace name `EmbedProvisionProfileTaskBase' could not be found. Are you missing an assembly reference?
15:39:29 Tasks/Mmp.cs(5,21): error CS0246: The type or namespace name `MmpTaskBase' could not be found. Are you missing an assembly reference?
```

**Comment by joj** [comment]
Referenced iOS instead of Mac... fixing. Also, weird. But fixing.

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
