### PR TITLE
[d15-7] Build with CSC instead of MCS (#3393)

### PR DESCRIPTION
**Pull request by chamons**
- Improve error messages from install-source when crashing

### CODE REVIEW

**Comment by spouliot** [comment]
Let's wait for the bots to give us results from `master` (including device tests) before merging to `d15-7`

**Comment by rolfbjarne** [comment]
Device tests for [master](http://xamarin-storage/macios-mac-master/3b/3b56d5e780c636b719c0899234cbc4861750ab0a/8f6fde3dd11a/jenkins-results/tests/index.html): all tvOS tests passed. No iOS/watchOS tests passed due to ongoing wifi network issues, which is unrelated.

**Comment by spouliot** [comment]
As far as the compiler is involved I think it covered enough.
Additional testing will be done on 15.7 and better include this sooner than later.
Removing label.

**Comment by spouliot** [comment]
@chamons unless other concerns were found let's merge this :)

**Comment by chamons** [comment]
Yeehaw. Landing compiler change in a release branch.

**Pull request merged**
