### PR TITLE
[SystemLog] Enable nullability + a few other fixes.

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Enable nullability and fix code accordingly.
* Use 'is' and 'is not' instead of '==' and '!=' for object identity.
* Use 'nameof (parameter)' instaed of string constants.

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Comment by mandel-macaque** [comment]
funcky bot, needs a re-trigger

**Review by dalexsoto — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/581).

**Pull request merged**
