### PR TITLE
Bump for Xcode 10 beta 4

### PR DESCRIPTION
**Pull request by dalexsoto**
**A note about merging this PR**: 

Let's **NOT** squash commits and do a merge commit instead so it is easier to revert the macOS tests and bumps of min versions to 10.9 in case we do not want to follow this path.

### CODE REVIEW

**Comment by VincentDondain** [comment]
```
/Applications/Xcode10-beta4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/simd/math.h:1403:10: fatal error:
      'cmath' file not found
#include <cmath>
```

**Comment by chamons** [comment]
That 👍 is obviously conditional on builds/test passing, but the idea looks right.

**Comment by dalexsoto** [comment]
We are getting there

**Comment by dalexsoto** [comment]
So I've verified locally that intro and xtro pass on both iOS 12 B4 and macOS 10.13/10.14 B4 also monotouch-tests run fine for me.

About MTouch it is still running locally so I will report back, that said those failures seemed to be legal and we might need to file an issue in order to merge this.

**A note about merging this PR**: Let's **NOT** squash commits and do a merge commit instead so it is easier to revert the macOS tests and bumps of min versions to 10.9 in case we do not want to follow this path.

**Comment by VincentDondain** [comment]
I think the timed out tests would pass if we re run but not the mtouch test. Not sure what's wrong with it.

**Comment by VincentDondain** [comment]
Full verbose build log of the mtouch AOT failure: https://gist.github.com/VincentDondain/faf612e93c8568aec1024aa2f2ad3a76

@dalexsoto found out it was related to https://github.com/xamarin/xamarin-macios/commit/53fdc017a8d3f0eaf638c987fd8bc964e6a61a29#diff-ff9e35b87c66245efc6f4798e6aa6cd9R12. The mtouch tests didn't run for this PR.

**Comment by dalexsoto** [comment]
build

**Comment by dalexsoto** [comment]
Breaking changes are expected from API changes from the previous beta

**Pull request merged**
