### PR TITLE
[msbuild] Extensions must be compiled before they can be copied into the main app.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failure is unrelated (launch failure due to bug #[50419](https://bugzilla.xamarin.com/show_bug.cgi?id=50419)).

**Comment by jstedfast** [comment]
`_CompileToNative` will compile the main app bundle, but not the AppExtension(s).

**Comment by jstedfast** [comment]
I take it that pr #1380 broke something. Your change effectively just reverses the change made in that commit, so maybe a better solution is to revert my commit?

**Comment by rolfbjarne** [comment]
Random build failure due to bug #[50634](https://bugzilla.xamarin.com/show_bug.cgi?id=50634).

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
Slack conversation/context:

```
Jeffrey Stedfast [17:54] @rolf do you have a test case for https://github.com/xamarin/xamarin-macios/pull/1430 ?
Jeffrey Stedfast [17:54] I am trying to figure out why it is breaking
Jeffrey Stedfast [17:54] I suspect that the real issue is some sort of target ordering problem
Jeffrey Stedfast [17:55] and maybe I just need some more explicit dependency ordering
Rolf Kvinge [19:03] @jeff that only applies when the extensions are built in the main app's mtouch invocation
Rolf Kvinge [19:04]  Which isn't in master yet, but I have that change done locally
Jeffrey Stedfast [19:04] oh
Rolf Kvinge [19:05] Because the extension executable will be put in the extension project's bin directory, it has to be done before copying the appex into the main app
Jeffrey Stedfast [19:06] if the AppExtensions need to be built before compiling the main app, we can prob just revert my commit that reordered the _CompileToNative target
Jeffrey Stedfast [19:06]  er, I got that backwards
Rolf Kvinge [19:06] The extensions and the main app will both be done in the same _CompileToNative task
Jeffrey Stedfast [19:07] right. what I'm saying is that your patch is essentially a revert of my commit
Jeffrey Stedfast [19:07]  afaict
```

**Comment by rolfbjarne** [comment]
Closing in favor of PR #1454.

**Pull request closed without merging**
