### PR TITLE
Handle any exceptions when returning from managed code back to our native runtime.

### PR DESCRIPTION
**Pull request by rolfbjarne**
There's a wrench lane for this: https://wrench.internalx.com/Wrench/ViewTable.aspx?lane_id=3392&host_id=243

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
