### PR TITLE
Set TrimMode to partial if not set

### PR DESCRIPTION
**Pull request by agocke**
Companion to https://github.com/dotnet/linker/pull/2856

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@agocke can you please take care of the conflicts?

**Comment by agocke** [comment]
These settings will only work in the .NET 7 SDK. Technically these settings are remapped in the task, so the question is what version of the task is used.

**Comment by agocke** [comment]
Note: the SDK change was just merged (https://github.com/dotnet/sdk/pull/26246) so we'll need to merge this soon to keep compat in .NET 7

**Comment by rolfbjarne** [comment]
> These settings will only work in the .NET 7 SDK.

OK, the PR should target the `net7.0` branch then, because our `main` branch is still using .NET 6.

**Comment by agocke** [comment]
Done. Anything else?

**Comment by rolfbjarne** [comment]
This looks good to go, except we'll have to wait until we get the corresponding linker changes from dotnet/runtime, because right now some tests fail with:

> Invalid assembly action 'partial'.

**Comment by agocke** [comment]
I didn't see a Darc subscription to the linker so I just pulled in the latest version manually.

**Comment by agocke** [comment]
It looks like this passes except for packaging, which is still waiting for an agent after 4 hours. @rolfbjarne I'll leave it up to you, but I think we should merge this ASAP. Xamarin apps will be broken with the new defaults.

**Comment by rolfbjarne** [comment]
> It looks like this passes except for packaging, which is still waiting for an agent after 4 hours. @rolfbjarne I'll leave it up to you, but I think we should merge this ASAP. Xamarin apps will be broken with the new defaults.

Our bots are a bit overloaded this week, so it took some time for the tests to run.

Unfortunately there are test failures which look related. I'll have a look today to see if I can figure out what's happening, but I'll be on vacation after today so it's likely this won't be completed/merged until I'm back. Our tests worked fine without these changes though, so I'm not sure apps are that broken, and we're in preview anyway for .NET 7, so it shouldn't be that much of a problem if it takes a while to get this merged.

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
Failures here still look related, we'll need to wait for @rolfbjarne's input.

**Pull request merged**
