### PR TITLE
[jenkins] Abort any executing builds on internal jenkins when new builds are scheduled for pull requests.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/1/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2/display/redirect) (on internal Jenkins) failed in stage 'Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.8 failed (introspection)

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/dc0f3fa4f375b387eab3ca61898ea56cd5cd71bb/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/dc0f3fa4f375b387eab3ca61898ea56cd5cd71bb/2/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/dc0f3fa4f375b387eab3ca61898ea56cd5cd71bb/2/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on macOS 10.8 failed (introspection)](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on macOS 10.10 failed (introspection)](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on macOS 10.7 failed (introspection)](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on macOS 10.9 failed (introspection)](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/2/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/4/display/redirect)

🔥 [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/4/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/4//console) 🔥

**Comment by rolfbjarne** [comment]
This is ready for review now.

The first [comment](https://github.com/xamarin/xamarin-macios/pull/4518#issuecomment-408439178) from xamarin-release-manager above is how aborted builds are reported.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (likely) aborted](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/5/display/redirect)

🔥 [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/5/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/6/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4518/6//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/0ef6d0c90eeb612d5b60343f073ec8fa4dd01087/6/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/0ef6d0c90eeb612d5b60343f073ec8fa4dd01087/6/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4518/0ef6d0c90eeb612d5b60343f073ec8fa4dd01087/6/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Pull request merged**
