### PR TITLE
[xcode15] Add support for Xcode 15 and corresponding OS versions.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by Westat-Transportation** [comment]
It looks like CLMonitor's interface was implemented in this PR but no classes were created.  So the API can't be used?  Am I reading this right @rolfbjarne ?

**Comment by rolfbjarne** [comment]
> It looks like CLMonitor's interface was implemented in this PR but no classes were created. So the API can't be used? Am I reading this right @rolfbjarne & @dalexsoto ?

Not sure what you mean; you should be able to use CLMonitor just fine in your code:

```cs
using CoreLocation;

var monitor = CLMonitor.RequestMonitor (...);
```

**Comment by Westat-Transportation** [comment]
Ok, I'll give that a try.  I was looking at some Swift examples online and they were directly instantiating a CLMonitor class and I could not find any evidence that such a constructor existed:
```csharp
var monitor = new CLMonitor("my_monitor");
```

**Comment by Westat-Transportation** [comment]
Ok, that does not work b/c `CLMonitor.RequestMonitor(...)` returns void.  After poking around and looking over Apple's ObjectiveC docs I arrived at this:
```csharp
            var eventQueue = new DispatchQueue("GeofencesQueue");
            var eventAction = new Action<CLMonitor, CLMonitoringEvent>((monitor, monitorEvent) => 
            { 
                if (monitorEvent.Identifier == "AppCondition" && monitorEvent.State == CLMonitoringState.Satisfied)
                {
                    Debug.WriteLine("Entered region");
                }
                else if (monitorEvent.Identifier == "AppCondition" && monitorEvent.State == CLMonitoringState.Unsatisfied)
                {
                    Debug.WriteLine("Exited region");
                }
            });
            var monitorCfg = CLMonitorConfiguration.Create("AppMonitor", eventQueue, eventAction);
            var monitorAction = new Action<CLMonitor>((monitor) => 
            {
                var condition = new CLCircularGeographicCondition(new CLLocationCoordinate2D(33.0, -85.0), 10);
                monitor.AddCondition(condition, "AppCondition");
            });
            CLMonitor.RequestMonitor(monitorCfg, monitorAction);
```
Will try on a physical phone soon and report back.  Thanks for pointing me to the right direction.

**Pull request merged**
