### PR TITLE
[dotnet] Add the Sdk build files to the Sdk NuGet.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Also add a very simple net5 test app (which doesn't build yet).

Current (expected) build result:

    > xamarin-macios/tests/dotnet/MySingleView $ dotnet build
    Microsoft (R) Build Engine version 16.7.0-preview-20258-02+26f6d1d87 for .NET
    Copyright (C) Microsoft Corporation. All rights reserved.

      Determining projects to restore...
    xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.ios-x64 with version (= 5.0.0-preview.6.20264.1)
    xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj : error NU1102:   - Found 1 version(s) in nuget.org [ Nearest version: 5.0.0-preview.4.20251.6 ]
    xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj : error NU1102:   - Found 1 version(s) in Nuget Official [ Nearest version: 5.0.0-preview.4.20251.6 ]
    xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj : error NU1102:   - Found 0 version(s) in local-dotnet-feed
    xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj : error NU1102:   - Found 0 version(s) in Dotnet arcade
      Failed to restore xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj (in 951 ms).

This fails because the .NET build logic isn't being told that it should look
for the mono runtime packs instead of the .NET Core runtime packs.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8644/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8644/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8644/1//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8644/1//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.0.246.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/xamarin.ios-13.21.0.246.pkg)
* [xamarin.mac-6.21.0.246.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/xamarin.mac-6.21.0.246.pkg)
* [Microsoft.iOS.Ref.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Ref.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Runtime.ios-arm.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Runtime.ios-arm64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Runtime.ios-x64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Runtime.ios-x86.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.iOS.Sdk.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.iOS.Sdk.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8644.38+sha.06b8955fb.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/jenkins-results/apicomparison/api-diff.html) (no change)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8644/06b8955fbcdf53018910be6f2f5d1a65f31ed012/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>30 tests failed, 154 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * framework-test/iOS Unified 64-bits - simulator/Debug: Failed
 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug: Failed
 * fsharp/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * dont link/iOS Unified 64-bits - simulator/Debug: Failed
 * dont link/iOS Unified 64-bits - simulator/Release: Failed
 * link all/iOS Unified 64-bits - simulator/Debug: Failed
 * link all/iOS Unified 64-bits - simulator/Release: Failed
 * link sdk/iOS Unified 64-bits - simulator/Debug: Failed
 * link sdk/iOS Unified 64-bits - simulator/Release: Failed
 * mono-native-compat/iOS Unified 64-bits - simulator/Debug: Failed
 * mono-native-compat/iOS Unified Today Extension 64-bits - simulator/Debug: Failed
 * mono-native-unified/iOS Unified 64-bits - simulator/Debug: Failed
 * mono-native-unified/iOS Unified Today Extension 64-bits - simulator/Debug: Failed
 * [NUnit] Mono BCL tests group 1/iOS Unified 64-bits - simulator/Debug: Failed
 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono BCL tests group 3/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono BCL tests group 4/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono BCL tests group 5/iOS Unified 64-bits - simulator/Debug: Failed
 * mscorlib Part 1/iOS Unified 64-bits - simulator/Debug: Failed
 * mscorlib Part 2/iOS Unified 64-bits - simulator/Debug: Failed
 * mscorlib Part 3/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemCoreXunit Part 1/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemCoreXunit Part 2/iOS Unified 64-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (all optimizations): Failed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* monotouch-test/watchOS: https://github.com/xamarin/maccore/issues/581
* iOS 64-bit tests: https://github.com/xamarin/maccore/issues/2225

**Comment by filipnavara** [comment]
> This fails because the .NET build logic isn't being told that it should look for the mono runtime packs instead of the .NET Core runtime packs.

The runtime pack name actually looks fine. I guess nuget.config is missing reference to the proper package repository? (`<add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />`)

**Comment by rolfbjarne** [comment]
> The runtime pack name actually looks fine. I guess nuget.config is missing reference to the proper package repository?

You're right, I'll fix that in a later PR.

**Pull request merged**
