### PR TITLE
[d16-4] Bump mono 2019-08@ef75d4be

### PR DESCRIPTION
**Pull request by VincentDondain**
New commits in mono/mono:

* mono/mono@ef75d4bef75 [2019-08]   BeginConnect complete to early when not using callback. (#17416)

Diff: https://github.com/mono/mono/compare/01dbbb746f4174130ef1226e4a9683f2f9a70f9d..ef75d4bef7509b23103fffa2acca039e9acbb157

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Is good to see that mono added a new test for that \o/

**Comment by mandel-macaque** [comment]
As usual, memory issues on 32b, will ignore and will create the appropriate issue on the mono side.

**Comment by mandel-macaque** [comment]
@dalexsoto @VincentDondain issues are unrelated to the bump, that has nee on and off. Confirmed by @rolfbjarne

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* monotouch-test/iOS 32-bits: https://github.com/xamarin/maccore/issues/1391
* monotouch-test/watchOS 32-bits: https://github.com/xamarin/maccore/issues/581

**Pull request merged**
