### PR TITLE
[Maccore] Bump maccore to pick up some ci fixes.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by chamons** [comment]
👍  Approved for d16-0 as it is a CI fix.

**Comment by rolfbjarne** [comment]
We'll probably need https://github.com/xamarin/maccore/commit/a5782e3dc78c51da327013ddc8a57f36d053f9ec as well, so wait with merging this to see if that commit works out in master, then we can get everything at the same time.

**Comment by dalexsoto** [comment]
Added don’t merge label so we don’t miss Rolf’s comment

**Comment by mandel-macaque** [comment]
@dalexsoto sounds good, would be nice to get this to make sure we do not get red builds in d16-0

**Comment by rolfbjarne** [comment]
Upcoming additional maccore commit: https://github.com/xamarin/maccore/pull/1421

**Pull request merged**
