### PR TITLE
Fix sending MidiPacket when MidiPacket has been created using a point…

### PR DESCRIPTION
**Pull request by jamesdlow**
Fix sending MidiPacket when MidiPacket has been created using a pointer to a byte[] rather than a byte[] passed as a reference.
MidiPacket.bytes is intiailized to a Array.Empty<byte> so it is never null, and so packet.BytePointer is never used.
We therefore need to check for ByteArray.Length being 0.
Midipacket.bytes is never 0 when intiailized to a 0 length byte[] as that constructor checked for 0 length byte[]

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@jamesdlow would you be able to create a self-contained test case for this (not using `managed-midi`)?

**Comment by mandel-macaque** [comment]
@jamesdlow @rolfbjarne  I have requested a rerun for the failing test.

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Marking as `do-not-merge` until we have tests, since this particular piece of code has regressed multiple times already.

**Comment by jamesdlow** [comment]
@microsoft-github-policy-service agree

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Pull request merged**
