### PR TITLE
[mtouch/mmp/bgen] Add support for response files.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This is the first part of the fix for #56501.

https://bugzilla.xamarin.com/show_bug.cgi?id=56501

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@spouliot / @chamons it turns out this is a slight breaking change, any argument starting with a `@` will now be parsed as a response file. This means this will break:

    --sim @myapp.app

although this version will continue to work:

    --sim=@myapp.app

I think it's quite rare to start filenames with an `@` character, so I _think_ we'll be fine... what do you think?

I can minimize the risk by going over the MSBuild tasks and make sure they use the argument version that works, but that doesn't help for root assemblies, since those don't have an accompanying option (although that could be added, something like `--root-assembly=...`).

It does however turn something that looked trivial into something quite more complex 😒

**Comment by chamons** [comment]
I'm fine w\ that personally. An app/filename starting with @ is extremely unlikely.

I'll let @spouliot give the 👍 / 👎  since XI is more conservative in not breaking people.

**Comment by spouliot** [comment]
@rolfbjarne does quoting work ? e.g. `--sim "@myapp.app"` ?

This new feature will need to be added to the release notes and we can mention a workaround (one is needed) in case people have files starting with a "@"

**Comment by rolfbjarne** [comment]
@spouliot no, quoting won't work (the args parameter to the managed Main method doesn't get the quotes). Also if it had worked, it would become impossible to quote response files :smile:

The universal workaround is of course to rename all files that start with `@` to something else.

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
`csc` seems to accept `@@x` to load a response file `@x`. Can we get the same behaviour ? Something tells me we have someone using `@` (and there are such apps in the App Store)

**Comment by rolfbjarne** [comment]
> `csc` seems to accept `@@x` to load a response file `@x`. Can we get the same behaviour?

That should already work, but I assume you mean that passing `@x` should _not_ try to load a response file? That'll be a bit more complicated, because Mono.Options doesn't support that, but it should be possible to work around it somehow.

**Comment by spouliot** [comment]
The ideal behaviour (which is what `csc` seems to do) would be:

* `@x` -> load response file `x`;

* `@@x` -> use `@x` as the argument;

That would not block any existing scenario but I'm not sure if Mono.Options supports that...

**Comment by rolfbjarne** [comment]
@spouliot how is that less breaking than what this PR proposes? `@x` will still change from being an option to an argument (`--foo @x`) to a response file.

**Comment by spouliot** [comment]
It's for files that starts with an `@`, e.g. assemblies, for which no alternative exists in the PR (unless `--root-assembly=...` is added). 

If we have a different way to achieve this then it's fine too :) but we cannot assume such files don't exists (or that they can be easily renamed).

**Comment by rolfbjarne** [comment]
OK; then I think I prefer `--root-assembly`, since it's a bit more obvious what's going on.

**Comment by rolfbjarne** [comment]
@emaf are you launching mtouch/mmp directly for any reason, or are you only doing it through the MSBuild tasks? If you're launching directly, you may have to update the code that creates the mtouch/mmp arguments.

**Comment by emaf** [comment]
@rolfbjarne we're calling both through the MSBuild tasks. Does the same apply to mlaunch?

**Comment by rolfbjarne** [comment]
@emaf No, the same does not apply to mlaunch, we're not implementing support for response files to mlaunch. I guess that means nothing has to change on your side (which is good :smile:) Thanks!

**Pull request merged**
