### PR TITLE
Bump F# to 4.0.1.5

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
```make[3]: *** No rule to make target `/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/fsharp/packages/FSharp.Compiler.Tools.4.0.0.1/tools/FSharp.Core.dll', needed by `build-proto'.  Stop.```

@alexischr ^ did you hit this with mono ?

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
@kumpera I have not heard back from @alexischr and the previous tag does not build either. XI/XM fsharp tag remains the same as C7 was.

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by mandel-macaque** [comment]
build

**Comment by spouliot** [comment]
Nothing changed so I'm not sure why the latest worked... but it might be due to a newer (4.6) mono.
@mandel-macaque out of curiosity why did you kick a new bu1ld ?

**Pull request merged**
