### PR TITLE
[AppKit] Update bindings to Xcode 12 Beta 5 

### PR DESCRIPTION
**Pull request by tj-devel709**
I closed the last PR, made my changes, and force pushed which did not allow me to open the PR back up. I apologize for that!
Here is the link to closed PR: https://github.com/xamarin/xamarin-macios/pull/9476

### CODE REVIEW

**Comment by tj-devel709** [comment]
Hi @spouliot Manuel helped me fix the issue with the merge conflicts so hopefully it is okay now!

**Comment by tj-devel709** [comment]
@whitneyschmid thanks for your comment in my last PR https://github.com/xamarin/xamarin-macios/pull/9476, but I think we were both deceived by Github. In the `Files Changed` tab, it shows arrows where you can reveal like 20 lines higher and lower than what it's showing you originally but eventually it gives up and the arrow option goes away but there is still a break in the line number. In this case it goes from around line 3XX to line 27,XXX. So the actual header above those properties and methods contained [Mac (11,0)] but its just not visible on that tab. I may not have explained it well so let me know if that makes sense. I was about to make the changes but Manuel showed me that!

**Comment by whitneyschmidt** [comment]
> @whitneyschmid thanks for your comment in my last PR #9476, but I think we were both deceived by Github. In the `Files Changed` tab, it shows arrows where you can reveal like 20 lines higher and lower than what it's showing you originally but eventually it gives up and the arrow option goes away but there is still a break in the line number. In this case it goes from around line 3XX to line 27,XXX. So the actual header above those properties and methods contained [Mac (11,0)] but its just not visible on that tab. I may not have explained it well so let me know if that makes sense. I was about to make the changes but Manuel showed me that!

No worries! It totally looked fishy 🐟 Thank you for digging into it and figuring out what was going on. The same thing has happened to me too in the past 😆

**Comment by spouliot** [comment]
> No worries! It totally looked fishy 🐟 

It was a good catch - even if there was no 🐟 on the line
I had to open the file myself to double check :-) Not sure why there was no up arrow to see previous lines

**Comment by mandel-macaque** [comment]
The fact that GitHub decides the size of the context of a change at random is something to worry about.

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
