### PR TITLE
[msbuild] Fix minor typos in DetectSdkLocationsTaskBase

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by VincentDondain** [comment]
@jstedfast I'm not sure why we had `   ` (multiple spaces) in error messages.

**Comment by jstedfast** [comment]
it was meant to indent the messages so that they weren't at the same level as the logged property value diagnostics.

**Comment by VincentDondain** [comment]
@jstedfast The logged property value diagnostics? Right now we're getting: `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets: error :   Could not find valid a usable Xcode app bundle`

**Comment by jstedfast** [comment]
oh, right, I was thinking it would end up being printed as diagnostics and not an error. So the indenting is probably useless.

**Pull request merged**
