### PR TITLE
Use correct namespace for async debugging helpers. Fixes #59015

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by vargaz** [comment]
This should include the get_ObjectIdForDebugger () method as well.

**Comment by vargaz** [comment]
Its not a regression, the problem happens on android now.

**Comment by spouliot** [comment]
@vargaz "[iOS]error: * Assertion at /Users/builder/data/lanes/4691/6bea7a5b/source/xamarin-macios/external/mono/mono/mini/debugger-agent.c:4712, condition `array->len == 1' not met while debugging async methods" from VERIFIED/FIXED from  https://bugzilla.xamarin.com/show_bug.cgi?id=55037

sounds very close to "2017-08-24 17:01:29.365 sampleSIGABRT.iOS[1952:392599] error: * Assertion at /Users/builder/data/lanes/5143/80f17b0b/source/xamarin-macios/external/mono/mono/mini/debugger-agent.c:4714, condition `array->len == 1' not met" from https://bugzilla.xamarin.com/show_bug.cgi?id=59015

even if it seems (from the code) that it was never really fixed (but it did went thru all the process steps)

**Comment by spouliot** [comment]
PR #2782 does the same but adds unit tests

**Pull request closed without merging**
