### PR TITLE
Add XAMCORE_4_0 todo.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
> #warning? What does that do?

    SCNMatrix4.cs(44,11): warning CS1030: #warning: 'Our managed SCNMatrix4 is row-major, while the native SCNMatrix4 is column-major.'
    SCNMatrix4.cs(45,11): warning CS1030: #warning: 'This should be fixed, but it's a breaking change.'
    SCNMatrix4.cs(46,11): warning CS1030: #warning: 'See https://github.com/xamarin/xamarin-macios/issues/4525 for more information.'

**Comment by rolfbjarne** [comment]
> hmm... not sure it's the best way to track those

I'm open for better ideas, but this seems like the one place they won't be forgotten.

**Comment by spouliot** [comment]
let's discuss such issues on our next call

**Comment by rolfbjarne** [comment]
Moved to issue #4652.

**Pull request closed without merging**
