### PR TITLE
[Speech] Add Speech Framework from Xcode 8 Beta 1

### PR DESCRIPTION
**Pull request by dalexsoto**
FIXME: `SFSpeechRecordingRecognitionRequest` is not in the public api
filled radar://26799291 https://trello.com/c/s6s6YKua

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by dalexsoto** [comment]
Ready to be reviewed and merged! No additional failures reported by in introspection tests

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by migueldeicaza** [comment]
LGTM

**Comment by dalexsoto** [comment]
build

Good to be merged once build finishes, introspection test pass.

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@dalexsoto LGTM, you can merge after the conflict is resolved :-)

**Pull request merged**
