### PR TITLE
Revert "Enable logging during mac introspection tests (#510)"

### PR DESCRIPTION
**Pull request by chamons**
- This reverts commit 9e731e842c2b1584c3b353a83a6f5a0a85973f07.
- We've hopefully nailed down the test failure.

### CODE REVIEW

**Comment by chamons** [comment]
@spouliot Not sure if we're ready to pull the trigger on this, but the last few builds I looked at looked cool (fwict).

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
it's quite easy to re-enable if needed :)

**Pull request merged**
