### PR TITLE
[AudioUnit] Fix some breaking changes

### PR DESCRIPTION
**Pull request by dalexsoto**
commit 1f207bd3f3df363cb5a74e59b93acd8eb6e1fec2 in xamarin/maccore
introduced some breaking changes, this fixes them

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@dalexsoto API diff still reports some breaking changes (but the one you fixed are gone). Did you plan a 2nd commit for them (same branch) ?

> Namespace MonoTouch.AudioUnit
> 
> Type Changed: MonoTouch.AudioUnit.AUImplementorStringFromValueCallback
> 
> Removed methods:
> 
> 	public virtual MonoTouch.Foundation.NSString EndInvoke (System.Single]? value, System.IAsyncResult result);
> 	public virtual MonoTouch.Foundation.NSString Invoke (AUParameter param, System.Single]? value);
> Removed Type MonoTouch.AudioUnit._AUImplementorStringFromValueCallback
> 
>

**Comment by dalexsoto** [comment]
@spouliot hey, about `Removed Type MonoTouch.AudioUnit._AUImplementorStringFromValueCallback` this was an internal delegate so I do not see much use to bring it back. see https://github.com/xamarin/maccore/commit/47148dff07d0d48781a4c95656812ef5277b75cf#diff-d967f2b0b7df02360108020c39772347R48

About `EndInvoke` and `Invoke` this was a side effect of changing the Delegate signature from `NSString` to `string`

>Type Changed: AudioUnit.AUImplementorStringFromValueCallback
>
>Removed methods:
> 
> 	public virtual Foundation.NSString EndInvoke (System.Single]? value, System.IAsyncResult result);
> 	public virtual Foundation.NSString Invoke (AUParameter param, System.Single]? value);
> 
>Added methods:
> 
> 	public virtual string EndInvoke (System.Single]? value, System.IAsyncResult result);
> 	public virtual string Invoke (AUParameter param, System.Single]? value);

Old Signature: https://github.com/xamarin/xamarin-macios/commit/1f207bd3f3df363cb5a74e59b93acd8eb6e1fec2#diff-621eebee494c6c485da18dacdc63642eL2043
```
// AUAudioTODO - This should return string but trampoline generated code expected NSObject based.
 public delegate NSString AUImplementorStringFromValueCallback (AUParameter param, ref float? value);
```

New Signature: https://github.com/xamarin/xamarin-macios/commit/1f207bd3f3df363cb5a74e59b93acd8eb6e1fec2#diff-d967f2b0b7df02360108020c39772347R51

 `delegate string AUImplementorStringFromValueCallback (AUParameter param, ref float? value);`

@spouliot do we want to un-break any of the changes above?

**Comment by rolfbjarne** [comment]
Internal types should not show up as a breaking change, so that's either a bug in the apidiff tool or the type was public at some point.

Also we'll always want to maintain compatibility unless it's difficult (or impossible) to avoid it. I haven't looked much at the delegate, but it seems to me that instead of changing the signature we could just add a new delegate with the proper signature and keep the old one.

**Comment by spouliot** [comment]
@dalexsoto my Xamarin.iOS.dll from C7 shows it was public (not an apidiff bug) so it must remain there - at least for `!XAMCORE_4_0` but you can add an `[Obsolete]` on it.

```namespace AudioUnit
{
	public delegate NSString _AUImplementorStringFromValueCallback(AUParameter param, IntPtr value);
}
```

I agree with @rolfbjarne, *if* we need to _change_ from `NSString` to `string` on `AUImplementorStringFromValueCallback` then it needs to be a new delegate.

**Comment by dalexsoto** [comment]
@spouliot I removed another internal delegate on audio unit.cs (AURenderPullInputBlock) and it shows up in the API diff so maybe there is a bug in the apidiff tool

screen shot 2016-06-10 at 9 33 07 am

**Comment by dalexsoto** [comment]
@spouliot might not be a bug in apidiff tool then, it seems that somehow internal delegates end up as public in Xamarin.iOS.dll O.o

**Comment by spouliot** [comment]
AFAICS there are no attributes in the binding file (audiounit.cs) that would generate non-public delegates. IOW the generated code is public and that's what we need to maintain.

**Comment by dalexsoto** [comment]
build

**Pull request closed without merging**
