### PR TITLE
[msbuild] Revert the response-file changes

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650253

### CODE REVIEW

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
Hmm, somehow the test runner got confused and says it failed due to queued tests?

**Comment by chamons** [comment]
build

**Comment by VincentDondain** [comment]
Wait I don't get it, why are you reverting support for response files that was added here: https://github.com/xamarin/xamarin-macios/pull/3635?

We should do whatever fix is needed but keep our response file support. There were good reasons to have that.

**Comment by jstedfast** [comment]
I'm thinking that this might be closer to the long-term fix: https://github.com/mono/mono/pull/9641

The reason for this is mostly just that fixing this the right way has proven more difficult than expected and we are running out of time to fix this for the next release.

**Comment by jstedfast** [comment]
Well, I'd like to do it in a slightly cleaner way. For example, instead of depending on callers to choose between Add() and AddLine(), it should be an option on the CommandLineArgumentBuilder.

When I wrote this patch, I noticed some inconsistencies between the use of Add() and AddLine() (which technically works due to the fact that the Mono.Options parser attempts to parse each line into multiple arguments delimited by spaces, but it's not as clean.

**Comment by dalexsoto** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4468/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4468/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4468/2b82c6d998473916b1105fce61d31cc1f3274f15/2/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4468/2b82c6d998473916b1105fce61d31cc1f3274f15/2/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4468/2b82c6d998473916b1105fce61d31cc1f3274f15/2/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
Superseded by #4495.

**Pull request closed without merging**
