### PR TITLE
[build] Remove MT.D source build and replace it with a binary

### PR DESCRIPTION
**Pull request by dalexsoto**
This commit removes MonoTouch.Dialog from our source build and
replaces it with a binary from https://github.com/xamarin/macios-binaries/tree/c913506df2d106f9c073f211b7c66b03eefc89f2/MonoTouch.Dialog-Unified

The MT.D hash used in this commit is fixed to migueldeicaza/MonoTouch.Dialog@92c6e14

### CODE REVIEW

**Comment by dalexsoto** [comment]
Huh? interesting, I am pretty sure I ran the tvOS tests

**Comment by dalexsoto** [comment]
@rolfbjarne do you have an idea why this is happening? I ran `make jenkins` locally and seems to do the right thing here https://gist.github.com/dalexsoto/c53926dc76c9337455b125a6ecbd4a89

**Comment by rolfbjarne** [comment]
This looked puzzling, so I had a quick look, and just became more puzzled.

I guess I'll have to have a deeper look 👀

**Comment by rolfbjarne** [comment]
This makes no sense 😒

I rebuilt & reran the tests manually on the bot, and it worked just fine.

I guess I'll have to add debug code to xharness to see what's going on.

**Comment by dalexsoto** [comment]
we've been (un?)lucky enough to build 3 times under the same bot...

**Comment by rolfbjarne** [comment]
Yay, I figured out it: it's the code to build the previous revision & calculate the api/generator diff that's interfering.

Now to find a fix...

**Comment by spouliot** [comment]
added `do-not-merge` label since it's green, approved but _now_ has debugging code that should not be merged.

**Comment by dalexsoto** [comment]
Removed the do-not-merge tag since there is no more debug spew and it is now truly green :)

**Pull request merged**
