### PR TITLE
[corevideo] Small update for iOS 10 beta 1

### PR DESCRIPTION
**Pull request by spouliot**
and tests for 4CC to enums conversion

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by VincentDondain** [comment]
LGTM 👍

**Comment by spouliot** [comment]
oops, need to fix typo tests before merging

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
