### PR TITLE
XM] Add NSAccessibilityElement as a class

### PR DESCRIPTION
**Pull request by iainx**
Add NSAccessibilityElement as a class and rename the NSAccessibilityElement protocol to NSAccessibilityElementProtocol to match Swift

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
API diff is happy, but we don't have tests enabled yet -> I'll let @chamons vet this :)

**Comment by chamons** [comment]
@iainx did you run dontlink-mac on this?

**Comment by iainx** [comment]
@chamons I did, yes

> Tests run: 25, Passed: 25, Errors: 0, Failures: 0, Inconclusive: 0
>  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

**Comment by chamons** [comment]
LGTM then. Landing.

**Pull request merged**
