### PR TITLE
Bump mono and watch-mono

### PR DESCRIPTION
**Pull request by lambdageek**
to pick up mono/mono@44d346f73a684738c00775c1fd6ee56877019898

Fixes [#42625](https://bugzilla.xamarin.com/show_bug.cgi?id=42625)

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
Build error:

    make[3]: *** No rule to make target `/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/install/watchos/bcl/Facades/System.Private.CoreLib.Threading.dll', needed by `/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.WatchOS/Facades/System.Private.CoreLib.Threading.dll'.  Stop.

This looks similar to an issue not long ago where the list of Facade assemblies differed between the mono and watch-mono repositories (due to implementation details it's currently complicated to have two separate lists, so we have only one, fetched from the mono repository, which must match the list of Facade assemblies produced by the watch-mono repository).

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by lambdageek** [comment]
Ah... bumping `external/mono` is not so simple.

- [ ] We need to wait mono/mono#3314 so that we don't get errors about `SUBMODULES.json` anymore
- [ ] We need something like the following in `builds/Makefile`
```diff
-MAC_4_5_FACADE_ASSEMBLY_NAMES = $(MAC_FACADE_ASSEMBLY_NAMES)
+MAC_4_5_FACADE_ASSEMBLY_NAMES = $(xammac_net_4_5_PARALLEL_SUBDIRS)
```
or else there's an error about `System.IO.Ping`
- [ ] After all that `make all -j8` succeeds, but `make install -j8` complains like
```diff
--- .ios-facade-check1	2016-07-21 12:11:52.000000000 -0400
+++ .ios-facade-check2	2016-07-21 12:11:52.000000000 -0400
@@ -62,6 +62,7 @@
 System.Net.WebSockets.Client
 System.ObjectModel
 System.Private.CoreLib.InteropServices
+System.Private.CoreLib.Threading
 System.Reflection
 System.Reflection.Extensions
 System.Reflection.Primitives
@@ -77,6 +78,8 @@
 System.Runtime.Numerics
 System.Runtime.Serialization.Formatters
 System.Runtime.Serialization.Json
+System.Runtime.Serialization.Primitives
+System.Runtime.Serialization.Xml
 System.Security.AccessControl
 System.Security.Claims
 System.Security.Cryptography.Algorithms
@@ -96,12 +99,14 @@
 System.Security.Cryptography.ProtectedData
 System.Security.Cryptography.RSA
 System.Security.Cryptography.RandomNumberGenerator
+System.Security.Cryptography.X509Certificates
 System.Security.Principal
 System.Security.Principal.Windows
 System.Security.SecureString
 System.ServiceModel.Duplex
 System.ServiceModel.Http
 System.ServiceModel.NetTcp
+System.ServiceModel.Primitives
 System.ServiceModel.Security
 System.ServiceProcess.ServiceController
 System.Text.Encoding

*** There are Facade assemblies in ../external/mono/mcs/class/lib/monotouch/Facades not defined in ../external/mono/mcs/class/Facades/subdirs.make***
```

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
@spouliot we're still missing netstandard/facade commits from the xcode8 branch, right?

**Comment by spouliot** [comment]
@rolfbjarne yes, the fixes for C7SR1 [1] (a bit different) were just accepted by QA, so it's _saf'ish_ to backport them if this PR blocks you or @lambdageek 

[1] https://trello.com/c/EvFbqG9M/75-xa-xi-xm-mono-netstandard-wave1

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by lambdageek** [comment]
So... did it pass or fail? From the log it kind of looks like everything built and the tests seem to have passed and then it died doing some administrative stuff. IDK.

**Comment by spouliot** [comment]
@lambdageek I thought it only happened on watchOS 3 since I had not seen it on master. Anyway that's unrelated to your changes

**Comment by xamarin-release-manager** [comment]
Build failure

**Pull request merged**
