### PR TITLE
[tests] Automatically download mono packages before running device builds.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Automatically download mono packages and setup symlinks before running device
builds.

This simplifies the build scripts on Azure Devops slightly.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6187/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6187/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.13', Running XM tests on '10.10', Running XM tests on '10.10'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6187/1//console)
✅ Packages: [xamarin.ios-12.15.0.189.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/package/xamarin.ios-12.15.0.189.pkg) [xamarin.mac-5.15.0.189.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/package/xamarin.mac-5.15.0.189.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6187/1/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6187/1/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6187/be21d164ebfcf136693bb6733da5f97104ded2e7/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>3 tests failed, 167 tests passed.</summary>

## Failed tests

 * [NUnit] Mono Mac OS X BCL tests group 2/Mac/Modern: Failed (Test run crashed (exit code: 134).)
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
 * Generator tests/NUnit: Failed (Execution failed with exit code 1)
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* Xamarin.Mac tests on 10.13 failed: https://github.com/xamarin/maccore/issues/1663
* Xamarin.Mac tests on 10.10 failed: https://github.com/xamarin/maccore/issues/1645
* [NUnit] Mono Mac OS X BCL tests group 2/Mac/Modern: Failed (Test run crashed (exit code: 134).)
* introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): https://github.com/xamarin/maccore/issues/581
* Generator tests/NUnit: https://github.com/xamarin/maccore/issues/1661

**Comment by mandel-macaque** [comment]
@rolfbjarne any changes we have to do in the pipeline config for this?

**Comment by rolfbjarne** [comment]
@mandel-macaque we can simply a little bit once these changes are in every branch we care about (i.e. in about 6 months)

**Pull request merged**
