### PR TITLE
[tools] Don't call mono_marshal_ilgen_init in .NET.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Ref: https://github.com/dotnet/runtime/issues/74628.

### CODE REVIEW

**Review by chamons — APPROVED** [review]

**Comment by lambdageek** [comment]
I'm now a little bit concerned that this was the wrong fix, after all.
When using the interpreter you link the `mono-ilgen.a` library and I think in that case the call to `mono_marshal_ilgen_init` has to stay, after all.  So maybe we need the runtime fix https://github.com/dotnet/runtime/pull/74658 after all

https://github.com/xamarin/xamarin-macios/blob/028afc2eabb4af8b7087ebd7f9a6cf6f66ec96b8/tools/mtouch/Target.mtouch.cs#L1530

**Comment by chamons** [comment]
Adding do-not-merge until runtime folks give us a final 👍  / 👎  on the fix - @lambdageek @steveisok 

FYI @dalexsoto

**Comment by lambdageek** [comment]
just to record our thinking.  we think 👍  because it unblocks key scenarios (hot reload; other uses of the interpreter) but it is not 100% the correct fix because it seems like there are circumstances where `mono_marshal_ilgen_inti` does real work (I am not 100% clear on what scenario tht might be - something with the interpreter and maybe SRE calling a p/invoke).

We also started a PR to explore reverting the ilgen componentization (https://github.com/dotnet/runtime/pull/74675).

**Comment by dalexsoto** [comment]
As noted, the plan is to keep going on this PR and if https://github.com/dotnet/runtime/pull/74675 makes the RC1 cut we will need to revert the ilgen component changes in both macios and android (/cc @jonathanpeppers ) once the RC1 runtime build flows to us.

**Comment by rolfbjarne** [comment]
Test failure are unrelated (https://github.com/xamarin/maccore/issues/2612).

**Comment by rolfbjarne** [comment]
Merging this while waiting for the revert of the ilgen componentization (https://github.com/dotnet/runtime/pull/74675) to flow to us.

**Pull request merged**
