### PR TITLE
Add symlink that points to current mono sdks dir

### PR DESCRIPTION
**Pull request by rolfbjarne**
Use that instead of an msbuild variable that won't work in VSMac.

Also bump maccore to get an equivalent fix there.

Diff: https://github.com/xamarin/maccore/compare/34725fe136aee39a9f9984bbb508b6670654f7b3..104656b89060d3c98cdc626709f7cadc467549af

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This is the part of #6097 that's required to make the tip of maccore to build (#6097 requires breaking changes in maccore which has already been implemented; this PR makes sure master is still buildable with the tip of maccore/master in case #6097 is delayed).

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
Test failures on public Jenkins are unrelated:

* */watchOS: https://github.com/xamarin/maccore/issues/581

**Comment by spouliot** [comment]
known issues
* HE0038 -> https://github.com/xamarin/maccore/issues/581
* 3x tests app without test cases -> fixed in another PR
* certificate pinning on 10.10 -> https://github.com/xamarin/maccore/issues/1645

**Pull request merged**
