### PR TITLE
Include assembly refs in _CompileToNative Inputs

### LINKED ISSUE #9014: [Bug] XF for Mac, have to clean before each build to see changes
### Description
Code changes aren't reflected when running the Mac app unless the current project is cleaned first

Instructions for creating an XF for Mac app: https://devblogs.microsoft.com/xamarin/preview-bringing-macos-to-xamarin-forms/

Forum conversation where Xamarin asked me to raise this issue here: https://forums.xamarin.com/discussion/183016/anyone-here-having-to-clean-before-every-build-for-mac-apps#latest

### Steps to Reproduce

1. Unzip the attached example and open the solution, restore packages etc
2. Set XF4Mac as startup project
3. Run it, see that the text is black
4. Change the label text colour to Red in MainPage.cs
5. Run it 

### Expected Behavior
Label text should be red

### Actual Behavior
Label text is still black

### Basic Information

- Version with issue: 4.5 +, 
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Clean the project before each build. Tedious, but it works

[XF4iOSAndroidMacDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4865955/XF4iOSAndroidMacDemo.zip)

### PR DESCRIPTION
**Pull request by mattleibow**
Fixes #9014

### CODE REVIEW

**Comment by chamons** [comment]
Once landed, this should be cherry picked to d16-8 and xcode12.

**Comment by mattleibow** [comment]
@rolfbjarne, we can do that... Just a sec :)

**Comment by rolfbjarne** [comment]
@mattleibow There are 10 failures in the mmp tests: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/14423/Test_20Report/mmptest/285/Log-20200713_172654.html (ignore the monotouch-test failure, that's a known issue)

**Comment by mattleibow** [comment]
@rolfbjarne I was dumb. I renamed a item. I did not update the usage. I should not be allowed near code.

**Pull request merged**
