### PR TITLE
[XHarness] Bump nuget to pickup watchOS sim bump.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by mandel-macaque** [comment]
That is a network issue in the CI, shall we merge or wait for a second run?

**Comment by spouliot** [comment]
@mandel-macaque twice, one day apart ? let's re-run it to be sure

**Review by tj-devel709 — APPROVED** [review]

**Review by spouliot — CHANGES_REQUESTED** [review]
Bots are not able to all run tests with this PR
3 times in a row, on different days
This is not a networking issue

**Comment by mandel-macaque** [comment]
First two are network CI issues:

* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4463854&view=logs&j=704af8c3-a112-593d-cee6-636e1ea22709&t=88ba42ca-f9d0-5ef5-f577-40815d0dc0f2
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4466045&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=6075440f-a394-52c4-0336-c72ca872194b

Last is not, looking at why the min is not working, but probably we need a new change in the nuget.

**Review by stephen-hawley — APPROVED** [review]

**Comment by mandel-macaque** [comment]
There is something weird going on..

**Comment by spouliot** [comment]
@mandel-macaque what's happening with this PR ?
bots are not running any tests, except macOS and those are not on 11.3 so they are not helpful

**Pull request merged**
