### PR TITLE
[Template] Adding dotnet ios-storyboard template

### PR DESCRIPTION
**Pull request by tj-devel709**
The current dotnet template for iOS comes with an App Delegate method overriding the `FinishedLaunching` method and creating a "Hello, iOS!" from there. When we do the sample porting, we have to  remove this override method's contents and enable using a storyboard from the info.plist. @dalexsoto recommended that we have a separate ios template to avoid having to do this for each project.

This PR copies over most of the ios template but removes the `FinishedLaunching` logic, adds using a storyboard to info.plist, and also creates a basic storyboard. 

I am guessing there is something else I have to do to be able to call `dotnet new ios-storyboard`?
@rolfbjarne  @chamons

### CODE REVIEW

**Comment by dalexsoto** [comment]
Is `dotnet/Templates/Microsoft.iOS.Templates/ios-storyboard/Resources/LaunchScreen.xib` really needed? I do not think it is

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
> I am guessing there is something else I have to do to be able to call `dotnet new ios-storyboard`?

Just using `dotnet` will use the global .NET installation, and the template is installed into the local .NET installation when you build. The local one is somewhere here:

> ./builds/downloads/dotnet-sdk-6.0.200-*-osx-x64/dotnet 

So you can do something like this (from the tests/dotnet subdirectory of our repository):

```shell
$ ../../builds/downloads/dotnet-sdk-6.0.200-preview.22071.6-osx-x64/dotnet new ios-storyboard
```

Alternatively you can get this `donut` script which will find the correct executable and copy it to your ~/bin directory: https://github.com/rolfbjarne/scripts/blob/main/donut, and then you can do (still in the tests/dotnet subdirectory):

```shell
$ donut new ios-storyboard
```

And that should find the new template.

**Comment by chamons** [comment]
@stephen-hawley  - See the https://github.com/rolfbjarne/scripts/blob/main/donut conversation above on why everyone needs a 🍩 in their toolbox (and life)

**Comment by rolfbjarne** [comment]
We have an `ios-storyboard` template now, which creates just the storyboard (adding it to an existing project), which means this template will have to be renamed (`iosapp-with-storyboard` maybe?)

**Pull request closed without merging**
