### PR TITLE
Reduce string duplication in the platform assemblies (part 2)

### PR DESCRIPTION
**Pull request by spouliot**
The size of unicode strings for the minimal MySingleView.app (.net
version) goes from 5171 to 4553 characters (each being 2 bytes).

This was 6315 before [part 1](https://github.com/xamarin/xamarin-macios/pull/14191).

[Size report](https://gist.github.com/9f24ce012556c6f4e1a7d09de8f83efc)

Part of the work to fix https://github.com/xamarin/xamarin-macios/issues/14188

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]
/azp run

**Review by chamons — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
There's a monotouch-test failure:

```
XamarinTests.ObjCRuntime.RegistrarSharedTest
	[FAIL] IntPtrCtor :   #message
  Expected: String containing "Failed to marshal the Objective-C object 0x6000034b17e0 (type: IntPtrCtorTestClass). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'XamarinTests.ObjCRuntime.RegistrarSharedTest+IntPtrCtorTestClass' does not have a constructor that takes one IntPtr argument)."
  But was:  "ObjCRuntime.RuntimeException: Failed to lookup the required marshalling information.
Additional information:
	Selector: conformsToProtocol:
	Type: IntPtrCtorTestClass
 ---> ObjCRuntime.RuntimeException: Failed to get the 'this' instance in a method call to XamarinTests.ObjCRuntime.RegistrarSharedTest+IntPtrCtorTestClass.InvokeConformsToProtocol. ---> ObjCRuntime.RuntimeException: Failed to marshal the Objective-C object 0x105553171519456 (type: IntPtrCtorTestClass). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'XamarinTests.ObjCRuntime.RegistrarSharedTest+IntPtrCtorTestClass' does not have a constructor that takes one IntPtr argument).
  at ObjCRuntime.Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution) [0x0007f] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:1166 
  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x00018] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:1195 
  at ObjCRuntime.Runtime.ConstructNSObject (System.IntPtr ptr, System.IntPtr klass, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x0000a] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:1174 
  at ObjCRuntime.Runtime.GetNSObject (System.IntPtr ptr, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution, System.Boolean evenInFinalizerQueue) [0x0001c] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:1393 
  at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject (System.Type type, System.IntPtr selector, System.Boolean is_static, System.IntPtr obj, System.IntPtr& mthis, System.IntPtr desc) [0x0004b] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:862 
   --- End of inner exception stack trace ---
  at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject (System.Type type, System.IntPtr selector, System.Boolean is_static, System.IntPtr obj, System.IntPtr& mthis, System.IntPtr desc) [0x0008a] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:869 
  at ObjCRuntime.Runtime.GetMethodAndObjectForSelector (System.IntPtr klass, System.IntPtr sel, System.Boolean is_static, System.IntPtr obj, System.IntPtr& mthis, System.IntPtr desc) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:811 
  at ObjCRuntime.Runtime.get_method_and_object_for_selector (System.IntPtr cls, System.IntPtr sel, System.Boolean is_static, System.IntPtr obj, System.IntPtr& mthis, System.IntPtr desc, System.IntPtr& exception_gchandle) [0x00008] in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:721 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) ObjCRuntime.Messaging.bool_objc_msgSend_IntPtr(intptr,intptr,intptr)
  at XamarinTests.ObjCRuntime.RegistrarSharedTest+<>c__DisplayClass2_0.<IntPtrCtor>b__0 () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/api-shared/ObjCRuntime/RegistrarTest.cs:35 
  at NUnit.Framework.Assert.Throws (NUnit.Framework.Constraints.IResolveConstraint expression, NUnit.Framework.TestDelegate code, System.String message, System.Object[] args) [0x00013] in <d392db2fb3d64f4fa564a7b744fc7801>:0 "

		  at XamarinTests.ObjCRuntime.RegistrarSharedTest.IntPtrCtor () [0x000c2] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/api-shared/ObjCRuntime/RegistrarTest.cs:46 
```

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2443).

**Pull request merged**
