### PR TITLE
[XM] Exclude NSPopover from apitest due to random crashes

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Comment by chamons** [comment]
Trivial changes are trivial, but can you humor me for a review @timrisi?

**Comment by timrisi** [comment]
Why the rename (or capitalization) on Skip?  Just to match other test files?

**Comment by chamons** [comment]
Yeah. Most of our methods start with capital letters, it just stood out and looked wrong.

**Comment by timrisi** [comment]
KK.  LGTM

**Pull request merged**
