### PR TITLE
Bump maccore to fix mlaunch NRE when starting Simulator bundles

### PR DESCRIPTION
**Pull request by premun**
New commits in xamarin/maccore:
 
* [xamarin/maccore@c89fd6a](https://github.com/xamarin/maccore/commit/c89fd6a) Fix `--launchsimbundleid` action (#2412)

Diff: https://github.com/xamarin/maccore/compare/b9aaee72545d046614dd5fa77e947a9372381013..c89fd6a694110794099592488bf7f15915d99e74

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@premun  looks like we have failures and the are related with the sim.

**Comment by premun** [comment]
@mandel-macaque I might have actually created the commit on an old commit from main. I checked the logs and it doesn't seem related. Also the command that I was fixing is not used in this repository but hopefully I didn't introduce some side effect. 

I rebased so let's try again.

**Comment by spouliot** [comment]
@premun this is because of the P4 bump that was auto merged, even if not tested (and incorrect).

You can just merge `main` back into your PR and it should be fine (since it was reverted).

**Comment by mandel-macaque** [comment]
Ah! much better!

**Review by dalexsoto — APPROVED** [review]

**Pull request merged**
