### PR TITLE
[msbuild] Added support for building CoreML models

### PR DESCRIPTION
**Pull request by jstedfast**

### CODE REVIEW

**Comment by jstedfast** [comment]
Replaces https://github.com/xamarin/xamarin-macios/pull/2608

**Comment by jstedfast** [comment]
I don't understand why the unit test fails. The error seems to suggest that Xamarin.iOS doesn't have iOS 11 API's?

**Comment by VincentDondain** [comment]
@jstedfast you probably want to add a `Setup` to your tests with `TestRuntime.AssertXcodeVersion (9, 0);`.

**Comment by VincentDondain** [comment]
QA trello card: https://trello.com/c/bUltEorP

**Comment by jstedfast** [comment]
@spouliot ah, hmm, I assumed it was ok to use since we're including it in the ios-samples repo.

**Comment by spouliot** [comment]
QA approved -> https://devdiv.visualstudio.com/DevDiv/Xamarin%20VS%20for%20Mac/_workitems?id=505983&_a=edit

**Pull request merged**
