### PR TITLE
Add a CODEOWNERS file.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This comes from https://github.com/xamarin/maccore/wiki/BUGZ#who-to-ask-about-what-, please check if I've put you in the right place (and not missing anything obvious).

**Comment by VincentDondain** [comment]
Add me to `UIKit` I did most for the bindings for `xcode9`.

Also maybe you should have done that in `xcode9` (new Frameworks), I'm `ARKit` for instance (:

**Comment by VincentDondain** [comment]
Also please update the wiki once this is merged to link to this file (and remove what's in the wiki so it's no out of sync) (:

**Comment by VincentDondain** [comment]
Maybe we can just add the new frameworks here already no?

**Comment by rolfbjarne** [comment]
Test failure is unrelated (random introspection/Mac crash due to bug #[46115](https://bugzilla.xamarin.com/show_bug.cgi?id=46115)).

**Comment by rolfbjarne** [comment]
The wiki has been updated to point to the CODEOWNERS file.

**Pull request merged**
