### PR TITLE
[msbuild] Add support for passing extra args to btouch

### PR DESCRIPTION
**Pull request by jstedfast**
Partial fix for https://bugzilla.xamarin.com/show_bug.cgi?id=51753

### CODE REVIEW

**Comment by jstedfast** [comment]
failure doesn't look related

**Comment by rolfbjarne** [comment]
@jstedfast the MSBuild - mac tests are failing because of:

> /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/_mac-build/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets: error : Error executing task BTouch: Required property 'ProjectDir' not set.

which looks related.

**Comment by jstedfast** [comment]
@rolfbjarne yea, that's related. I'll fix up the Mac targets in a bit and add that patch to this PR for review.

**Comment by jstedfast** [comment]
looks like it's failing to install a watchapp to sim?

**Comment by rolfbjarne** [comment]
Yeah, this failure is unrelated (bug #[50419](https://bugzilla.xamarin.com/show_bug.cgi?id=50419)).

**Pull request merged**
