### PR TITLE
Merge xcode10.2 into d16-1

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by VincentDondain** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by VincentDondain** [comment]
The build timeout because of 32b dialogs...

**Comment by VincentDondain** [comment]
build

**Comment by VincentDondain** [comment]
Known failures:
- watchOS sim crash (**59 errors**): https://github.com/xamarin/maccore/issues/581
- iOS 32b timeout (**11 errors**): https://github.com/xamarin/maccore/issues/1500

No new failures, this is good to merge

**Pull request merged**
