### PR TITLE
[XM] Fix APIBreaks

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Comment by chamons** [comment]
AVCaptureAutoFocusSystem was removed in:

> commit 65ffc88aa5a72a88be0e8a8c1060760d0129d9db
> Author: Manuel de la Pena <v-mandel@microsoft.com>
> Date:   Thu Aug 11 14:22:59 2016 +0200
> 
>     [AVFoundation] Update bindings for XCode8. Focus on enums and structs. (#591)
> 

Modified methods:
	public virtual bool WriteToUrl (Foundation.NSUrl url, Foundation.NSDictionary options, SCNSceneExportDelegate handler, SCNSceneExportProgressHandler exportProgressHandler) was in:

> 
> commit 58a0e6136aa60450dc3aead41796a400f1990483
> Author: Alex Soto <dalexsoto@gmail.com>
> Date:   Fri Aug 5 07:23:02 2016 -0500
> 
>     [Scenekit] Update SceneKit to Xcode8 Beta 4 (#552)
>     
>     * Fixed reports of xtro tests
>     * Fixed some members that are @required members of an existing protocol (XAMCORE_4_0)
>     * Added some new typo fixes to Intrespection tests
>     * Fixed SCNNode.EnumerateChildNodes delegate signature
> 


public SCNView (CoreGraphics.CGRect frame, SCNRenderingOptions options); was in:

> 
> commit 921b254adcf0ea6e0cbb9b1edcf192509e568c59
> Author: Sebastien Pouliot <sebastien.pouliot@gmail.com>
> Date:   Sat Aug 6 10:59:16 2016 -0400
> 
>     [watchos][scenekit] Enable SceneKit on watchOS (#563)
>     
>     * Enable some SceneKit-related WatchKit API
>     * Enable some SceneKit-related SpriteKit API
>     * Enable some SceneKit-related Foundation API
>     * Fix generator to include `using SceneKit;` on watchOS
>     * Adjust xtro tests since watchOS headers include some stuff that's not available in reality
>     * Lots of [Watch (3,0)] attributes

**Comment by spouliot** [comment]
before merging please copy/paste the above comment in the commit message

**Comment by spouliot** [comment]
Commenting here - but they are different API break than the one being fixed.

```
Type Changed: AppKit.INSAccessibility

Added property:

	public virtual bool AccessibilityRequired { get; set; }
	
Type Changed: GameKit.IGKTurnBasedEventHandlerDelegate

Added method:

	public virtual void HandleTurnEvent (GKTurnBasedMatch match, bool activated);


Type Changed: Metal.IMTLRenderCommandEncoder

Added methods:

	public virtual void DrawIndexedPatches (uint numberOfPatchControlPoints, IMTLBuffer patchIndexBuffer, uint patchIndexBufferOffset, IMTLBuffer controlPointIndexBuffer, uint controlPointIndexBufferOffset, IMTLBuffer indirectBuffer, uint indirectBufferOffset);
	public virtual void DrawPatches (uint numberOfPatchControlPoints, IMTLBuffer patchIndexBuffer, uint patchIndexBufferOffset, IMTLBuffer indirectBuffer, uint indirectBufferOffset);
	public virtual void TextureBarrier ();
```

Adding methods to an interface is a breaking change. Existing binary that implements those interface would become invalid (incomplete) with a new .dll.

The first one is macOS specific (should be easy not to make it `abstract`) but for the others you'll need to take care not to break XI API.

**Comment by chamons** [comment]
@spouliot I had asked about those on chat. Fixed in 2nd commit.

**Pull request merged**
