### PR TITLE
[tests] Add sample tester.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Add a unit project that looks for iOS/macOS/tvOS sample projects in several
repositories, and builds them all.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
So Azure DevOps decided to run the sample testing pipeline automatically; this won't work because there are no packages yet. I've disabled the automatic PR testing for now, I'll re-schedule a build once there are packages.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/3//console)
✅ Packages: [xamarin.ios-12.11.0.332.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/package/xamarin.ios-12.11.0.332.pkg) [xamarin.mac-5.11.0.332.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/package/xamarin.mac-5.11.0.332.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/jenkins-results/apicomparison/api-diff.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/24082c1095a839b36abc1d116c88bc4c677a8a84/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 229 tests passed.</summary>

## Failed tests

 * [NUnit] Mono SystemIOCompressionFileSystemTests/watchOS - simulator/Debug: Crashed
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.13'' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/4//console)
✅ Packages: [xamarin.ios-12.11.0.333.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ca447c31122a69c7d43df780c9ccfca52e9c29b3/4/package/xamarin.ios-12.11.0.333.pkg) [xamarin.mac-5.11.0.333.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ca447c31122a69c7d43df780c9ccfca52e9c29b3/4/package/xamarin.mac-5.11.0.333.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ca447c31122a69c7d43df780c9ccfca52e9c29b3/4/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ca447c31122a69c7d43df780c9ccfca52e9c29b3/4/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ca447c31122a69c7d43df780c9ccfca52e9c29b3/4/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-5870/4/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/5/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/5/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/5//console)
✅ Packages: [xamarin.ios-12.11.0.334.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/package/xamarin.ios-12.11.0.334.pkg) [xamarin.mac-5.11.0.334.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/package/xamarin.mac-5.11.0.334.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/3e02eb43e65371fa1f6c3671fdf4d0599801dfc6/5/jenkins-results/tests/index.html) 🔥

# Test results

# Test run in progress: Built: 156, Running: 1, RunQueued: 6, Succeeded: 67, Ignored: 1180

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/6/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/6/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-5870/6//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/7/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/7/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/7//console)
✅ Packages: [xamarin.ios-12.11.0.335.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/package/xamarin.ios-12.11.0.335.pkg) [xamarin.mac-5.11.0.335.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/package/xamarin.mac-5.11.0.335.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/071d412a6d00082375d4be8249bf03a2ddf3ef19/7/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 229 tests passed.</summary>

## Failed tests

 * [xUnit] Mono SystemRuntimeSerializationXunit/watchOS - simulator/Debug: Crashed
</details>

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/8/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/8//console)
✅ Packages: [xamarin.ios-12.11.0.336.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/package/xamarin.ios-12.11.0.336.pkg) [xamarin.mac-5.11.0.336.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/package/xamarin.mac-5.11.0.336.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/jenkins-results/generator-diff/index.html) (no change)
✅ [Test run succeeded](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/8/jenkins-results/tests/index.html)

**Comment by rolfbjarne** [comment]
Currently waiting on RE to add an Azure Devops PAT to internal Jenkins so that the internal Jenkins build can trigger the sample testing job (when the `run-sample-tests` label is present).

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/9/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/9/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/9//console)
✅ Packages: [xamarin.ios-12.11.0.336.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/package/xamarin.ios-12.11.0.336.pkg) [xamarin.mac-5.11.0.336.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/package/xamarin.mac-5.11.0.336.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/ac0464398baf56710c53145e3ce4f78bc7720b33/9/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 0 tests skipped, 228 tests passed.</summary>

## Failed tests

 * [NUnit] Mono SystemTransactionsTests/watchOS - simulator/Debug: Crashed
 * [NUnit] Mono SystemSecurityTests/watchOS - simulator/Debug: Crashed
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/10/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/10/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/10//console)
✅ Packages: [xamarin.ios-12.11.0.392.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/14fa23f72689bcf37a8634ebeaef0f20cb725bea/10/package/xamarin.ios-12.11.0.392.pkg) [xamarin.mac-5.11.0.392.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/14fa23f72689bcf37a8634ebeaef0f20cb725bea/10/package/xamarin.mac-5.11.0.392.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/14fa23f72689bcf37a8634ebeaef0f20cb725bea/10/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-5870/10//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;Failed to build src/
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/14fa23f72689bcf37a8634ebeaef0f20cb725bea/10/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 229 tests passed.</summary>

## Failed tests

 * [xUnit] Mono SystemNumericsXunit/watchOS - simulator/Debug: Crashed
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5870/11/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5870/11/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5870/11//console)
✅ Packages: [xamarin.ios-12.11.0.393.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/package/xamarin.ios-12.11.0.393.pkg) [xamarin.mac-5.11.0.393.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/package/xamarin.mac-5.11.0.393.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5870/7fc1a5e343b288e8675f53e8cdc3ee77729dadf8/11/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 0 tests skipped, 228 tests passed.</summary>

## Failed tests

 * [xUnit] Mono SystemJsonXunit/watchOS - simulator/Debug: Crashed
 * [xUnit] Mono SystemCoreXunit/watchOS - simulator/Debug: Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated.

* System.Json/watchOS: https://github.com/xamarin/maccore/issues/581
* System.Core/watchOS: https://github.com/xamarin/maccore/issues/581

**Pull request merged**
