### PR TITLE
Merge xcode11 into d16-3 (updated).

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7009/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7009/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-7009/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7009/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7009/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#3)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7009/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7009/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.15', Running XM tests on '10.15'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7009/3//console)
✅ Packages: 
* [xamarin.ios-13.2.0.38.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7009/80bcb021b35e62b5bd8fc5a44c05546b78468fe0/3/package/xamarin.ios-13.2.0.38.pkg)
* [xamarin.mac-6.2.0.38.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7009/80bcb021b35e62b5bd8fc5a44c05546b78468fe0/3/package/xamarin.mac-6.2.0.38.pkg)
* [xamarin.ios-13.2.0.38.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7009/80bcb021b35e62b5bd8fc5a44c05546b78468fe0/3/package/notarized/xamarin.ios-13.2.0.38.pkg)
* [xamarin.mac-6.2.0.38.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-7009/80bcb021b35e62b5bd8fc5a44c05546b78468fe0/3/package/notarized/xamarin.mac-6.2.0.38.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-7009/df523c8b1861fb39a86489df6972a7f5e6016c10/3/jenkins-results/api-diff/index.html)
⚠️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-7009/df523c8b1861fb39a86489df6972a7f5e6016c10/3/jenkins-results/apicomparison/api-diff.html) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-7009/df523c8b1861fb39a86489df6972a7f5e6016c10/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Xamarin.Mac tests on 10.15 failed: Xamarin.Mac tests on macOS 10.15 failed (introspection)](https://jenkins.internalx.com/job/macios/job/PR-7009/3/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-7009/df523c8b1861fb39a86489df6972a7f5e6016c10/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 386 tests' device not found, 161 tests passed.</summary>

## Failed tests

 * mscorlib/iOS Unified 32-bits - simulator/Debug: Crashed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* link all/Mac Modern/Release: https://github.com/xamarin/maccore/issues/649
* mscorlib/iOS 32-bit: https://github.com/xamarin/maccore/issues/1659
* monotouch-test/watchOS: https://github.com/xamarin/maccore/issues/581
* introspection/macOS 10.15: failed because the second to last commit was built. The last commit includes fixes for these failures.

**Pull request merged**
