### PR TITLE
[jenkins] Run the api diff.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
yay :) RE should know how to export the results. E.g. there's a table built on wrench data that mono shows for test results.

**Comment by spouliot** [comment]
@rolfbjarne heard back from @duncanmak ?

**Comment by rolfbjarne** [comment]
nope

**Comment by duncanmak** [comment]
Sorry, it's been a busy couple of days.

I need to get this plugin set up on Jenkins - https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin

**Comment by spouliot** [comment]
@duncanmak that looks like what we need. Please ping us when available :)

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
