### PR TITLE
[tvos] Enable ExternalAccessory, MultipeerConnectivity and ReplayKit frameworks, existing in iOS but just added in tvOS 10

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
Not yet ready: Some, few existing API needs to be tweaked for the platform (see introspection results)

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
