### PR TITLE
Update mono ref to latest mono-4.6.0-branch

### PR DESCRIPTION
**Pull request by pjcollins**
https://github.com/mono/mono/commit/d0fc1a66e21eddba20ade505d6880238a0253d9e

### CODE REVIEW

**Comment by spouliot** [comment]
Conflict due to another bump PR that was needed (and included another change). The results of this PR are still useful and can be merged manually (if successful).

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
iOS (32 and 64 bits) and tvOS fails to build `link sdk` with

    MTOUCH: error MT2002: Failed to resolve "System.Void System.Security.SecurityCriticalAttribute::.ctor(System.Security.SecurityCriticalScope)" reference from "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" 

watchOS build for `link sdk` fails with

    MTOUCH: error MT2002: Failed to resolve "System.Configuration.ConfigurationException" reference from "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" 

Something is clearly off as the version is `4.0.0.0` and not `2.0.5.0`

@marek-safar @akoeplinger ^ some recent changes in mono 4.6 could do that ?

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build

**Comment by akoeplinger** [comment]
@spouliot closed PRs won't build.

**Comment by spouliot** [comment]
@akoeplinger thanks :)

Last night tests worked (all, including the same revision) so I'm not sure why this failed here on also on wrench.

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
@akoeplinger same failure again :|

**Comment by akoeplinger** [comment]
For future reference, my theory on Slack which turned out the be the cause of the failure:

> the more I think about it the more it makes sense that the missing build/Makefile change from 59125e6f9c089a12b4b9b4d4b9ca07a44336c26e would've caused this. because in my netstandard work I added a dependency from System.ServiceModel.dll to System.IdentityModel.dll. If the bump is then done without adding that assembly to the ios assemblies list it'd then just search for the dll somewhere else (I assume). if it then picks the net_4_x version, we'd have this issue, because that dll would contain the `[assembly: SecurityCritical (SecurityCriticalScope.Explicit)]` attribute which is normally filtered out on NET_2_1

**Pull request closed without merging**
