### PR TITLE
[CoreMidi] Fix MidiEndpoint dispose handle

### PR DESCRIPTION
**Pull request by olegoid**
Fix MidiEndpoint dispose handle, now it throws exception:
https://gist.github.com/olegoid/1c884816f56dd2f9fd3164c23e8aa8ff

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
What was happening before ? Is this related to a bug report or does it solve something else (sample?). If we have future issues regarding this commit we need this type of information before reverting it (otherwise the next fix only breaks/regress other things).

Also please add a test case that check the new, desired, behaviour.

**Comment by olegoid** [comment]
Hello @spouliot, sorry for late reply.

Yes, there is a bug related to this PR: https://bugzilla.xamarin.com/show_bug.cgi?id=43582

**Comment by rolfbjarne** [comment]
LGTM once a test case has been added.

**Comment by dalexsoto** [comment]
This is now tracked in https://github.com/xamarin/xamarin-macios/pull/717 Thanks @olegoid for the actual investigation and fix :)

**Pull request closed without merging**
