### PR TITLE
Bump [watch-]mono to master to get fix for #43658.

### PR DESCRIPTION
**Pull request by rolfbjarne**
https://bugzilla.xamarin.com/show_bug.cgi?id=43658

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@spouliot This is bumping mono to master (it's currently using the mono-4.6.0-branch), is that something we're trying not to do? The alternatives are to put this fix in the mono-4.6.0-branch, or use a temporary workaround that doesn't require a mono bump: https://gist.github.com/rolfbjarne/26b77f5935a2df47647335b1348dfe9f

**Comment by spouliot** [comment]
@rolfbjarne as long as the runtime team is ready to support mobile/aot/bitcode on `master` (and not a `mono-4.7.0-branch`) then I'm fine (in fact, prefer) for `xamarin-macios/master` to track `mono/master`.

**Comment by rolfbjarne** [comment]
CC @kumpera to answer https://github.com/xamarin/xamarin-macios/pull/653#issuecomment-242059841

**Comment by kumpera** [comment]
If the option is between a hack and switch macios/master to mono/master, going with master is the better option.

As long as you guys give us enough time (2-4 weeks) to stabilize it before a release, it's fine.

**Pull request merged**
