### PR TITLE
Cycle8 msbuild codesign simulator no cert

### PR DESCRIPTION
**Pull request by jstedfast**

### CODE REVIEW

**Comment by jstedfast** [comment]
This is a backport of the 2 patches I did for master in order to get codesigning working for Simulator builds.

The first patch, 5bee06e, forces the use of an actual codesign certificate/key while the second patch updates the logic to allow the use of signing with the special `"-"` certificate/key.

**Comment by spouliot** [comment]
@jstedfast this needs a trello card for approval. Since we have this early enough (thanks!) it's still time to ask for SR0 approval 

https://trello.com/b/CbeJB7pF/platform-cycle-8-service-release-0

**Comment by jstedfast** [comment]
Thanks! Created https://trello.com/c/16gZYtMj/13-xi-do-not-require-codesign-certificate-for-ios-simulator-builds

**Comment by jstedfast** [comment]
BTW, should this be a PR against cycle8 or xcode8?

**Comment by spouliot** [comment]
It needs to be in `xcode8` (but it get can there thru a `cycle8` to `xcode8` merge). We should know the SR0 branch name by the time this is verified, on master, by QA.

**Comment by jstedfast** [comment]
ok

**Pull request merged**
