### PR TITLE
SafariServices bindings for iOS 10 and macOS 10.12

### PR DESCRIPTION
**Pull request by timrisi**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by timrisi** [comment]
Looks like I updated the wrong Constants location when I built locally, will fix

**Comment by spouliot** [comment]
FYI you can continue to push to your local branch and the same PR will be built again (as much time as commits goes in). At the end you can (when it makes sense) just _squash_ all the commits together when merging.

**Comment by timrisi** [comment]
Yah, in this case I closed it and opened the new PR cause I pulled in a bunch of random extra commits somehow that werne't supposed to be there.

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request closed without merging**
