### PR TITLE
[UniformTypeIdentifiers] Fix for support for Xcode 14 beta 1, 2 & 3

### PR DESCRIPTION
**Pull request by SotoiGhost**

### CODE REVIEW

**Comment by tj-devel709** [comment]
Is there a todo file change from this?

**Comment by mandel-macaque** [comment]
Nice nice catch.

**Comment by mandel-macaque** [comment]
@tj-devel709  he is fixing a mistake I made when trying to re-use a delegate. @SotoiGhost nice one.

**Comment by mandel-macaque** [comment]
Merging cecil tests are known: https://github.com/xamarin/maccore/issues/2607

**Pull request merged**
