### PR TITLE
Replaced DotNetZip with System.IO.Compression.ZipFile in Xamarin.iOS.…

### PR DESCRIPTION
**Pull request by mauroa**
…Tasks.Windows

### CODE REVIEW

**Review by emaf — APPROVED** [review]

**Review by chamons — COMMENTED** [review]
What triggered this work?

Seems reasonable, I'd like @rolfbjarne approval.

**Comment by dalexsoto** [comment]
Does this touch anything done in the Mac? and if so was it tested there? I can't find it where but IIRC there was a reason (discussion) for not using what was provided by the SDK and use `DotNetZip` instead

**Comment by mauroa** [comment]
@dalexsoto @chamons this is a change that only affects the Windows pack and we only use it for unzipping purposes. DotNetZip was throwing some errors when running builds programmatically from the XamarinVS extension with the new project system, so that makes the archive process to fail in VS. This is an attempt to see if unzipping with System.IO.Compression can get rid of those errors since we haven't been able to find out the root cause of the DotNetZip problems. I'm testing the Windows pack produced by this CI build to validate if everything works as expected

**Comment by mandel-macaque** [comment]
@chamons  @dalexsoto  we should get that Ionic library out of or repo, this is a good move, is the only part of the project that uses it

**Review by chamons — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@mauroa did you test the PR to make sure it works? If so, feel free to merge.

**Comment by mauroa** [comment]
Closing as this change will be included soon with other related changes

**Pull request closed without merging**
