### PR TITLE
Backport d15-3 SR2 fixes

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
```
20:22:03 FATAL: command execution failed
20:22:03 java.nio.channels.ClosedChannelException
20:22:03 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
...
20:22:03 ERROR: Build step failed with exception
20:22:03 
java.lang.NullPointerException
...
```

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
A known (config) issue with bots -> "xammac tests" failing with "Password could not be saved to keychain" https://bugzilla.xamarin.com/show_bug.cgi?id=58394

**Pull request merged**
