### PR TITLE
Bump mono to the latests head and sync with android on 52f6ea14

### PR DESCRIPTION
**Pull request by mandel-macaque**
Commits are:

* https://github.com/mono/mono/commit/c22486e39d129cb8117177a6f9c768e69fc4ebaa [mach] cast objc_msgSend{,Super} usages (#14836)
* https://github.com/mono/mono/commit/569f51dcfb3d8a83f17a0c9b68bddab22224b594 [AppDomain] Cross-appdomain wrapper throws NIE for methods with ref struct arguments
* https://github.com/mono/mono/commit/cd7b4752b09d7e7212712214c471615ae065399a [corlib] Add back Serializable attribute on some reflection classes 
* https://github.com/mono/mono/commit/141ca7d28dafc92602c1551a2e67f6acb7e2a9ed [corlib] Add test for transparent proxies for classes with methods that take ref struct args
* https://github.com/mono/mono/commit/f910438c45ef46b2280ddacae20e0be8e20d2466 Bump API snapshot submodule
* https://github.com/mono/mono/commit/36141442b5b54dce07c0242e8b92b724fa1eda89 Treat ternary operations as non-constant... (#13873)
* https://github.com/mono/mono/commit/2e3ed441038b9b7f83d6603d06b7850ebdf6baca Move ternary SSA cfold test from basic.cs to objects.cs.
* https://github.com/mono/mono/commit/d572acdae7c6e13268626f18fa1153674a8da0be [2019-02] Implement RSACertificateExtensions.CopyWithPrivateKey().
* https://github.com/mono/mono/commit/1d5398bb6af531ff4da82999df5245830e331f30 [install] Include .exe extension when symlinking the mono binary
* https://github.com/mono/mono/commit/04659832c3d3bd698f4cef33f41e810f98dd5b61 [runtime] Switch to GC Unsafe for all GC external API functions  
* https://github.com/mono/mono/commit/1e9f3bfbc5aea9452c761ae10b7716d961846ad2 [aot] Open AOT profile files using "rb" so it works on windows.
* https://github.com/mono/mono/commit/fe3332ccdfd58ec5f98455ce6961cc8c3fea50ca [corlib] Add missing Unsafe.Unbox () method.
* https://github.com/mono/mono/commit/700e2bbd3cf3575ba50e4f3f22cd9499849b166b Bump API snapshot submodule
* https://github.com/mono/mono/commit/d563138704cd6a89328b7d8099682492ab61826d [runtime] Fix gshared support for BeginInvoke ()/EndInvoke () wrappers.
* https://github.com/mono/mono/commit/52f6ea149f412fa58a4d98a957fe85a2a7b720b5 [System.Net.Http]: Add hack to the legacy HttpClient to pass down

Full diff: https://github.com/mono/mono/compare/c6edaa62f94b37bd34ddf99514c904dbc86caf12...52f6ea149f412fa58a4d98a957fe85a2a7b720b5

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Not merging until we are sure about the mac issue: `xammac_tests[73291:143748981] error: mono_gchandle_free Cannot enter GC unsafe region if the thread is not attached`

**Comment by lambdageek** [comment]
This crash `xammac_tests[73291:143748981] error: mono_gchandle_free Cannot enter GC unsafe region if the thread is not attached` is due to https://github.com/mono/mono/commit/04659832c3d3bd698f4cef33f41e810f98dd5b61.

I could just revert the change to `mono_gchandle_free`, but I'm just checking on a couple things:
1. Whether it's ok for SGen that we're calling `sgen_gchandle_free` from a thread that's not attached to Mono.
2. Whether it's ok that sgen calls back to mono which fires a profiler event - `gc_handle_deleted` from a detached thread https://github.com/mono/mono/blob/2019-02/mono/metadata/sgen-mono.c#L2651

I think (1) is probably ok, and i'm not super-sure about (2).

**Comment by mandel-macaque** [comment]
New commits from the last bump

* https://github.com/mono/mono/commit/537654c1c79564668e4cab9735be613028328a70 Improve robustness of post-install script
* https://github.com/mono/mono/commit/eb22ea3ed9be8b928e877db89e56b4012e1b6885 [coop] Mark a few functions with MONO_PROFILER_API
* https://github.com/mono/mono/commit/925e951f4b5a7a0e06874732d002f92a318a539b [runtime] Don't do GC Unsafe transition in mono_gchandle_free
* https://github.com/mono/mono/commit/5a7adade186177f739fdade6bdaaf6a873467396 [profiler] Don't switch to GC Safe when locking if thread isn't attached to the runtime.
* https://github.com/mono/mono/commit/fdf6490d049ca9d76b7bbc2a70a15e3e610dfb30 Add missing read barrier to mono_lazy_initialize().
* https://github.com/mono/mono/commit/8ba06cc40a94e27f34e40ce72825ee62a814a95d Fix bug and race in mono_lazy_initialize.
Complete diff: https://github.com/mono/mono/compare/52f6ea149f412fa58a4d98a957fe85a2a7b720b5...537654c1c79564668e4cab9735be613028328a70

**Comment by mandel-macaque** [comment]
Failure is known: https://github.com/xamarin/maccore/issues/581

**Pull request merged**
