### PR TITLE
[NativeAOT] Remove IlcKeepManagedDebuggerSupport workaround

### LINKED ISSUE #18478: NativeAOT: investigate whether setting IlcKeepManagedDebuggerSupport is still needed
Check if this is needed:

[`fb1f26b` (#17374)](https://github.com/xamarin/xamarin-macios/pull/17374/commits/fb1f26b58144fb57eeb8c842f6c578187b05e5fe)

after:

https://github.com/dotnet/runtime/commit/652433bfe9858f7f4d6f6ffcf0c994cb9b91e482

Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1235547251

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #18478

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Fails with: 

> EXEC An item with the same key has already been added. Key: System.Diagnostics.Debugger.IsSupported [/Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/tmp-test-dir/monotouch-test1699/monotouch-test.csproj]

[build-MacCatalyst-20230629_070323.binlog.zip](https://github.com/xamarin/xamarin-macios/files/11906201/build-MacCatalyst-20230629_070323.binlog.zip)

**Comment by filipnavara** [comment]
Thanks. I'll retry locally.

**Comment by ivanpovazan** [comment]
@filipnavara should we try again with the newest net8.0 bump?

**Comment by filipnavara** [comment]
> @filipnavara should we try again with the newest net8.0 bump?

The fix was merged into dotnet/runtime only today in the morning, so I don't think it went through the full dotnet/sdk flow yet.

**Comment by filipnavara** [comment]
We should merge/rebase this one and retest once https://github.com/xamarin/xamarin-macios/pull/18548 lands.

**Review by ivanpovazan — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
