### PR TITLE
Mark CALayer.Contents as unsafe for automatic expansion by debuggers

### PR DESCRIPTION
**Pull request by chamons**
- https://bugzilla.xamarin.com/show_bug.cgi?id=58116
- Existing GetContentsAs will return the conents as correct type if you know it.

### CODE REVIEW

**Comment by lewing** [comment]
This case is more debugger related than IntelliSense related though.  Isn't [DebuggerBrowsable(DebuggerBrowsableState.Never)] also appropriate for this attribute and others like it?

**Comment by chamons** [comment]
Yes, I originally had that, typo'ed the copy paste, and then fixed it with the wrong thing.

Fixing...

**Comment by abock** [comment]
You should build and test your changes locally before pushing to reduce CI contention. I think you're missing `using System.Diagnostics;`.

**Comment by chamons** [comment]
@abock Fair enough... I didn't have a master laying around and didn't want to burn 1-2 hours of local build time (thanks mono bumps) for an "obvious" fix. Of course, as the history shows nothing is obvious....

**Pull request merged**
