### PR TITLE
[msbuild] Hot Restart fixes

### PR DESCRIPTION
**Pull request by emaf**
Adds missing css files needed on Maui Blazor apps and avoids copying unnecessary files into the bundle (overdue task since the .NET migration).

### CODE REVIEW

**Review by mauroa — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (#15986).

**Comment by MackinnonBuck** [comment]
@emaf Do you think https://github.com/dotnet/maui/issues/7468 is related to the CSS issue that this PR fixed?

**Pull request merged**
