### PR TITLE
Fix lstat P/Invoke on arm64

### LINKED ISSUE #12435: Running MergeAppBundles task on arm64 dotnet fails
```
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018: The "MergeAppBundles" task failed unexpectedly. [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018: System.EntryPointNotFoundException: Unable to find an entry point named 'lstat$INODE64' in shared library '/usr/lib/libSystem.dylib'. [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.Utils.PathUtils.lstat(String path, stat& buf) [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.Utils.PathUtils.IsSymlink(String file) in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/PathUtils.cs:line 196 [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.MacDev.Tasks.MergeAppBundlesTaskBase.GetFileType(String path) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MergeAppBundlesTaskBase.cs:line 448 [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.MacDev.Tasks.MergeAppBundlesTaskBase.MergeAppBundles() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MergeAppBundlesTaskBase.cs:line 287 [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.MacDev.Tasks.MergeAppBundlesTaskBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MergeAppBundlesTaskBase.cs:line 249 [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Xamarin.MacDev.Tasks.MergeAppBundles.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/MergeAppBundles.cs:line 10 [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(308,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
```

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #12435

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by filipnavara** [comment]
My bad, right? I will fix the build right away :-)

**Comment by rolfbjarne** [comment]
```
/Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/PathUtils.cs(198,8): error CS0103: The name 'RuntimeInformation' does not exist in the current context [/Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/mmp.csproj]
/Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/PathUtils.cs(198,50): error CS0103: The name 'Architecture' does not exist in the current context [/Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/mmp.csproj]
```

**Comment by filipnavara** [comment]
Interesting. There's `using System.Runtime.InteropServices` at the top of the file. Admittedly I test only subset of the dotnet build... I'll run it locally. It looks like MMP targets NetFX 4.6 and these APIs were added in 4.7.1.

**Review by dalexsoto — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2443).

**Pull request merged**
