### PR TITLE
Enable logging during mac introspection tests on wrench

### PR DESCRIPTION
**Pull request by chamons**
- API_TEST_LOG_PROGRESS=1 on wrench introspection tests
- Try to track down a random crash
- https://bugzilla.xamarin.com/show_bug.cgi?id=42267

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
Did you really wanted this only on wrench ? e.g. it crashed on jenkins (but your change does not apply there). Jenkins could be faster, unless you plan to use (again and again) the faster mac-only bots on wrench ?

**Comment by chamons** [comment]
@spouliot / @rolfbjarne I did it there only because I knew where to poke. Where is the jenkins entry point? Does it just call  run-mac-introspection (and should I just hack that)?

**Comment by rolfbjarne** [comment]
Can you add a `Environment.SetEnvironmentVariable` to the test itself? That would work on both wrench & jenkins.

**Comment by chamons** [comment]
@rolfbjarne I don't even have to do that that. See latest diff. Only problem is that it'll slow down / spam local test runs as well, but I'm not sure here how to test for Jenkins OR Wrench.

Thoughts?

**Comment by rolfbjarne** [comment]
@chamons spamming is absolutely fine with me when tracking down random bugs :smile: I don't think there will be any significant slowdown either (and the same reasoning applies anyhow: much more time is spent when trying to figure out a random crash and you don't have enough debug spew).

**Pull request merged**
