### PR TITLE
Bump maccore to bring doc fixes to be able to build packages for d15-5

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Related maccore pr -> https://github.com/xamarin/maccore/pull/566

**Comment by mandel-macaque** [comment]
@spouliot will merge once bots are green.

**Comment by mandel-macaque** [comment]
Hm.. failure during the watch tests. Unrelated to the change. Strange. Will request a rebuild.

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
Failure is due to https://bugzilla.xamarin.com/show_bug.cgi?id=55719

**Comment by spouliot** [comment]
@Aguilex this makes the bots green (failing docs steps) but it does not change what's shipping in the packages.

**Pull request merged**
