### PR TITLE
[net8.0] Remove workarounds for SDK and runtime bugs

### LINKED ISSUE #18741: NativeAOT: revert workaround for PublishAotUsingRuntimePack
This workaround:

[`84a0aa6` (#18727)](https://github.com/xamarin/xamarin-macios/pull/18727/commits/84a0aa634cf55a99b523120a3780a381c900b3cd)

should be reverted once we get this fix:

https://github.com/dotnet/sdk/pull/34640

### LINKED ISSUE #18784: NativeAOT: revert workaround for dotnet/runtime#90800
We should revert the following:

* [`959cef6` (#18770)](https://github.com/xamarin/xamarin-macios/pull/18770/commits/959cef65e224ca50d04f75dd44e8af1003d3fea4)
* [`1ddcc87` (#18770)](https://github.com/xamarin/xamarin-macios/pull/18770/commits/1ddcc87bafb2d835d19b15f92239192d90e579aa)

once the fix for https://github.com/dotnet/runtime/issues/90800 flows to us.

CC @filipnavara

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #18741
Fixes #18784

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
All the managed static registrar variations are failing with:

```
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Failed to marshal the Objective-C object 0x849fd78c365b08c3 (type: NSTaggedPointerString). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.NSString' does not have a constructor that takes one NativeHandle argument). (ObjCRuntime.RuntimeException)
    at ObjCRuntime.Runtime.MissingCtor(IntPtr ptr, IntPtr klass, Type type, MissingCtorResolution resolution, IntPtr sel, RuntimeMethodHandle method_handle)
    at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution, IntPtr sel, RuntimeMethodHandle method_handle)
    at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution)
    at ObjCRuntime.Runtime.ConstructNSObject(IntPtr ptr, IntPtr klass, MissingCtorResolution missingCtorResolution)
    at ObjCRuntime.Runtime.GetNSObject(IntPtr ptr, MissingCtorResolution missingCtorResolution, Boolean evenInFinalizerQueue)
    at ObjCRuntime.Runtime.GetNSObject(NativeHandle ptr)
    at Foundation.NSDictionary.ObjectForKey(NSObject key)
    at ObjCRuntime.Runtime.get_iOSSupportVersion()
    at UIKit.UIDevice.CheckSystemVersion(Int32 major, Int32 minor)
    at TestRuntime.CheckiOSSystemVersion(Int32 major, Int32 minor, Boolean throwIfOtherPlatform) in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/common/TestRuntime.cs:line 974
    at TestRuntime.CheckXcodeVersion(Int32 major, Int32 minor, Int32 build) in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/common/TestRuntime.cs:line 568
    at MonoTouchFixtures.BackgroundTasks.BGTaskSchedulerTest.RegisterTestTasks() in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/BackgroundTasks/BGTaskSchedulerTest.cs:line 22
    at AppDelegate.PostFinishedLaunching() in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/monotouch-test/AppDelegate.cs:line 35
    at AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/builder/azdo/_work/3/s/xamarin-macios/tests/common/AppDelegate.cs:line 45
    at AppDelegate.__Registrar_Callbacks__.callback_2_AppDelegate_FinishedLaunching(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
```

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2630).

**Pull request merged**
