### PR TITLE
[mtouch] Fix tests broken by localization

### PR DESCRIPTION
**Pull request by wachaudh**
Fixes https://github.com/xamarin/xamarin-macios/issues/7793.

### CODE REVIEW

**Comment by spouliot** [comment]
@wachaudh bots still does not have devices
`Not run: 211, Invalid: 0, Ignored: 211, Skipped: 0`
so make sure you tested locally before merging :)

**Comment by rolfbjarne** [comment]
build

**Comment by dalexsoto** [comment]
@rolfbjarne I think he needs to create a branch in xamarin-macios and not be in his own fork to run device tests, right?

**Comment by rolfbjarne** [comment]
@dalexsoto no, Sebastien is referring to the fact that we don't enable device support for PR builds by default, which means that we can't (and don't) run tests that need device support (such as tests that build for device). That's fixed by adding the `enable-device-build` label, which I did earlier today, and re-kicked a test run.

**Comment by mandel-macaque** [comment]
Failing tests are known:

* https://github.com/xamarin/maccore/issues/581
* https://github.com/xamarin/maccore/issues/1440

**Pull request merged**
