### PR TITLE
[msbuild/tools] Fix path issues in the FilterStaticFrameworks task and ExtractBindingLibraries step. Fixes #15289.

### LINKED ISSUE #15289: Build fails if app references library which contains framework library inside
_From @nevse on Mon, 13 Jun 2022 11:06:07 GMT_

### Description

Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the issue described bellow. This issue has a Very High priority for us and we do not have a workaround. Thank you for your help

We are using prevew version of  Visual Studio (17.3.0 Preview 1.1) and was straggled with issue while running my app. 
```
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(656,3): error : Could not find a part of the path 'C:\Users\nevse\Library\Caches\Xamarin\mtbs\builds\EditorsGetStarted\c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6\obj\Debug\net6.0-ios\iossimulator-x64\linker-cache\DXListView.framework\DXListView'
```

To run my app on VS on Windows I am using 'pair to mac' and running app on ios simulator on my mac. 
Our bindning library 'Binaries\iOS\iossimulator-x64\DevExpress.Maui.iOS.CollectionView.dll ' contains Framework library with option "<NoBindingEmbedding>false</NoBindingEmbedding>"

### Steps to Reproduce

1. I've prepared the project to reproduce issue. You can find it here https://github.com/nevse/maui-tests-pair-to-mac-static-lib
2. open solution `src\EditorsGetStarted.sln` in vs 2022 (17.3.0 Preview 1.1) 
3. pair to mac, choose one of ios emulator and try to run app

you will obtain error similar to below one

```
error : Could not find a part of the path 'C:\Users\nevse\Library\Caches\Xamarin\mtbs\builds\EditorsGetStarted\c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6\obj\Debug\net6.0-ios\iossimulator-x64\linker-cache\DXListView.framework\DXListView
```

But the real path on mac is 'Users/nevse/library/caches/Xamarin/mtbs/builds/EditorsGetStarted/c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/DXListView.framework/DXListView'

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS, Windows

### Affected platform versions

ios15, windows 10

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

_Copied from original issue dotnet/maui#7980_

### PR DESCRIPTION
**Pull request by rolfbjarne**
In the FilterStaticFrameworks task:

* Convert Windows-style paths to Mac-style paths.
* Give a better error if a framework can't be found.
* Don't try to copy frameworks that don't exist on Windows to the Mac.

In the ExtractBindingLibrariesStep:

* Return a relative path to frameworks we've extracted to make things easier for
  remote builds.

* In the _ComputeFrameworkFilesToPublish target, don't compute the source
  directory for frameworks using RootDir + Directory, because some frameworks
  may only exist on the mac, and RootDir + Directory will be a Windows path
  when building remotely. Instead use 'Identity', which is a relative path and
  will work on both Windows and Mac.

Fixes https://github.com/xamarin/xamarin-macios/issues/15289.

### CODE REVIEW

**Review by emaf — APPROVED** [review]

**Comment by dominic7125** [comment]
Has this fix merged into Xamarin or net6.0-ios?

**Comment by chamons** [comment]
This has been merged into 6.0.4 release branch, currently available in 17.3 Preview 6, and will be in the next stable release.

**Comment by dominic7125** [comment]
> 

I still have the problem with 17.3.0 Preview 6.
I will try to create a sample project to reproduce and open an issue for this.

**Comment by LukasKuchta** [comment]
I can confirm @dominic7125 report. I have a same trouble on last version of **Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 1.0**

MAUI/Net6 and IOS binding of native framework. 

Exactly same as https://github.com/dotnet/maui/issues/8000 

`Error    CS1566    Error reading resource 'TestFramework.framework' -- 'Access to the path 'C:\Users\...\FrameworkTest_ForGithub\TestMauiApp\TestMauiFrameworkBindings\Native References\TestFramework.framework' is denied.'    TestMauiFrameworkBindings`

Any workaround or solution ?

**Comment by rolfbjarne** [comment]
@LukasKuchta please file a new issue (https://github.com/xamarin/xamarin-macios/issues/new) and attach a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and we'll have a look.

**Comment by dominic7125** [comment]
@LukasKuchta 
I tried the latest version of Visual Studio.
I could build the app binding dynamic framework on Visual studio for Mac, but failed on PC.
Binding static framework is still not builtable.

**Pull request merged**
