### PR TITLE
[hotrestart] Fixed MSBuild outputs when using $(AppBundleManifest)

### PR DESCRIPTION
**Pull request by mauroa**
We only want the file name of the app manifest path to define the outputs because the app manifest will be always located at the app bundle root level.
For MAUI, the app manifest source file could be located on a sub-folder (like \Platforms\iOS\Info.plist) so if we take the full value of the property we will end up looking the manifest in the wrong place inside the app bundle, causing the inputs/outputs checks to fail and forcing many tasks to always run (like code sign), also causing unwanted behaviors like breaking incremental builds and incremental deployments

### CODE REVIEW

**Review by chamons — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]
> because the app manifest will be always located at the app bundle root level

FYI that's not true for Mac and Mac Catalyst (but it is true for iOS, tvOS and watchOS).

I don't think we support neither from Windows right now, so unless I'm wrong this should not be an issue.

**Comment by mauroa** [comment]
> > because the app manifest will be always located at the app bundle root level
> 
> FYI that's not true for Mac and Mac Catalyst (but it is true for iOS, tvOS and watchOS).
> 
> I don't think we support neither from Windows right now, so unless I'm wrong this should not be an issue.

Thanks for the clarification. Right, Hot Restart is only supported for iOS so the assumption should be enough

**Comment by mauroa** [comment]
@rolfbjarne can we merge this PR or should we re-run all the checks?

**Comment by dalexsoto** [comment]
@mauroa Rolf is still out, I have not seen that failure before so just to be on the safe side I re-merged main into your PR

**Pull request merged**
