### PR TITLE
[dotnet] Include all files in the Resources subdirectory as bundle resources. Fixes #13808.

### LINKED ISSUE #13808: [.NET] Add everything in Resources/* as a BundleResource item
As title says.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Include all files in the project's Resources subdirectory as BundleResource
items (except .DS_Store files, which are pretty omnipresent on macOS).

Also, contrary to the other default includes, add a condition so files are
only included if we have a resource prefix (typically "Resources"), otherwise
the entire hard drive might be included, and that's not really what we want.

Fixes https://github.com/xamarin/xamarin-macios/issues/13808.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2451).

**Review by chamons — APPROVED** [review]
Wish we had a test for this, but LGTM.

**Comment by rolfbjarne** [comment]
> Wish we had a test for this, but LGTM.

I augmented an existing test for it.

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]
Love it.

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

*  monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2443
* [NUnit] Mono Mac OS X BCL tests group 2/Mac Full/Debug: https://github.com/xamarin/maccore/issues/2542

**Pull request merged**
