### PR TITLE
Updated Xamarin.Messaging version

### PR DESCRIPTION
**Pull request by mauroa**

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
hmm we might have an issue with the skip-all-tests label. Will fix that.

**Comment by mandel-macaque** [comment]
@mauroa AFAIK you are goo to merge, I'll follow up with https://github.com/xamarin/maccore/issues/2448

**Comment by mauroa** [comment]
@mandel-macaque I don't have permissions to merge the PR right now :/

**Pull request merged**
