### PR TITLE
[Metal] Update for Xcode 9.3

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Diffs are:

* iOs -> https://github.com/xamarin/xamarin-macios/wiki/Metal-iOS-xcode9.3-beta1
* macOS -> https://github.com/xamarin/xamarin-macios/wiki/Metal-macOS-xcode9.3-beta1
* TVOS -> https://github.com/xamarin/xamarin-macios/wiki/Metal-tvOS-xcode9.3-beta1

**Comment by VincentDondain** [comment]
Not sure the changes in this PR are valid.

See headers:

```
typedef NS_OPTIONS(NSUInteger, MTLResourceOptions)
{
    MTLResourceCPUCacheModeDefaultCache  = MTLCPUCacheModeDefaultCache  << MTLResourceCPUCacheModeShift,
    MTLResourceCPUCacheModeWriteCombined = MTLCPUCacheModeWriteCombined << MTLResourceCPUCacheModeShift,

    MTLResourceStorageModeShared     NS_ENUM_AVAILABLE(10_11, 9_0)  = MTLStorageModeShared     << MTLResourceStorageModeShift,
    MTLResourceStorageModeManaged    NS_ENUM_AVAILABLE(10_11, NA)   = MTLStorageModeManaged    << MTLResourceStorageModeShift,
    MTLResourceStorageModePrivate    NS_ENUM_AVAILABLE(10_11, 9_0)  = MTLStorageModePrivate    << MTLResourceStorageModeShift,
    MTLResourceStorageModeMemoryless NS_ENUM_AVAILABLE(NA,    10_0) = MTLStorageModeMemoryless << MTLResourceStorageModeShift,

    MTLResourceHazardTrackingModeUntracked NS_ENUM_AVAILABLE(10_13, 10_0) = 0x1UL << MTLResourceHazardTrackingModeShift,

    // Deprecated spellings
    MTLResourceOptionCPUCacheModeDefault       = MTLResourceCPUCacheModeDefaultCache,
    MTLResourceOptionCPUCacheModeWriteCombined = MTLResourceCPUCacheModeWriteCombined,
} NS_ENUM_AVAILABLE(10_11, 8_0);
```

`MTLResourceReserved` doesn't show up in the `MTLResourceOptions` typedef. They only added defines.

Note that sharpie doesn't detect those changes either.

We didn't bind `MTLResourceCPUCacheModeShift`, `MTLResourceCPUCacheModeMask`, `MTLResourceStorageModeShift`, `MTLResourceStorageModeMask` and so on.

It looks like these defines are still internal, maybe coming in next beta (or never).

Adding don't merge for now.

**Comment by mandel-macaque** [comment]
Lets leave the PR open 'til we get more info and deal with it once we have more info.

**Comment by spouliot** [comment]
Closing. No real value in exposed those

**Pull request closed without merging**
