### PR TITLE
Bump Xcode 9 to beta 6

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by spouliot** [comment]
looks like beta 6 was not installed yet on bots

**Comment by VincentDondain** [comment]
build

**Comment by VincentDondain** [comment]
Damn symlink, should be fixed now...

**Comment by VincentDondain** [comment]
build

**Comment by spouliot** [comment]
tvOS failure filled as https://bugzilla.xamarin.com/show_bug.cgi?id=58929 (seems random)

**Comment by VincentDondain** [comment]
@spouliot why is it random? I can repro consistently it's kinda like the `Gujarati Sangam MN` font we're using for tvOS doesn't have a rare ligature anymore.

Also there was a `xammac tests` failure (not covered by your last comment).

**Pull request merged**
