### PR TITLE
[release/8.0.1xx-xcode15.1] Add build_stage parameter to vs-insertion-prep

### PR DESCRIPTION
**Pull request by mcumming**

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@mcumming  why are we not selecting some of the tests?

**Comment by mcumming** [comment]
> @mcumming why are we not selecting some of the tests?

🤷‍♂️ Looking into it.

**Comment by rolfbjarne** [comment]
> > @mcumming why are we not selecting some of the tests?
> 
> 🤷‍♂️ Looking into it.

It's because legacy xamarin is disabled in this branch.

**Pull request merged**
