### PR TITLE
[xharness] Add the XI MSBuild tests to the jenkins test run.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
Can this be merged ? if so I think we can enable test failures on `master` (and `cycle8` once branched) and we're hopefully not far for `xcode8` too

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by rolfbjarne** [comment]
This fails because the MSBuild tasks try to do device builds, which won't work because we've disabled the device runtimes on jenkins.

Let me fix that.

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
