### PR TITLE
[xcode11][tests] Provision dotnet for the sample tests. Fixes xamarin/maccore#1811. (#6473)

### PR DESCRIPTION
**Pull request by rolfbjarne**
Also synchronize configuration file creation to not run into threading issues.

Fixes https://github.com/xamarin/maccore/issues/1811.

This is a backport of #6473 and #6185.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6488/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6488/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-6488/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6488/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6488/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.15', Running XM tests on '10.15'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6488/2//console)
✅ Packages: [xamarin.ios-12.99.1.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/package/xamarin.ios-12.99.1.3.pkg) [xamarin.mac-5.99.1.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/package/xamarin.mac-5.99.1.3.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.15 failed: Xamarin.Mac tests on macOS 10.15 failed (introspection, xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6488/2/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/c9e27525ea2e23b1335e2322cb2860269de20da3/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 232 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): TimedOut
</details>

**Comment by rolfbjarne** [comment]
All samples tests failed due to #6326, will try this again once that issue is fixed (fix is already in progress).

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6488/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6488/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.15', Running XM tests on '10.15'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6488/3//console)
✅ Packages: [xamarin.ios-12.99.1.37.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/package/xamarin.ios-12.99.1.37.pkg) [xamarin.mac-5.99.1.37.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/package/xamarin.mac-5.99.1.37.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/jenkins-results/api-diff/index.html)
⚠️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/jenkins-results/apicomparison/api-diff.html) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Xamarin.Mac tests on 10.15 failed: Xamarin.Mac tests on macOS 10.15 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6488/3/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6488/130d3900d1fefdd86df927e14d119b0e6d598ccc/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 233 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* monotouch-test/watchOS 32-bits: https://github.com/xamarin/maccore/issues/581
* xammac_tests tests on 10.15: https://github.com/xamarin/maccore/issues/1856

Sample test failures are also unrelated

* WeatherWidget: https://github.com/xamarin/maccore/issues/1877
* SamplePhotoApp.tvOS: https://github.com/xamarin/maccore/issues/1878
* sampleapp-with-framework: https://github.com/xamarin/maccore/issues/1878
* sampleapp: https://github.com/xamarin/maccore/issues/1878
* sampleapp-with-native-references: https://github.com/xamarin/maccore/issues/1878
* hugeapp: https://github.com/xamarin/maccore/issues/1878
* PhotoFilter: https://github.com/xamarin/maccore/issues/1878

**Pull request merged**
