### PR TITLE
[msbuild] Re-aot referencing assemblies. Fixes #17708.

### LINKED ISSUE #17708: [ios] Modifying code in library referenced by application results in AOT module loading failure
### Steps to Reproduce

1. Clone https://github.com/frenzibyte/MissingAOTModule
2. Deploy and run `MissingAOTModule` on physical device
3. Edit string value of local variable in `Class1.Something()` to anything else
4. Deploy and run again

### Expected Behavior

Application runs again successfully after performing all steps above.

### Actual Behavior

Application fails to run with the following error message:
```
2023-03-05 05:28:46.764 MissingAOTModule[2257:588544] error: Failed to load AOT module 'MissingAOTModule' while running in aot-only mode because a dependency cannot be found or it is out of date.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10339c51c - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x103387618 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1033dc62c - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10339bd30 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x20db95a90 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x20dc2f1ac - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1c87e9ca0 - /usr/lib/system/libsystem_c.dylib : abort
	0x1030fe628 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : xamarin_find_protocol_wrapper_type
	0x1033d65f0 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1033d6724 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1033765a8 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x103262de4 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x103262904 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x103264500 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1030fda98 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : xamarin_get_block_descriptor
	0x1030fd808 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : xamarin_get_block_descriptor
	0x1030fdc78 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : xamarin_get_block_descriptor
	0x10310f404 - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : xamarin_log
	0x1033d9e2c - /private/var/containers/Bundle/Application/20CB850F-E81B-4290-94D3-44EAFA0BBDD2/MissingAOTModule.app/MissingAOTModule : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1df6a5948 - /usr/lib/dyld : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1fd9f2200):0x1fd9f21f0  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1fd9f2200  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1fd9f2210  8e ed ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  .........{...._.
0x1fd9f2220  c0 03 5f d6 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  .._..#...{......

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
Application 'sh.ppy.MissingAOTModule' terminated (with exit code '' and/or crashing signal '6).
```

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5 (build 1802)
Installation UUID: bceb643f-0f9e-497c-95b2-707c97319415

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.201/Sdks
SDK Versions:
	7.0.201
	6.0.406
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.3
	6.0.14

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: Not found

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 1444-07-23 00:26:05 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 1444-07-23 00:26:05 UTC

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 1444-07-23 00:26:00 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:14-0500

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Build Information
Release ID: 1705001802
Git revision: bfdc90915981031f5bdda171c7eebf116a558598
Build date: 2023-02-14 00:24:08+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:15:09 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64


```

</details>

### Build Logs

[msbuild-binlogs.zip](https://github.com/xamarin/xamarin-macios/files/10890647/msbuild-binlogs.zip)

### Example Project (If Possible)

[MissingAOTModule.zip](https://github.com/frenzibyte/MissingAOTModule/archive/refs/heads/master.zip)

### PR DESCRIPTION
**Pull request by rolfbjarne**
If an assembly changes, then we must AOT compile that assembly again (which we already
did), in addition to any assembly that references the modified assembly (which we
didn't do).

So rework the AOTCompile target: remove the Inputs and Outputs (because the dependency
tracking is too complicated for MSBuild to resolve), and instead move the logic to
detect if an assembly must be AOT-compiled again into the AOTCompile task.

Note that this PR has a custom port to .NET 8: #18518.

Fixes https://github.com/xamarin/xamarin-macios/issues/17708.

### CODE REVIEW

**Comment by ivanpovazan** [comment]
Is the added task specific to NativeAOT builds or it is general (triggered for every AOT compilation configuration: MonoAOT and NativeAOT) ?

**Comment by rolfbjarne** [comment]
@ivanpovazan only MonoAOT. However, I'll likely rewrite this completely, it won't work with the aot dedup logic.

**Review by emaf — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2630).

**Pull request merged**
