### PR TITLE
[scenekit] Remove [Protocolize] from SCNSceneRendererDelegate param

### PR DESCRIPTION
**Pull request by chamons**
- Related to (but does not fix) https://github.com/xamarin/ios-samples/issues/446

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
Probably we should look or create an issue on those Protocolize attributes and remove them from everywhere

**Comment by chamons** [comment]
Tracked in https://github.com/xamarin/xamarin-macios/issues/14585

**Review by rolfbjarne — APPROVED** [review]
This isn't really wrong (removing `[Protocolize]` is something we'd eventually want to do anyway), but it doesn't change anything (`[Protocolize]` really means "use the I* interface instead when targeting Unified" - and we're always targetingUnified since Classic has been dead for years).

The actual problem is here:

https://github.com/xamarin/ios-samples/blob/56aa9e2ea1e5e6236b588e37223a78539f7c9477/ios11/ARKitPlacingObjects/PlacingObjects/ViewController%2BARSceneViewDelegate.cs#L11-L12

In any case I'm good with this change, so approving 👍

**Comment by chamons** [comment]
🤦 - That makes sense. I'll fix that as wel.

**Review by stephen-hawley — APPROVED** [review]

**Comment by chamons** [comment]
Really fixed in https://github.com/xamarin/ios-samples/pull/447

**Review by mandel-macaque — APPROVED** [review]

**Pull request merged**
