### PR TITLE
Bump maccore and macios-binaries to get fix for #6216.

### PR DESCRIPTION
**Pull request by rolfbjarne**
maccore diff: https://github.com/xamarin/maccore/compare/454450958e601857ce244ccaa9a2f1a377dabc87..4cca112bc12be50ff3415652147e7e72eaea14e5

New commits in xamarin/macios-binaries:

* xamarin/macios-binaries@b474fa2 Bump mlaunch to xamarin/maccore@4cca112bc1 (#20)

macios-binaries diff: https://github.com/xamarin/macios-binaries/compare/718cef60c9c9226d54d0578126716804230db7c2..b474fa2e732974fde2edbfe054f23c5eefd0255b

Fixes https://github.com/xamarin/xamarin-macios/issues/6216.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failures on public Jenkins are all due to https://github.com/xamarin/maccore/issues/1725 (and unrelated).

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6229/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6229/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.10', Running XM tests on '10.10'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6229/2//console)
✅ Packages: [xamarin.ios-12.15.0.215.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/2/package/xamarin.ios-12.15.0.215.pkg) [xamarin.mac-5.15.0.215.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/2/package/xamarin.mac-5.15.0.215.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/2/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-6229/2//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at 4103cfdb
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 1.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 2.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 3.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 4.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 6.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/generated/
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib.csproj
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6229/2/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>35 tests failed, 136 tests passed.</summary>

## Failed tests

 * mscorlib/iOS Unified 32-bits - simulator/Debug: TimedOut
 * monotouch-test/tvOS - simulator/Debug: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemTransactionsTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemXmlTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemJsonTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemServiceModelWebTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemIOCompressionTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono MonoDataSqliteTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemDataTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemNetHttpTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemServiceModelTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: Crashed
 * [NUnit] Mono SystemWebServicesTests/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemDataXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemJsonXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemSecurityXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemLinqXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemXmlXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemRuntimeCompilerServicesUnsafeXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemNumericsXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemCoreXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: Crashed
 * [xUnit] Mono MicrosoftCSharpXunit/watchOS 32-bits - simulator/Debug: Crashed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (all optimizations): Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6229/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6229/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6229/3//console)
✅ Packages: [xamarin.ios-12.15.0.215.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/3/package/xamarin.ios-12.15.0.215.pkg) [xamarin.mac-5.15.0.215.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/3/package/xamarin.mac-5.15.0.215.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/3/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-6229/3//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at 4103cfdb
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 1.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 2.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 3.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 4.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 6.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/generated/
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib.csproj
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6229/4103cfdbb59aa3cf57794113323cb1ca612a91e8/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>7 tests failed, 164 tests passed.</summary>

## Failed tests

 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Debug (all optimizations): Failed
 * [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: Crashed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated.

* monotouch-test/*: https://github.com/xamarin/maccore/issues/1725
* [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: https://github.com/xamarin/maccore/issues/581
* introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): https://github.com/xamarin/maccore/issues/581

**Pull request merged**
