### PR TITLE
[xharness] Automatically detect and use .NET 5

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8909/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8909/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.9'' 🔥

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/1//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/1//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.186.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/xamarin.ios-13.21.1.186.pkg)
* [xamarin.mac-6.21.1.186.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/xamarin.mac-6.21.1.186.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.186+sha.7d0af4f22.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.225+sha.7d0af4f22.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-8909/1/display/redirect) 🔥
🔥 [Failed to publish results](https://jenkins.internalx.com/job/macios/job/PR-8909/1//console) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/7d0af4f225ec06f1bb079b16ac4546a95ae5061b/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 182 tests passed.</summary>

## Failed tests

 * [xUnit] Mono Mac OS X BCL tests group 4/Mac Full/Debug: Failed (Test run failed.)
 * Generator tests/.NET: BuildFailure
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8909/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8909/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Running XM tests on '10.9'' 🔥

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/2//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/2//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.187.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/xamarin.ios-13.21.1.187.pkg)
* [xamarin.mac-6.21.1.187.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/xamarin.mac-6.21.1.187.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.187+sha.fe5804e2b.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.226+sha.fe5804e2b.nupkg)

</details>

🔥 [Failed to publish results](https://jenkins.internalx.com/job/macios/job/PR-8909/2//console) 🔥
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/jenkins-results/api-diff/index.html)
🔥 [Failed to publish results](https://jenkins.internalx.com/job/macios/job/PR-8909/2//console) 🔥
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/fe5804e2bf936da2eec5d7731da92f7dbf358c2f/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Failed to publish results](https://jenkins.internalx.com/job/macios/job/PR-8909/2//console) 🔥
🔥 [Test run failed]() 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests, dontlink (system))](https://jenkins.internalx.com/job/macios/job/PR-8909/2/display/redirect) 🔥

**Comment by rolfbjarne** [comment]
> LGTM but could we not use the existing `DOTNET` variable and ensure 5.0 is the minimum ?
> Seems less likely to have confusing/partial updates between the two of them

Just for the record: turns out I was wrong, we do need to use a stable .NET version (3.1.100) in a few places, so I changed this PR to make xharness auto-detect which version to use.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8909/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8909/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.9'' 🔥

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/3//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8909/3//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.194.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/xamarin.ios-13.21.1.194.pkg)
* [xamarin.mac-6.21.1.194.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/xamarin.mac-6.21.1.194.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8909.194+sha.1e14cae16.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8909.233+sha.1e14cae16.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/jenkins-results/apicomparison/api-diff.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-8909/3/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8909/1e14cae16c78559a4f3a70bec08859af31c20d43/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>3 tests failed, 181 tests passed.</summary>

## Failed tests

 * [xUnit] Mono Mac OS X BCL tests group 4/Mac Full/Debug: Failed (Test run failed.)
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>

**Comment by rolfbjarne** [comment]
Test failure are unrelated

* xammac tests/*: https://github.com/xamarin/maccore/issues/2248
* monotouch-test/watchOS 32-bit: https://github.com/xamarin/maccore/issues/581
* monotouch-test/tvOS - simulator/Debug (static registrar): https://github.com/xamarin/maccore/issues/1605
* [xUnit] Mono Mac OS X BCL tests group 4/Mac Full/Debug: https://github.com/xamarin/maccore/issues/2227

**Pull request merged**
