### PR TITLE
[do-not-merge] EnC prototype

### PR DESCRIPTION
**Pull request by lewurm**
please ignore. I need a 📦 package 📦 .

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8393/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8393/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-8393/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.10', Running XM tests on '10.12', Running XM tests on '10.11', Running XM tests on '10.14', Running XM tests on '10.13', Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.10 failed (apitest)

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8393/2//console)
    ⚠️ Mono built from source
✅ Packages: 
* [xamarin.ios-13.21.0.48.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/414fb193596828ac49018b512669b4264910f283/2/package/xamarin.ios-13.21.0.48.pkg)
* [xamarin.mac-6.21.0.48.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/414fb193596828ac49018b512669b4264910f283/2/package/xamarin.mac-6.21.0.48.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/414fb193596828ac49018b512669b4264910f283/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/414fb193596828ac49018b512669b4264910f283/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/414fb193596828ac49018b512669b4264910f283/2/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/2/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.11', Running XM tests on '10.12', Running XM tests on '10.10', Running XM tests on '10.10', Running XM tests on '10.14', Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.11 failed (apitest)

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8393/3//console)
    ⚠️ Mono built from source
✅ Packages: 
* [xamarin.ios-13.21.0.49.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/3f7f213e069ef508b6882086b0d449ad20503fe2/3/package/xamarin.ios-13.21.0.49.pkg)
* [xamarin.mac-6.21.0.49.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/3f7f213e069ef508b6882086b0d449ad20503fe2/3/package/xamarin.mac-6.21.0.49.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/3f7f213e069ef508b6882086b0d449ad20503fe2/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/3f7f213e069ef508b6882086b0d449ad20503fe2/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/3f7f213e069ef508b6882086b0d449ad20503fe2/3/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/3/display/redirect) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.11', Running XM tests on '10.13', Running XM tests on '10.13', Running XM tests on '10.10', Running XM tests on '10.14', Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.11 failed (apitest)

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8393/4//console)
    ⚠️ Mono built from source
✅ Packages: 
* [xamarin.ios-13.21.0.51.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/02d7d2cb7a6548c11fd951e005f5e8d203f668f3/4/package/xamarin.ios-13.21.0.51.pkg)
* [xamarin.mac-6.21.0.51.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8393/02d7d2cb7a6548c11fd951e005f5e8d203f668f3/4/package/xamarin.mac-6.21.0.51.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/02d7d2cb7a6548c11fd951e005f5e8d203f668f3/4/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/02d7d2cb7a6548c11fd951e005f5e8d203f668f3/4/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8393/02d7d2cb7a6548c11fd951e005f5e8d203f668f3/4/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on 10.11 failed: Xamarin.Mac tests on macOS 10.11 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.12 failed: Xamarin.Mac tests on macOS 10.12 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.14 failed: Xamarin.Mac tests on macOS 10.14 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (apitest)](https://jenkins.internalx.com/job/macios/job/PR-8393/4/display/redirect) 🔥

**Comment by mandel-macaque** [comment]
Closing it was used for testing and there is not need to have a PR.

**Pull request closed without merging**
