### PR TITLE
Disable response files hack

### PR DESCRIPTION
**Pull request by chamons**
- This is a potential hacky fix to the 15.8 quoting mess
- Since response files are causing the problem, we could just disable them!?!?

### CODE REVIEW

**Comment by chamons** [comment]
- The root cause of the 15.8 regression seems to be that some arguments need quoting - the move to response files is causing response files with entire lines that are quoted
- These line quotes are being ignored by options.cs
- However real quotes are needed
- This is a potential last-minute band-aid in lieu of playing wack-a-mole with quoting bugs.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4464/1/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4464/1//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4464/2de417f02fe79573ba6d1183a029d4e0d0c6ed9a/1/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4464/2de417f02fe79573ba6d1183a029d4e0d0c6ed9a/1/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4464/2de417f02fe79573ba6d1183a029d4e0d0c6ed9a/1/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by chamons** [comment]
it appears this broke some iOS tests, possibly due to some newline behavior Jeff mentioned last night.

The joys of moving fast to unbreak things.

**Comment by chamons** [comment]
https://github.com/xamarin/xamarin-macios/pull/4468 is handling this now.

**Pull request closed without merging**
