### PR TITLE
[nnyeah] sidebar navigation sample

### PR DESCRIPTION
**Pull request by stephen-hawley**
This is a port of the StoryboardSample from the Sidebar Navigation library.
The code is more or less lock stock and barrel the same and I'm not hugely concerned with it.

For me, the most useful thing to get feedback on is the Makefile as I will be using it as a boilerplate for the other samples.

### CODE REVIEW

**Review by dalexsoto — CHANGES_REQUESTED** [review]
I do not think the full example really belongs here, probably material for https://github.com/xamarin/ios-samples this in the end will rot. I think what we are interested in is the conversion itself of the dll and find a way to unit test the result. Right now the sample itself won't validate the results unless it is ran. @mandel-macaque @chamons 💭s?

**Comment by chamons** [comment]
Given the likely lifespan of this tool, I believe one time validation with the samples we have alongside early testing from internal users is the best path forward. Now that we have this additional case working, I propose we document, move forward towards internal testing, and back fill additional test cases as they come up.

**Comment by stephen-hawley** [comment]
So do you want me to back out this PR?

**Comment by mandel-macaque** [comment]
@dalexsoto we can make a test that is compiling the example, to avoid it to be forgotten, that will also give and end-to-end test. @stephen-hawley I think is ok, and we will need to add it as a xharness test.

**Pull request closed without merging**
