### PR TITLE
[xharness] Add support to configure which tests to run on Jenkins by using labels on pull requests.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
I was wonder if xharness should look at comments or labels, but I figured labels are more self-documenting (there would be a fixed list of pre-defined labels, so no need to document the comment syntax, and typos (which would cause xharness to not understand) would not be be possible).

**Comment by spouliot** [comment]
This is read (from github) at test time right ? so we have about 20 minutes (build time) after a PR to set the labels ?

**Comment by rolfbjarne** [comment]
Yes, you have until the build finishes to set the labels.

**Comment by rolfbjarne** [comment]
Also `hub` can set labels when creating pull requests.

Another idea I had was to add a label to build the device runtimes (and run the tests we disable because we don't build the device runtimes), which would have to be set before the build starts.

**Comment by rolfbjarne** [comment]
Build failure seems to be a broken bot - bug [#46204](https://bugzilla.xamarin.com/show_bug.cgi?id=46204)

**Comment by rolfbjarne** [comment]
build

**Comment by akoeplinger** [comment]
Nifty idea 👍 

One thing to keep in mind is that GitHub has a rate limit of 60 unauthenticated API requests per hour per IP. If you run into that we can generate an API auth token and pass that as an env var in the PR job.

**Pull request merged**
