### PR TITLE
[XHarness] Ignore tests that fail on device.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
@spouliot I talked with @akoeplinger , do we have a mono issue? I know we talked about these tests.

**Comment by akoeplinger** [comment]
I don't think we have a mono bug as these tests never ran on devices before so we need to make a general pass over them anyway.

**Comment by mandel-macaque** [comment]
@akoeplinger do we create a mono bug, to track this? that way once the bug is closed, we can remove the tests/file

**Comment by akoeplinger** [comment]
@mandel-macaque yeah I'll do that on monday.

**Comment by spouliot** [comment]
known HE0038 issue on watchOS sim -> https://github.com/xamarin/maccore/issues/581

**Pull request merged**
