### PR TITLE
Bump Xcode requirement to 8.0 beta 3

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
* monotouch-test on watchOS crash (again) after all tests are executed (still the same failure as before);

* msbuild-mac tests fails - and that's probably because of `cycle8` merge as netstandard is not yet fully correct. @chamons will look at this tomorrow

I'm merging beta 3 support so binding work can continue - but we'll have to monitor results on each PR until the above are resolved.

**Pull request merged**
