### PR TITLE
[build] Fixes System.Drawing.Primitives facades to be proxy for appro…

### PR DESCRIPTION
**Pull request by marek-safar**
…priate profiles. Fixes #42557

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
@marek-safar That test timeout is a known issue (under investigation). The build was successful.

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build failure

**Pull request closed without merging**
