### PR TITLE
[d16-3] Enable notarization

### PR DESCRIPTION
**Pull request by dalexsoto**
It was decided that we want to have d16-3 notarized packages, test packages of d16-3 with enabled notarization are being tested in:

- https://github.com/xamarin/md-addins/pull/5376
- https://github.com/xamarin/XamarinVS/pull/10926

If we are happy with the results we will be inserting these into d16-3/release-8.3

### CODE REVIEW

**Comment by dalexsoto** [comment]
Windows tests are happy 😃 https://github.com/xamarin/XamarinVS/pull/10926

**Comment by dalexsoto** [comment]
Build

**Comment by dalexsoto** [comment]
VSMac is also happy https://github.com/xamarin/md-addins/pull/5376

**Comment by rolfbjarne** [comment]
Superseded by #6927.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6923/3/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6923/3//console)
✅ Packages: 
* [xamarin.ios-12.16.1.25.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/package/xamarin.ios-12.16.1.25.pkg)
* [xamarin.mac-5.16.1.25.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/package/xamarin.mac-5.16.1.25.pkg)
* [xamarin.ios-12.16.1.25.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/package/notarized/xamarin.ios-12.16.1.25.pkg)
* [xamarin.mac-5.16.1.25.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/package/notarized/xamarin.mac-5.16.1.25.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6923/6de026c57a03f52e94980ed9bfbf77d9a779e56b/3/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Pull request closed without merging**
