### PR TITLE
[macos] Fix Multiple Native References

### PR DESCRIPTION
**Pull request by chamons**
- https://bugzilla.xamarin.com/show_bug.cgi?id=56098
- Moderate test cleanup in separate commit to make writing test easier / fix duplication.

### CODE REVIEW

**Comment by chamons** [comment]
Bah. I was right. Bots can't run tests that need to sign it seems right now.

```		  SigningKey: <null>
/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/_mac-build/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets: error : No valid OS X code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com.
	Task "DetectSigningIdentity" execution -- FAILED```

**Comment by chamons** [comment]
Card filed against RE to fix bot configuration. Blocked until done.

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
build

**Comment by spouliot** [comment]
@chamons are the build success a sign that the bots are fine ? if so we can remove the `dont-merge` tag and merge the PR

**Comment by spouliot** [comment]
c.c. @emaf since this change a msbuild related file

**Comment by chamons** [comment]
The don't merge was waiting for RE to add certificates to bots (which is now done).

I didn't want to add broken tests.

**Pull request merged**
