### PR TITLE
[runtime] Use printf on watchOS, NSLog doesn't shown up (by default)

### PR DESCRIPTION
**Pull request by rolfbjarne**
Don't use NSLog on watchOS, since it's not printed by default anywhere (starting with watchOS 3).

Instead use printf, which shows up in the IDE (if launched from the IDE) or in the device log (if not launched from the IDE).

This also makes Console.WriteLine work on a watchOS 3 device (since it ends up calling xamarin_log).

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@spouliot this might be nice to get in C8, since Console.WriteLine is kind of basic functionality...

**Comment by spouliot** [comment]
@rolfbjarne C8 will be XI 10.0 (xcode8) even if XI 9.10 is kept alive (need the branch for XM and it's the last release with classic). Still there's no harm to backport the commit (if the bots are fine with it).

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
@spouliot well, I actually meant the xcode8 branch when I said C8 (it was just a backwards way of asking for a review :smile:)

**Pull request merged**
