### PR TITLE
[runtime] Add some debugging aid to xamarin_release_managed_ref.

### PR DESCRIPTION
**Pull request by rolfbjarne**
It's fairly frequent (due to various types of coding errors) to have the
call to '[self release]' in xamarin_release_managed_ref crash. These
crashes are typically very hard to diagnose, because it can be hard to
figure out which object caused the crash. So now we store the native
object in a static variable, so that it can be read using lldb from a core
dump.

Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1481312.

### CODE REVIEW

**Review by Therzok — APPROVED** [review]
❤️

**Review by Therzok — APPROVED** [review]
I hope it's not a case where the handle is already nulled out at this point.

**Comment by rolfbjarne** [comment]
@Therzok the crash would look different if that was the case

**Review by chamons — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2612).

**Comment by Therzok** [comment]
Can we backport this to 6.x release branch?

**Comment by rolfbjarne** [comment]
@Therzok this will be included in our Xcode 14 release, which will most likely be out later this month.

**Pull request merged**
