### PR TITLE
[msbuild] Import Xamarin.iOS.Analysis.targets

### PR DESCRIPTION
**Pull request by VincentDondain**
Update reference to `maccore` which includes the bump to an updated `xamarin-analysis` and the corresponding `Makefile` changes.

_Note: the `Xamarin.iOS.Analysis.targets` file contains the code of the first Analysis rule (XIA0001) which detects if the linker is enabled for debug/device mode and suggests to try to turn it on if disabled._

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
LGTM, any feedback @jstedfast ?

**Comment by jstedfast** [comment]
I think it looks ok. I'm not sure what the Analysis targets are, though or where they come from.

**Comment by VincentDondain** [comment]
@jstedfast They come from here: https://github.com/xamarin/xamarin-analysis/commit/4af0114cdcced32d3124674f8e0546ecc153214e. That's the xamarin-analysis repo.

**Comment by VincentDondain** [comment]
And here is the Makefile in maccore: https://github.com/xamarin/maccore/blob/master/analysis/Makefile

**Comment by jstedfast** [comment]
thanks.

**Pull request merged**
