### PR TITLE
Fix assigning of _DefaultLinkMode

### PR DESCRIPTION
**Pull request by filipnavara**
Noticed it when inspecting build logs, it was not hit in production for us.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — COMMENTED** [review]
Actually the code was correct.

We initialize _LinkMode with the value for _DefaultLinkMode:

https://github.com/xamarin/xamarin-macios/blob/92362ea2635d8ebfdcb2a189a8295c5907b8830d/msbuild/Xamarin.Shared/Xamarin.Shared.targets#L2118

and `TrimMode` is a valid value for `_LinkMode`:

https://github.com/xamarin/xamarin-macios/blob/92362ea2635d8ebfdcb2a189a8295c5907b8830d/dotnet/targets/Xamarin.Shared.Sdk.targets#L453

**Comment by filipnavara** [comment]
Ah, thanks for the double check and sorry for the noise!

**Pull request closed without merging**
