### PR TITLE
[msbuild] Implement ITaskCallback in ReadAppManifest to tell the remote task execution that any files on Windows shouldn't be copied back to the mac.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1394206.

### CODE REVIEW

**Review by emaf — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2414).

**Comment by rolfbjarne** [comment]
Pending verification from @emaf that the fix actually works.

**Comment by emaf** [comment]
@rolfbjarne I've just tested it and the ReadAppManifest worked fine, but now the WriteAppManifest task is failing, it looks we need to do the same change in that one.

This is the output of the task:
2>Task "WriteAppManifest" (TaskId:210)
2>  Task Parameter:
2>      AppManifests=
2>          obj\iPhoneSimulator\Debug\actool\partial-info.plist
2>          obj\iPhoneSimulator\Debug\AppManifest.plist (TaskId:210)
2>  Task Parameter:SessionId=915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8 (TaskId:210)
2>  Task Parameter:AppBundleManifest=bin\iPhoneSimulator\Debug\App34.iOS.app\Info.plist (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3324165-03:00 - Started (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3324165-03:00 - Initializing (TaskId:210)
2>  [xma]: Trying to get a Build Connection for Session '915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8': Xamarin.Messaging.Build.Client.BuildConnection.915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8, Lifetime: AppDomain (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3324165-03:00 - Initialized (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3334183-03:00 - Determining the modified inputs that should be copied to the Mac (2 files) (TaskId:210)
2>  [xma]: Determining task items to copy to the server for 'App34.iOS'... (TaskId:210)
2>  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.CompareItemsMessage to topic xvs/build/compare-items (TaskId:210)
2>  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.CompareItemsMessage to topic build915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b820652emanu/+/xvs/build/compare-items (TaskId:210)
2>  [xma]: The following items should be copied to the server for 'App34.iOS': obj\iPhoneSimulator\Debug\actool\partial-info.plist, obj\iPhoneSimulator\Debug\AppManifest.plist (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3454228-03:00 - Copying inputs (2 files) (TaskId:210)
2>  [xma]: SCP uploading 'obj/iPhoneSimulator/Debug/actool/partial-info.plist' to 'obj/iPhoneSimulator/Debug/actool/partial-info.plist' for 'App34.iOS'... (TaskId:210)
2>  [xma]: Preparing directory /Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/actool before uploading... (TaskId:210)
2>  [xma]: Executing SSH command 'mkdir -p "/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/actool"'... (TaskId:210)
2>  [xma]: SCP uploading 'obj/iPhoneSimulator/Debug/AppManifest.plist' to 'obj/iPhoneSimulator/Debug/AppManifest.plist' for 'App34.iOS'... (TaskId:210)
2>  [xma]: Preparing directory /Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug before uploading... (TaskId:210)
2>  [xma]: Executing SSH command 'mkdir -p "/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug"'... (TaskId:210)
2>  [xma]: Trying to copy to '/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/actool/partial-info.plist' from cache... (TaskId:210)
2>  [xma]: Executing SSH command 'cp -f "/Users/ema/Library/Caches/Xamarin/XMA/Cache/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" "/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/actool/partial-info.plist"'... (TaskId:210)
2>  [xma]: Trying to copy to '/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/AppManifest.plist' from cache... (TaskId:210)
2>  [xma]: Executing SSH command 'cp -f "/Users/ema/Library/Caches/Xamarin/XMA/Cache/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" "/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/AppManifest.plist"'... (TaskId:210)
2>  [xma]: Successfully copied '/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/actool/partial-info.plist' from cache (TaskId:210)
2>  [xma]: Successfully copied '/Users/ema/Library/Caches/Xamarin/mtbs/builds/App34.iOS/915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b8/obj/iPhoneSimulator/Debug/AppManifest.plist' from cache (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.3977049-03:00 - Serializing intputs (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.4037008-03:00 - Executing (TaskId:210)
2>  [xma]: Starting remote task execution for 'App34.iOS': Xamarin.MacDev.Tasks.WriteAppManifest (TaskId:210)
2>  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/App34.iOS/915ad52002fWriteAppManifest (TaskId:210)
2>  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic build915ad52a0d87a749e3d9cd9caf40628084e8ac066465ffc1341447f8903d62b820652emanu/+/xvs/build/execute-task/App34.iOS/915ad52002fWriteAppManifest (TaskId:210)
2>  WriteAppManifest: 2021-09-10T12:00:09.4300706-03:00 - Logging messages (TaskId:210)
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error : "Error loading '{0}': {1}
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error :         "
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error : System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error :   at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x003da] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Text/StringBuilder.cs:1637 
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error :   at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:471 
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error :   at System.String.Format (System.IFormatProvider provider, System.String format, System.Object[] args) [0x00018] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:463 
2>C:\Program Files\Microsoft Visual Studio\2022\Test\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(393,3): error :   at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString (System.Globalization.CultureInfo culture, System.String unformatted, System.Object[] args) [0x00009] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/msbuild-15/src/Framework/LazyFormattedBuildEventArgs.cs:228 
2>  WriteAppManifest: 2021-09-10T12:00:09.4300706-03:00 - Finished (TaskId:210)

**Comment by emaf** [comment]
@dalexsoto regarding the talk we were having about Xcode 13, we won't be able to test it until this new problem is fixed too ^

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@emaf I made the same change to WriteAppManifest as well. We should have updated packages in 8-10 hours.

**Comment by rolfbjarne** [comment]
@emaf you can find packages here: https://github.com/xamarin/xamarin-macios/commit/e426a400d9ec5f98974ff8bd59aeedcb91728482#commitcomment-56285285

**Comment by emaf** [comment]
@rolfbjarne the problem is fixed now! Let's get this merged!

**Comment by varyamereon** [comment]
This didn't make it into Preview 4.1? I'm still experiencing the issue described in #12735.

**Comment by emaf** [comment]
Yes, this didn't make it into Visual Studio 2022 17.0 Preview 4/4.1, it will be shipped in Preview 5.

**Pull request merged**
