### PR TITLE
[tests][xtro] Fix catalyst changes with xcode12.5 RC. Fixes #11308.

### LINKED ISSUE #11308: xtro failures in main
xtro fails in main:

```
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supports32BitFloatFiltering not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supports32BitMSAA not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supportsQueryTextureLOD not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
```

### PR DESCRIPTION
**Pull request by spouliot**
xtro should soon be re-enabled and spot those on the (backport) PR

Fixes https://github.com/xamarin/xamarin-macios/issues/11308.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@mandel-macaque xtro didn't run for this PR, probably because of:

> The environment variable 'ghprbPullId' was not found, so no pull requests will be checked for test selection.

**Comment by spouliot** [comment]
```
/Users/builder/azdo/_work/1/s/xamarin-macios/dotnet/package/common.csproj(51,3): error : Failed to resolve SDK 'Microsoft.DotNet.SharedFramework.Sdk/6.0.0-beta.21212.6'. Package restore was successful but a package with the ID of "Microsoft.DotNet.SharedFramework.Sdk" was not installed.
/Users/builder/azdo/_work/1/s/xamarin-macios/dotnet/package/common.csproj(52,49): error MSB4022: The result "" of evaluating the value "$(DotNetSharedFrameworkTaskFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [/Users/builder/azdo/_work/1/s/xamarin-macios/dotnet/package/Microsoft.iOS.Runtime.iossimulator-x64/package.csproj]
make[1]: *** [nupkgs/Microsoft.iOS.Runtime.iossimulator-x64.14.5.100-ci.pr.gh11340.666+sha.309eba08b.nupkg] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Filled as https://github.com/xamarin/maccore/issues/2427

**Comment by mandel-macaque** [comment]
@spouliot the fix to pick up the test selection has landed in main, you will not longer need to add the labels for this type of changes.

**Comment by spouliot** [comment]
* monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed -> ICE known failure https://github.com/xamarin/maccore/issues/1605
* Xtro/Mac: Failed (Test run failed.) -> fixed by another PR in parallel -> https://github.com/xamarin/xamarin-macios/pull/11342

**Pull request merged**
