### PR TITLE
[MapKit] Manually make MKUserLocation implement the MKAnnotation protocol. Fixes #21759.

### LINKED ISSUE #21759: Microsoft.Maui.Controls.Maps crash when IsShowingUser = true in Release mode (iOS, NET 9 rc2)
_From @MichelePannacciTerex on Sun, 10 Nov 2024 17:30:09 GMT_

### Description

I'm expercienced a crash in the map control in Release mode on real device only if IsShowingUser = true while zooming/pinching on the map.

`Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)`

Tried both Microsoft.Maui.Controls.Maps version 9.0.0-rc.2.24503.2 and the latest ones 8.0.92 and  8.0.93 but all of them has the same problem. This used to work using .NET 8, at least on iOS 17.x.

### Steps to Reproduce

Attached a simple project, apparently no special things to do other than set IsShowingUser = true to reproduce the error.
This on real device.

P.S. in the .csproj you have to adjust the CodesignKey.

[TestMap.zip](https://github.com/user-attachments/files/17692368/TestMap.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18, iOS 18.1 NET 9 rc2

### Did you find any workaround?

Not really a workaround but just adding a Circle to the map and polling the position my self.

### Relevant log output

```shell
------------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
2024-11-10 17:59:57.531 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 17:59:57.532 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 17:59:57.541 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.379 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 18:00:03.380 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 18:00:03.387 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
xcrun devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap
2024-11-10 18:00:03.944 TestMap[9176:2472092] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2024-11-10 18:00:04.208 TestMap[9176:2472092] CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
=================================================================
	Native Crash Reporting
2024-11-10 18:00:17.862 TestMap[9176:2472092] Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
   at MapKit.MKMapView._MKMapViewDelegate.__Registrar_Callbacks__.callback_788_MapKit_MKMapView__MKMapViewDelegate_GetViewForAnnotation(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
=================================================================
--- End of stack trace from previous location ---
=================================================================
   at ObjCRuntime.Runtime.ThrowException(IntPtr )
	Native stacktrace:
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
=================================================================
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at TestMap.Program.Main(String[] args)
	0x102484a38 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_dump_native_crash_info
	0x10246f214 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_handle_native_crash
	0x1024f08f0 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : sigabrt_signal_handler.cold.1
	0x10248434c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_runtime_setup_stat_profiler
	0x216dbcafc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x216f86ef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x19690bad8 - /usr/lib/system/libsystem_c.dylib : abort
	0x102325c48 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : _ZL12log_callbackPKcS0_S0_iPv
	0x1023bc808 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_invoke_unhandled_exception_hook
	0x102459b6c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_jit_exec
	0x10232e09c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : xamarin_main
	0x1024cb544 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : main
	0x1b453aec8 - /usr/lib/dyld : <redacted>
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1def191d4):0x1def191c4  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1def191d4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1def191e4  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
0x1def191f4  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'.........T
=================================================================
	Managed Stacktrace:
=================================================================

=================================================================
18:00:03  Acquired tunnel connection to device.
18:00:03  Enabling developer disk image services.
18:00:03  Acquired usage assertion.
Launched application with com.mydomain.TestMap bundle identifier.
Waiting for the application to terminate...
App terminated due to signal 6.
error MT1045: Failed to execute 'devicectl': 'devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap' returned the exit code 1.
error MT1046: Additional output: xcrun devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap
error MT1046: Additional output: 2024-11-10 18:00:03.944 TestMap[9176:2472092] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
error MT1046: Additional output: 2024-11-10 18:00:04.208 TestMap[9176:2472092] CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Native Crash Reporting
error MT1046: Additional output: 2024-11-10 18:00:17.862 TestMap[9176:2472092] Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)
error MT1046: Additional output: =================================================================
error MT1046: Additional output: Got a SIGABRT while executing native code. This usually indicates
error MT1046: Additional output: a fatal error in the mono runtime or one of the native libraries
error MT1046: Additional output: used by your application.
error MT1046: Additional output:    at MapKit.MKMapView._MKMapViewDelegate.__Registrar_Callbacks__.callback_788_MapKit_MKMapView__MKMapViewDelegate_GetViewForAnnotation(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
error MT1046: Additional output: =================================================================
error MT1046: Additional output:
error MT1046: Additional output: --- End of stack trace from previous location ---
error MT1046: Additional output: =================================================================
error MT1046: Additional output:    at ObjCRuntime.Runtime.ThrowException(IntPtr )
error MT1046: Additional output: 	Native stacktrace:
error MT1046: Additional output:    at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
error MT1046: Additional output: =================================================================
error MT1046: Additional output:    at UIKit.UIApplication.Main(String[] , Type , Type )
error MT1046: Additional output:    at TestMap.Program.Main(String[] args)
error MT1046: Additional output: 	0x102484a38 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_dump_native_crash_info
error MT1046: Additional output: 	0x10246f214 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_handle_native_crash
error MT1046: Additional output: 	0x1024f08f0 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : sigabrt_signal_handler.cold.1
error MT1046: Additional output: 	0x10248434c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_runtime_setup_stat_profiler
error MT1046: Additional output: 	0x216dbcafc - /usr/lib/system/libsystem_platform.dylib : <redacted>
error MT1046: Additional output: 	0x216f86ef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
error MT1046: Additional output: 	0x19690bad8 - /usr/lib/system/libsystem_c.dylib : abort
error MT1046: Additional output: 	0x102325c48 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : _ZL12log_callbackPKcS0_S0_iPv
error MT1046: Additional output: 	0x1023bc808 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_invoke_unhandled_exception_hook
error MT1046: Additional output: 	0x102459b6c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_jit_exec
error MT1046: Additional output: 	0x10232e09c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : xamarin_main
error MT1046: Additional output: 	0x1024cb544 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : main
error MT1046: Additional output: 	0x1b453aec8 - /usr/lib/dyld : <redacted>
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Basic Fault Address Reporting
error MT1046: Additional output: =================================================================
error MT1046: Additional output: Memory around native instruction pointer (0x1def191d4):0x1def191c4  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
error MT1046: Additional output: 0x1def191d4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
error MT1046: Additional output: 0x1def191e4  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
error MT1046: Additional output: 0x1def191f4  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'.........T
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Managed Stacktrace:
error MT1046: Additional output: =================================================================

error MT1046: Additional output: =================================================================
error MT1046: Additional output: 18:00:03  Acquired tunnel connection to device.
error MT1046: Additional output: 18:00:03  Enabling developer disk image services.
error MT1046: Additional output: 18:00:03  Acquired usage assertion.
error MT1046: Additional output: Launched application with com.mydomain.TestMap bundle identifier.
error MT1046: Additional output: Waiting for the application to terminate...
error MT1046: Additional output: App terminated due to signal 6.
```

_Copied from original issue dotnet/maui#25762_

### PR DESCRIPTION
**Pull request by rolfbjarne**
It's important that MKUserLocation class implements the IMKAnnotation
interface, because a MKUserLocation instance might be passed as a parameter to
a function that takes an IMKAnnotation. If the managed class doesn't implement
the interface, this can result in an InvalidCastException at runtime.

Fixes https://github.com/xamarin/xamarin-macios/issues/21759.

### CODE REVIEW

**Review by mcumming — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by bitshftr** [comment]
Curious if someone can tell me how/when this will be deployed.  I see that Microsoft.Maui.Controls.Maps version 9.0.21 was released on December 12th (so 1 week ago as I'm writing this), but this PR was committed 2 weeks ago.  The fix is **not** in version 9.0.21.  How can we tell what version this fix has been / will be released in?

**Comment by bitshftr** [comment]
> It will be shipped as part of the iOS workload, which is released independently from MAUI.
> 
> A release with this fix is in progress, unless something goes rather badly it'll be out later today or tomorrow.

Does this mean it will be in a Visual Studio 2022 update?  I'm just trying to understand how I can get this update.

**Comment by rolfbjarne** [comment]
> > It will be shipped as part of the iOS workload, which is released independently from MAUI.
> > A release with this fix is in progress, unless something goes rather badly it'll be out later today or tomorrow.
> 
> Does this mean it will be in a Visual Studio 2022 update? I'm just trying to understand how I can get this update.

Yes, eventually, but unfortunately that will be sometime early next year, because of how VS's release schedule doesn't match ours.

**Comment by rolfbjarne** [comment]
> Just trying to understand how updates are delivered. You said "It will be shipped as part of the iOS workload"..."later today or tomorrow." How do I get this update?

You can do "dotnet workload update" from the command line, and I believe VS should pick up the updated workload(s).

> From my perspective, I have VS which notifies of its own updates, and I have the MAUI nuget packages which I can update via Manage NuGet Packages for my project. You're saying that the update isn't part of either of these. Do I need to look somewhere else to update "the iOS workload"?

Correct (see above).

**Pull request merged**
