### PR TITLE
[Tests] Use safe listed password by our Credentials Scanner tool

### PR DESCRIPTION
**Pull request by dalexsoto**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
I'm not sure I'm happy sharing my password :/

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8580/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8580/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: script returned exit code 128

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/ddfun-vsdrops/1//console)
✅ Packages: 
* [xamarin.ios-13.21.0.199.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/package/xamarin.ios-13.21.0.199.pkg)
* [xamarin.mac-6.21.0.199.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/package/xamarin.mac-6.21.0.199.pkg)
* [xamarin.ios-13.21.0.199.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/package/notarized/xamarin.ios-13.21.0.199.pkg)
* [xamarin.mac-6.21.0.199.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/package/notarized/xamarin.mac-6.21.0.199.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/ddfun-vsdrops/1/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/ddfun-vsdrops/123a564dfa5fe059de4e28905c76d48d372cdcd4/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 183 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 1)
</details>

**Comment by dalexsoto** [comment]
@monojenkins backport d16-7

**Comment by dalexsoto** [comment]
@monojenkins backport d16-7

**Pull request merged**
