### PR TITLE
[wkwebkit] Update for iOS 10 beta 1

### PR DESCRIPTION
**Pull request by spouliot**
Also adjust introspection tests for the new NSSecureCoding
conformance of some existing types.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by dalexsoto** [comment]
LGTM 👍

**Comment by spouliot** [comment]
some tests were not executed due to `19:04:48 Could not download mlaunch: System.Net.WebException: Error: ConnectFailure (Connection timed out)`

build

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
