### PR TITLE
Prefer generic overload of Marshal methods

### PR DESCRIPTION
**Pull request by filipnavara**
Non-generic overloads produce NativeAOT warnings.

### CODE REVIEW

**Comment by filipnavara** [comment]
Contributes to #18629 /cc @ivanpovazan

**Comment by ivanpovazan** [comment]
It would be good to think about how to test these kind of fixes for warnings.

**Comment by mandel-macaque** [comment]
> It would be good to think about how to test these kind of fixes for warnings.

We do have some tests that ensure we have compilations with no warnings: https://github.com/xamarin/xamarin-macios/blob/main/tests/dotnet/UnitTests/ProjectTest.cs#L447

We could do something similar.

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
