### PR TITLE
[msbuild] Don't override the OnDemandResourcesUrl if previously set

### PR DESCRIPTION
**Pull request by jstedfast**
This change allows users to specify a custom URL for hosting their
OnDemand Resources.

### CODE REVIEW

**Comment by jstedfast** [comment]
Might be nice to back-port this minor change to 15-2 as well.

The reason I'm adding this is that a customer needs this.

For now, I suggested just editing his Xamarin.iOS.Common.targets to make this exact same change but it'd be nice if he didn't need to do that.

**Comment by spouliot** [comment]
@jstedfast please always c.c. @emaf and @kzu on all msbuild related changes. thanks

**Comment by spouliot** [comment]
@jstedfast this has **not** been reviewed by all parties and it has **not** even build. Please do not merge PR, without a green checkmark, unless you have looked why they failed.

**Comment by jstedfast** [comment]
the build failure had nothing to do with the change, I checked.

**Comment by spouliot** [comment]
A build failure is not an excuse to merge without the test being executed.

**Pull request merged**
