### PR TITLE
Build System.Security for XM Mobile

### PR DESCRIPTION
**Pull request by chamons**
- Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=42692

### CODE REVIEW

**Comment by chamons** [comment]
Blind patch apply from C7. Wait for build before accepting.

**Comment by spouliot** [comment]
netstandard has not been ported to master yet. Waiting for QA result on C8 first

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by chamons** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by chamons** [comment]
@spouliot Please let me know when netstandard hits master from and I can land this. I merged it up to this morning (no conflict).

**Comment by akoeplinger** [comment]
@chamons from my understanding netstandard hit master a while ago. Can we get this merged? And I guess backported to Cycle8?

**Comment by chamons** [comment]
@spouliot thoughts?

**Comment by spouliot** [comment]
@chamons @akoeplinger point me to the commits - I did not port the changes (from cycle8) since it's a WIP and I'm working on xcode8.

**Comment by akoeplinger** [comment]
@spouliot https://github.com/xamarin/xamarin-macios/pull/434

**Comment by spouliot** [comment]
@akoeplinger thanks, forgot about it :) LGTM

**Comment by spouliot** [comment]
@chamons that's fine to (rebase and) merge - if it was not covered by other PR/commits.

**Pull request merged**
