### PR TITLE
[runtime] integrate mono 2017-10

### PR DESCRIPTION
**Pull request by lewurm**
either this PR or https://github.com/xamarin/xamarin-macios/pull/2906

### CODE REVIEW

**Comment by lewurm** [comment]
closed, see https://github.com/xamarin/xamarin-macios/pull/2906

**Comment by lewurm** [comment]
build

**Comment by rolfbjarne** [comment]
@lewurm there are some breaking changes in the BCL: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5456/API_diff/, please review those to see if they're expected.

**Comment by rolfbjarne** [comment]
build

**Comment by marek-safar** [comment]
The API diff looks good from my POV. The `BufferToBSTR` mistake should not ideally happen but it was for a very short period of time and the API entry point is very unlikely used by anyone.

**Comment by rolfbjarne** [comment]
It seems the Jenkins bot might be running out of disk space, but with a non-obvious error, so I'm not sure.

**Comment by rolfbjarne** [comment]
build

**Comment by GouriKumari** [comment]
QA Passed Test Results:
BCL new tests in mono-2017-10: http://xqa-jenkins2.corp.microsoft.com:8080/job/XI/view/mono2017-10/job/bclunified-mono2017-10-newtests/2/testReport/XQA.iOS/iOSUnitTests/ 
BCL unified tests: http://xqa-jenkins2.corp.microsoft.com:8080/job/XI/view/mono2017-10/job/bclunified-mono-2017-10/6/testReport/XQA.iOS/iOSUnitTests/
tvOS Unified Tests: http://xqa-jenkins2.corp.microsoft.com:8080/job/XI/view/mono2017-10/job/tvosunittests-mono-2017-10/5/testReport/XQA.iOS/TVOSUnitTests/
XIUnifies tests: Verified failed tests, http://xqa-jenkins2.corp.microsoft.com:8080/job/XI/view/mono2017-10/job/xiunifiedlongtests-mono-2017-10/5/testReport/XQA.iOS/iOSUnitTests/
Sample Tests:

**Comment by spouliot** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=60540 is unrelated to `2017-10`, it exists in `master`

https://bugzilla.xamarin.com/show_bug.cgi?id=60571 seems a regression that was fixed in `2017-06` but _maybe_ not backported to `2017-10` ? @vargaz ?

**Comment by luhenry** [comment]
@spouliot https://bugzilla.xamarin.com/show_bug.cgi?id=60571 should be fixed with https://github.com/mono/mono/pull/6005. Let me bump mono on this branch so we can have a build that QA can test

**Comment by spouliot** [comment]
The other issues are unrelated (seems to be an issue running them in parallel on mac). @luhenry unless someone else expressed concerns recently this can be merged into master :)

**Pull request merged**
