### PR TITLE
Bump maccore.

### PR DESCRIPTION
**Pull request by rolfbjarne**
New commits in xamarin/maccore:

* xamarin/maccore@f1526568f4 [tests] Run the correct sample tests when launched from CI (#2234)

Diff: https://github.com/xamarin/maccore/compare/ed6d1468221f2220cd3f39294427160f0d3fbced..f1526568f4797283512c67c3f2058152556d9104

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8866/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8866/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8866/2//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8866/2//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.146.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/xamarin.ios-13.21.1.146.pkg)
* [xamarin.mac-6.21.1.146.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/xamarin.mac-6.21.1.146.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8866.146+sha.d5e81e3a5.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8866.185+sha.d5e81e3a5.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8866/d5e81e3a56172aa1a0f6181362230c5d9ccb2dcd/2/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-8866/2/display/redirect) 🔥

**Comment by mandel-macaque** [comment]
@rolfbjarne ignore the mac os 10.9 issues, is due to the bot.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8866/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8866/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.9'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-8866/3//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8866/3//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-13.21.1.147.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/xamarin.ios-13.21.1.147.pkg)
* [xamarin.mac-6.21.1.147.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/xamarin.mac-6.21.1.147.pkg)
* [Microsoft.iOS.Ref.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Ref.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Runtime.ios-arm.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Runtime.ios-arm64.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Runtime.ios-x64.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Runtime.ios-x86.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.iOS.Sdk.13.5.100-ci.pr.gh8866.147+sha.0ae1ef236.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.tvOS.Ref.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.tvOS.Runtime.tvos-arm64.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.tvOS.Runtime.tvos-x64.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.tvOS.Sdk.13.4.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.watchOS.Ref.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.watchOS.Runtime.watchos-arm.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.watchOS.Runtime.watchos-x86.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)
* [Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/package/Microsoft.watchOS.Sdk.6.2.100-ci.pr.gh8866.186+sha.0ae1ef236.nupkg)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8866/0ae1ef23617ea6f9b9dfcbab86299c0315d2fcaa/3/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-8866/3//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on 10.9 failed: Xamarin.Mac tests on macOS 10.9 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-8866/3/display/redirect) 🔥

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* API comparison: https://github.com/xamarin/maccore/issues/1467
* macOS 10.9: https://github.com/xamarin/maccore/issues/2221
* Sample tests: https://github.com/xamarin/maccore/issues/2236 (but they launched using the correct job, which is what this PR is about)

**Pull request merged**
