### PR TITLE
[mobilecoreservices] Modernize UTType

### PR DESCRIPTION
**Pull request by spouliot**
* Use `is` instead of `==` for null checks
* Use `ThrowHelper` to throw common exceptions
* Use faster `CFString` API (over the slower `NSString` variants)

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Comment by chamons** [comment]
Test failure was "App Build monotouch-test Debug [dotnet]", which I had not seen before.

**Comment by spouliot** [comment]
@chamons they are build failures so I must have missed some tests 👀

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Known flaky test: https://github.com/xamarin/maccore/issues/2443

**Pull request merged**
