### PR TITLE
[src] Remove the ModelAttribute.AutoGeneratedName property in .NET.

### PR DESCRIPTION
**Pull request by rolfbjarne**
AutoGeneratedName was a toggle to implement a certain (correct) behavior,
while at the same time not cause breaking changes.

Now that we can do breaking changes in .NET, we can remove the toggle (i.e.
the property), and just always do the right thing (that is: automatically
generate a _unique_ Objective-C name for Model classes, unless a name is
specified manually).

Ref: https://github.com/xamarin/xamarin-macios/issues/5107

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by chamons — APPROVED** [review]
I'm not 100% sure I prefer another #if block over ignoring AutoGeneratedName setting in NET, though since the blocks are so tightly scoped it shouldn't interact poorly with the attribute rename (when I get back to that finally).

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* introspection/Mac Catalyst [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2414
* monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): https://github.com/xamarin/maccore/issues/581

**Comment by rolfbjarne** [comment]
@chamons my criteria was to optimize for the cleanest code once we drop support for legacy and can remove all the !NET code. That said, I can wait with merging this until your attribute changes are done if that makes things easier for you.

**Comment by chamons** [comment]
Nope, there are no attributes inside the #if blocks so it should be fine. 🤞

**Pull request merged**
