### PR TITLE
[msbuild] code cleanup

### PR DESCRIPTION
**Pull request by jstedfast**

### CODE REVIEW

**Comment by spouliot** [comment]
👍

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
@chamons looks like a random failure on the mac tests -> https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/981/

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by chamons** [comment]
@spouliot Crash log suggests:

17  com.apple.QuickLookUIFramework	0x00007fff8e54ad14 -[QLPreviewPanel initWithContentRect:styleMask:backing:defer:] + 79

I'm going to blacklist QLPreviewPanel and see if it helps.

**Pull request merged**
