### PR TITLE
[Tests] Fix the Network tests.

### PR DESCRIPTION
**Pull request by mandel-macaque**
The pattern used to Cancel then Dispose the connection is wrong and
ended up crashing the tests sometimes. It is a race condition and is
very rare, but makes the tests flaky. The changes ensures that we
Dispose the connection, which internally closes it.

Also cleaned some on the CWL that were not needed.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Exactly why did the crash occur? Under which sequence of events? Could we make it easier for customers to not make the same mistake by changing our API somehow?

**Comment by mandel-macaque** [comment]
@rolfbjarne I was using the API wrong. I was getting the Cancelation of the network in the state change handler, then disposing the object there. The crash was happening when the BlockLiteral was being cleaned. 

Users should not be doing that (cancel != dispose) and there is nothing I can think of that would about that from happening. The handler does not pass the connection, it was a variable I was storing in the test case.

**Comment by rolfbjarne** [comment]
@mandel-macaque I don't see how Cancel + Dispose would cause problems when freeing the block, since it should only be freed once in any case. And if it's freed too early, then it would crash somewhere else.

**Comment by mandel-macaque** [comment]
@rolfbjarne I had a hard time to repro, let me check if I can get the trace for you.

**Comment by mandel-macaque** [comment]
@rolfbjarne is not a block literal issue, but a double dispose (I probably read the stack wrong). Here is the sample crash:

```
2019-10-24 10:53:38.794758-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestConnectionSetupTime
2019-10-24 10:53:38.802170-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestDuration
2019-10-24 10:53:38.811304-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestEnum
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x100479fa5 - /Users/mandel/Library/Developer/CoreSimulator/Devices/700272AE-6820-464C-90C6-382373785E60/data/Containers/Bundle/Application/DC84263F-9870-4FC8-ABDE-F9DC0679D3A7/monotouchtest.app/monotouchtest : mono_dump_native_crash_info
	0x10046ded5 - /Users/mandel/Library/Developer/CoreSimulator/Devices/700272AE-6820-464C-90C6-382373785E60/data/Containers/Bundle/Application/DC84263F-9870-4FC8-ABDE-F9DC0679D3A7/monotouchtest.app/monotouchtest : mono_handle_native_crash
	0x100481221 erateResolutions
2019-10-24 10:53:38.812264-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestPreviousAttemptCount
2019-10-24 10:53:38.813053-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestProxyConfigured
2019-10-24 10:53:38.813760-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestProxyEnpoint
2019-10-24 10:53:38.814235-0400 monotouchtest[77857:44932969] 	[PASS] NWEstablishmentReportTest.TestUsedProxy
2019-10-24 10:53:38.815712-0400 monotouchtest[77857:44932969] NWEstablishmentReportTest : 54 ms
2019-10-24 10:53:38.817229-0400 monotouchtest[77857:44932969] Tests run: 7 Passed: 7 Inconclusive: 0 Failed: 0 Ignored: 0
2019-10-24 10:53:38.818235-0400 monotouchtest[77857:44935952] State is Cancelled and error
- /Users/mandel/Library/Developer/CoreSimulator/Devices/700272AE-6820-464C-90C6-382373785E60/data/Containers/Bundle/Application/DC84263F-9870-4FC8-ABDE-F9DC0679D3A7/monotouchtest.app/monotouchtest : mono_sigsegv_signal_handler_debug
	0x7fff51d15b5d - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x14 - Unknown
	0x7fff50cb5f02 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib : _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class
	0x7fff50cc54b3 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib : objc_destructInstance
	0x7fff50ccb94f - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib : -[NSObject dealloc]
	0x7fff50ad8d85 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libnetwork.dylib : -[NWConcrete_nw_connection dealloc]
	0x7fff50ccc0d6 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib : _ZN11objc_object17sidetable_releaseEb
	0x110f4573b - Unknown
	0x7fff51afd7b9 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x7fff51aff861 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_queue_override_invoke
	0x7fff51b0cbf9 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_root_queue_drain
	0x7fff51b0d39b - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_worker_thread2
	0x7fff51d1d6b3 - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_pthread.dylib : _pthread_wqthread
	0x7fff51d1d3fd - /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_pthread.dylib : start_wqthread

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff50ccc00b):0x7fff50ccbffb  00 00 0f 1f 00 48 85 ff 74 02 79 01 c3 48 8b 07  .....H..t.y..H..
0x7fff50ccc00b  f6 40 20 04 74 0a be 01 00 00 00 e9 0d 00 00 00  .@ .t...........
0x7fff50ccc01b  48 8b 35 de b1 f7 38 ff 25 b8 ff c4 36 55 48 89  H.5...8.%...6UH.
0x7fff50ccc02b  e5 41 57 41 56 41 55 41 54 53 48 83 ec 28 41 89  .AWAVAUATSH..(A.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at CoreFoundation.CFObject:CFRelease <0x0008a>
	  at CoreFoundation.NativeObject:Release <0x00022>
	  at CoreFoundation.NativeObject:Dispose <0x00032>
	  at CoreFoundation.NativeObject:Dispose <0x00018>
	  at MonoTouchFixtures.Network.NWEstablishmentReportTest:ConnectionStateHandler <0x000da>
	  at Network.NWConnection:Trampoline_StateChangeCallback <0x000ae>
	  at Network.NWConnection:Trampoline_StateChangeCallback <0x0007a>
```

**Comment by rolfbjarne** [comment]
@mandel-macaque 

1. It should be safe to call Dispose multiple times on managed objects, so a double dispose shouldn't be a problem.
2. The issue is that if Cancel+Dispose causes a crash, then just Cancel will also cause a crash, because the Dispose will happen later anyway when the GC collects the object in question. Your solution is to just never Cancel, but that doesn't help if something's wrong with Cancel (can you write a test that uses Cancel and never crashes?)

BTW the crash was fairly simple to reproduce by running monotouch-test from VSfM and then just manually run the NWEstablishmentReportTest test multiple times.

**Comment by mandel-macaque** [comment]
@rolfbjarne that is the way I repro the issue ;) Lets see if cancel is crashing, but I'd be surprised.

**Pull request merged**
