### PR TITLE
[runtime] integrate mono 2017-10 (rebased)

### PR DESCRIPTION
**Pull request by lewurm**
Wrench lane: https://wrench.internalx.com/Wrench/ViewTable.aspx?lane_id=5541&host_id=379 (green)

### CODE REVIEW

**Comment by luhenry** [comment]
We should probably wait for https://github.com/xamarin/xamarin-android/pull/943 to be ready to merge before merging this one, as we don't want to risk having different embedded versions between Android and iOS.

**Comment by GouriKumari** [comment]
Updated  automation test info in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=514854&_a=edit. Based  on QA test results, mono-2017-10 can be integrated with macios master. QA approved.

**Comment by spouliot** [comment]
@lewurm any reason why this PR made from `mono-2017-10` ? 

There are other changes (at least tests integration) being merged into the `mono-2017-10` branch and they don't show up here.

**Comment by lewurm** [comment]
That's very confusing;  I wasn't expecting someone to PR against `mono-2017-10`: https://github.com/xamarin/xamarin-macios/pull/2900

In that case, I agree, we should merge `mono-2017-10` instead. See https://github.com/xamarin/xamarin-macios/pull/2905

**Pull request closed without merging**
