### PR TITLE
Updating Xamarin.iOS.HotRestart.Client to 1.0.124

### PR DESCRIPTION
**Pull request by MSLukeWest**
The latest version has Component Governance fixes in it: https://github.com/xamarin/isignsharp/pull/52/files

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869900

### CODE REVIEW

**Comment by rolfbjarne** [comment]
The build fails with:

> /Users/builder/azdo/_work/4/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj : error NU1102: Unable to find package Microsoft.VisualStudio.Threading.Analyzers with version (>= 17.7.35)

which makes sense, because that version is not available on [nuget.org](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers) (17.7.30 is the latest version).

**Comment by MSLukeWest** [comment]
> The build fails with:
> 
> > /Users/builder/azdo/_work/4/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj : error NU1102: Unable to find package Microsoft.VisualStudio.Threading.Analyzers with version (>= 17.7.35)
> 
> which makes sense, because that version is not available on [nuget.org](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers) (17.7.30 is the latest version).

@rolfbjarne Thanks for pointing out the error for me.  I fixed this in the newer version, looks like the build passes now.

cc @mauroa

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
