### PR TITLE
Bump maccore to point to commit with the docs fix.

### PR DESCRIPTION
**Pull request by mandel-macaque**
This revision in maccore has a fix for 58312 that makes sure that the xml can be correctly parsed when it contains templated actions with more than one arg.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Changes in maccore are here: https://github.com/xamarin/maccore/pull/561

**Comment by spouliot** [comment]
23:35:54 [9/14/2017 7:35:54 PM] : System.IO.IOException: Disk full. Path

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
System.IO.IOException: Disk full. Path /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/jenkins-results/tests/introspection_149/test-classic-20170914_235234.log again :(

**Pull request merged**
