### PR TITLE
[Generator] Allow the generator to write calls that will take arrays of structures.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Initially, the generator will try to use the following code when it sees
a parameter that is an array of structures:

**Binding code**

```csharp
[Export ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:")]
void ConvertSparsePixelRegions (MTLRegion [] pixelRegions, MTLRegion [] tileRegions, MTLSparseTextureRegionAlignmentMode mode, nuint numRegions);
```

**Generated code**

```csharp
var nsa_pixelRegions = NSArray.FromNSObjects (pixelRegions);
var nsa_tileRegions = NSArray.FromNSObjects (tileRegions);
```

With the change, the generator will write something like:

```csharp
if (pixelRegions == null)
	throw new ArgumentNullException ("pixelRegions");
if (tileRegions == null)
	throw new ArgumentNullException ("tileRegions");

var nsa_pixelRegionsHandle = GCHandle.Alloc (pixelRegions, GCHandleType.Pinned);
IntPtr nsa_pixelRegions = nsa_pixelRegionsHandle.AddrOfPinnedObject ();
var nsa_tileRegionsHandle = GCHandle.Alloc (tileRegions, GCHandleType.Pinned);
IntPtr nsa_tileRegions = nsa_tileRegionsHandle.AddrOfPinnedObject ();

try {
	if (IsDirectBinding) {
		global::api0.Messaging.void_objc_msgSend_IntPtr_IntPtr_int_nuint (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), nsa_pixelRegions, nsa_tileRegions, (int)mode, numRegions);
	} else {
		global::api0.Messaging.void_objc_msgSendSuper_IntPtr_IntPtr_int_nuint (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), nsa_pixelRegions, nsa_tileRegions, (int)mode, numRegions);
	}
} finally {
	nsa_pixelRegionsHandle.Free ();
	nsa_tileRegionsHandle.Free ();

}
```

This allows to stop using manual bindings for those cases in which we
are taking a struct[] which there are a few.

Fixes: https://github.com/xamarin/xamarin-macios/issues/6994

### CODE REVIEW

**Comment by rolfbjarne** [comment]
The generated code would be simpler with the array type in the P/Invoke declaration:

```csharp
[DllImport (...)]
static extern void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_nuint (IntPtr handle, IntPtr sel, MTLRegion[] pixelRegions, MTLRegion[] tileRegions, int mode, nuint numRegions);
```

and then the generated code would become:

```csharp
if (pixelRegions == null)
	throw new ArgumentNullException ("pixelRegions");
if (tileRegions == null)
	throw new ArgumentNullException ("tileRegions");

if (IsDirectBinding) {
	global::api0.Messaging.void_objc_msgSend_IntPtr_IntPtr_int_nuint (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegions, tileRegions, (int)mode, numRegions);
} else {
	global::api0.Messaging.void_objc_msgSendSuper_IntPtr_IntPtr_int_nuint (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegions, tileRegions, (int)mode, numRegions);
}
```

**Comment by spouliot** [comment]
I was about to suggest `fixed` instead of allocating (and free'ing) two `GGHandle` but @rolfbjarne suggestion is even simpler :)

**Comment by Therzok** [comment]
Might be worth annotating arrays with `[In]`, the runtime will not marshal back any changes done to the array.

**Comment by Therzok** [comment]
I wonder if you can use [MemoryMarshal](https://source.dot.net/#System.Private.CoreLib/MemoryMarshal.cs,83) APIs to safe the headache of pinning, etc.

**Comment by dalexsoto** [comment]
Agreed, I think Rolf suggestion is simpler

**Review by rolfbjarne — COMMENTED** [review]
https://github.com/xamarin/xamarin-macios/pull/7539#issuecomment-561393255

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
https://github.com/xamarin/xamarin-macios/pull/7539#issuecomment-561393255

**Comment by rolfbjarne** [comment]
This is an old PR :) Things have changed a bit since then, and most importantly the new detail now is that we only want to create blittable P/Invokes, and arrays aren't blittable. We'll have to do something like Sebastien suggested instead:

```cs
[DllImport (...)]
static unsafe extern void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_nuint (IntPtr handle, IntPtr sel, MTLRegion* pixelRegions, MTLRegion* tileRegions, int mode, nuint numRegions);

if (pixelRegions is null)
	throw new ArgumentNullException (nameof (pixelRegions));
if (tileRegions is null)
	throw new ArgumentNullException (nameof (tileRegions));

fixed (MTLRegion* pixelRegionsPtr = &pixelRegions[0]) {
    fixed (MTLRegion* tileRegionsPtr = &tileRegions[0]) {
        if (IsDirectBinding) {
        	global::api0.Messaging.void_objc_msgSend_IntPtr_IntPtr_int_nuint (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, numRegions);
        } else {
        	global::api0.Messaging.void_objc_msgSendSuper_IntPtr_IntPtr_int_nuint (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, numRegions);
        }
    }
}
```

and then we'll also probably need to check the length of the arrays to ensure length>0 before getting the address of the first item.

**Comment by dustin-wojciechowski** [comment]
The approach I took to get the indentations correct is a little rough and hoping the upcoming refactoring work will introduce a better overall solution :( 

Here's what the generator produces now with this PR:
```
public unsafe extern static void void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_UIntPtr (IntPtr receiver, IntPtr selector, MTLRegion* arg1, MTLRegion* arg2, int arg3, UIntPtr arg4);

public virtual void ConvertSparsePixelRegions (MTLRegion[] pixelRegions, MTLRegion[] tileRegions, MTLSparseTextureRegionAlignmentMode mode, nuint numRegions)
		{
			if (pixelRegions is null)
				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (pixelRegions));
			if (tileRegions is null)
				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (tileRegions));
			if (pixelRegions.Length > 0) {
				fixed (MTLRegion* pixelRegionsPtr = &pixelRegions[0]) {
					if (tileRegions.Length > 0) {
						fixed (MTLRegion* tileRegionsPtr = &tileRegions[0]) {
							if (IsDirectBinding) {
								global::api0.Messaging.void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
							} else {
								global::api0.Messaging.void_objc_msgSendSuper_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
							}
						}
					}
				}
			}
		}
```

A discrepancy I noticed is that ```UIntPtr``` is being used instead of ```nint``` and not sure which value we want.

**Comment by mandel-macaque** [comment]
@dustin-wojciechowski  I agree on waiting on cleaning the generator to deal with the indentation better, I have added a new test case in which we return an IntPtr[] and it fails as you can see in the generated code: https://gist.github.com/mandel-macaque/1937910665e7d5c8693d153157db14fd

@rolfbjarne  should we agree that in this branch too? 

Ps: I cannot/should not approve my own pr.

**Comment by rolfbjarne** [comment]
The problem with the length checks here: https://github.com/xamarin/xamarin-macios/pull/7539#issuecomment-1804311548 is that nothing will happen if length is 0 - but we still have to call the native code in that case (an empty array might be valid input - and if it's not, we should throw an exception instead of ignoring the condition - however the generator must at least support the general, non-exceptional, case).

Note that null arrays might be valid too.

Luckily C# allows us to use the array itself, instead of the first element, in the fixed statement:

```cs
public virtual void ConvertSparsePixelRegions (MTLRegion[] pixelRegions, MTLRegion[] tileRegions, MTLSparseTextureRegionAlignmentMode mode, nuint numRegions)
{
	if (pixelRegions is null)
		ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (pixelRegions));
	if (tileRegions is null)
		ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (tileRegions));
	fixed (MTLRegion* pixelRegionsPtr = pixelRegions) {
		fixed (MTLRegion* tileRegionsPtr = tileRegions) {
			if (IsDirectBinding) {
				global::api0.Messaging.void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
			} else {
				global::api0.Messaging.void_objc_msgSendSuper_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
			}
		}
	}
}
```

and that works both when the array is null and when the array is empty (the pointer is `NULL` in both cases)

**Comment by dustin-wojciechowski** [comment]
Output with latest commit:
```csharp
public virtual void ConvertSparsePixelRegions (MTLRegion[] pixelRegions, MTLRegion[] tileRegions, MTLSparseTextureRegionAlignmentMode mode, nuint numRegions)
{
	if (pixelRegions is null)
		ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (pixelRegions));
	if (tileRegions is null)
		ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (tileRegions));
	fixed (MTLRegion* pixelRegionsPtr = pixelRegions) {
		fixed (MTLRegion* tileRegionsPtr = tileRegions) {
			if (IsDirectBinding) {
				global::api0.Messaging.void_objc_msgSend_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.Handle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
			} else {
				global::api0.Messaging.void_objc_msgSendSuper_MTLRegionArray_MTLRegionArray_int_UIntPtr (this.SuperHandle, Selector.GetHandle ("convertSparsePixelRegions:toTileRegions:alignmentMode:numRegions:"), pixelRegionsPtr, tileRegionsPtr, (int)mode, (UIntPtr) numRegions);
			}
		}
	}
}
```

Note, the test will still fail because I have to address the return type next so this isn't complete just yet.

**Comment by dalexsoto** [comment]
@mandel-macaque will take this into account in rgen instead

**Pull request closed without merging**
