### PR TITLE
[DO_NOT_MERGE] msbuild switch

### PR DESCRIPTION
**Pull request by radical**
This is WIP, it *builds* locally. But hasn't been tested yet - WIP!

### CODE REVIEW

**Comment by rolfbjarne** [comment]
👍 You might want to incorporate the changes from PR #1364 too.

**Comment by spouliot** [comment]
@radical what's the status of this PR ?

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
@radical anything from this PR needed as mono 5.x warns about xbuild deprecation ?

**Comment by radical** [comment]
@spouliot With 15.2 the target is to have all user projects working with msbuild, but not necessarily our own product builds. I was trying to do that earlier though. I’ll try that again and if I’m able to get that done in time then you can decide whether you want to take it for 15.2 or not.

**Comment by chamons** [comment]
The msbuild boat sailed long ago successfully. @radical agrees this can be closed.

**Comment by radical** [comment]
Also, these changes are optional, at least for now. We should eventually move from the old API, but the code in it's current form should build with msbuild now. If you hit any problems, then let me know!

**Pull request closed without merging**
