### PR TITLE
[networkextension] Update to Xcode 12.3 beta 1

### PR DESCRIPTION
**Pull request by spouliot**
Mostly changes in Xcode 12.2 (beta 3)
https://github.com/xamarin/xamarin-macios/wiki/NetworkExtension-iOS-xcode12.2-beta3

and macOS-only changes from 12.3 beta 1
https://github.com/xamarin/xamarin-macios/wiki/NetworkExtension-macOS-xcode12.3-beta1

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
build

**Review by rolfbjarne — APPROVED** [review]

**Comment by spouliot** [comment]
macOS/introspection failure will be fixed by merging https://github.com/xamarin/xamarin-macios/pull/10162

**Review by mandel-macaque — APPROVED** [review]

**Comment by spouliot** [comment]
build

**Pull request merged**
