### PR TITLE
Revert "bump maccore to deprecate docs' classic dependency"

### PR DESCRIPTION
**Pull request by dalexsoto**
This reverts commit 95d1968856979e9f367a87dcc1aaecb41ec80c9a.

Unfortunately with this commit our build fails with

```
[5:06:58] GEN      XamMac.CFNetwork.xml
[5:06:58] install: ../../../../xamarin-macios/external/macios-binaries/docs/macOS/classic/XamMac.xml: No such file or directory
[5:06:58] install: ../../../../xamarin-macios/external/macios-binaries/docs/macOS/classic/XamMac.CFNetwork.xml: No such file or directory
[5:06:58] make[6]: *** [../../../../xamarin-macios/external/macios-binaries/docs/macOS/classic/XamMac.xml] Error 71
[5:06:58] make[6]: *** Waiting for unfinished jobs....
[5:06:58] make[6]: *** [../../../../xamarin-macios/external/macios-binaries/docs/macOS/classic/XamMac.CFNetwork.xml] Error 71
```

### CODE REVIEW

**Comment by dalexsoto** [comment]
@joelmartinez Will review and PR again l8tr

**Comment by dalexsoto** [comment]
Unrelated build failure
* [MSBuild/iOS random failure](https://github.com/xamarin/maccore/issues/592)

**Comment by rolfbjarne** [comment]
@joelmartinez It seems the problem is that the `macios-binaries` submodule wasn't bumped. I tried this locally, and the build goes further, but it fails later with:

```
Building MsDoc from Mono Docs

Unhandled Exception:
System.ArgumentException: Namespace 'MonoTouch.OpenTK' not found in monodoc index.
  at Xamarin.XmlDocSync.MonoDocXml.Load (System.String path) [0x001e2] in <3c766a6de50f4c6a834f70dcadbbf6e0>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.CreateMsDoc (System.String monoDocsPath, System.String assemblyPath, System.String outputPath) [0x0006a] in <5784eb3873354833a50e7a5370fcbea7>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.Main (System.String[] args) [0x000ee] in <5784eb3873354833a50e7a5370fcbea7>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Namespace 'MonoTouch.OpenTK' not found in monodoc index.
  at Xamarin.XmlDocSync.MonoDocXml.Load (System.String path) [0x001e2] in <3c766a6de50f4c6a834f70dcadbbf6e0>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.CreateMsDoc (System.String monoDocsPath, System.String assemblyPath, System.String outputPath) [0x0006a] in <5784eb3873354833a50e7a5370fcbea7>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.Main (System.String[] args) [0x000ee] in <5784eb3873354833a50e7a5370fcbea7>:0 
make[2]: *** [build/unified/Xamarin.iOS.xml] Error 1
rm build/msxml/msxml.exe
make[1]: *** [all-recurse] Error 1
make: *** [all-recurse] Error 1
```

**Comment by joelmartinez** [comment]
@rolfbjarne thanks for checking ...we will work on fixing this error, and resubmit a PR that is bumped to the new change (and will include the change for `macios-binaries` as well.

**Comment by lobrien** [comment]
The above exception was caused because I had failed to delete the no-longer-needed directory en/MonoTouch.OpenTK/ and https://github.com/xamarin/XmlDocSync/blob/master/src/XmlDocSync/MonoDocXml.cs#L63-L71 iterates over all directories and throws this exception when it cannot find a corresponding element in index.xml. 

So, I wrote a little script to validate the elements in index.ml with the directory names. It found MonoTouch.OpenTK/ and AudioUnitWrapper/, which I deleted in ios-api-docs commit d42d35c6.

**Pull request merged**
