### PR TITLE
[msbuild] Add msbuild error code logic

### PR DESCRIPTION
**Pull request by VincentDondain**
- `LoggingExtensions` has a new `MTError` extension method that helps generate an msbuild error with the proper MTxxx format.
- Added error codes for 44 msbuild errors.
- Updated `docs/website/mtouch-errors.md` and `tools/mtouch/error.cs` accordingly.
- MT7001 contains some extra documentation (troubleshooting steps).

### CODE REVIEW

**Comment by VincentDondain** [comment]
I added some headers to the documentation file. Also made sure that the error page is a bit less "mtouch" oriented.

**Comment by jstedfast** [comment]
Seems reasonable to me

**Comment by rolfbjarne** [comment]
PR #1306 will add more errors that should be converted to error codes.

**Comment by VincentDondain** [comment]
@spouliot I addressed your doc renaming concern (:

**Comment by VincentDondain** [comment]
Build failure seems unrelated.

**Comment by VincentDondain** [comment]
@rolfbjarne yes I guess I could but I wouldn't put it in this PR though.

Also @jstedfast please note that, in the future, all new msbuild errors should have their error codes (;

**Comment by rolfbjarne** [comment]
OK, in a new PR is fine with me 👍

**Comment by VincentDondain** [comment]
@rolfbjarne done: https://github.com/xamarin/xamarin-macios/pull/1325

**Pull request merged**
