### PR TITLE
Bump maccore (maciostools) to bring all the required xcode9 changes and fix simulator failures on wrench

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Wont PR https://github.com/xamarin/xamarin-macios/pull/2737 bring the same changes + the fixes in the docs?

**Comment by spouliot** [comment]
@mandel-macaque no, different branch - that's for `d15-5` and due to a merge snafu in maciostools (master is fine(

**Comment by spouliot** [comment]
known mono/roslyn random crash -> https://bugzilla.xamarin.com/show_bug.cgi?id=56665

**Comment by spouliot** [comment]
build

**Pull request merged**
