### PR TITLE
Bump maccore to get fix for #3446.

### PR DESCRIPTION
**Pull request by rolfbjarne**
commit xamarin/maccore@96b704e9eede7191324d1d231280477742a53e2f
Author: Rolf Bjarne Kvinge <rolf@xamarin.com>
Date:   Tue Feb 13 16:05:28 2018 +0100

    Bump maciostools to get fix for xamarin/xamarin-macios#3446. (#635)

Fixes xamarin/xamarin-macios#3446

### CODE REVIEW

**Comment by spouliot** [comment]
this would bump over the mono-extensions bump
which would make wrench fails when compiling the cross compilers (which jenkins does not do)
so we need to have 2017-12 merged before

**Comment by dalexsoto** [comment]
Removing don't merge since we already merged mono 2017-12 into master

**Comment by dalexsoto** [comment]
cross posting so we do not end with reverted changes https://github.com/xamarin/xamarin-macios/pull/3487

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/xamarin-macios/issues/3480)

**Pull request merged**
