### PR TITLE
[builds] Adjust ifdefs to fix not building device architectures. Fixes maccore#1074.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/maccore/issues/1074.

### CODE REVIEW

**Comment by spouliot** [comment]
@rolfbjarne let's back port to open branches - so we minimize the PR build times :) thanks!

**Comment by rolfbjarne** [comment]
Building mono went from 49 to 32 minutes (both builds on the same bot). Not as much as I'd hoped, but still better than nothing.

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
@monojenkins backport d15-9

**Comment by rolfbjarne** [comment]
@monojenkins backport xcode10.1

**Pull request merged**
