### PR TITLE
[XM] Rework binding project test to try to fix build machine issues

### PR DESCRIPTION
**Pull request by chamons**
- https://bugzilla.xamarin.com/show_bug.cgi?id=50634

### CODE REVIEW

**Comment by chamons** [comment]
Let's see if this helps...thoughts?

**Comment by rolfbjarne** [comment]
Let's build it a few times to see if it breaks.

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
@chamons it looks like you have to merge in master now for it to continue building.

**Comment by chamons** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
the tests timed out !?

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
@chamons I think this looks good, none of the build failures here have been due to the bug you're trying to fix.

**Pull request merged**
