### PR TITLE
Fixup Xamarin.Mac Hybrid AOT and improve testing

### PR DESCRIPTION
**Pull request by chamons**
Right now hybrid AOT does not do what we think. We are passing the hybrid arguments too late, and are not testing things with assemblies stripped.

This changeset does a number of things to fix the situation:

- Fixup argument order in launcher.m so it comes before the assembly filename, so hybrid-aot is actually respected
- In release hybrid configuration, add stripping of all assemblies (else why are you using hybrid?)
- Force hybrid mode to also require all AOTing. See https://bugzilla.xamarin.com/show_bug.cgi?id=55041
- Fixup mmp "unit" tests to be runable outside mmptest again. Broken due to mono 5.0 nunit changes

### CODE REVIEW

**Comment by chamons** [comment]
@rolfbjarne I believe the entire point of hybrid was to allow cil-strip to work (unlike normal AOT).

**Comment by chamons** [comment]
The answer came back from https://bugzilla.xamarin.com/show_bug.cgi?id=55041

For hybrid AOT to work with stripping, we must AOT ALL assemblies in the application. If you don't, you get bad behavior as noted.

I'll add stripping to aot.cs and only allow hybrid when you select all

**Comment by chamons** [comment]
Another update, so it appears the restriction that all assemblies must be AOTed before stripping gives sane results is due to a inliner bug. In any case, let's add a restriction when we add stripping support until that is fixed.

https://bugzilla.xamarin.com/show_bug.cgi?id=55041

**Comment by chamons** [comment]
Ok, I think this is ready for real review now.

**Comment by timrisi** [comment]
Xammac tests:
Unified45.cs(27,7): error CS0121: The call is ambiguous between the following methods or properties: 'TI.RunAndAssert(string, string, string, bool, Func<string>)' and 'TI.RunAndAssert(string, StringBuilder, string, bool, Func<string>)' 
Unified45.cs(53,7): error CS0121: The call is ambiguous between the following methods or properties: 'TI.RunAndAssert(string, string, string, bool, Func<string>)' and 'TI.RunAndAssert(string, StringBuilder, string, bool, Func<string>)' 
Unified45.cs(73,7): error CS0121: The call is ambiguous between the following methods or properties: 'TI.RunAndAssert(string, string, string, bool, Func<string>)' and 'TI.RunAndAssert(string, StringBuilder, string, bool, Func<string>)' 
System.ServiceModel/Net45.cs(51,7): error CS0121: The call is ambiguous between the following methods or properties: 'TI.RunAndAssert(string, string, string, bool, Func<string>)' and 'TI.RunAndAssert(string, StringBuilder, string, bool, Func<string>)'

**Comment by chamons** [comment]
My bad. Forgot to build unrelated tests locally. Fixing

**Comment by spouliot** [comment]
@chamons since it was not tested (at least correctly) in the previous sprint then let's add this to the 15.3 trello board.

**Comment by chamons** [comment]
https://trello.com/c/SQ3oB0iI/10-xm-working-hybrid-aot-with-stripping

**Comment by chamons** [comment]
Looks like my fix broke things. Looking.

**Comment by chamons** [comment]
All of the test failures appear to be iOS signing (bot) issues that have been reported to RE.

**Comment by chamons** [comment]
Test failure appears to be new intermittent failure:

https://bugzilla.xamarin.com/show_bug.cgi?id=56520

**Pull request merged**
