### PR TITLE
[runtime] Always release blocks on the main thread. Fixes #4130. (#4312)

### LINKED ISSUE #4130: Reproducible native crash bug with WKWebView in latest Xamarin.iOS
(Coming from Bugzilla we were at a loss where to post this and wrongly submitted this bug report to the Xamarin forums first, sorry about that).

Loading a WKWebView with a HTML string twice using a WKNavigationDelegate that overrides DecidePolicy crashes Xamarin.

### Steps to Reproduce

Create a new project with this UIVIewController
```
    public class TestController : UIViewController
    {
        class Navigator : WKNavigationDelegate
        {
            public override void DecidePolicy(WKWebView webView, WKNavigationAction navigationAction, Action<WKNavigationActionPolicy> decisionHandler)
            {
		decisionHandler(WKNavigationActionPolicy.Cancel);
	    }
        }

        WKWebView page;

        void AddPage()
        {
            page?.RemoveFromSuperview();
            page = new WKWebView(new CGRect(0, 0, 400, 400), new WKWebViewConfiguration());
            page.NavigationDelegate = new Navigator();
            page.LoadHtmlString("", new NSUrl(NSBundle.MainBundle.ResourceUrl + ""));

            View.AddSubview(page);

            Console.WriteLine("OK");
        }

        public override void ViewDidLoad()
        {
            UIButton button = new UIButton(new CGRect(200, 500, 0, 0));

            button.SetTitle("Add page", UIControlState.Normal);
            button.SizeToFit();
            button.TouchUpInside += (sender, e) => AddPage();

            View.AddSubview(button);
        }
    }
```
Pressing the button should add an empty webview to the view controller and print "OK" to stdout. This works the first time, but waiting a second and pressing the button again will add the page, print "OK" and then either simply hang or crash the application Sometimes you might get away with more presses, but ultimately it does crash.

### Expected Behavior

App shouldn't crash

### Actual Behavior

App crash

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/4130.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
`do-not-merge` since this PR is only to create a d15-8 package with the fix for #4130.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4500/1/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4500/1//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/1/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/1/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4500/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4500/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/2/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/2/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
@davidortinau XI package: 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4500/d807bb8f2fbd6508a847ba1c9e97060ad58f9799/2/package/xamarin.ios-11.14.0.14.pkg

Closing this PR, since we got what we wanted.

**Comment by kalyanmungi** [comment]
This crash is happening across our app and we are on Xamarin iOS 11.12.0.4. Waiting for Xamarin iOS 11.14. We delayed our release until 11.14 general release. Can we please know, When is Xamarin iOS 11.14 stable version releasing?

**Comment by rolfbjarne** [comment]
@kalyanmungi 11.14 is scheduled for release in mid August (so a couple of weeks more or less), but the public build won't have this fix.

However, you can use the package mentioned in my previous comment, which is the public build + this fix.

**Comment by ubeerli** [comment]
@rolfbjarne Thanks for your package. Do you know when this fix will be in a public release?

**Comment by rolfbjarne** [comment]
@ubeerli current *estimate* is sometime around mid/end of November.

**Comment by Depechie** [comment]
@rolfbjarne just to be clear...

> However, you can use the package mentioned in my previous comment, which is the public build + this fix.

What public build is this for Visual Studio for Mac? v 7.5.4 or what do you mean with this public build reference.

**Comment by rolfbjarne** [comment]
> @rolfbjarne just to be clear...

>> However, you can use the package mentioned in my previous comment, which is the public build + this fix.
> What public build is this for Visual Studio for Mac? v 7.5.4 or what do you mean with this public build reference.

The equivalent Visual Studio for Mac is v7.6 (which is currently in the beta channel, but it should be released very soon (days) to the stable channel).

So the best procedure to get this fix right now is:

1. Change the channel in Visual Studio for Mac to the beta channel, and update to what Visual Studio for Mac downloads.
3. Download the mentioned package and install it.

Have in mind that very soon step 1. should be from the stable channel instead (you might have to redo step 3 at that point, since I'm not sure if Visual Studio for Mac will reinstall the official package instead after switching channels).

**Comment by Depechie** [comment]
Thanks for the details info!
Maybe 1 small extra, will the About Visual Studio popup list the use of the 11.14 version of Xamarin.iOS?
In other words if we want to double check if a mac has the installed patch or not, how do we track this best?

**Comment by rolfbjarne** [comment]
@Depechie The About Visual Studio popup will list the package you install manually, and it will show this section:

    Xamarin.iOS
    Version: 11.14.0.14 (Visual Studio Community)
    Hash: d807bb8f
    Branch: HEAD
    Build date: 2018-07-25 09:04:12-0400

The most important part to verify is the hash (which is also a part of the url to the package).

**Comment by pineapple216** [comment]
@rolfbjarne Is this fix included in the current Xamarin iOS stable release (12.0.0.15)?

**Comment by kalyanmungi** [comment]
@rolfbjarne  Can you please provide a similar Xamarin iOS package to install it on Windows machine. The package you provided supports macOS only. We have Jenkins on Windows side, so we have to do pairing over to the mac. Since the Xamarin iOS package on windows side is different from the one on macOS side, we're getting following error.

`Runtime does not contain a definition for 'ReleaseBlockOnMainThread`

**Pull request closed without merging**
