### PR TITLE
[MTouch] If we are building a shared code extension, do not build the msym dir. #60415

### PR DESCRIPTION
**Pull request by mandel-macaque**
We used to try and build the msym dir for shared code extensions, this meant that a warning was given because in that case, the msym is shared, therefore we already have it in the app path as per comments in the bug https://bugzilla.xamarin.com/show_bug.cgi?id=60415

Since the action is done at the very end, we know what we are building and we can scape the method if we are an extension and shared.

### CODE REVIEW

**Comment by spouliot** [comment]
@rolfbjarne good point. Can you point @mandel-macaque to the code sharing tests ? The warning should already be reported (and just missed/ignored) and the only thing that can be tested is it's absence moving forward. Thanks!

**Comment by mandel-macaque** [comment]
@spouliot got an idea on how to do it

**Comment by rolfbjarne** [comment]
It looks like none of the mtouch tests produce an MT0095 warning, so a new test would have to be written.

**Comment by mandel-macaque** [comment]
Failing tests are related to network issues as pointed here https://github.com/xamarin/maccore/issues/582

**Comment by mandel-macaque** [comment]
@spouliot @rolfbjarne will merge unless told otherwise :)

**Pull request merged**
