### PR TITLE
[Network] Add nullability support.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Fixed 2 issues that have been raised by the compiler.

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by whitneyschmidt — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by spouliot — COMMENTED** [review]
Large changes in `main` will make back porting `xcode12` harder - even if this framework has not really been updated yet

**Review by spouliot — CHANGES_REQUESTED** [review]
see breaking changes

it's sadly easy to create a nullable type (breaking change) instead of a nullable annotation (which is not a breaking change)

Also we should figure out why xtro does not report (and does not seem to ignore) nullability for this framework

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@spouliot xtro does not pick it up, but mainly because the headers do not state it :/

**Comment by mandel-macaque** [comment]
@spouliot the delegate change was a mistake, is an enum and will never be null. xtro was ran with no issue.

**Comment by mandel-macaque** [comment]
Failure is due to a known issue https://github.com/xamarin/maccore/issues/1605

**Review by spouliot — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@monojenkins backport xcode12

**Pull request merged**
