### PR TITLE
[jenkins] Fail if test run fails.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by spouliot** [comment]
note: that branch includes your previous, unrelated commit

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
Both test failures are due to https://bugzilla.xamarin.com/show_bug.cgi?id=37794.

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
So introspection-mac is randomly failing, but I've run it 200 times locally without any crashes 😞 

I'll merge this, and then we can always back it out again if it turns out too painful.

**Pull request merged**
