### PR TITLE
[msbuild] Enable nuget package conflict resolution

### PR DESCRIPTION
**Pull request by radical**
Fixes https://github.com/mono/mono/issues/10602 .

From the issue:
```
We need to enable this to support the system assemblies conflict
resolution which we now rely on for any new packages to enhance
developers experience and get us out of dependency on specific package
versions.
```

### CODE REVIEW

**Comment by radical** [comment]
Need to add in a few more places, will update PR in a bit.

**Comment by radical** [comment]
Updated. Essentially we want to have the property set before the `Microsoft.{CSharp,FSharp,Common}*` targets get imported.

**Comment by radical** [comment]
Where should I add a test project for this?

**Comment by rolfbjarne** [comment]
> Where should I add a test project for this?

I think msbuild/tests/ is the best place, in the Xamarin.iOS.Tasks.Tests unit test project.

**Comment by chamons** [comment]
FYI - msbulid/tests is only for iOS. https://github.com/xamarin/xamarin-macios/tree/master/tests/msbuild-mac is where you'd need to add a XM test.

**Comment by marek-safar** [comment]
@spouliot can we get this in? It's needed for 2018-06

**Comment by spouliot** [comment]
@marek-safar I thought it was waiting on a test from @radical -> 
https://github.com/xamarin/xamarin-macios/pull/4945#issuecomment-427523073

**Pull request merged**
