### PR TITLE
[AppKit] NSTextView allows passing nil to PasteAsPlainText and PasteAsRichText.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This is documented in Apple's documentation, their headers, and even proved
experimentally.

### CODE REVIEW

**Comment by spouliot** [comment]
I was expecting a better failure than a NRE from xtro :( but it did fail ;-)

**Comment by spouliot** [comment]
@mandel-macaque the xtro failure is not reported correctly but the stack trace comes from xharness (not xtro itself).

**Comment by spouliot** [comment]
local output
```
?unknown-entry? !missing-null-allowed! 'System.Void AppKit.NSTextView::PasteAsPlainText(Foundation.NSObject)' is missing an [NullAllowed] on parameter #0 in 'macOS-AppKit.ignore'
?unknown-entry? !missing-null-allowed! 'System.Void AppKit.NSTextView::PasteAsRichText(Foundation.NSObject)' is missing an [NullAllowed] on parameter #0 in 'macOS-AppKit.ignore'
Sanity check failed (2)
make: *** [classify] Error 2
```
as expected

**Comment by rolfbjarne** [comment]
> @mandel-macaque the xtro failure is not reported correctly but the stack trace comes from xharness (not xtro itself).

Filed: https://github.com/xamarin/xamarin-macios/issues/8883

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-7

**Pull request merged**
