### PR TITLE
[coretelephony] Update for Xcode 11 beta 1

### PR DESCRIPTION
**Pull request by spouliot**
No changes in beta 2 and 3

### CODE REVIEW

**Comment by spouliot** [comment]
```
16:15:27 Unable to load assembly: ../../../class/lib/xammac_net_4_5/nunitlite.dll
16:15:27 /Applications/Xcode11-beta3.app/Contents/Developer/usr/bin/make test-local
16:15:27 
make[10]: *** [../../../class/lib/xammac_net_4_5/nunitlite.dll] Error 1
16:15:27 make[9]: *** [do-all] Error 2
16:15:27 make[8]: *** [all-recursive] Error 1
16:15:27 make[7]: *** [../../build/deps/nunit-xammac_net_4_5.stamp] Error 2
16:15:27 make[7]: *** Waiting for unfinished jobs....
```

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
2nd build failure was similar
```
18:01:26 error CS0009: Metadata file '/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/mcs/class/lib/xammac_net_4_5/nunitlite.dll' could not be opened -- PE image doesn't contain managed metadata.
18:01:26 cat <./../../build/deps/_monotouch_System.Net.Http_test.dll.sources >../../build/deps/_monotouch_System.Net.Http_test.dll.response
18:01:26 cp -f ./../../tools/nunit-lite/nunit-lite-console/nunit-lite-console.exe.config.tmpl ./../../class/lib/monotouch/tests/monotouch_System.Net.Http_test.dll.nunitlite.config
18:01:26 /Applications/Xcode11-beta3.app/Contents/Developer/usr/bin/make test-local
18:01:26 Console.cs(26,17): error CS0234: The type or namespace name 'Runner' does not exist in the namespace 'NUnitLite' (are you missing an assembly reference?)
18:01:26 Console.cs(27,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
```

**Pull request merged**
