### PR TITLE
renamed tableview to tableView to follow naming convention

### PR DESCRIPTION
**Pull request by zippo227**
A name change to prevent warnings and reflect the documentation.

### CODE REVIEW

**Comment by spouliot** [comment]
Parameter name changes are _technically_ breaking changes. It's not as bad as others and we, sometime, update them - but we do try not to unless they are wrong/confusing.

**Comment by rolfbjarne** [comment]
I agree with Sebastien, this may cause existing code to stop compiling, which means it needs a compelling reason to be accepted.

**Comment by zippo227** [comment]
It will probably generate a warning in someone's code, but I thought the goal was to move forward and keep making Xamarin better. It irks me in my project to have one overriden function required to use tableview to prevent a warning. It also differs from the documentation which specifies tableView.

**Comment by dalexsoto** [comment]
We totally get the issue, we might at some point allow all breaking changes we have pending to become a thing.

> I thought the goal was to move forward and keep making Xamarin better.

Yup, definitely this is our main goal but also breaking anyone else's code is also bad, without telling them in advance that this breaking change is going to happen; this makes the assumption that Xamarin got worse instead of better 😉.

Please wrap your new code using `#if XAMCORE_4_0` in this PR like this:

```csharp

	[Export ("tableView:numberOfRowsInSection:")]
#if XAMCORE_4_0
	nint RowsInSection (UITableView tableView, nint section);
#else
	nint RowsInSection (UITableView tableview, nint section);
#endif

```

And do the same for the other member. This will allow a future (not determined yet) version of Xamarin to have this breaking changes.

**Comment by zippo227** [comment]
Requested changes added. Thanks for the solution @dalexsoto

**Comment by spouliot** [comment]
approve

**Comment by dalexsoto** [comment]
@zippo227 Thanks a lot for your contribution!

**Pull request merged**
