### PR TITLE
[AppKit] Add Catalyst attributes

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by chamons** [comment]
Seems like a hang, but given i'm touching Catalyst...

**Comment by chamons** [comment]
Also running locally.

**Comment by chamons** [comment]
Passes locally: -Mac Catalyst [dotnet] (Succeeded) Run Build

**Review by mandel-macaque — APPROVED** [review]

**Pull request merged**
