### PR TITLE
bump mono (2018-08)

### PR DESCRIPTION
**Pull request by lewurm**
Commit list for mono/mono:

* mono/mono@f919fb58c4e Fix https://github.com/mono/mono/issues/11898 (#11904)
* mono/mono@95fbc224368 Fix race condition in XmlCharType.Instance (#11828)
* mono/mono@bcda0048552 [aot] Emit runtime invoke wrappers for up to 40 parameters for bitcode, newly added tests depend on it.
* mono/mono@f0e466618d1 [crash] Add managed exception class name (#11821)
* mono/mono@23f2024af80 [2018-08] Fix Encoding serialization issue (#11807)
* mono/mono@414cafac931 [interp] Don't include internal frames in stack trace (#11793)
* mono/mono@68746a81f28 [ci] Disable log compression in pipeline builds for now - second attempt
* mono/mono@1f62222fa64 [mini] use AOT trampolines in interp mixed mode (#11781)
* mono/mono@d0184b6970e [ci] Disable log compression in pipeline builds for now
* mono/mono@a4c0912ecfb [loader] ignore 'internalcall' impl attribute on 'abstract' methods
* mono/mono@7b9d9b3f1ba [arm64] Fix passing r4/r8 arguments on the stack in the gsharedvt trampoline.
* mono/mono@e3a4484af76 [2018-08] Add .NET 4.7.2 reference assemblies (#11733)

Diff: https://github.com/mono/mono/compare/99b6da79449eb166ee2f7819f054e6776d923fff...f919fb58c4e3f803659e403814110697162750f6

### CODE REVIEW

**Comment by lewurm** [comment]
```
16:12:54 Running xibuild with args: -t -- /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/xharness.exe --verbose --jenkins --autoconf --rootdir /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests --sdkroot /Applications/Xcode101.app/Contents/Developer --markdown-summary=/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/TestSummary.md
16:12:54 
16:12:54 [0x10f66b5c0:] EXCEPTION handling: System.UnauthorizedAccessException: Access to the path "/Library/Frameworks/Mono.framework/Versions/5.18.0/etc/mono/registry/last-btime" is denied.
16:12:54 
16:12:54 "<unnamed thread>" tid=0x10f66b5c0 this=0x100bd4130 , thread handle : 0x7f81aa402cb0, state : not waiting
16:12:54   at System.IO.FileStream..ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,System.IO.FileOptions) [0x00259] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:274
16:12:54   at System.IO.FileStream..ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:144
16:12:54   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool) [0x0002a] in <96207d0baa204f48a53ad6be05f5ecba>:0
16:12:54   at System.IO.StreamWriter.CreateFile (string,bool,bool) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/streamwriter.cs:226
16:12:54   at System.IO.StreamWriter..ctor (string,bool,System.Text.Encoding,int,bool) [0x00055] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/streamwriter.cs:192
```
?

**Comment by spouliot** [comment]
@lewurm that's stack trace comes from the system mono. It seems (limited details) that xibuild (a simple wrapper around msbuild) is doing registry access and that fails.

**Comment by rolfbjarne** [comment]
@lewurm https://github.com/mono/mono/issues/11998

**Comment by rolfbjarne** [comment]
Test failure is unrelated:

* mmptest/macOS/NonSystem: https://github.com/xamarin/maccore/issues/1234

**Pull request merged**
