### PR TITLE
[build] remove 4.x profile dependency

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This is a real build failure:

```
14:23:09 The assembly mscorlib.dll was not found or could not be loaded.
14:23:09 It should have been installed in the `/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/install/tools64/lib/mono/4.5/mscorlib.dll' directory.
14:23:09 make[3]: *** [/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/install/watchos/bcl/I18N.MidEast.dll.mdb] Error 1
```

Might have something to do with mdb rebase.

**Comment by marek-safar** [comment]
I know, trying to understand the Makefile foo for the changes I need to do

**Comment by marek-safar** [comment]
build

**Comment by rolfbjarne** [comment]
MDB_REBASE is used in src/ too: https://github.com/xamarin/xamarin-macios/blob/master/src/Makefile#L268

**Comment by rolfbjarne** [comment]
Why not use the mono-api tools from the mono clone we have? It makes it easier to get any fixes to those tools (which has happened a few times in the past).

**Comment by marek-safar** [comment]
I am not sure it's worth to build whole mono just because of these 2 tools used on wrench only.

**Comment by rolfbjarne** [comment]
I don't understand, we only build those tools (which takes a couple of seconds) when we need them. We don't build a whole mono just because of these tools.

**Comment by marek-safar** [comment]
because you assume they will work with installed mono version, e.g adding new dependency for them will break you

**Comment by rolfbjarne** [comment]
That's a new test failure:

> * Assertion at /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/mono/metadata/assembly.c:1856, condition `ref_asm_class != NULL && ref_asm_class != mono_defaults.object_class && !strcmp(ref_asm_class->name, "ReferenceAssemblyAttribute")' not met

It only happens with linked tests (linkall and linksdk) - probably too much is linked away.

**Comment by marek-safar** [comment]
@rolfbjarne ok to merge?

**Comment by rolfbjarne** [comment]
@spouliot Does this look good to you? I'm not sure about the apidiff changes, but you use apidiff much more than I do, so whatever you say is fine with me.

**Comment by rolfbjarne** [comment]
All the test failures are unrelated:

* monotouch-test/Unified 64bits failed to load simulators (bug [#46368](https://bugzilla.xamarin.com/show_bug.cgi?id=46368))
* fsharp/watchOS timed out during build (bug [#46097](https://bugzilla.xamarin.com/show_bug.cgi?id=46097))

**Comment by spouliot** [comment]
No, the changes to mono-api-diff are not correct. They are breaking the current (and future) PR results (see API Diff results on jenkins).

Right now we, the macios team, control both the data (local in the repo) and the branch/bump of the mono repo including the tool. This way we can ensure it remains in sync (e.g. format) for the live of any branch without disruptions from changes on the bots. E.g. we cannot assume all bots have the same mono (system) mono version installed. That's even more unlikely with long cycle + SR and it's not in our control (unlike the mono branch we use).

**Comment by marek-safar** [comment]
@spouliot changed mono-api-diff to be still used from mono checkout

**Comment by spouliot** [comment]
@marek-safar thanks!

**Pull request merged**
