### PR TITLE
Pass features not available on iOS to linker

### LINKED ISSUE #4174: "Your mono runtime and class libraries are out of sync message" on building unit test projects with XI master
### Steps to Reproduce

1. Update System with Xamarin.iOS project, XI version: 11.11.0.331 (master: 238eb94c) 
2. Build and Run any unit test on device.

### Expected Behavior
Build Log should not contain any out of sync messages.

### Actual Behavior
"Your mono runtime and class libraries are out of sync" message is  present in build logs.

### Environment

```
Operating System: Mac OS X 10.13.4
Bot Name: XQA-XI-Sierra-6
Mono version: 5.14.0.106 (820bff26b3b)  (2018-05-25 17:29:19 -04:00)
XA version: 8.3.99.19 (HEAD/09df99bdc) 
XI version: 11.11.0.331 (master: 238eb94c) 
XM version: 4.5.0.331 (master: 238eb94c)  (2018-05-25 07:47:00 -04:00)
XVS version: 
XS version: 7.6.0.971 (e936c76)  (2018-05-28 12:49:41 -04:00)
```

### Build Logs

http://xqa.blob.core.windows.net/gist/report-c8b3a0e9db67473ebe1ff9df22e7c44d.txt, with mono 5.14
http://xqa.blob.core.windows.net/gist/report-641ce6bd5c0545618ad5b7f981fcbbdf.txt with mono 5.12

### Example Project (If Possible)

Any unit test project in xamarin-macios/tests/ folder. 

## Additional Info:
This is not a new issue in master. It was happening for quite sometime. I confirmed that QA tests are checking out the correct external/mono and build logs are not giving false results, also checked manually. This issue is occurring in bots with either mono 5.14 or 5.12 installed.

### PR DESCRIPTION
**Pull request by marek-safar**
Fixes #4174

### CODE REVIEW

**Comment by marek-safar** [comment]
Do I need to investigate the failures?

**Comment by mandel-macaque** [comment]
@marek-safar the failing tests seem to be on the Security side. We might want @spouliot to take a look since he knows best in that namespace.

* MonoTouchFixtures.Security.RecordTest.DeskCase_83099_InmutableDictionary
* MonoTouchFixtures.Security.RecordTest.DeskCase_83099_InmutableDictionary
* MonoTouchFixtures.Security.RecordTest.DeskCase_83099_InmutableDictionary

**Comment by marek-safar** [comment]
I think I saw these failing previously too and they are for sure present in the new 2018-06 bump (https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/7678/Test_20Report/)

**Comment by spouliot** [comment]
@marek-safar it's a random failure on bots -> 
https://github.com/xamarin/maccore/issues/868

**Comment by marek-safar** [comment]
@spouliot updated, thanks

**Comment by spouliot** [comment]
@chamons @rolfbjarne I thought `remoting` was disabled on **modern** (because it is for **mobile**). Maybe I misremember or it changed at some point ?

**Comment by rolfbjarne** [comment]
@spouliot doesn't look like anything is disabled for macOS, there's no --enable-minimal option here: https://github.com/xamarin/xamarin-macios/blob/08a9bdcc18c807b10487baa078a71cd4f2a5deb9/builds/Makefile#L218-L229

**Comment by spouliot** [comment]
@rolfbjarne hmm... I don't recall the reason (if there was one) but changing this now would not be a good idea.

**Comment by rolfbjarne** [comment]
@spouliot yeah, I agree, which I suppose means that no change is required for mmp in this PR.

**Comment by marek-safar** [comment]
Should I revert the mmp change then?

**Comment by spouliot** [comment]
@marek-safar yes, sorry for that

**Pull request merged**
