### PR TITLE
Bump maccore to get fix for #5888.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This also requires a minor fix in MachO.cs.

Diff: https://github.com/xamarin/maccore/compare/758f471fbc69e7f979a513f76a4b00a7c8308bf6..f7ca470c0ab275ace656efb569d0a4e4923ad664

Fixes https://github.com/xamarin/xamarin-macios/issues/5888.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5969/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5969/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5969/1//console)

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5969/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5969/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5969/2//console)
✅ Packages: [xamarin.ios-12.15.0.5.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/package/xamarin.ios-12.15.0.5.pkg) [xamarin.mac-5.15.0.5.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/package/xamarin.mac-5.15.0.5.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/jenkins-results/api-diff/index.html)
⚠️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/jenkins-results/apicomparison/api-diff.html) (🔥 breaking changes 🔥)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-5969/a77215fcb742b7ec4d25f6a99432b9f69b4275e4/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 0 tests skipped, 237 tests passed.</summary>

## Failed tests

 * MSBuild tests/iOS: Failed (Execution failed with exit code 2)
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated.

* MSBuild/iOS: https://github.com/xamarin/xamarin-macios/issues/5974

**Pull request merged**
