### PR TITLE
Fix AppleTLS SecTrustResult by cherry picking fix + bump mono d15-4

### PR DESCRIPTION
**Pull request by chamons**
https://github.com/xamarin/xamarin-macios/pull/2850 for XM

### CODE REVIEW

**Comment by chamons** [comment]
build

**Comment by rolfbjarne** [comment]
This will fail on Jenkins until PR #2871 is merged.

**Comment by rolfbjarne** [comment]
@chamons PR #2871 has been merged, so if you merge d15-4 into your branch it should work now.

**Comment by chamons** [comment]
```16:06:38 [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Disk full. Path /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/jenkins-results/tests/monotouch-test_5/build-watchOS-20171010_120502.txt
16:06:38   at System.IO.FileStream.FlushBuffer () [0x000```

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
Error known: https://bugzilla.xamarin.com/show_bug.cgi?id=59040

**Pull request merged**
