### PR TITLE
[Rgen] Keep track of properties/methods/ctrs that use smart enums.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Smart enums are special when writing the bindings. Keep track of them in the code changes structures. For example, if a user add a BindingType attr to an enum, we should regenerated the methods that use it.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by mandel-macaque** [comment]
monotounch tests and donet tests are not affected by the changes, the failures are unrelated to the PR.

**Pull request merged**
