### PR TITLE
[tests] Merge the msbuild-mac tests into the Xamarin.MacDev.Tests project.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
All the test failures are due to https://github.com/xamarin/xamarin-macios/issues/10211.

**Comment by sky41906** [comment]
> Build failure
> ✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//console)
> ✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//console)
> ✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//API_20diff_20_28from_20stable_29)
> ✅ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//API_20diff_20_28PR_20only_29) (no change)
> ✅ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//Generator_20Diff) (no change)
> 🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15837//Test_20Report) 🔥
> 
> # Test results
> 
> <details>
> <summary>6 tests failed, 127 tests passed.</summary>
> 
> ## Failed tests
> 
>  * [NUnit] Mono SystemNumericsTests/watchOS 32-bits - simulator/Debug: Failed
>  * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: Failed
>  * [xUnit] Mono SystemNumericsXunit/watchOS 32-bits - simulator/Debug: Failed
>  * [xUnit] Mono MicrosoftCSharpXunit/watchOS 32-bits - simulator/Debug: Failed
>  * [xUnit] Mono SystemCoreXunit Part 1/watchOS 32-bits - simulator/Debug: Failed
>  * mmptest/macOS/Debug: Failed (Execution failed with exit code 33)
> </details>
>

**Pull request merged**
