### PR TITLE
Make MidiPacket.ByteArray and MidiPacket.BytePointer public

### PR DESCRIPTION
**Pull request by Youssef1313**
PR https://github.com/xamarin/xamarin-macios/pull/19705 obsoleted `MidiPacket.Bytes` with obsoletion message that suggests to use internal properties. This PR changes those properties to be public so that it's actually usable.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Code looks safe, I've triggered the tests to make sure that we do not have any xtro/intro test failing before we land. Thanks for the contribution!

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
I do not believe the test failures are related, but a hiccup in the CI when trying to find the old xamarin.pkg files. I have retriggered to see if a second run fixes it.

Sorry, you got us in a major redesign of the CI.

**Comment by Youssef1313** [comment]
> I do not believe the test failures are related, but a hiccup in the CI when trying to find the old xamarin.pkg files. I have retriggered to see if a second run fixes it.
> 
> Sorry, you got us in a major redesign of the CI.

No problem! And thanks for taking care of it and for the fast review.

The CI is still failing though, does it need another re-run?

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
