### PR TITLE
[msbuild] Repack all iOS Task assemblies into Xamarin.iOS.Tasks.dll

### PR DESCRIPTION
**Pull request by jstedfast**
https://bugzilla.xamarin.com/show_bug.cgi?id=52729

### CODE REVIEW

**Comment by jstedfast** [comment]
This PR replaces https://github.com/xamarin/xamarin-macios/pull/2875

**Comment by chamons** [comment]
build

**Comment by jstedfast** [comment]
Does anyone understand what is failing in the build?

**Comment by chamons** [comment]
@jstedfast 

https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5603/Test_Report/

```iOS (BuildFailure)
Project file: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks.sln
Platform: Configuration:
Build duration: 00:00:07.0559854
Run duration: 00:37:01.1999263
Main log
Build log
: error : Error building target CoreCompile: Microsoft.Build.BuildEngine.InvalidProjectFileException: Unable to parse condition "Exists(@(IntermediateAssembly -> '%(FullPath)')) And '$(ILRepack)' != 'false'" : Expected an item list at position 8 in condition "Exists(@(IntermediateAssembly -> '%(FullPath)')) And '$(ILRepack)' != 'false'". Missing opening parantheses after the '@'. ---> Microsoft.Build.BuildEngine.ExpressionParseException: Expected an item list at position 8 in condition "Exists(@(IntermediateAssembly -> '%(FullPath)')) And '$(ILRepack)' != 'false'". Missing opening parantheses after the '@'. ```

**Comment by jstedfast** [comment]
Ok, that suggests that xbuild is being used instead of msbuild on the bots :(

**Comment by chamons** [comment]
@jstedfast Correct. msbuild currently does not have sufficient redirect support to build all of the tests and use the local built binaries. @radical is working on that.

However, I don't know of a reason why the msbuild/ can't be built w\ msbuild. You could look at changing that and see how it goes.

**Comment by jstedfast** [comment]
I modified the Makefile to make it use msbuild for building the msbuild/ directory tho. :-\

**Comment by chamons** [comment]
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5603/Test_Report/

```xbuild /verbosity:diagnostic /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks.sln``` :(

**Comment by rolfbjarne** [comment]
@jstedfast I've just pushed a fix

**Comment by chamons** [comment]
A wild @rolfbjarne to the rescue! 🎉

**Comment by jstedfast** [comment]
thanks @rolfbjarne !

**Comment by rolfbjarne** [comment]
This happens now:

```
  /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj(135,5): error : INFO: IL Repack - Version 2.0.13;
  INFO: ------------- IL Repack Arguments -------------;
  /out:/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks/obj/Debug/Xamarin.iOS.Tasks.dll  /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks/obj/Debug/Xamarin.iOS.Tasks.dll /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks.Core/bin/Debug/Xamarin.iOS.Tasks.Core.dll /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/Xamarin.MacDev/Xamarin.MacDev/bin/Debug/Xamarin.MacDev.dll /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks.Core/bin/Debug/Xamarin.MacDev.Tasks.Core.dll /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks/bin/Debug/Xamarin.MacDev.Tasks.dll /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks/bin/Debug/Mono.Cecil.dll;
  -----------------------------------------------;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks/obj/Debug/Xamarin.iOS.Tasks.dll;
  INFO: Failed to load debug information for /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks/obj/Debug/Xamarin.iOS.Tasks.dll;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks.Core/bin/Debug/Xamarin.iOS.Tasks.Core.dll;
  INFO: Failed to load debug information for /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.iOS.Tasks.Core/bin/Debug/Xamarin.iOS.Tasks.Core.dll;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/Xamarin.MacDev/Xamarin.MacDev/bin/Debug/Xamarin.MacDev.dll;
  INFO: Failed to load debug information for /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/Xamarin.MacDev/Xamarin.MacDev/bin/Debug/Xamarin.MacDev.dll;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks.Core/bin/Debug/Xamarin.MacDev.Tasks.Core.dll;
  INFO: Failed to load debug information for /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks.Core/bin/Debug/Xamarin.MacDev.Tasks.Core.dll;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks/bin/Debug/Xamarin.MacDev.Tasks.dll;
  INFO: Failed to load debug information for /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks/bin/Debug/Xamarin.MacDev.Tasks.dll;
  INFO: Adding assembly for merge: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/Xamarin.MacDev.Tasks/bin/Debug/Mono.Cecil.dll;
  INFO: Processing references;
  INFO: Processing types;
  INFO: Merging <Module>;
  INFO: Merging <Module>;
  ERROR: Duplicate type Xamarin.iOS.Tasks.ACToolTaskBase;
  System.InvalidOperationException: Duplicate type Xamarin.iOS.Tasks.ACToolTaskBase from Xamarin.iOS.Tasks.Core.dll, was also present in Xamarin.iOS.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;
  at ILRepacking.RepackImporter.Import (Mono.Cecil.TypeDefinition type, Mono.Collections.Generic.Collection`1[T] col, System.Boolean internalize) [0x00165] in <64e369dd574e4d42a56b1689deff9155>:0;
  at ILRepacking.Steps.TypesRepackStep.RepackTypes () [0x00142] in <64e369dd574e4d42a56b1689deff9155>:0;at ILRepacking.Steps.TypesRepackStep.Perform () [0x00000] in <64e369dd574e4d42a56b1689deff9155>:0;
  at ILRepacking.ILRepack.Repack () [0x00305] in <64e369dd574e4d42a56b1689deff9155>:0;at ILRepacking.Application.Main (System.String[] args) [0x0004a] in <64e369dd574e4d42a56b1689deff9155>:0
```

which seems to be a rebuild issue (if I do `msbuild *.sln` twice in xamarin-macios/msbuild, the error occurs the second time). Maybe the ilrepacked assembly is used as input for second build?

**Comment by jstedfast** [comment]
Yea, that's what is happening. How do I fix this? Why is it being "re"built?

**Comment by rolfbjarne** [comment]
It's first built during normal `make`, then the second time to (try to) build the tests.

In any case it doesn't matter why: it should be possible to build the solution multiple times.

I don't know how to fix it, maybe @kzu knows?

**Comment by spouliot** [comment]
ping @kzu / @emaf

**Pull request merged**
