### PR TITLE
[msbuild] Add support for Metal in the simulator. Fixes #7392.

### LINKED ISSUE #7392: Support Metal in Simulator (iOS 13)
### Steps to Reproduce

1. Target iOS 13
2. Add some Metal code with Metal Shader
3. Compile on the Simulator

### Expected Behavior
With iOS 13, Metal is supported in the Simulator, but Xamarin build has not been updated for this.

### Actual Behavior
Compiler says that Metal is not supported in the Simulator.

### Environment
Xamarin.iOS 13.6.0.12
XCode 11.2
macOS 10.15

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes #7392.

### CODE REVIEW

**Comment by dalexsoto** [comment]
+1 to back port this into Xcode 11.4

**Comment by chamons** [comment]
Please backport this to to Xcode 11.4

**Comment by rolfbjarne** [comment]
> Have you checked `simlauncher` if it linked with the framework ?

It works fine, simlauncher actually links with Metal twice...

https://github.com/xamarin/xamarin-macios/blob/2b733ae79c9b405049a2794e08d203fcaf0c7653/tools/mtouch/Makefile#L112
https://github.com/xamarin/xamarin-macios/blob/2b733ae79c9b405049a2794e08d203fcaf0c7653/tools/mtouch/Makefile#L122

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-6
@monojenkins backport d16-5
@monojenkins backport xcode11.4

**Pull request merged**
