### PR TITLE
[apidiff] Update the references (URL) to 16.0 final releases

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by spouliot** [comment]
@chamons not time critical, I built the diff locally for release notes

**Comment by spouliot** [comment]
@monojenkins backport to master

**Comment by spouliot** [comment]
@rolfbjarne that will screw my stats ;-)

**Comment by spouliot** [comment]
test failures are unrelated (network connectivity issue) to the PR

**Comment by chamons** [comment]
@spouliot We have approval to land non-build-impacting changes like this in d16-1 currently.

**Pull request merged**
