### PR TITLE
[WIP][Tests] Reenable dns tests on the watch.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Ran tests locally, worked but might be pure luck. Letting bots work to see the output.

**Comment by dalexsoto** [comment]
#Courage 👍

**Comment by mandel-macaque** [comment]
@spouliot Looks like it was an issue with the simulator on apples side or something of the kind. I though about it when I saw the sim inclusion on the watch, probably, they got something wrong in the betas. If you are ok, we can land this.

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
let's try it a 2nd time before hitting wrench

**Comment by mandel-macaque** [comment]
Thos failures are related to the mac => https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/4965/Test_Report/

We could try another build, to see if the watch is ok. If it is the case, I'm inclined to land this. @rolfbjarne  @spouliot comments?

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
Exact same error in the mac, nothing to do with the watch:
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/4966/Test_Report/

**Pull request merged**
