### PR TITLE
[XHarness] Add missing ignore in Corlib.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Fixes https://github.com/xamarin/maccore/issues/1351

### CODE REVIEW

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by mandel-macaque** [comment]
was aborted due to a timeout in the middle of the tests... is due to the 32 dialog :/

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
I'm closing this PR after landing https://github.com/xamarin/xamarin-macios/pull/5446 since the failing test is in an ignored category.

**Pull request closed without merging**
