### PR TITLE
[msbuild] Don't put gcc/linker flags in the response file, since Mono.Options doesn't support escaping quotes. Fixes vsts#649776. (#4495)

### PR DESCRIPTION
**Pull request by rolfbjarne**
Mono.Options doesn't (yet) support escaped quotes when parsing response files,
which becomes a problem because escaped quotes are necessary when passing
paths with spaces as gcc/linker flags.

So don't write gcc/linker flags in the response file, and instead pass them as
normal command line arguments, and to be on the safe side, do the same thing
for all extra arguments passed to mmp/mtouch.

Also add tests.

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/649776.

### CODE REVIEW

**Comment by spouliot** [comment]
```
20:27:00 + '[' -f ./jenkins/run-tests.sh ']'
20:27:00 + $'./jenkins/run-tests.sh\302\240'
20:27:00 /var/folders/wm/s_3npz453hjccvhy16rcy7zm0000gn/T/jenkins2227026038963084631.sh: line 5: ./jenkins/run-tests.sh : No such file or directory
20:27:00 + EC=1
20:27:00 + df -h
20:27:00 Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
20:27:00 /dev/disk1s1   234Gi  160Gi   71Gi    70% 2569196 9223372036852206611    0%   /
20:27:00 devfs          183Ki  183Ki    0Bi   100%     634                   0  100%   /dev
20:27:00 /dev/disk1s4   234Gi  2.0Gi   71Gi     3%       2 9223372036854775805    0%   /private/var/vm
20:27:00 map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
20:27:00 map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
20:27:00 + touch /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/build-completed.stamp
20:27:00 + exit 1
20:27:00 Build step 'Execute shell' marked build as failure
```

not clear why it failed, does not seems to be disk space related. @rolfbjarne any clue ?

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
@Aguilex merging as discussed / approved

**Pull request merged**
