### PR TITLE
[msbuild] Added support for Siri Intents

### PR DESCRIPTION
**Pull request by jstedfast**
This PR implements the MSBuild portion of the new Siri Intents feature. There are 2 parts:

1. `IntentsDefinitionCompiler` - this maps to Xcode's `intentbuilderc` which (mostly) just copies the `Intents.intentdefinition` file into the app bundle (or, in our case, copies it into an intermediate output directory and adds it to the list of bundle resources with a LogicalName set). The other thing it seems to do is set some default values for some version fields and such. We let `intentbuilderc` do its thing.
2. `IntentsDefinitionCodegen` - this duplicates Xcode's codegen step which generates Objective-C code and compiles them into object files for linking into the main app during the later build phase. For us, we generate C# source files (one per intent, just like Xcode does) and add the C# source files to the `Compile` items list.

This PR supersedes https://github.com/xamarin/xamarin-macios/pull/4775

The only changes between this PR and the previous PR is the code generator now includes logic to generate the "Handling" class which makes use of some new XI APIs introduced in master.

Note: This PR is the same as https://github.com/xamarin/xamarin-macios/pull/4898 so that we can get packages to hand off to QA in order for them to test this feature.

### CODE REVIEW

**Comment by jstedfast** [comment]
build

**Comment by jstedfast** [comment]
build

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4976/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-4976/2//console) 🔥

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/3/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/3//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/daf9e5c7798680a5d5acb23181d7057d43862ddc/3/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-4976/3//console) 🔥
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
@jstedfast there are packages now ([xamarin.ios-12.5.1.62.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/daf9e5c7798680a5d5acb23181d7057d43862ddc/3/package/xamarin.ios-12.5.1.62.pkg))

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4976/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Provisioning' 🔥 : hudson.AbortException: script returned exit code 127

🔥 [Provisioning failed](https://jenkins.internalx.com/job/macios/job/PR-4976/4//console) 🔥

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/5/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/5//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/49fd0a4b0741f87e9e8f931bea9c094f48e333c3/5/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/49fd0a4b0741f87e9e8f931bea9c094f48e333c3/5/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/49fd0a4b0741f87e9e8f931bea9c094f48e333c3/5/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by jstedfast** [comment]
@VincentDondain unit tests added

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/6/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/6//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/721312dab9776066f8679b87125d66b647fd3b9b/6/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/721312dab9776066f8679b87125d66b647fd3b9b/6/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/721312dab9776066f8679b87125d66b647fd3b9b/6/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/7/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/7//console)
✅ Packages: [xamarin.ios-12.7.0.37.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/48cbf5f2b0fafd7f486dcb42a573f0715cdde29c/7/package/xamarin.ios-12.7.0.37.pkg) [xamarin.mac-5.7.0.37.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/48cbf5f2b0fafd7f486dcb42a573f0715cdde29c/7/package/xamarin.mac-5.7.0.37.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/48cbf5f2b0fafd7f486dcb42a573f0715cdde29c/7/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-4976/7//console) 🔥
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4976/8/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/8/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/9/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/9//console)
✅ Packages: [xamarin.ios-12.7.0.80.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/e97a12e84a2469cd15517b4d212d1cd30033dc08/9/package/xamarin.ios-12.7.0.80.pkg) [xamarin.mac-5.7.0.80.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/e97a12e84a2469cd15517b4d212d1cd30033dc08/9/package/xamarin.mac-5.7.0.80.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/e97a12e84a2469cd15517b4d212d1cd30033dc08/9/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/e97a12e84a2469cd15517b4d212d1cd30033dc08/9/jenkins-results/apicomparison/api-diff.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/e97a12e84a2469cd15517b4d212d1cd30033dc08/9/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/10/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/10//console)
✅ Packages: [xamarin.ios-12.15.0.290.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/6736f3ac6e032bd2333ad58977b9e3150244ab41/10/package/xamarin.ios-12.15.0.290.pkg) [xamarin.mac-5.15.0.290.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4976/6736f3ac6e032bd2333ad58977b9e3150244ab41/10/package/xamarin.mac-5.15.0.290.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4976/6736f3ac6e032bd2333ad58977b9e3150244ab41/10/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-4976/10//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at 6736f3ac
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 1.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 2.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 3.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 4.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/BCL tests group 6.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 1-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 2-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 3-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/Mac OS X BCL tests group 4-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/generated/
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-full.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib-mac-modern.csproj
&nbsp;&nbsp;&nbsp;&nbsp;tests/bcl-test/mscorlib.csproj
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4976/11/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/11/display/redirect) (on internal Jenkins) failed in stage(s) 'Signing' 🔥 : hudson.AbortException: script returned exit code 3

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/11//console)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4976/12/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4976/12/display/redirect) (on internal Jenkins) failed in stage(s) 'Signing' 🔥 : hudson.AbortException: script returned exit code 3

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4976/12//console)

**Comment by rolfbjarne** [comment]
A lot of our code has changed, so this PR needs major work to be applicable again, which we don't have on our plan right now.

So I'm closing this, we can always reopen if we decide to spend time on this in the future.

**Pull request closed without merging**
