### PR TITLE
[tests] Add additional test to try to narrow down #xamarin/maccore@2443.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Ref: https://github.com/xamarin/maccore/issues/2443

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* introspection/Mac Catalyst [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2414
* fsharp/Mac [dotnet]/Debug [dotnet]: #12738

**Pull request merged**
