### PR TITLE
Bump to mono:2018-06

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by spouliot** [comment]
PR failed while building mono

```
19:08:41 libtool: install: chmod 644 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/sdks/out/ios-sim64-release/lib/libMonoSupportW.a
19:08:41 libtool: install: ranlib -no_warning_for_no_symbols /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/sdks/out/ios-sim64-release/lib/libMonoSupportW.a
19:08:41 cp ../external/mono/sdks/builds/ios-sim64-release/config.h /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/install/simulator64/include/mono-2.0
19:08:41 cp ../external/mono/sdks/builds/ios-sim64-release/mono/eglib/eglib-config.h /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/builds/install/simulator64/include/mono-2.0
19:08:41 make: *** [all-recurse] Error 1
```

**Comment by spouliot** [comment]
@marek-safar  in addition to @rolfbjarne comments above:

* The xammac failures are logged in https://github.com/xamarin/maccore/issues/868 and only happens in `xam-mac-mini-1`. I pinged RE so its permissions can be verified.

* The AOT failure needs to be fixed before running the tests on device (or everything will fail at build time).

* The System unit tests failure should be fixed once PR 4447 is merged, but I'm not sure the current code is correct (or at least optimal). Is the native library for System.Native also needed for XI (it's for XM only in the PR) ?

**Comment by vargaz** [comment]
Testcase for the 32+llvm failures:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
using System;

public class Tests
{
	static object mutex = new object ();

	internal static void GetRandomBytes ()
	{
		lock (mutex) {
		}
	}

	public static void Main () {
	}
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by vargaz** [comment]
Seems to be a problem with the binary object file writer, running with the assembly writer seems to work. Can somebody try this patch:

diff --git a/tools/mtouch/mtouch.cs b/tools/mtouch/mtouch.cs
index 4d51b646e..9ee066ea7 100644
--- a/tools/mtouch/mtouch.cs
+++ b/tools/mtouch/mtouch.cs
@@ -306,6 +306,8 @@ namespace Xamarin.Bundler
 				return app.LLVMAsmWriter.Value;
 			switch (app.Platform) {
 			case ApplePlatform.iOS:
+				if (app.Is32Build)
+					return true;
 				return false;
 			case ApplePlatform.TVOS:
 			case ApplePlatform.WatchOS:

**Comment by marek-safar** [comment]
@vargaz that change didn't work, make separate issue for this https://github.com/mono/mono/issues/9750

**Comment by rolfbjarne** [comment]
Most of the crashes seems to be this assert:

    link sdk[49592]: error: * Assertion at /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/mono/metadata/object.c:7896, condition `init_message_method != NULL' not met
    link sdk[49592]: critical: Stacktrace:
    link sdk[49592]: critical:   at <unknown> <0xffffffff>
    link sdk[49592]: critical:   at (wrapper managed-to-native) object.__icall_wrapper_mono_delegate_begin_invoke (object,intptr) <0x00012>
    link sdk[49592]: critical:   at (wrapper delegate-begin-invoke) System.Action`1<T_REF>.begin_invoke_IAsyncResult__this___T_AsyncCallback_object (T_REF,System.AsyncCallback,object) [0x0001d] in <643e5a0761d140d1977f1bbd2bd72153>:0
    link sdk[49592]: critical:   at LinkSdk.Aot.AotBugsTest.Bug5354 () [0x00021] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/linker/ios/link sdk/AotBugs.cs:489

**Comment by lewurm** [comment]
@rolfbjarne hopefully fixed by https://github.com/mono/mono/pull/9820

**Comment by lewurm** [comment]
should https://github.com/xamarin/xamarin-macios/pull/4277/commits/4bacab3d5c7fa86a0e6437f64bb9f08ea3d0741b be reverted?

**Comment by vargaz** [comment]
It was already reverted.

**Comment by lewurm** [comment]
@vargaz I don't see the revert on this PR, i.e. this branch: https://github.com/xamarin/xamarin-macios/compare/mono-2018-06

**Comment by vargaz** [comment]
Pushed.

**Comment by spouliot** [comment]
many tests seems to fail with
```
6   com.xamarin.monotouch-test    	0x004effa3 monoeg_assertion_message + 83 (goutput.c:117)
7   com.xamarin.monotouch-test    	0x00418d4b mono_message_init + 219
8   com.xamarin.monotouch-test    	0x004192af mono_method_call_message_new + 143 (object.c:8319)
9   com.xamarin.monotouch-test    	0x00453d50 mono_threadpool_begin_invoke + 144 (threadpool.c:435)
10  com.xamarin.monotouch-test    	0x003d6139 mono_delegate_begin_invoke + 153 (marshal.c:1298)
```
and XI never supported remoting (and related message types). So I guess something changed (re-enabled inside mono makefiles?) in the thread pool code and this gets reached.

@luhenry who's looking into the runtime crashes for the 2018-06 branch ?

**Comment by marek-safar** [comment]
@spouliot Zoltan is looking into them

**Comment by vargaz** [comment]
Isn't this a linker problem ? I.e. some classes got linked out.

**Comment by marek-safar** [comment]
It might be linker related as we are removing more managed code than before.

**Comment by spouliot** [comment]
@vargaz @marek-safar it's linker _related_ but not the cause (nor recent for the linker). The runtime build for XI (back to Novell days) never supported remoting so all the (managed) messaging code is removed (because it's a lot of code and recursively marks even more).

In the existing mono the use of `mono_message_init` is under
```
#ifndef DISABLE_REMOTING
```
(e.g. `marshal.c`) so the types it requires can be safely removed from the applications.

**Comment by vargaz** [comment]
MonoTouch.Tuner/RemoveCode.cs contains:
                                return type.Name != "AsyncResult" && type.Name != "LogicalCallContext"
                                        && type.Name != "MonoMethodMessage";

So the MonoMethodMessage class is supposed to be retained. I looked at a linked mscorlib.dll created
by 11.14.0.4, and the class was retained, along with its InitMessage () method whose absence triggers the assert in mono_message_init ().

**Comment by lewurm** [comment]
this is a recent regression in the linker description, it should be fixed by https://github.com/mono/mono/pull/9820

**Comment by spouliot** [comment]
```
17:53:38 System.IO.IOException: Disk full. Path /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/jenkins-results/tests/MSBuild tests_268/execute-20180801_133514.txt
```
:(

**Comment by marek-safar** [comment]
build

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/18/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/18//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/fc561b247cc0bfef0a365c4d9e27c5db26eed542/18/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/fc561b247cc0bfef0a365c4d9e27c5db26eed542/18/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/fc561b247cc0bfef0a365c4d9e27c5db26eed542/18/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by marek-safar** [comment]
@spouliot are we ready to go?

**Comment by marek-safar** [comment]
build

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/20/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/20//console) 🔥

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/19/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/19//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3eeff7e4baeca412f110eadeac0f84b8eee72c97/19/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3eeff7e4baeca412f110eadeac0f84b8eee72c97/19/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3eeff7e4baeca412f110eadeac0f84b8eee72c97/19/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by vargaz** [comment]
build

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/21/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4277/21//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3901d8e2726bcbd81c18af0a2f3bcb5cd6d787b6/21/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3901d8e2726bcbd81c18af0a2f3bcb5cd6d787b6/21/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/3901d8e2726bcbd81c18af0a2f3bcb5cd6d787b6/21/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by marek-safar** [comment]
@vargaz could you please close the issues resolved by the latest bump

@spouliot could you resume the device testing?

**Comment by spouliot** [comment]
QA just filled
https://github.com/xamarin/xamarin-macios/issues/4617
https://github.com/xamarin/xamarin-macios/issues/4618
for 2018-06 (partial results)

**Comment by GouriKumari** [comment]
Executed XI and XM tests against  Mono version: 5.16.0.108 (7a9c54ebd45)  (2018-08-13 12:19:08 -04:00), XI version: 11.15.0.48 (PR-4277: 3901d8e2) 
and XM version: 4.7.0.48 (3901d8e2)  (2018-08-08 06:27:48 -04:00).

 XI Results:
- Bugs: https://github.com/xamarin/xamarin-macios/issues/4618, https://github.com/xamarin/xamarin-macios/issues/4617. 
- XI Submission tests failed: QA Apple ID got locked, until it is fixed tests will fail
- XI unit tests: Tests failed to launch on a few devices due to an environment issue (iPhone7 and iPadAir)
- Sample building and BCL tests on device are queued

 XM  Results:
- XM tests did not show any new failures, All failures are known and is already filed.

 VSFMac Integration tests:
- There are a few template failures which I am confirming with Manish to see that they are not new.

[Tests Run ](https://devdiv.visualstudio.com/DevDiv/_release?releaseId=141903&forceOpenOldView=true&_a=release-contribution-tab-ms.vss-test-web.test-result-in-release-management)

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/22/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/22//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/b3245a6930b7a6f4eaccdee01f9dbba520a0d205/22/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/b3245a6930b7a6f4eaccdee01f9dbba520a0d205/22/jenkins-results/apicomparison/index.html) (please review changes)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/b3245a6930b7a6f4eaccdee01f9dbba520a0d205/22/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/23/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/23//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/c844903be5ae3c30551f46de1760ac2fe0075551/23/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-4277/23//console) 🔥
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by marek-safar** [comment]
@spouliot @rolfbjarne would you like to rerun the tests?

I don't think we can merge it before XA is done but maybe you could make dev15.9 branch PR meantime

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/24/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/24//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/dc0ccb33fd46f139f43071e6b15488cc566e74cc/24/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/dc0ccb33fd46f139f43071e6b15488cc566e74cc/24/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/dc0ccb33fd46f139f43071e6b15488cc566e74cc/24/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/25/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/25//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/d491fd46b6495ad4089570b3afecf3b018adbf30/25/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/d491fd46b6495ad4089570b3afecf3b018adbf30/25/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/d491fd46b6495ad4089570b3afecf3b018adbf30/25/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
@marek-safar this also looks like a new failure:

    [FAIL] FileTest.LastWriteTimeSubMsCopy : Iteration #0 failed, untouched: 11:19:59:3535130 copy_touched: 11:19:59:0000000 

I'll take care of the MTouch test failure, and the rest are known issues.

**Comment by lewurm** [comment]
@rolfbjarne `FileTest.LastWriteTimeSubMsCopy` seems to fail on iOS 32bit simulator. do you know if it fails on iOS 32bit device as well?

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/26/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/26//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/f69a8fc169fe3661d9110c6b2374acb06852e0c7/26/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/f69a8fc169fe3661d9110c6b2374acb06852e0c7/26/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/f69a8fc169fe3661d9110c6b2374acb06852e0c7/26/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
@lewurm `FileTest.LastWriteTimeSubMsCopy` fails in both 32-bit and 64-bit mode on an iOS 10.3.3 device. It does not fail in either 32-bit nor 64-bit mode on an iOS 8.2 device.

It seems to be an issue when the filesystem is APFS, since APFS was introduced in iOS 10.2.

**Comment by rolfbjarne** [comment]
@spouliot the device tests look good, no new failures.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/27/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/27//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ce5331f2c9656b0e4b51947c4e534ac6659282a3/27/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ce5331f2c9656b0e4b51947c4e534ac6659282a3/27/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ce5331f2c9656b0e4b51947c4e534ac6659282a3/27/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/28/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-4277/28//console) 🔥

**Comment by rolfbjarne** [comment]
@luhenry there seems to be some llvm-related build problem (from here: https://jenkins.internalx.com/blue/rest/organizations/jenkins/pipelines/macios/branches/PR-4277/runs/28/nodes/45/steps/49/log/?start=0):

```
CMake Error: Generator: execution of make failed. Make command was: "/usr/local/bin/gmake" "cmTC_9fd47/fast"
-- Check for working C compiler: /Applications/Xcode94.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler
  "/Applications/Xcode94.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/sdks/builds/llvm-llvm64/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/local/bin/gmake" "cmTC_9fd47/fast"

  

  Generator: execution of make failed.  Make command was:
  "/usr/local/bin/gmake" "cmTC_9fd47/fast"

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:47 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/sdks/builds/llvm-llvm64/CMakeFiles/CMakeOutput.log".
See also "/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/sdks/builds/llvm-llvm64/CMakeFiles/CMakeError.log".
make[3]: *** [.stamp-llvm-llvm64-configure] Error 1
```

**Comment by GouriKumari** [comment]
QA  tests executed against Mono version: MonoFramework-MDK-5.16.0.132.macos10.xamarin.universal.pkg, XI: xamarin.ios-11.17.0.60.pkg and  XM: xamarin.mac-4.9.0.60.pkg

Test Results:  83.75 % pass
https://devdiv.visualstudio.com/DevDiv/_release?releaseId=150395&forceOpenOldView=true&_a=release-summary

1. XI unified tests: Bugs: #4618, #4617 reported in the previous QA test run passed. There are two failures in this test run which seems to be random network issue. 
2. BCL tests: all unit tests passed
3. tvOS: all unittests passed
3. XM tests: No new failures. All failures are already reported.
4. VSFMac: There are test failures which I will confirm with IDE team.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/29/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/29//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/a285ec72bce1fe52fc84a9738c47b6fee9373ce9/29/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/a285ec72bce1fe52fc84a9738c47b6fee9373ce9/29/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/a285ec72bce1fe52fc84a9738c47b6fee9373ce9/29/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/30/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/30//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/c7654a0457a56827452bcddad9821c655d05922f/30/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/c7654a0457a56827452bcddad9821c655d05922f/30/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/c7654a0457a56827452bcddad9821c655d05922f/30/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/31/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/31//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/28347f91677b859e270e43f61f997bd2d9359531/31/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/28347f91677b859e270e43f61f997bd2d9359531/31/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/28347f91677b859e270e43f61f997bd2d9359531/31/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/32/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/32//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/cdbf1227d2f41a3fb7ded30edb99fdeca03ef4f8/32/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/cdbf1227d2f41a3fb7ded30edb99fdeca03ef4f8/32/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/cdbf1227d2f41a3fb7ded30edb99fdeca03ef4f8/32/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/33/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/33//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ac8fd9e60aba0fae174eb7175a54d42a3c6b61f1/33/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ac8fd9e60aba0fae174eb7175a54d42a3c6b61f1/33/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/ac8fd9e60aba0fae174eb7175a54d42a3c6b61f1/33/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by marek-safar** [comment]
@spouliot could we get this in now when you have separate 15.9 branch to unblock us on PRs which depend on this one?

**Comment by spouliot** [comment]
@marek-safar yeah, I don't like long-running PR either. However that would break _master must be releasable_ and _SDK must ship identical mono_. Also we are close to branch for the next milestone and I'd rather not run into the same 15.9 situation again.

How close are we wrt XA and 2018-06 ?

**Comment by marek-safar** [comment]
Unfortunately, I don't know how long before the code is in XA, we have only about 13 tests failures (not serious) but I have no idea when @jonpryor is going to merge it.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-4277/36/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4277/36/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.11'' 🔥 : hudson.AbortException: Xamarin.Mac tests on macOS 10.11 failed (xammac_tests)

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-4277/36//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4277/f77c43483ae4c0156e619d2a7187523dd2515f02/36/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-4277/36//console) 🔥
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.
🔥 [Xamarin.Mac tests on macOS 10.11 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-4277/36/display/redirect) 🔥

**Comment by chamons** [comment]
I have not, but it completely looks like a "random failure". Filed as https://github.com/xamarin/maccore/issues/1084

The last test listed is a CloudKit test, so I could see some async \ network causing wonky test behavior.

**Comment by taikodragon** [comment]
When might we see this in VS / VS4M?

**Comment by chamons** [comment]
@taikodragon Since this has _just_ landed in master, it wouldn't be until the 16.x timeframe.

You can read about the VS release schedule [here](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-release-rhythm), and there are no announced dates currently, but thinking on the order of months would be reasonable.

**Pull request merged**
