### PR TITLE
[d16-4] Bump mono 2019-08@52810372

### PR DESCRIPTION
**Pull request by VincentDondain**
New commits in mono/mono:

* mono/mono@528103728fc [2019-08] Update NETStandard2.1 APIs (#17123)

Diff: https://github.com/mono/mono/compare/d8441deead62b3af591c6daefb5013b09ef1ab8b..528103728fc2aedb7b6062e11255d39a0ed3f31c

### CODE REVIEW

**Comment by VincentDondain** [comment]
We need to wait for Xamarin.Android to have a similar PR before merging this.

**Comment by dalexsoto** [comment]
build

**Comment by VincentDondain** [comment]
Nope we need other changes in the PR let me close and do a simple backport

**Comment by VincentDondain** [comment]
This is the right PR: https://github.com/xamarin/xamarin-macios/pull/7150

**Pull request closed without merging**
