### PR TITLE
[mtouch] Add support for stripping bitcode from frameworks when not needed. Fixes #55256.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This dramatically decreases the size of watchOS apps built for debug when
using frameworks, because it ends up removing all the bitcode from
Mono.framework.

https://bugzilla.xamarin.com/show_bug.cgi?id=55256

### CODE REVIEW

**Comment by spouliot** [comment]
Not urgent but can you add some numbers (e.g. size and how faster it deploys) in the wiki release notes (15.3) ? thanks :D

**Comment by rolfbjarne** [comment]
I'm not sure it's worth it, because no watchOS apps have ever used frameworks before (only with code sharing and with intents extensions, which is new), so there's nothing to compare with.

**Comment by spouliot** [comment]
@rolfbjarne does not the current debug builds _suffers_ from the extra bitcode ? which, being large, affect deploy time ?

**Comment by rolfbjarne** [comment]
Test failures are all because our certificate for wrench.internalx.com expired (which is known and being fixed).

**Comment by rolfbjarne** [comment]
@spouliot the extra bitcode is only there when we link (and bundle) a shared library/framework that mtouch _didn't_ build (for example Mono.framework). This scenario never occurred for watchOS until we added support for intents extensions.

OTOH I guess it might be worth putting in the 15.3 release notes if we don't backport this PR to 15.2.

**Pull request merged**
