### PR TITLE
[CI] Remove beta3 from bots.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Removing Xcode's causes a problem if they're the selected system Xcode:

```
xcrun: error: active developer path ("/Applications/Xcode_13.0.0-beta3.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
```

Ref: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5035261&view=results

**Review by spouliot — COMMENTED** [review]
preview.7 still needs beta3 until a backport is made

**Review by stephen-hawley — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@spouliot  AFAIK we are ok to merge this now.

**Review by spouliot — APPROVED** [review]

**Pull request merged**
