### PR TITLE
[nnyeah] Fix method hashing of generic matching non-generic due to Cecil limitation.

### PR DESCRIPTION
**Pull request by chamons**
- This gets iOS integration tests passing

From what I can tell we are failing due to:

    public static new PHLivePhotoViewAppearance GetAppearance (UITraitCollection traits) {
    public static new PHLivePhotoViewAppearance GetAppearance<T> (UITraitCollection traits) where T: PHLivePhotoView {

having the same hash, as the generic constraints are not printed.

To solve this we take on a small (250ish) dependency on code from MonoMod.Common (MIT licensed). They have code which creates stable hash keys that include generic information.

### CODE REVIEW

**Comment by chamons** [comment]
Not 100% sold on this fix, but wanted to run it by everyone.

**Review by rolfbjarne — COMMENTED** [review]
Seems like it would be better to take the generic arguments into account rather than just randomly choosing the first method we see?

**Comment by mandel-macaque** [comment]
@rolfbjarne that is my concern too, I believe that using FullName is the right way rather than ToString () (I need to test my theory).

**Comment by chamons** [comment]
Yeah, that fix occurred to me last night after getting off work. I"ll give it a shot.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
This is not the correct path. The issue we have is as follows, lets use https://docs.microsoft.com/en-us/dotnet/api/uikit.uiview.getappearance?view=xamarin-ios-sdk-12 as an example method.

We have the two following  method overloads:

* [GetAppearance(UITraitCollection)](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiview.getappearance?view=xamarin-ios-sdk-12#uikit-uiview-getappearance(uikit-uitraitcollection))
* [GetAppearance< T >(UITraitCollection)](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiview.getappearance?view=xamarin-ios-sdk-12#uikit-uiview-getappearance-1(uikit-uitraitcollection))

In this case, Mono.Cecil will return the following ToString/Fullname for **both**:
```
PhotosUI.PHLivePhotoView/PHLivePhotoViewAppearance PhotosUI.PHLivePhotoView::GetAppearance(UIKit.UITraitCollection
```
That means we will have issues when using the FullName and the ToString as a valid unique key for the dictionary.  The issue is that we need to be able to get the constrains for the transformation.

We CANNOT do the following:
```csharp
if (meme is GenericInstanceMethod) 
```
This is because we are talking about ta MethodDefinition and not a MethodReference (the inheritance is diff).
We also CANNOT do:
```csharp
if (member.IsGenericInstance)
```
The issue is that it will be false for the <T> version of the method (I did not expect that). We need to fins a proper way to construct the signature, this change only ignores methods and hides the underlying issue.

Adding some extra info, the member does have the generic parameters.

**Comment by tj-devel709** [comment]
Oops, didn't read all the comments until after I reviewed the code!

**Comment by dalexsoto** [comment]
> We should add a reference to [MonoMod.Common](https://github.com/MonoMod/MonoMod.Common/tree/093ef864257b2eb332ef727e389c2679d98c594e) and change the usage of `MethodReference.ToString` to the extension method `GetID` which takes generics into account.

I am not sure we want to take the whole thing as a dependency, probably we can use what we need of course with the correct attribution.

**Comment by chamons** [comment]
@stephen-hawley @dalexsoto @mandel-macaque - I've taken a subset of MonoMod.Common as a one-file dependency. I believe I've done attribution correctly.

**Comment by chamons** [comment]
I also did not change the copied code to match our coding conventions or nullability (for now). I want to get tests online before doing too much monkeying.

**Review by mandel-macaque — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Pull request merged**
