### PR TITLE
[iTunesLibrary] Adopt XAMCORE_4_0 changes in .NET.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by tj-devel709** [comment]
Whoops, double approved!

**Comment by tj-devel709** [comment]
Although it does appear that the whole file has whitespace changes, not sure if that is what was intended.

**Review by chamons — APPROVED** [review]

**Comment by chamons** [comment]
@tj-devel709  - That file was checked in with CRLF unlike the rest of our source code:

```
donblas@Masterwork xamarin-macios % dos2unix -ic src/appkit.cs
donblas@Masterwork xamarin-macios % dos2unix -ic src/ituneslibrary.cs 
donblas@Masterwork xamarin-macios % dos2unix -ic src/iTunesLibrary/ITCompat.cs
src/iTunesLibrary/ITCompat.cs
```

You can see this in VSCode in the bottom right:

image

For more [info](https://en.wikipedia.org/wiki/Newline).

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@tj-devel709  @chamons it was done by an external contributor (now employee by the way) before we got the .editorconfig in This could have been avoided with a git hook.

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2443).

**Pull request merged**
