### PR TITLE
[mono] Bump mono to latest HEAD of 2019-08

### PR DESCRIPTION
**Pull request by dalexsoto**
This brings parity with d16-4 [android bump](https://github.com/xamarin/xamarin-android/pull/4037) plus the xcode11.3 binaries.

diff: https://github.com/mono/mono/compare/3e882ed1a2013f756bdbe104c23e8ff54d5fa49c...688c64e98a719ac774ae40d3705542646b27e719

* [MacSDK] Bump xamarin-gtk-theme.py to latest revision from private mono/mono@296a9af
* [merp] Remove extraneous waitpid invocation (#17762) mono/mono@a77128c
* Bump msbuild to track mono-2019-08 (#17854) mono/mono@14aac0c
* [2019-08] bump msbuild+roslyn to track mono-2019-08 (#17954)   mono/mono@0c92502
* [2019-08] [runtime] Treat calling a non-virtual method through… (#17961) mono/mono@c4a1b40
* [arm] if mtriple is provided, do not set -march mono/mono@56325f4
* [interp] track valuetype stack for CEE_RET too (#17998) mono/mono@bef1e63
* [2019-08] Enable GSS on android (#18116) mono/mono@da5b1c6
* [debugger] skip suspend for unattached threads (#18138)  mono/mono@e3084ec
* Merge remote-tracking branch 'upstream/2019-08' into 2019-08-xcode11.3  mono/mono@03f982f
* [sdks] Use Xcode 11.3 stable version for iOS/Mac SDKs mono/mono@688c64e

### CODE REVIEW

**Comment by dalexsoto** [comment]
build

**Comment by chamons** [comment]
`[2019-08] bump msbuild+roslyn to track mono-2019-08 (#17954) mono/mono@0c92502` scares me but manager :+1: as meta-QB approves.

**Comment by mandel-macaque** [comment]
FYI I'm investigating the tests issues.

**Comment by spouliot** [comment]
Device tests in `xcode11.3` are broken (no mono binaries for the current hash) until we use something more recent
https://github.com/xamarin/xamarin-macios/commit/aaafa2df6f6449caf0672b20e289cd1d809a9da7

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
build

**Pull request closed without merging**
