### PR TITLE
[tools] Revert workaround for dotnet/runtime#45535.

### PR DESCRIPTION
**Pull request by rolfbjarne**
The dotnet/runtime issue in question has been fixed.

Ref: https://github.com/dotnet/runtime/issues/45535
Ref: https://github.com/xamarin/xamarin-macios/pull/10182/commits/39948aa2c90e1d0edc9f21dc3528878740b4385e

### CODE REVIEW

**Comment by rolfbjarne** [comment]
CC @filipnavara

**Comment by filipnavara** [comment]
LGTM. The workaround for `System.Security.Cryptography.Native.Apple` can be removed too. The last one for `System.Native` maybe too (depends on the exact bump of runtime package; it is fixed upstream).

**Comment by rolfbjarne** [comment]
@filipnavara looks like it's not fully fixed in dotnet/runtime:

```
Undefined symbols for architecture x86_64:
  "_NetSecurityNative_AcceptSecContext", referenced from:
     -u command line option
  "_NetSecurityNative_AcquireAcceptorCred", referenced from:
     -u command line option
  "_NetSecurityNative_DeleteSecContext", referenced from:
     -u command line option
  "_NetSecurityNative_DisplayMajorStatus", referenced from:
     -u command line option
  "_NetSecurityNative_DisplayMinorStatus", referenced from:
     -u command line option
  "_NetSecurityNative_ImportPrincipalName", referenced from:
     -u command line option
  "_NetSecurityNative_ImportUserName", referenced from:
     -u command line option
  "_NetSecurityNative_InitSecContext", referenced from:
     -u command line option
  "_NetSecurityNative_InitSecContextEx", referenced from:
     -u command line option
  "_NetSecurityNative_InitiateCredSpNego", referenced from:
     -u command line option
  "_NetSecurityNative_InitiateCredWithPassword", referenced from:
     -u command line option
  "_NetSecurityNative_IsNtlmInstalled", referenced from:
     -u command line option
  "_NetSecurityNative_ReleaseCred", referenced from:
     -u command line option
  "_NetSecurityNative_ReleaseGssBuffer", referenced from:
     -u command line option
  "_NetSecurityNative_ReleaseName", referenced from:
     -u command line option
  "_NetSecurityNative_Unwrap", referenced from:
     -u command line option
  "_NetSecurityNative_Wrap", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by filipnavara** [comment]
That's really weird. I will need to verify that the consumed assets are the correct ones. The blocking P6/P7 bumps are not making that easy.

**Comment by rolfbjarne** [comment]
@filipnavara here are build logs if that helps:

[build-tvOS-20210624_055706.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6709593/build-tvOS-20210624_055706.binlog.zip)

[build-tvOS-20210624_055706.txt.zip](https://github.com/xamarin/xamarin-macios/files/6709613/build-tvOS-20210624_055706.txt.zip)

**Comment by filipnavara** [comment]
It is still broken for System.Net.Http and System.Net.Mail on the dotnet/runtime side. The same fix that was applied here:
https://github.com/dotnet/runtime/blob/abccfadbf570033efee8ac9a6992f6f7ee51f474/src/libraries/System.Net.Security/src/System.Net.Security.csproj#L281-L289 (https://github.com/dotnet/runtime/pull/51861)
needs to be applied on two more places:
https://github.com/dotnet/runtime/blob/abccfadbf570033efee8ac9a6992f6f7ee51f474/src/libraries/System.Net.Http/src/System.Net.Http.csproj#L321-L326
https://github.com/dotnet/runtime/blob/abccfadbf570033efee8ac9a6992f6f7ee51f474/src/libraries/System.Net.Mail/src/System.Net.Mail.csproj#L154-L159

System.Net.Security does appear to be fixed though.

cc @MaximLipnin

**Review by mandel-macaque — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@filipnavara / @MaximLipnin: as of `6.0.0-rc.1.21369.14` there are still problems in System.Net.Mail.dll:

    System.Net.Mail.dll
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_ReleaseGssBuffer
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_DisplayMinorStatus
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_DisplayMajorStatus
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_ImportUserName
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_ImportPrincipalName
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_ReleaseName
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_AcquireAcceptorCred
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_InitiateCredSpNego
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_InitiateCredWithPassword
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_ReleaseCred
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_InitSecContext
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_InitSecContextEx
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_AcceptSecContext
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_DeleteSecContext
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_Wrap
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_Unwrap
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_IsNtlmInstalled
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native
        Library: libSystem.Net.Security.Native.dylib Function: NetSecurityNative_EnsureGssInitialized
            ❌ Library libSystem.Net.Security.Native.dylib does not exist in ./microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-rc.1.21369.14/runtimes/tvossimulator-x64/native

is this known?

**Comment by filipnavara** [comment]
> is this known?

Not to me. The PR in dotnet/runtime was supposed to fix this. I'll check what is going on and how System.Net.Mail.dll is packed in the runtime packs.

(Side-note: I'm going to be out of civilisation for the next couple of days so if someone gets to it earlier than Monday then feel free to attack it.)

**Comment by filipnavara** [comment]
Apparently these files:
https://github.com/dotnet/runtime/blob/f5ed68b1832a0fca2c0db3e0a10b7268b709ee9f/src/libraries/System.Net.Mail/src/System.Net.Mail.csproj#L140-L145
are still in incorrectly included in tvOS builds.

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2443).

**Pull request merged**
