### PR TITLE
Fix binding project LinkWithAttributes generation to prevent rebuilds

### PR DESCRIPTION
**Pull request by chamons**
- https://bugzilla.xamarin.com/show_bug.cgi?id=45762

### CODE REVIEW

**Comment by chamons** [comment]
Similar in spirit to https://github.com/xamarin/xamarin-macios/pull/1014 but should fix both XI and XM since logic is shared in this case.

**Comment by chamons** [comment]
@spouliot Also proposed for C9.
@jstedfast Please review

**Comment by chamons** [comment]
This patch assumes PR 1014 lands first, It might not build w\o the other test changes (I just cherry picked for review).

**Comment by jstedfast** [comment]
looks good

**Pull request merged**
