### PR TITLE
[mtouch tests] Add Xamarin.Analysis.Tasks.dll as a valid assembly to have in the Classic BCL directory.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
