### PR TITLE
[objcruntime] Inline the use of the `Class.LookupFullName` method

### PR DESCRIPTION
**Pull request by spouliot**
inside it's _only_ caller and remove the API.

Remove old test that was already not useful (since the method could not
be removed anyway for quite a while).

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
failed, but i is unrelated AFAIK

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2494).

**Pull request merged**
