### PR TITLE
[linker] Update linker to recognize debug async notification methods. Fixes #55037

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by marek-safar** [comment]
@spouliot can you fast-track this as it needs to go to 15.2 too (Fixes #55037)

**Comment by spouliot** [comment]
@marek-safar got a link to a bug report ? test case ? QA will want this to verify before back porting

**Comment by marek-safar** [comment]
@spouliot bug number is in description comment

**Comment by marek-safar** [comment]
@spouliot can you cherry-pick it or do I need to PR to 15.2 branch ?

**Comment by rolfbjarne** [comment]
@marek-safar please create a PR for 15.2.

**Pull request merged**
