### PR TITLE
[DittoTask] If Source is a folder, add all its content as ITaskItem

### PR DESCRIPTION
**Pull request by SotoiGhost**
Possible fix for https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1492635

If the `ITaskItem` input property of the task is a folder path, the `TaskRunner` doesn't know how to copy the folder content to Mac. Let's use the `GetAdditionalItemsToBeCopied` method to tell the `TaskRunner` to copy all the folder content to Mac.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
I tried something very similar locally yesterday!

https://github.com/rolfbjarne/xamarin-macios/commit/1dd16a4733314c37c6ecd3546871a44074aeb364

it didn't fix the problem though, but this did: https://github.com/xamarin/xamarin-macios/pull/14376

**Comment by dalexsoto** [comment]
Let's go with @rolfbjarne's solution first and see if this does the trick we can always revisit if more tweaking is needed.

**Comment by emaf** [comment]
@dalexsoto @rolfbjarne I think this is correct, because the TaskRunner does not support copying directories. 

I'm guessing this and https://github.com/xamarin/xamarin-macios/pull/14376 are happening under different circumstances. I think in the problem Rolf fixed the files exist because they were copied by a previous task, but in the one Israel is fixing the files should be copy by Ditto to the Mac, and it won't happen because the DSYM is a folder.

Looking into the output of the task, it reports: There's no available inputs to copy to the Mac.

We probably need both fixes?

**Review by emaf — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
@rolfbjarne / @chamons / @mandel-macaque what do you think?

**Review by rolfbjarne — APPROVED** [review]

**Comment by dalexsoto** [comment]
Test failures are unrelated, This went ok https://github.com/xamarin/xamarin-macios/pull/14392 same code

**Pull request merged**
