### PR TITLE
[bump][maccore] Fix mlaunch watchos timeout issue

### PR DESCRIPTION
**Pull request by wachaudh**
Fixes the mlaunch watchos simulator timeout issue which caused Alex to revert mlaunch localization changes.

Diff: https://github.com/xamarin/maccore/compare/ad1696d6f33badd34f930e4ce1be9185b5a36dd7..e03f16b862686e378318ef362d447365878b750e

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This needs to be pushed to origin as well to run tests on internal jenkins.

**Comment by wachaudh** [comment]
Unrelated test failure

- https://github.com/xamarin/maccore/issues/2199

**Comment by mandel-macaque** [comment]
build

**Comment by wachaudh** [comment]
build

**Comment by wachaudh** [comment]
build

**Comment by mandel-macaque** [comment]
mmptest are unrelated @wachaudh  looks good but we should wait to get all the internal test results.

**Comment by rolfbjarne** [comment]
This PR is outdated, we've bumped maccore in other PRs.

**Pull request closed without merging**
