### PR TITLE
Fix bug 58243

### PR DESCRIPTION
**Pull request by jgold6**
NSApplicationLaunchUserNotificationKey is missing

### CODE REVIEW

**Comment by timrisi** [comment]
It looks like we have an existing (non-ideal) binding for this selector in appkit.cs:

```
[Category, BaseType (typeof (NSApplication))]
	partial interface NSRemoteNotifications_NSApplication {

		[MountainLion, Field ("NSApplicationLaunchUserNotificationKey", "AppKit")]
		NSString NSApplicationLaunchUserNotificationKey { get; }
	}
```

To use this one, you have to do NSRemoteNotifications_NSApplication. NSApplicationLaunchUserNotificationKey, the new binding is clearly a better option.  Do we want to ```#if !XAMCORE_4_0``` the old one?

**Comment by rolfbjarne** [comment]
whitelist

**Comment by chamons** [comment]
Wow, that binding is out in the middle of nowhere: "NSRemoteNotifications_NSApplication. NSApplicationLaunchUserNotificationKey"

@timrisi I agree. Since it's just a notification, we can expose it in two places I believe.

@jgold6 Can you add:

```
#if !XAMCORE_4_0
#endif
```

around it, to remove it from future bindings when we break API compatibility.

**Comment by jgold6** [comment]
Closing this PR as I made a mistake and did not create a new branch for my commits, making it hard to modify this PR to add the request #if statement.

**Pull request closed without merging**
