### PR TITLE
[msbuild] Even iOS Simulator builds now require signing certificates

### PR DESCRIPTION
**Pull request by jstedfast**
Now that dylibs and frameworks are required to be signed in order to
run on the Simulator, we cannot allow the DetectSigningIdentity task
to return success if it didn't find a codesign key.

"Fixes" https://bugzilla.xamarin.com/show_bug.cgi?id=44033

### CODE REVIEW

**Comment by jstedfast** [comment]
Just a note, but we'll probably want this to land in a C8 Service Release (not sure it's important enough for C8 proper).

**Comment by spouliot** [comment]
LGTM @VincentDondain please double-check

**Comment by VincentDondain** [comment]
LGTM too 👍

**Comment by olegtyshcneko** [comment]
wtf? are you kidding? Why should I have cert to test on simulator?

**Comment by jstedfast** [comment]
@olegtyshcneko As I mentioned in the original comment for this PR, starting with Xcode 8.0, the iOS Simulator now requires that all *.dylibs and *.frameworks be codesigned.

That said, however, we discovered that we could work around the need for an actual certificate after we merged this fix. You can see that PR in issue #833.

**Pull request merged**
