### PR TITLE
[d15-9] Bump Xamarin.MacDev to get fix for #5277.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Commit list for xamarin/Xamarin.MacDev:

* xamarin/Xamarin.MacDev@ba1629e Keys in property list dictionaries aren't necessarily unique. Fixes xamarin-macios#5277. (#39) (#40)
* xamarin/Xamarin.MacDev@21b7270 Cache EntitlementExtensions.AllKeys
* xamarin/Xamarin.MacDev@44b2fee Added new Xcode10 Watch Complication values (#34)
* xamarin/Xamarin.MacDev@e9e1bb1 Merge pull request #36 from xamarin/vsts-702327-d15-9
* xamarin/Xamarin.MacDev@e348034 VSTS 702327: Launch image sizes for iPhone XS Max and iPhone XR (#35)
* xamarin/Xamarin.MacDev@61e811c Use Version.TryParse
* xamarin/Xamarin.MacDev@62cdeac Added API to get the recommended Xcode version value
* xamarin/Xamarin.MacDev@3adc4a9 Merge pull request #33 from xamarin/vsts-692176-release-7.7
* xamarin/Xamarin.MacDev@25883d4 VSTS-692176: Add missing AutoFill Credential Provider entitlement

Diff: https://github.com/xamarin/Xamarin.MacDev/compare/39ea45bad4eb85358467b9f316fa6b30aa223e9c...ba1629eef4c8f73880a7c77e99e35d14e907a03e

Fixes https://github.com/xamarin/xamarin-macios/issues/5277.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
PR #5286 is identical, except that it bumps to a custom branch in Xamarin.MacDev that contains only this fix.

**Comment by spouliot** [comment]
This one is more risky, we should use #5286 and close this one

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-5285/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-5285/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥 : hudson.AbortException: script returned exit code 1

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-5285/1//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-5285/a73117793e0087d912a6495067ab9f2e6e5700e0/1/jenkins-results/api-diff/index.html)
🔥 [Failed to compare API and create generator diff](https://jenkins.internalx.com/job/macios/job/PR-5285/1//console) 🔥
✅ [Test run succeeded](http://xamarin-storage/jenkins/xamarin-macios/PR-5285/a73117793e0087d912a6495067ab9f2e6e5700e0/1/jenkins-results/tests/index.html)

**Comment by rolfbjarne** [comment]
Closing in favor of #5286.

**Pull request closed without merging**
