### PR TITLE
[msbuild] Don't override the OnDemandResourcesUrl if previously set

### PR DESCRIPTION
**Pull request by jstedfast**
This change allows users to specify a custom URL for hosting their
OnDemand Resources.

### CODE REVIEW

**Comment by jstedfast** [comment]
build

**Comment by jstedfast** [comment]
I don't actually understand what failed in this build

**Comment by rolfbjarne** [comment]
The failure is unrelated (bug #[54995](https://bugzilla.xamarin.com/show_bug.cgi?id=54995)).

**Comment by jstedfast** [comment]
ping @kzu

**Comment by spouliot** [comment]
@jstedfast you already have @emaf approval (for XVS), so you can fix the conflict and merge. Thanks!

**Pull request merged**
