### PR TITLE
Use the SDK UseMonoRuntime property instead of _XamarinRuntime in MSBuild

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by filipnavara** [comment]
Uh, my bad for the failed tests. I likely forgot to save something in the VS Code. I'll fix it as soon as I returned to the computer.

**Review by spouliot — APPROVED** [review]
@rolfbjarne was that (to be) connected with `XamarinRuntime` in `tools/dotnet-linker/LinkerConfiguration.cs` ?

**Comment by rolfbjarne** [comment]
> @rolfbjarne was that (to be) connected with `XamarinRuntime` in `tools/dotnet-linker/LinkerConfiguration.cs` ?

This should make sure that logic continues to work: https://github.com/xamarin/xamarin-macios/pull/11255/files#diff-2e24f1b6f44df7580244d00f106fa1a9e2257536fbca9d7bbdc74571549324a9R238-R239

Although changing LinkerConfiguration to take the `UseMonoRuntime` value would also work (the XamarinRuntime enum can stay as-is though, just choose one value or the other depending on the `UseMonoRuntime` value).

**Comment by rolfbjarne** [comment]
The .NET tests fail to build with:

> error MT2301: The linker step 'Setup' failed during processing: Invalid XamarinRuntime 'Mono' in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/tmp-test-dir/dont link22/obj/iPhoneSimulator/Debug/net6.0-ios/iossimulator-x64/custom-linker-options.txt 

this was for "don't link / iOS Unified 64-bits - simulator / Debug [dotnet]"

**Comment by filipnavara** [comment]
Thanks. I managed to make two cut & paste errors on the same line :D

**Pull request merged**
