### PR TITLE
[Harness] Completely remove the BCL prefix from the test importer.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Remove the last BCLPrefix and move the InfoPlistGenerator to the managed
namespace since it is part of the managed template.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
As with the others, draft until parent branches land.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8224/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8224/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8224/1//console)
✅ Packages: 
* [xamarin.ios-13.19.0.382.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/package/xamarin.ios-13.19.0.382.pkg)
* [xamarin.mac-6.19.0.382.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/package/xamarin.mac-6.19.0.382.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/761b81287e02c6ca20a063714cb29d2f23f9ae65/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 180 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8224/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8224/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8224/2//console)
✅ Packages: 
* [xamarin.ios-13.19.0.391.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/package/xamarin.ios-13.19.0.391.pkg)
* [xamarin.mac-6.19.0.391.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/package/xamarin.mac-6.19.0.391.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/3d018408004a4d0e21cfca2bc76f353cf74ed758/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>6 tests failed, 179 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8224/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8224/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8224/3//console)
✅ Packages: 
* [xamarin.ios-13.19.0.401.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/package/xamarin.ios-13.19.0.401.pkg)
* [xamarin.mac-6.19.0.401.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/package/xamarin.mac-6.19.0.401.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/jenkins-results/apicomparison/api-diff.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 183 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8224/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8224/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8224/4//console)
✅ Packages: 
* [xamarin.ios-13.19.0.401.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/package/xamarin.ios-13.19.0.401.pkg)
* [xamarin.mac-6.19.0.401.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/package/xamarin.mac-6.19.0.401.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/jenkins-results/apicomparison/api-diff.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/741d182eb17f9e94f885ef958d36a4a3a4c87a92/4/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 183 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8224/5/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8224/5/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8224/5//console)
✅ Packages: 
* [xamarin.ios-13.19.0.414.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/package/xamarin.ios-13.19.0.414.pkg)
* [xamarin.mac-6.19.0.414.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/package/xamarin.mac-6.19.0.414.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/jenkins-results/apicomparison/api-diff.html) (no change)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/jenkins-results/generator-diff/index.html) (please review changes)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8224/232f945ab27efa8c807c534d82ac30049b09b801/5/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary># Test run in progress: Built: 144, Running: 1, Succeeded: 39, Failed: 1, Ignored: 1078</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
</details>

**Pull request merged**
