### PR TITLE
[runtime/tools] Implement finding native support libraries when linking statically. Fixes #10950, #11145 and #12100.

### LINKED ISSUE #10950: dllmap for native libraries shipped with .NET
Now that we've added support for `PINVOKE_OVERRIDE` (#10504), we have to look into this to see if something needs to be done:

https://github.com/xamarin/xamarin-macios/blob/9153edebda911f4b2d66d7facdd2fccc418eb7f2/tools/common/Target.cs#L773-L794

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Add support for Mono Components.

* Modify how we look up symbols from native libraries shipped with Mono: we keep
  track of which native libraries we linked with, and depending on how we linked
  to those assemblies, we look the symbols up at runtime in either the current executable
  (if linking statically), or the actual library (where the P/Invoke says they're
  supposed to be).

* This means that we have to propagate how libmono is linked from the MSBuild code
  to the Application class so that our existing logic is able to correctly determine
  which native mono lib to use.

* Modify how we list the P/Invokes we need to preserve by taking into account the
  list of native libraries from Mono we have to link with (for .NET). For legacy
  Xamarin, I've reverted the logic to how it was before we started adding .NET support.

Fixes https://github.com/xamarin/xamarin-macios/issues/10950.
Fixes https://github.com/xamarin/xamarin-macios/issues/11145.
Fixes https://github.com/xamarin/xamarin-macios/issues/12100.

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@rolfbjarne @spouliot - do we know roughly any size gains, and/or startup perf impact if any ?

**Review by dalexsoto — APPROVED** [review]

**Review by spouliot — APPROVED** [review]
LGTM

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2443).

**Comment by rolfbjarne** [comment]
> @rolfbjarne @spouliot - do we know roughly any size gains, and/or startup perf impact if any ?

I would be quite surprised if this had any measurable startup perf impact, the only new thing we do now are a few string comparisons.

I haven't done any size measurements, so I don't know the size gain (if any) there.

**Comment by spouliot** [comment]
@SamMonoRT the size impact seems minimal between this commit and the previous one

| Directories / Files |  Previous Commit  |  This Commit  | diff |  %  |
| ------------------- | --: | --: | ---: | --: |
| ./_CodeSignature | | | | ||     CodeResources | 5,525 | 5,525 | 0 | 0.0% |
| ./ | | | | ||     archived-expanded-entitlements.xcent | 392 | 392 | 0 | 0.0% |
|     embedded.mobileprovision | 12,391 | 12,391 | 0 | 0.0% |
|     icudt.dat | 1,913,136 | 1,913,136 | 0 | 0.0% |
|     Info.plist | 1,057 | 1,057 | 0 | 0.0% |
|     MySingleView | 7,720,544 | 7,717,344 | -3,200 | -0.0% |
|     MySingleView.aotdata.arm64 | 792 | 792 | 0 | 0.0% |
|     MySingleView.dll | 4,608 | 4,608 | 0 | 0.0% |
|     PkgInfo | 8 | 8 | 0 | 0.0% |
|     runtimeconfig.bin | 733 | 733 | 0 | 0.0% |
|     System.Private.CoreLib.aotdata.arm64 | 729,656 | 729,656 | 0 | 0.0% |
|     System.Private.CoreLib.dll | 772,608 | 772,608 | 0 | 0.0% |
|     System.Runtime.aotdata.arm64 | 504 | 504 | 0 | 0.0% |
|     System.Runtime.dll | 5,120 | 5,120 | 0 | 0.0% |
|     Xamarin.iOS.aotdata.arm64 | 48,360 | 48,360 | 0 | 0.0% |
|     Xamarin.iOS.dll | 73,728 | 73,728 | 0 | 0.0% |
| | | | | |
| **Statistics** | | | | |
| | | | | |
| Native subtotal | 8,499,856 | 8,496,656 | -3,200 | -0.0% |
|     Executable | 7,720,544 | 7,717,344 | -3,200 | -0.0% |
|     AOT data | 779,312 | 779,312 | 0 | 0.0% |
| | | | | |
| Managed *.dll/exe | 856,064 | 856,064 | 0 | 0.0% |
| | | | | |
| **TOTAL** | 11,289,162 | 11,285,962 | -3,200 | -0.0% |

**Pull request merged**
