### PR TITLE
[AudioUnit] Adds 'Latency' property [get|set]ter to AudioUnit object

### PR DESCRIPTION
**Pull request by dalexsoto**
Fixes xamarin/xamarin-macios#5217

Unfortunately I could not come up with a good test for this, we could create a package and let the reporter of #5217 test it.

Thoughts? 💭

### CODE REVIEW

**Comment by chamons** [comment]
It looks like your merge from master grabbed bits of one of my patches. Check the diff.

**Comment by dalexsoto** [comment]
@chamons yes, shame on me, forgot to undo a change on master, fixed now.

**Comment by dalexsoto** [comment]
So I got [feedback from our customer](
https://github.com/xamarin/xamarin-macios/issues/5217#issuecomment-445536873):

> Thanks @dalexsoto for addressing this so quickly.
> 
> I've had tested it in my application and can confirm that it is working as expected. My only bit of feedback is the set and get methods allow you to specify an AudioUnitScopeType, but only AudioUnitScopeType.Global is valid for latency (all others return an invalid scope error). For simplicity it might be sensible not to provide this option and always use AudioUnitScopeType.Global.
> 
> Regarding a test case I don't have anything I could provide right now, but if one is required it should be possible to use AudioComponent to retrieve all the system provided AudioUnit's, and use this latency property to get their provided latency values.

So I have applied feedback, once it is green, this is good to be merged.

**Comment by dalexsoto** [comment]
Unrelated test failure:

* xtro "DocumentManager" failure -> https://github.com/xamarin/maccore/issues/1111

**Pull request merged**
