### PR TITLE
added BaseFontSizePercentageRelativeToVideoHeight to CMTextMarkupAttributes

### LINKED ISSUE #5429: BaseFontSizePercentageRelativeToVideoHeight not available in CMTextMarkupAttribute
Hello,

I have noticed that a lot of kCMTextMarkupAttribute fields are missing and `kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight` in particular is very useful when working with the AVPlayer and adding subtitles. I have added a PR with this field added to the `CMTextMarkupAttributesKeys` Enum list and `CMTextMarkupAttributes`. 

This issue/feature would be very useful to be implemented.

Kind regards,
Philippe Creytens

### PR DESCRIPTION
**Pull request by PhilippeCreytens**
fixes #5429

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by PhilippeCreytens** [comment]
The test has failed on
`?unknown-entry? !missing-field! kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight not bound in 'common-CoreMedia.ignore'`

Do I need to remove this missing-field check from the common-CoreMedia.ignore file in the tests/xtro-sharpie folder?

**Comment by PhilippeCreytens** [comment]
@dalexsoto I have updated the PR, the spaces are switched by tabs and I have removed the missing-field check in the tests/xtro-sharpie folder.

**Comment by spouliot** [comment]
Thank you for your contributions :)

**Pull request merged**
