### PR TITLE
[58851] Disable NSMenuView in AllItemsWithNSMenuShouldAllowNull

### PR DESCRIPTION
**Pull request by timrisi**

### CODE REVIEW

**Comment by chamons** [comment]
💯  on a radar filed (in obj-c), added to the trello board and linked here.

**Comment by timrisi** [comment]
Radar filed and trello card added: https://trello.com/c/HzdFI4CN/94-33966228-calling-the-setmenu-method-on-nsmenuview-causes-a-sigabbt

**Comment by chamons** [comment]
@timrisi Please add radar # inline the code.

**Comment by chamons** [comment]
Test failures all known:

https://bugzilla.xamarin.com/show_bug.cgi?id=58929
https://bugzilla.xamarin.com/show_bug.cgi?id=58394

**Pull request merged**
