### PR TITLE
[XHarness] Reenable the System.Configuration tests on mac os x.

### PR DESCRIPTION
**Pull request by mandel-macaque**
Reenable the tests and add support to ignoring certain tests depending
on the version of the mac os x that is under test. The
System.Configuration tests make no sense in Modern.

Fixes https://github.com/xamarin/maccore/issues/1189
Fixes https://github.com/xamarin/maccore/issues/1190

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Do not merge until we have the following PRs in:

* https://github.com/xamarin/xamarin-macios/pull/5697
* https://github.com/xamarin/xamarin-macios/pull/5696

We will need to rebase with master. Added it at this point to start a conversation about the new ignore way for the tests that are diff between Full and Modern.

**Comment by mandel-macaque** [comment]
@spouliot it is a workaround until we have the Mono SDK downloadable for Mac OS X. I agree that is ugly, reason for asking for reviews :)

**Comment by spouliot** [comment]
@mandel-macaque I remain confused - are the test built for Modern (it's incomplete for full) or Full (like the name suggest) ?

**Comment by mandel-macaque** [comment]
@spouliot currently, we only have them built for Full.

**Comment by mandel-macaque** [comment]
@spouliot to give you more context, we do not have the mono mac os sdk just yet, probably on 2019-02. But I can move fwd and reenable the tests. Once we have it, we will have to do less work. The idea, not be FULLY blocked by the mono team.

**Comment by mandel-macaque** [comment]
Crashes are known issues and unrelated to the PR.

**Comment by mandel-macaque** [comment]
build

**Pull request merged**
