### PR TITLE
[macos] Fix pdb mismatch when saving assemblies processed by mmp

### PR DESCRIPTION
**Pull request by chamons**
- Teach mmp's resolver to ask for symbol reading from Cecil
- Customer reports XM > 3.0 had broken library behavior but not before, possibly new cecil version?

### CODE REVIEW

**Comment by chamons** [comment]
Bah. Totally botched the title of the commit. Please remember to reword when squashing:

procssed => processed

**Comment by chamons** [comment]
Manual testing has not come up with a use case outside of the customer's large applications (I tried a number of them), so 15.6 is my suggestion given how late in 15.5 we are.

**Comment by chamons** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=58951 and a test hang?

https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5353/Test_Report/monotouch-test_16/run-27618A4A-7E49-4BAB-8F77-FA938CE88682-20171017_152557.log

@rolfbjarne Thoughts on log ^?

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* introspection/iOS
* introspection/tvOS: bug #[60227](https://bugzilla.xamarin.com/show_bug.cgi?id=60227)
* monotouch-test/iOS: bug #[60229](https://bugzilla.xamarin.com/show_bug.cgi?id=60229)
* monotouch-test/watchOS: bug #[58951](https://bugzilla.xamarin.com/show_bug.cgi?id=58951)

However, I'm wondering why this didn't show up for Xamarin.iOS; I think it would make sense to do whatever XI does.

**Comment by chamons** [comment]
@rolfbjarne So I can (and did) apply the same changes to mtouch but some deeper questions remain.

Why did this not break before? What is it about this huge customer application that triggered it? The synthetic examples I've produces so far have not shown the issue and the original would take hours if not days to tear apart.

On the surface, the change looks correct: We are rewriting pdbs so of course ask cecil to load them. Not all dlls have pdb, so don't throw.

But I can't give you a wonderful explanation on the why side with my current level of digging. If you believe that is necessary to get the 👍  I'll go grab my shovel.

**Comment by rolfbjarne** [comment]
@chamons I don't think it should be that complicated to figure out why mmp doesn't load certain pdbs, I can have a look if you send me the test case.

**Comment by chamons** [comment]
So, the question isn't why cecil/mmp isn't handling these pdbs. That can be shown with this trivial repro (message me for the dll/pdb):

            const string LibPath = @"MVVMTests.dll";
            var assemblyDef = AssemblyDefinition.ReadAssembly(LibPath);
            Console.WriteLine(assemblyDef.MainModule.HasSymbols); //false

The question is why it's handling any of them correctly. Without ReadSymbols being true, I always see HasSymbols be false due to module.Image.HasDebugTables ()  being false. 

Changing that to:

           ReadAssembly (libPath, new ReaderParameters { ReadSymbols = true })

gives me HasSymbols be true, and fixes the test application.

I'd expect that every single pdb rewrite would fail if we don't ask cecil to readsymbols, but they don't fwict. Thus my confusion...

**Comment by chamons** [comment]
Ok, I did some digging and have better answers. I also have a test project reproducing the issue.

From what I can tell, we walk assemblies and invoke ResolveFromAssemblyStep which calls TryReadSymbols of all assemblies being processed, which forces them to be loaded symbols into memory. So despite not asking cecil to load symbols, they are there anyway by the time we are writing assemblies out (and thus handle pdb correctly later).

However, in cases such as my repro, where you have multiple levels of library dependence AND reflection, the library in question might not be processed but it will be pulled along into being written out. Thus, without this change, we don't load symbols, don't write out the updated pdb, and it breaks debugging.

I filed a bug here: https://bugzilla.xamarin.com/show_bug.cgi?id=60277

The bug and some of this explanation should be added to the squashed commit description.

**Comment by chamons** [comment]
Great detective work @rolfbjarne 

I'll make those change shortly.

**Comment by chamons** [comment]
The mtouch changes are slightly larger - https://gist.github.com/chamons/b1b3e5db2f0824467696d7e407e976d2 and i'm unsure if we want this to touch mtouch at all. @rolfbjarne  ?

**Comment by rolfbjarne** [comment]
I take back my previous statement, I believe we (both XI and XM) should always load any .mdb/.pdb files and write back updated versions if the assembly changed. The difference between debug and release should be that release mode shouldn't put .mdb/.pdb files in the .app (this is how it already works in XI).

**Pull request merged**
