### PR TITLE
[Harness] Remove the BCLTestProjectInfo class.

### PR DESCRIPTION
**Pull request by mandel-macaque**
The class is not really needed. Move to a tuple, make the definition of
the group test project nicer since the dictionary initiallization makes
it cleaner.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
PR is a draft because is pointing to the parent branch remove-extra-class-bcl to minimise the diff. Once remove-extra-class-bcl lands will be moved to a normal PR. Doing it so that the review process is easier.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-8221/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-8221/2//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8221/3//console)
✅ Packages: 
* [xamarin.ios-13.19.0.380.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/package/xamarin.ios-13.19.0.380.pkg)
* [xamarin.mac-6.19.0.380.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/package/xamarin.mac-6.19.0.380.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ab95d460ea0de2fa2c0037e5976d737ac8e1c673/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 180 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#6)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/5/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/5/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#6)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8221/6/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8221/6/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8221/6//console)
✅ Packages: 
* [xamarin.ios-13.19.0.389.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8221/4d3e8b3c7092595023c06a0bac1d26d86a98839a/6/package/xamarin.ios-13.19.0.389.pkg)
* [xamarin.mac-6.19.0.389.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8221/4d3e8b3c7092595023c06a0bac1d26d86a98839a/6/package/xamarin.mac-6.19.0.389.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ef14901e05edef648107c9ca66a13c2779f0e77e/6/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ef14901e05edef648107c9ca66a13c2779f0e77e/6/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ef14901e05edef648107c9ca66a13c2779f0e77e/6/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8221/ef14901e05edef648107c9ca66a13c2779f0e77e/6/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>5 tests failed, 180 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Pull request merged**
