### PR TITLE
[msbuild] Added assembly reference unit tests

### PR DESCRIPTION
**Pull request by jstedfast**
Here's the unit test that @spouliot suggested in our team call on Monday.

### CODE REVIEW

**Comment by VincentDondain** [comment]
@jstedfast your new test is failing

```
Errors and Failures:
1) Test Failure : Xamarin.iOS.Tasks.AssemblyReferenceTests.TestAssemblyReferences
   Unknown assembly reference: pnunit.framework, Version=1.0.5463.34981, Culture=neutral, PublicKeyToken=null
at Xamarin.iOS.Tasks.AssemblyReferenceTests.TestAssemblyReferences () [0x000e1] in <e13811075a394c61a188cf90ce587008>:0
```

**Comment by VincentDondain** [comment]
@jstedfast could you add a description to the PR (and commit message when merging). It not clear to me *why* we need such test.

**Comment by jstedfast** [comment]
Wtf is pnunit? When I ran that locally there is no pnunit assembly.

**Comment by jstedfast** [comment]
@spouliot good question. I wonder if maybe we reference the dll but don't make use of it? I should probably check that...

**Comment by rolfbjarne** [comment]
> I wonder why this did not report Mono.Cecil since the other PR has a reference to it ?

Maybe because the tests hadn't loaded it yet.

**Pull request closed without merging**
