### PR TITLE
Don't use azureedge.net CDN

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by dalexsoto** [comment]
@directhex 

> Xamarin.Provisioning.ProvisioningException: Unable to download source (https://xamjenkinsartifact.blob.core.windows.net/build-package-osx-mono/2020-02/185/dffa5ab92245f2419238a35b7c2052e9a24036b4/MonoFramework-MDK-6.12.0.179.macos10.xamarin.universal.pkg) for 'Mono 6.12.0.179'

**Comment by directhex** [comment]
> @directhex
> 
> > Xamarin.Provisioning.ProvisioningException: Unable to download source (https://xamjenkinsartifact.blob.core.windows.net/build-package-osx-mono/2020-02/185/dffa5ab92245f2419238a35b7c2052e9a24036b4/MonoFramework-MDK-6.12.0.179.macos10.xamarin.universal.pkg) for 'Mono 6.12.0.179'

Dunno what to say, that URL works for me

**Comment by directhex** [comment]
" ---> Xamarin.Provisioning.UnsupportedDownloadHostException: ERROR: DownloadItemAsync: Downloads from 'xamjenkinsartifact.blob.core.windows.net' are not supported. Consider making the content available from download.visualstudio.microsoft.com or dl.xamarin.com if possible. If downloads from this host are needed contact VSEng (VSEngHelp@microsoft.com) for approval"

Well, whatever's to blame, that needs fixing pretty soon. The old CDN is going away _today_.

**Comment by directhex** [comment]
This PR. https://github.com/xamarin/provisionator/pull/534

**Review by rolfbjarne — APPROVED** [review]

**Comment by directhex** [comment]
How do we feel about scream-testing shutdown of the old CDN soon?

**Comment by rolfbjarne** [comment]
> How do we feel about scream-testing shutdown of the old CDN soon?

😱

The sooner the better IMHO, that way we have more time to fix any issues that pop up.

**Comment by directhex** [comment]
OK. Waiting for a response on the Android PR about scream testing

**Pull request merged**
