### PR TITLE
[sampletester] Bump xamarin-forms-book-samples to the tip of master, where a few fixes have been merged.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6186/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6186/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#2)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6186/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6186/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Running XM tests on '10.13', Running XM tests on '10.10', Running XM tests on '10.10'' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6186/2//console)
✅ Packages: [xamarin.ios-12.15.0.190.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/package/xamarin.ios-12.15.0.190.pkg) [xamarin.mac-5.15.0.190.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/package/xamarin.mac-5.15.0.190.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Xamarin.Mac tests on 10.13 failed: Xamarin.Mac tests on macOS 10.13 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6186/2/display/redirect) 🔥
🔥 [Xamarin.Mac tests on 10.10 failed: Xamarin.Mac tests on macOS 10.10 failed (xammac_tests)](https://jenkins.internalx.com/job/macios/job/PR-6186/2/display/redirect) 🔥
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/bd7e48e8ec5300ae361b1633d0780aa89fde2d18/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>3 tests failed, 167 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug: Crashed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
 * Generator tests/NUnit: Failed (Execution failed with exit code 1)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-6186/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-6186/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-6186/3//console)
✅ Packages: [xamarin.ios-12.15.0.197.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/package/xamarin.ios-12.15.0.197.pkg) [xamarin.mac-5.15.0.197.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/package/xamarin.mac-5.15.0.197.pkg)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-6186/5a8acb525c29c3dbcdcf60773a692db713314373/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 169 tests passed.</summary>

## Failed tests

 * [NUnit] Mono Mac OS X BCL tests group 2/Mac/Full: Failed (Test run crashed (exit code: 134).)
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): Crashed
</details>

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* Sample tests: all are due to https://github.com/xamarin/maccore/issues/1686.
* [NUnit] Mono Mac OS X BCL tests group 2/Mac/Full: https://github.com/xamarin/maccore/issues/1685
* introspection/watchOS 32-bits - simulator/Debug (watchOS 2.0): https://github.com/xamarin/maccore/issues/581

**Pull request merged**
