### PR TITLE
Disable Mac bits since xcode8.3 is cycle8-xi based

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by spouliot** [comment]
^ conflict, you reused your old branch ?

Also XM is released from `cycle8`, not `cycle8-xi`, so the release date would not change anything :)

**Comment by VincentDondain** [comment]
Yea I fixed that before your comment :P

My `xcode8.3` branch wasn't up to date when I branched.

**Comment by VincentDondain** [comment]
Mmh the tests are not happy that I disabled Mac!

`/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/introspection/Mac/introspection-mac-unified.csproj could not import "$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.CSharp.targets" `

**Comment by VincentDondain** [comment]
@rolfbjarne Wouldn't xharness need to be patched to pick up `INCLUDE_MAC` from the Make.config file?

Like this: https://github.com/xamarin/xamarin-macios/blob/cycle8-xi/tests/xharness/Harness.cs#L187 and we'd patch `MakefileGenerator.cs` or I am missing something?

**Comment by rolfbjarne** [comment]
@VincentDondain that's a good point, let me fix that in xharness.

**Comment by rolfbjarne** [comment]
I'm teaching xharness about `INCLUDE_MAC` in PR #1581.

**Comment by VincentDondain** [comment]
Since https://github.com/xamarin/xamarin-macios/pull/1581 is also commenting `INCLUDE_MAC` in the `Make.config` file let us close this PR.

**Comment by VincentDondain** [comment]
Restoring this PR since disabling `INCLUDE_MAC` in https://github.com/xamarin/xamarin-macios/pull/1581 was only added for test purposes.

**Comment by rolfbjarne** [comment]
build

**Comment by VincentDondain** [comment]
Perfect!

Unrelated monotouch-test failures: https://bugzilla.xamarin.com/show_bug.cgi?id=51801

**Pull request merged**
