### PR TITLE
Bump maccore to get updated docs.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Relevant commit list for xamarin/maccore:

* xamarin/maccore@d4790d6ac2 Bump NEEDED_IOS_API_DOCS_VERSION to iOS 12 (xamarin/maccore#1023)

Diff: https://github.com/xamarin/maccore/compare/07fde84362aac824c6d9596c8dae13cfa48a102e...d4790d6ac2e0599be31697e4aa766329544961c2

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@lobrien just a FYI that I've created this PR to propagate your docs bump all the way up.

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4790/2/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-4790/2//console) 🔥

**Comment by xamarin-release-manager** [comment]
🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-4790/3/display/redirect) (on internal Jenkins) failed in stage 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-4790/3//console) 🔥

**Comment by rolfbjarne** [comment]
@lobrien this bump fails the build with:

```
Building MsDoc from Mono Docs

Unhandled Exception:
System.ArgumentException: Namespace 'MonoTouch.Accelerate' not found in monodoc index.
  at Xamarin.XmlDocSync.MonoDocXml.Load (System.String path) [0x001e2] in <c33d4b1a5d21471684e82f21d070e986>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.CreateMsDoc (System.String monoDocsPath, System.String assemblyPath, System.String outputPath) [0x0006a] in <00a8cea4448142f8a27b7e9f144358c0>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.Main (System.String[] args) [0x000ee] in <00a8cea4448142f8a27b7e9f144358c0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Namespace 'MonoTouch.Accelerate' not found in monodoc index.
  at Xamarin.XmlDocSync.MonoDocXml.Load (System.String path) [0x001e2] in <c33d4b1a5d21471684e82f21d070e986>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.CreateMsDoc (System.String monoDocsPath, System.String assemblyPath, System.String outputPath) [0x0006a] in <00a8cea4448142f8a27b7e9f144358c0>:0 
  at Xamarin.XmlDocSync.CmdLine.Program.Main (System.String[] args) [0x000ee] in <00a8cea4448142f8a27b7e9f144358c0>:0 
make[3]: *** [build/unified/Xamarin.iOS.xml] Error 1

```

See https://jenkins.internalx.com/blue/rest/organizations/jenkins/pipelines/macios/branches/PR-4790/runs/3/nodes/45/steps/49/log/?start=0 for the full log

**Comment by rolfbjarne** [comment]
The docs bump in maccore has been reverted (https://github.com/xamarin/maccore/pull/1038), so I'm closing this.

**Pull request closed without merging**
