### PR TITLE
Migrate Messaging Build agent to .NET 8

### PR DESCRIPTION
**Pull request by emaf**
This is part of the effort to migrate the Pair to Mac agents .NET.

As the Xamarin.iOS.Tasks.Windows project targets netstandard2.0, I'm removing the Build agent reference, and modifying the Makefile to take it from it's output directory. Note: the agent zip file is generated in the intermediate output directory.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
It looks like the build on Windows can't connect to the Mac: https://gist.github.com/rolfbjarne/0a12209ae28f50621a9602eb9d4f0a64

I see that the broker is executed using .NET; this is from app.plist on the Mac:

```xml
	<array>
		<string>/usr/local/share/dotnet/dotnet</string>
		<string>/Users/builder/Library/Caches/Xamarin/XMA/Agents/Broker/2.0.0.13/Broker.dll</string>
```

This obviously requires having .NET installed already: does the new code handle not having .NET installed? Maybe it would be better to produce a self-contained Broker executable that doesn't require having .NET installed?

**Comment by emaf** [comment]
> It looks like the build on Windows can't connect to the Mac: https://gist.github.com/rolfbjarne/0a12209ae28f50621a9602eb9d4f0a64
> 
> I see that the broker is executed using .NET; this is from app.plist on the Mac:
> 
> ```
> 	<array>
> 		<string>/usr/local/share/dotnet/dotnet</string>
> 		<string>/Users/builder/Library/Caches/Xamarin/XMA/Agents/Broker/2.0.0.13/Broker.dll</string>
> ```
> 
> This obviously requires having .NET installed already: does the new code handle not having .NET installed? Maybe it would be better to produce a self-contained Broker executable that doesn't require having .NET installed?

Yeah, it is a new requirement as it was having mono installed before, and VS will handled the remote installation too (for CLI builds you have to manually install it). We decided not to generate a self-contained app because of the size of it and we would need to do that for the Build agent too. That said, I think the warning we show should mention something like "Ensure the .NET Runtime is installed".

Is the dotnet runtime not installed on the bots or is it under a custom path?

**Comment by rolfbjarne** [comment]
> Is the dotnet runtime not installed on the bots or is it under a custom path?

I'm not sure if it's installed by default or not (we don't install manually during the test run).

In any case I think the SayHello task should verify that the dotnet runtime is actually installed in the given path, and validate the dotnet version as well. Note that I don't even know if this is the actual problem - and as many problems as possible should be diagnosable using the binlog, otherwise this will be even worse when customers run into troubles :)

**Comment by rolfbjarne** [comment]
It still fails, but with a much better error message: 

> error VSX1002: The .NET runtime 8.0.1 or newer could not be found in the remote host under 'BundleStructure'. Please install it or try setting a different path using the MSBuild property "DotNetRuntimePath".

I think there's a bug in the implementation though, because it checks a Windows path, not a macOS path:

> [xma][info]: Executing SSH command: 'ls "D:/Users/xamarint-local/AppData/Local/Xamarin/iOS/Caches/Xamarin/XMA/SDKs/dotnet/dotnet"'

https://gist.github.com/rolfbjarne/3a5ff50ef08f45de96369b02168ee8a5

**Comment by rolfbjarne** [comment]
The SayHello target still fails: https://gist.github.com/rolfbjarne/af14febe57fa2c44b04913c5ad92612c

The .NET check works fine: https://gist.github.com/rolfbjarne/af14febe57fa2c44b04913c5ad92612c#file-gistfile1-txt-L49-L53

but then it fails later with "[xma][err]: An error occurred while trying to start the Broker...": https://gist.github.com/rolfbjarne/af14febe57fa2c44b04913c5ad92612c#file-gistfile1-txt-L49-L53

As far as I can tell there's no more information anywhere about this error, so I have no idea what's going on.

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
The tests are passing now! However, it looks like you're bumping Xamarin.MacDev to an earlier commit, maybe by mistake?

**Comment by emaf** [comment]
> The tests are passing now! However, it looks like you're bumping Xamarin.MacDev to an earlier commit, maybe by mistake?

I think it came into this branch from this merge from main: https://github.com/xamarin/xamarin-macios/pull/20705/commits/7910b523568b20849b91cc6bfc6dc0763d2022ca. Not sure why though.

I'll revert that.

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
