### PR TITLE
[coregraphics] Update up to beta 5

### PR DESCRIPTION
**Pull request by spouliot**
Apple removed CGColorConverter even if it was publicly exposed in iOS 9.3,
not that I recall any API that consumed it...

It was replaced by a new, very close, type named CGColorConversionInfo and
the existing code and tests were updated to the new API.

So for `CGColorConverter` we're

* iOS: Obsoleted + code removal
* tvOS: Obsoleted + code removal
* watchOS: the API can be removed as it was not exposed in a stable release
* macOS: it was not enabled (did not work)

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@VincentDondain this replaces some code you wrote for iOS 9.3, please review :)

**Comment by VincentDondain** [comment]
That looks good to me (:

**Pull request merged**
