### PR TITLE
[mac][msbuild] Opt-in to filtering out denied assemblies

### PR DESCRIPTION
**Pull request by radical**
PR for adding support for the filtering in msbuild:
	https://github.com/mono/msbuild/pull/23

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by chamons** [comment]
So this should only be for non-Modern profiles, since people who are recompiling for Modern aren't shipping windows bits.

Can we wrap this inside a:

```	
<When Condition=" '$(TargetFrameworkIdentifier)' == 'Xamarin.Mac'">
``` 
conditional?

**Comment by radical** [comment]
Added the condition from @chamons .

**Comment by radical** [comment]
@chamons for non-modern shouldn't the condition be `''$(TargetFrameworkIdentifier)' != 'Xamarin.Mac'` ? And how do we know that the windows/denied assemblies are not being used from the nugets?

**Comment by chamons** [comment]
Yeah, != Mac. What I get for copy pasting before coffee.

**Comment by radical** [comment]
The msbuild PR for supporting this has been merged now - https://github.com/mono/msbuild/commit/c907a5182a101624eb58e73fb24f97666abf477a .

**Comment by radical** [comment]
Can we merge this now? And cherry-pick to d15-4?

**Comment by spouliot** [comment]
@radical are the required commits available in mono's `d15-4-2017-04` branch ? if so we can ask for a backport

**Comment by radical** [comment]
IIUC, mono from 2017-06 would be used for 15.4 and 2017-04 for the products only. So, shouldn't it be `d15-4-2017-06`? The required commits are available in that branch. But they are *not* available in `d15-4-2017-04`. The fixes are in two parts:
1. Installing the list of denied assemblies to xbuild/msbuild's common path https://github.com/mono/mono/commit/cbc738c44dfe061a37e0e64c4ac333b72e8e8475
2. And adding support in msbuild (https://github.com/mono/msbuild/commit/c907a5182a101624eb58e73fb24f97666abf477a)

**Comment by spouliot** [comment]
@radical you're right, it's `d15-4-2017-06`

**Pull request merged**
