### PR TITLE
[WatchKit] Bind WKInterfaceDevice.PreferredContentSizeCategory as string. Fixes #44456.

### PR DESCRIPTION
**Pull request by rolfbjarne**
https://bugzilla.xamarin.com/show_bug.cgi?id=44456

### CODE REVIEW

**Comment by spouliot** [comment]
`NS_ENUM_STRING` means it's an `NSString` that behaves like an enum and, for us, means it's *very likely* a candidate to become enum. Let me double check that...

**Comment by spouliot** [comment]
The removed code existed in Xamarin.iOS.dll, so this is a breaking change.

> Type Changed: WatchKit.WKInterfaceDevice
> 
> Modified properties:
> 
> 	public virtual UIKit.UIContentSizeCategory Foundation.NSString PreferredContentSizeCategory { get; }
>

**Comment by rolfbjarne** [comment]
I see my comment is confusing:

* UIApplication.PreferredContentSizeCategory: defined as NS_APPLE_ENUM, we bound using enum.
* WKInterfaceDevice.PreferredContentSizeCategory: defined as NSString (whose values are not publicly documented), we bound as enum in Xamarin.iOS.dll (thus the API break), and not bound in Xamarin.WatchOS.dll (before this PR).

**Comment by rolfbjarne** [comment]
@spouliot I've updated the patch to just use a new name.

**Comment by spouliot** [comment]
`NS_APPLE_ENUM` that's a new one ;-)

I normally don't like a suffix like `String` but I have a feeling that the constant will eventually be exposed properly and we'll have to adapt that property again (and could use a suffix less name, like `PreferredContentSize`).

**Pull request merged**
