### PR TITLE
[msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.

### LINKED ISSUE #15267: PartialAppManifest compile error (Windows)
Looks like [partial app manifests](https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties#partialappmanifest) are [not copied ](https://github.com/xamarin/xamarin-macios/blob/8adbefdac8813bbcbb05e35611ba15491f903744/msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs#L22)to remote build server from windows workstation.
That causes compile time error:
 
### Steps to Reproduce

1. Create empty Xamarin.iOS project from VS template (or use sample attached [PM.zip](https://github.com/xamarin/xamarin-macios/files/8900200/PM.zip))
2. Add _Info.Partial1.plist_ file
3. Edit project file or set build action to: **PartialAppManifest**
4. Try compile it on Windows
5. Observe partial app manifest error:
```
1>Task "CompileAppManifest"
1>  CompileAppManifest: 2022-06-14T16:29:53.0902267+03:00 - Started
1>  CompileAppManifest: 2022-06-14T16:29:53.0902267+03:00 - Initializing
1>  [xma]: Trying to get a Build Connection for Session 'c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd': Xamarin.Messaging.Build.Client.BuildConnection.c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd, Lifetime: AppDomain
1>  CompileAppManifest: 2022-06-14T16:29:53.0902267+03:00 - Initialized
1>  CompileAppManifest: 2022-06-14T16:29:53.0922616+03:00 - Determining the modified inputs that should be copied to the Mac (1 files)
1>  [xma]: Determining task items to copy to the server for 'PM'...
1>  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.CompareItemsMessage to topic xvs/build/compare-items
1>  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.CompareItemsMessage to topic buildc824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd6112Yauhe/+/xvs/build/compare-items
1>  [xma]: The following items should be copied to the server for 'PM': Info.plist
1>  CompileAppManifest: 2022-06-14T16:29:53.1909183+03:00 - Copying inputs (1 files)
1>  [xma]: SCP uploading 'Info.plist' to 'Info.plist' for 'PM'...
1>  [xma]: Preparing directory /Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd before uploading...
1>  [xma]: Executing SSH command 'mkdir -p "/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd"'...
1>  [xma]: Trying to copy to '/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd/Info.plist' from cache...
1>  [xma]: Executing SSH command 'cp -f "/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/XMA/Cache/17ba6a7bf867630d5da41055213a43150d963bc906d76698d1f77353176c7bea" "/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd/Info.plist"'...
1>  [xma]: Successfully copied '/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd/Info.plist' from cache
1>  CompileAppManifest: 2022-06-14T16:29:53.3168947+03:00 - Serializing intputs
1>  CompileAppManifest: 2022-06-14T16:29:53.3518408+03:00 - Executing
1>  [xma]: Starting remote task execution for 'PM': Xamarin.iOS.Tasks.CompileAppManifest
1>  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/PM/c824bfa002fCompileAppManifest
1>  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic buildc824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd6112Yauhe/+/xvs/build/execute-task/PM/c824bfa002fCompileAppManifest
1>  CompileAppManifest: 2022-06-14T16:29:53.5023224+03:00 - Logging messages
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(439,3): error : Error loading partial Info.plist template file 'Info.Partial1.plist': Could not find file "/Users/Yauheni_Aliashkevich/Library/Caches/Xamarin/mtbs/builds/PM/c824bfa070a42da7e9be373da41cd30b184bc5dc30d69c1bc0a3fd7a514c93fd/Info.Partial1.plist"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(439,3): error :         
1>  The file obj/iPhoneSimulator/Debug/AppManifest.plist is up-to-date.
1>  CompileAppManifest: 2022-06-14T16:29:53.5053229+03:00 - Finished
1>Done executing task "CompileAppManifest" -- FAILED.
1>Done building target "_CompileAppManifest" in project "PM.csproj" -- FAILED.
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
The exclusion of partial app manifests happened here, but the commit doesn't explain why:

https://github.com/xamarin/xamarin-macios/commit/f4a4b232f8130a9172f6ac86c52a64c42d227bd5#diff-178de6110858688b9f7c2e8e57a873f5ac9498b355a456bfc18547ab2df876bc

It's certainly wrong if the partial app manifest is a part of the project, but
this exclusion might be because partial app manifests might be added as a part
of the build as well.

So change the logic to copy partial app manifests from Windows if they exist
there.

Fixes https://github.com/xamarin/xamarin-macios/issues/15267.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2558).

**Comment by emaf** [comment]
@rolfbjarne I think the intention was to exclude the partial app manifest generated by some other task. The problem is that file in Windows is empty, so we were replacing the real one in the Mac by the empty one from Windows.

The code you changed will be executed on Windows, and items that go through that code will exist there. The problem is it won't discriminate between empty and non-empty partial app manifests. I think we should check if it's an empty file instead of if it exists.

**Comment by rolfbjarne** [comment]
@emaf ok, changed to only copy non-empty files now.

**Review by tj-devel709 — APPROVED** [review]

**Review by mauroa — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Pull request merged**
