### PR TITLE
[tests] Ignore failing GestureRecognizerTest for now

### PR DESCRIPTION
**Pull request by VincentDondain**
- WIP PR https://github.com/xamarin/xamarin-macios/pull/5462 more investigation needed so ignore test which is preventing green builds

### CODE REVIEW

**Comment by VincentDondain** [comment]
@monojenkins backport to d16-0

**Comment by VincentDondain** [comment]
@chamons do you think we can still merge this PR?

**Comment by spouliot** [comment]
@VincentDondain this one is on master ;-)

**Comment by VincentDondain** [comment]
Oops too many tabs opened (:

**Pull request merged**
