### PR TITLE
[msbuild] Don't force mcs for Xamarin.Mac

### PR DESCRIPTION
**Pull request by jstedfast**

### CODE REVIEW

**Comment by spouliot** [comment]
@jstedfast there's at least one more

```
Sebastiens-iMac:xamarin-macios poupou$ git grep mcs msbuild/
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets:              <!-- work around a bug in the Mono Microsoft.CSharp.Targets that defaults the compiler to gmcs -->
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets:              <CscToolExe Condition="'$(OS)' == 'Unix'">mcs</CscToolExe>
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets:              <!-- We default to *mcs compiler above, so, select the .mdb as the debug ext -->
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props:         <CscToolExe Condition="'$(CscToolExe)' == ''">mcs</CscToolExe>
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props:         <!-- We default to mcs compiler above, so, select .mdb as the debug ext. This file gets correctly
```

**Comment by jstedfast** [comment]
Yep, already got that one.

**Comment by spouliot** [comment]
@jstedfast I meant `msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props` (there was two file in my grep).

**Comment by jstedfast** [comment]
Weird, I don't have a Xamarin.Mac.ObjCBinding.CSharp.props in either d15-2 nor master.

**Comment by jstedfast** [comment]
Aha, it's there in the file system but not included in the project.

**Comment by radical** [comment]
Does this need to change too - https://github.com/xamarin/xamarin-macios/blob/d15-2/tests/common/Configuration.cs#L274 ?

**Comment by jstedfast** [comment]
@radical nothing seems to actually use it

**Comment by radical** [comment]
And this - https://github.com/xamarin/xamarin-macios/blob/master/tools/pmcs/pmcs#L51 ?

**Comment by radical** [comment]
https://github.com/xamarin/xamarin-macios/blob/master/tools/pmcs/BuiltinProfiles.cs#L114 ? I am just grep'ing, I don't actually know how they are being used or their impact.

**Comment by radical** [comment]
https://github.com/xamarin/xamarin-macios/blob/master/tests/test-libraries/Makefile#L27
tests/xharness/BCLTarget.cs
https://github.com/xamarin/xamarin-macios/blob/master/Make.config#L234

**Comment by rolfbjarne** [comment]
@radical Changing our own build to use csc instead of mcs is handled in PR #1992.

**Pull request merged**
