### PR TITLE
[xtro] Improve detection of Catalyst missing API by fixing xtro

### PR DESCRIPTION
**Pull request by chamons**
- Redo of https://github.com/xamarin/xamarin-macios/pull/12616 with a second fix included

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Comment by chamons** [comment]
Test issues appear to be https://github.com/xamarin/maccore/issues/2494

**Review by spouliot — APPROVED** [review]

**Comment by spouliot** [comment]
`Xtro/Mac: BuildFailure` indicate a problem, likely `sanity` check failed

**Review by rolfbjarne — APPROVED** [review]
> +7 −9,219

Nice!

**Comment by spouliot** [comment]
yep, sanity check failed
```
12:38:58.6135150 ?unknown-entry? !missing-field! ACAccountTypeIdentifierLinkedIn not bound in 'MacCatalyst-Accounts.ignore'
12:38:58.6135700 ?unknown-entry? !missing-field! ACLinkedInAppIdKey not bound in 'MacCatalyst-Accounts.ignore'
12:38:58.6135880 ?unknown-entry? !missing-field! ACLinkedInPermissionsKey not bound in 'MacCatalyst-Accounts.ignore'
12:38:58.6606940 ?unknown-entry? !missing-selector! LAAuthenticationView::context not bound in 'MacCatalyst-LocalAuthenticationEmbeddedUI.ignore'
12:38:58.6607380 ?unknown-entry? !missing-selector! LAAuthenticationView::controlSize not bound in 'MacCatalyst-LocalAuthenticationEmbeddedUI.ignore'
12:38:58.6607570 ?unknown-entry? !missing-selector! LAAuthenticationView::initWithContext: not bound in 'MacCatalyst-LocalAuthenticationEmbeddedUI.ignore'
12:38:58.6607710 ?unknown-entry? !missing-selector! LAAuthenticationView::initWithContext:controlSize: not bound in 'MacCatalyst-LocalAuthenticationEmbeddedUI.ignore'
12:38:58.6607860 ?unknown-entry? !missing-type! LAAuthenticationView not bound in 'MacCatalyst-LocalAuthenticationEmbeddedUI.ignore'
12:38:58.6962000 ?unknown-entry? !missing-type! MEEmailAddress not bound in 'MacCatalyst-MailKit.ignore'
12:38:58.6962370 ?unknown-entry? !missing-selector! MEEmailAddress::addressString not bound in 'MacCatalyst-MailKit.ignore'
12:38:58.6962540 ?unknown-entry? !missing-selector! MEEmailAddress::initWithRawString: not bound in 'MacCatalyst-MailKit.ignore'
12:38:58.6962690 ?unknown-entry? !missing-selector! MEEmailAddress::rawString not bound in 'MacCatalyst-MailKit.ignore'
12:38:58.7559800 ?unknown-entry? !missing-selector! ASIdentifierManager::clearAdvertisingIdentifier not bound in 'MacCatalyst-AdSupport.ignore'
12:38:58.8394660 ?fixed-todo? Entry '!missing-enum! FIMenuKind not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8395400 ?fixed-todo? Entry '!missing-protocol! FIFinderSync not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8395640 ?fixed-todo? Entry '!missing-selector! +FIFinderSyncController::defaultController not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8395850 ?fixed-todo? Entry '!missing-selector! +FIFinderSyncController::isExtensionEnabled not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8396070 ?fixed-todo? Entry '!missing-selector! +FIFinderSyncController::showExtensionManagementInterface not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8396780 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::directoryURLs not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8397220 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::lastUsedDateForItemWithURL: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8397680 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::selectedItemURLs not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8397820 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::setBadgeIdentifier:forURL: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8397930 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::setBadgeImage:label:forBadgeIdentifier: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398240 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::setDirectoryURLs: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398380 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::setLastUsedDate:forItemWithURL:completion: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398490 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::setTagData:forItemWithURL:completion: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398600 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::tagDataForItemWithURL: not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398860 ?fixed-todo? Entry '!missing-selector! FIFinderSyncController::targetedURL not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8398990 ?fixed-todo? Entry '!missing-type! FIFinderSync not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8399100 ?fixed-todo? Entry '!missing-type! FIFinderSyncController not bound' in 'MacCatalyst-FinderSync.todo' might be fixed since there's no corresponding 'MacCatalyst-FinderSync.raw' file
12:38:58.8739840 ?fixed-todo? Entry '!missing-enum! NCUpdateResult not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8740180 ?fixed-todo? Entry '!missing-protocol! NCWidgetListViewDelegate not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8740320 ?fixed-todo? Entry '!missing-protocol! NCWidgetProviding not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8740430 ?fixed-todo? Entry '!missing-protocol! NCWidgetSearchViewDelegate not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8740540 ?fixed-todo? Entry '!missing-selector! +NCWidgetController::defaultWidgetController not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8740950 ?fixed-todo? Entry '!missing-selector! +NCWidgetController::widgetController not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8741100 ?fixed-todo? Entry '!missing-selector! NCWidgetController::setHasContent:forWidgetWithBundleIdentifier: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8741210 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::contents not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8741490 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::delegate not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8741820 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::editing not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8741960 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::hasDividerLines not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742070 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::minimumVisibleRowCount not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742180 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::rowForViewController: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742280 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setContents: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742580 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setDelegate: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742710 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setEditing: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742820 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setHasDividerLines: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8742930 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setMinimumVisibleRowCount: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743220 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::setShowsAddButtonWhenEditing: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743360 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::showsAddButtonWhenEditing not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743470 ?fixed-todo? Entry '!missing-selector! NCWidgetListViewController::viewControllerAtRow:makeIfNecessary: not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743570 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::delegate not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743680 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::searchDescription not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8743960 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::searchResultKeyPath not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8744090 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::searchResults not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8744320 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::searchResultsPlaceholderString not bound' in 'MacCatalyst-NotificationCenter.todo' might be fixed since there's no corresponding 'MacCatalyst-NotificationCenter.raw' file
12:38:58.8744440 ?fixed-todo? Entry '!missing-selector! NCWidgetSearchViewController::setDelegate: not
```

**Comment by chamons** [comment]
Yep, need to pull main and do it again.

**Comment by chamons** [comment]
🤞

**Review by dalexsoto — APPROVED** [review]
Nice!! ❤️

**Comment by chamons** [comment]
Test failure: https://github.com/xamarin/xamarin-macios/issues/12640

**Pull request merged**
