### PR TITLE
[msbuild] Always codesign iOS frameworks

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=43264

### CODE REVIEW

**Comment by spouliot** [comment]
Unit tests failed
> MSBuild tests - iOS (Failed) Hide

**Comment by jstedfast** [comment]
The problem is `1. Output: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/msbuild/tests/MyWebViewApp/bin/iPhoneSimulator/Debug/MyWebViewApp.app/Frameworks/Mono.framework/Mono: User interaction is not allowed.` - seems like maybe an issue on the bots? Maybe codesign can't be executed?

**Comment by spouliot** [comment]
@MSylvia can you check that our Jenkins bot can sign (like wrench) using the default Apple code signing identify on the bot ? thanks!

**Comment by rolfbjarne** [comment]
@jstedfast will this cause any dylibs to be signed as well?

**Comment by jstedfast** [comment]
Nope, we have 2 separate targets for signing dylibs vs frameworks. This will *only* sign frameworks.

**Comment by spouliot** [comment]
build

**Comment by MSylvia** [comment]
build

**Comment by jstedfast** [comment]
Same error :(

**Pull request merged**
