### PR TITLE
[generator] Use ordinal string comparison.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Test results when running the generator for XM/full:

Profile output size before: 9,4 GB
Profile output size after:  5,6 GB

Duration before: 21,5 s
Duration after:  19,0 s
Difference:     - 2,5 s = -11,6 %

Total memory usage barely changed (5kb less within a total of 1,0 GB),
but the number of method calls fell drastically:

Method calls before: 868.053.383
Method calls after:  492.325.187
Difference:        - 375.728.196 = -43,3%

The top 10 method calls also changed significantly.

Method call summary before

```
Total(ms) Self(ms)      Calls Method name
  128879    28400    3509251 Mono.Globalization.Unicode.SimpleCollator:CompareInternal (string,int,int,string,int,int,bool&,bool&,bool,bool,Mono.Globalization.Unicode.SimpleCollator/Context&)
   16074    16074   79118946 Mono.Globalization.Unicode.CodePointIndexer:ToIndex (int)
   15952    10492   26747901 Mono.Globalization.Unicode.MSCompatUnicodeTable:Category (int)
   26425    10473   26747901 Mono.Globalization.Unicode.SimpleCollator:Category (int)
   14743     8679   14952304 Mono.Globalization.Unicode.MSCompatUnicodeTable:IsIgnorable (int,byte)
   31345     8113   10413595 System.RuntimeType:GetBaseType ()
   12266     7303   12523021 Mono.Globalization.Unicode.SimpleCollator:GetContraction (string,int,int)
   20555     5812   14952304 Mono.Globalization.Unicode.SimpleCollator:IsIgnorable (int,System.Globalization.CompareOptions)
   93341     5529    2674913 System.MonoCustomAttrs:GetCustomAttributes (System.Reflection.ICustomAttributeProvider,System.Type,bool)
    8229     5337   13551378 System.RuntimeType:GetAttributeFlagsImpl ()
```

Method call summary after

```
Total(ms) Self(ms)      Calls Method name
   31646     8168   10412459 System.RuntimeType:GetBaseType ()
   94899     5672    2674880 System.MonoCustomAttrs:GetCustomAttributes (System.Reflection.ICustomAttributeProvider,System.Type,bool)
    8343     5395   13550176 System.RuntimeType:GetAttributeFlagsImpl ()
    5646     5243    2914268 (wrapper managed-to-native) System.MonoCustomAttrs:GetCustomAttributesInternal (System.Reflection.ICustomAttributeProvider,System.Type,bool)
    5147     5147    9727785 (wrapper managed-to-native) object:__icall_wrapper_ves_icall_array_new_specific (intptr,int)
   11140     4432   10948127 System.Type:get_Attributes ()
   19601     4362   10716826 System.Type:get_IsInterface ()
   15238     4344   10716826 System.RuntimeTypeHandle:IsInterface (System.RuntimeType)
    4133     4133          1 (wrapper managed-to-native) System.Threading.WaitHandle:WaitOne_internal (intptr,int)
    5922     3851    9541170 (wrapper stelemref) object:virt_stelemref_class (intptr,object)
```

### CODE REVIEW

**Comment by Therzok** [comment]
Might be worth patching up the string-key collections too?
https://github.com/xamarin/xamarin-macios/blob/master/src/generator.cs#L1562

Lots of them in generator.cs

**Comment by rolfbjarne** [comment]
@Therzok that didn't change much at all, neither for total memory usage nor total method calls.

**Comment by Therzok** [comment]
That would improve the key comparison speed on indexing (adding/getting/removing a value from the dictionary).

**Comment by spouliot** [comment]
worst timing ever - build

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
random failure (introspection/mac/unified) unrelated to commit
https://bugzilla.xamarin.com/show_bug.cgi?id=46102

**Pull request merged**
