### PR TITLE
[uikit] NSLayoutContraints fixes

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fix missing [Internal] attribute.
- Fix styling.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
for some reason the first build (yes that will trigger another one) did not complete

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
watchOS (Crashed) unrelated

**Pull request merged**
