### PR TITLE
Bump for Xcode 10.2 final

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by dalexsoto** [comment]
build

**Comment by dalexsoto** [comment]
Timed out

```
20:20:58  > git submodule update --init --recursive external/mono # timeout=60
21:20:58 ERROR: Timeout after 60 minutes
```

**Comment by dalexsoto** [comment]
Build

**Comment by dalexsoto** [comment]
This one is still going and should report back when done https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/9614/

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
The breaking changes are expected (we're following Apple, and they're not breaking changes relative to the latest stable).

**Pull request merged**
