### PR TITLE
[system-dependencies] Add CMake dependency.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This will obviously fail until the bots have cmake installed, since it's not being auto-provisioned.

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
`cmake` was installed on jenkins bots and the latest build ran fine (now to wrench...)

**Pull request merged**
