### PR TITLE
[tests] Bump sampletester hashes to pick up fixes

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-10020/1/display/redirect) (on internal Jenkins) succeeded

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-10020/1//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-10020/1//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-14.7.0.230.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/xamarin.ios-14.7.0.230.pkg)
* [Microsoft.iOS.Ref.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Ref.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Runtime.ios-arm.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Runtime.ios-arm64.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Runtime.ios-x64.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Runtime.ios-x86.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Sdk.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Sdk.14.1.100-ci.pr.gh10020.68+sha.f010c46ad.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh10020.1353+sha.f010c46ad.nupkg)
* [Microsoft.tvOS.Ref.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.tvOS.Ref.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.tvOS.Runtime.tvos-arm64.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.tvOS.Runtime.tvos-x64.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.tvOS.Sdk.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.tvOS.Sdk.14.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.watchOS.Ref.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.watchOS.Ref.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.watchOS.Runtime.watchos-arm.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.watchOS.Runtime.watchos-x86.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.watchOS.Sdk.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.watchOS.Sdk.7.0.100-ci.pr.gh10020.729+sha.f010c46ad.nupkg)
* [Microsoft.iOS.Bundle.14.1.100-ci.pr.gh10020.68.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.iOS.Bundle.14.1.100-ci.pr.gh10020.68.pkg)
* [Microsoft.macOS.Bundle.10.15.100-ci.pr.gh10020.1353.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.macOS.Bundle.10.15.100-ci.pr.gh10020.1353.pkg)
* [Microsoft.tvOS.Bundle.14.0.100-ci.pr.gh10020.729.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.tvOS.Bundle.14.0.100-ci.pr.gh10020.729.pkg)
* [Microsoft.watchOS.Bundle.7.0.100-ci.pr.gh10020.729.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.watchOS.Bundle.7.0.100-ci.pr.gh10020.729.pkg)
* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/delete-xma-build-host.pkg)
* [Microsoft.NET.Workload.iOS.14.1.100-ci.pr.gh10020.68.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.NET.Workload.iOS.14.1.100-ci.pr.gh10020.68.msi)
* [Microsoft.NET.Workload.macOS.10.15.100-ci.pr.gh10020.1353.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.NET.Workload.macOS.10.15.100-ci.pr.gh10020.1353.msi)
* [Microsoft.NET.Workload.tvOS.14.0.100-ci.pr.gh10020.729.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.NET.Workload.tvOS.14.0.100-ci.pr.gh10020.729.msi)
* [Microsoft.NET.Workload.watchOS.7.0.100-ci.pr.gh10020.729.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/package/Microsoft.NET.Workload.watchOS.7.0.100-ci.pr.gh10020.729.msi)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-10020/f010c46ad6bea8e9bf5d6e8bfb8694c07e9f389c/1/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Review by rolfbjarne — APPROVED** [review]

**Comment by spouliot** [comment]
build

**Review by dalexsoto — APPROVED** [review]

**Comment by spouliot** [comment]
Other issues are the update of Xcode location, fixed by another PR

**Comment by spouliot** [comment]
@monojenkins backport to d16-8
@monojenkins backport to d16-7

**Comment by spouliot** [comment]
@monojenkins backport to xcode12.2

**Pull request merged**
