### PR TITLE
[simlauncher] Link with the IdentityLookup framework.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This makes it possible to use types from the IdentityLookup when using
simlauncher.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@VincentDondain if we don't, and someone tries to use any of the types in the `IdentityLookup` framework, their app won't work.

**Comment by VincentDondain** [comment]
Ah yes yes, I should have expanded the GitHub code diff, I forgot what that code was for (:

**Comment by spouliot** [comment]
we need to add a test for this
or generate that list as part of the build
too easy to miss :|

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/624)

**Pull request merged**
