### PR TITLE
[linker] Simplify attribute removal code slightly.

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Merge the MobileRemoveAttributes class into CoreRemoveAttributes, since in
  this case it's just confusing to have two separate classes, since there's no
  reason to have split logic (we already have a third class to separate XM/XI logic).

* Also rename RemoveAttributes to MonoTouchRemoveAttributes to better reflect
  its usage (there's no specific XM class).

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/615)

@spouliot that wasn't a very actionable comment :smile: I agree that it would be nice to share mode code with XA, but I don't think this patch prevents that in any way. But if you think it's better to not do this change, that's of course fine with me.

**Comment by spouliot** [comment]
@rolfbjarne it was just a quick comment (neither approved or requesting changes) :)

**Comment by spouliot** [comment]
setting `don't-merge` until we have a plan in place to share the `Mobile*` parts with XA. c.c. @radekdoulik

**Comment by rolfbjarne** [comment]
Closing; this is old and needs work to complete since it has merge conflicts.

**Pull request closed without merging**
