### PR TITLE
[Harness] Generalize the BuildProjectTask

### PR DESCRIPTION
**Pull request by mandel-macaque**
Use composition to generalize the BuildProjectTask to later reuse it in
the CLI.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8299/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8299/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run' 🔥 : org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8299/1//console)
✅ Packages: 
* [xamarin.ios-13.19.0.427.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8299/e221475f6f896b01b42d42f67e3b50524a6f2078/1/package/xamarin.ios-13.19.0.427.pkg)
* [xamarin.mac-6.19.0.427.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8299/e221475f6f896b01b42d42f67e3b50524a6f2078/1/package/xamarin.mac-6.19.0.427.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/e221475f6f896b01b42d42f67e3b50524a6f2078/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/e221475f6f896b01b42d42f67e3b50524a6f2078/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/e221475f6f896b01b42d42f67e3b50524a6f2078/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Failed to publish results](https://jenkins.internalx.com/job/macios/job/PR-8299/1//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8299/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8299/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8299/2//console)
✅ Packages: 
* [xamarin.ios-13.21.0.12.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/package/xamarin.ios-13.21.0.12.pkg)
* [xamarin.mac-6.21.0.12.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/package/xamarin.mac-6.21.0.12.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/jenkins-results/api-diff/index.html)
⚠️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/jenkins-results/apicomparison/api-diff.html) (🔥 breaking changes 🔥)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8299/0ffc6c978a98475360f09442568f994281dcc074/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 184 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
</details>

**Comment by mandel-macaque** [comment]
Known issue: https://github.com/xamarin/maccore/issues/581

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8299/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8299/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: script returned exit code 128

**Pull request merged**
