### PR TITLE
[dotnet][macos] The only runtime is CoreCLR (not a feature)

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by mandel-macaque** [comment]
we are hitting some misbehaving bots that take took long to build, we are investigating https://github.com/xamarin/maccore/issues/2590

**Review by rolfbjarne — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by spouliot** [comment]
@rolfbjarne closed, right after an `/azp run`, by mistake ?

**Comment by rolfbjarne** [comment]
That was a mistake

**Comment by rolfbjarne** [comment]
I guess I just hit the wrong button :)

**Pull request merged**
