### PR TITLE
[Harness] Merge the Generator and the Factory in a same object and rename namespace.

### PR DESCRIPTION
**Pull request by mandel-macaque**
The Generator and the Factory classes are a xamarin-macios thing.
Initially, they were separated because the code that generated the bcl
tests was not inside xharness. That is not longer the case. We can merge
both classes, generalize the namespace and be more prepared to move out
of the xamarin-macios repo.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
PR is a draft because is pointing to the parent branch, remove-test-project-info. Will be a normal PR once the parent branch lands, doing this to simplify the review process.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8222/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8222/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8222/2//console)
✅ Packages: 
* [xamarin.ios-13.19.0.381.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/package/xamarin.ios-13.19.0.381.pkg)
* [xamarin.mac-6.19.0.381.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/package/xamarin.mac-6.19.0.381.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef03b1636c2ce1ace5c1d16776c17bddf0a48038/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 184 tests passed.</summary>

## Failed tests

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
</details>

**Comment by premun** [comment]
Please also rename `BCLTestProjectGeneratorTest`

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8222/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8222/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8222/3//console)
✅ Packages: 
* [xamarin.ios-13.19.0.389.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/package/xamarin.ios-13.19.0.389.pkg)
* [xamarin.mac-6.19.0.389.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/package/xamarin.mac-6.19.0.389.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-8222/ef14901e05edef648107c9ca66a13c2779f0e77e/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>6 tests failed, 179 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Debug: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * xammac tests/Mac Modern/Release: TimedOut (Execution timed out after 1200 seconds.)
 * mmptest/macOS/Debug: Failed (Execution failed with exit code 1)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>

**Comment by mandel-macaque** [comment]
@premun BCLTestProjectGenerator is specific for xamarin-macios and will not leave the project. The prefix BCL is correct because it is just used for the BCL tests.

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8222/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8222/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: There is already a newer build in progress (#5)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8222/5/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8222/5/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: script returned exit code 128

**Pull request merged**
