### PR TITLE
[Foundation] Add support to the ServerCertificateValidationCallback on the NSUrlSessionHandler

### PR DESCRIPTION
**Pull request by mandel-macaque**
This changes allows to use the service point manager callback within the
NSUrlSessionHanlder.

The logic is as follows:

1. Check that the challange is about the ssl cert.
2. Convert the SecTrust info to the managed objects.
3. Call the users cb.
4. If user returns true, continue, else, cancel and create an exception
similar to the one used in the managed code.

Fixes https://github.com/xamarin/xamarin-macios/issues/4170

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Awesome feedback! Thanks for or the concerns!

**Comment by mandel-macaque** [comment]
@baulig I don't mind you taking over the implementation, but if you are happy with it, I would not mind taking a look on how to hook it up to the new way. I used the ServicePointManager because it was mentioned in the issue, I am more than happy to be ready to the new way to do things, and the more code we reuse the better.

@spouliot I was expecting something of the kind, I created the PR to start the conversation and try to move this forward.. The only issues we have to be worried about are the current way in which we are dealing with the authentication. But this can be quite simple since we just need to check the ProtectionSpace.AuthenticationMethod and branch there. We can expose the SecTrust to the users, and then do the correct thing with the completion handler. So we can either expose a callback to the NSUrlSessionHandler (similar to what is done). But I would wait for that approach until we see what @baulig  is planning, since having a central way to do it and shared between the implementations would me a nicer approach, meaning that the users won't have to add too much custom code per implementation.

PS: I should have used a draft PR, I keep forgetting about that feature, again, I wanted to get the conversation started so that users can see that we do have planes for this.

**Comment by baulig** [comment]
Let me clarify one thing here about what is meant by "the new code".

There are two pieces to it: the code in the `System.Net.Http` and `System.Net.Http.Headers` namespace that we're switching over to the CoreFX implementation - and the actual `SocketsHttpHandler`.

All profiles will receive the former (so that we could completely nuke the `System.Net.Http` and `System.Net.Http.Headers` directories in `mcs/class/System.Net.Http`) - but you can still use the native handlers _without_ the sockets handler (which can either be removed by the linker or "physically" omitted in the first place like on web assembly).

As part of that work, I will go over all the native handlers (like `CFNetworkHandler`, `NSUrlSessionHandler` etc.) and hook up the new certificate validator.  Let's also keep in mind that the new sockets handler does not have any dependencies on the web stack anymore - so ideally, the linker should be able to completely eliminate the web stack.

In addition to what @spouliot pointed out regarding `X509Certificate2`, this is also an expensive operation if the `X509Certificate2` instance is not properly constructed from a native handle.

@mandel-macaque No worries, I have already started work on this last week, but then got distracted by build issues in the `mono-2019-02` branch (related to `Mono.Native`).  There is also a draft PR: https://github.com/mono/mono/pull/13339.

**Comment by spouliot** [comment]
Superseded by https://github.com/xamarin/xamarin-macios/pull/6103

**Pull request closed without merging**
