### PR TITLE
[msbuild] Remove stale CodeSignatures when cloning appex's into paren…

### PR DESCRIPTION
**Pull request by jstedfast**
…t app bundle (#2057)

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55676

### CODE REVIEW

**Comment by jstedfast** [comment]
Backport of https://github.com/xamarin/xamarin-macios/pull/2057 to d15.2

**Comment by spouliot** [comment]
@jstedfast my understanding is that this change would require a bump in XVS and that it is too late (without further approval) to do so. c.c. @Aguilex @AdrianMurphy and @GouriKumari

**Comment by Aguilex** [comment]
while @spouliot is right wrt to the insertion into VS2017 15.2, let's get this into our macios 15.2 branch and bump XVS. We will then ship an updated XVS through the updater channels for VS2015/2013 users. We can also make this newer XVS vsix file available to any customers who can't wait for the next insertion (i.e. 15.3)

**Comment by spouliot** [comment]
fine with me, merging :)
@emaf / @kzu please bump

**Pull request merged**
