### PR TITLE
[msbuild] Rework code signing.

### PR DESCRIPTION
**Pull request by rolfbjarne**
The main theme here is that code signing will be done in the outermost
executable project, not in any app extension projects or watch projects, nor
during the RID-specific build of a .NET universal app. This makes codesigning
easier to reason about and other affected logic (such as strip/dsymutil)
easier to handle, in particular for .NET universal apps. Another benefit is
that the differences between the iOS and macOS code bases have been
eliminated.

The first step is to collect all the information we need from the targets
files. Every app bundle (be it app extension, watch app or main app) will add
its own output app bundle (.app/.appex) to the _CodesignBundle item group.
Then every app bundle will load this informarion from referenced app bundles,
and finally store this information on disk (in the 'codesign-bundle.items'
file). This means that in the end the main app bundle will have a list of all
contained app bundles in the app (recursively), in the _CodesignBundle item
group.

Separately we keep a list of other items that need signing, in the
_CodesignItems item group, and we do the same store/load logic for every
contained/contained app bundle (in the 'codesign.items' file, so a the end the
main app bundle will have a list of all the _CodesignItems for all contained
app bundles (recursively).

The previous steps occur in the _CollectCodesigningData and
_StoreCodesigningData targets.

The next step is to use the new ComputeCodesignItems task to compute
everything we need to know for code signing. This task takes over the
responsibility for listing all the *.dylib and *.metallib files, and the
*.framework directories in the app bundles, that need signing (which was
previously done in the targets file). This logic is significantly easier to
write, debug and test in C# than MSBuild.

In addition the ComputeCodesignItems also figures out a stamp file path we use
to determine if something needs (re-)signing. Previously .framework
directories did not have a stamp location, so they'd always end up resigned in
a rebuild, while now we'll automatically skip signing *.framework directories
unless something changed in them.

I've also tried to comment everything thorougly, for the next poor soul having
to deal with any bugs.

Behavioral differences:

* We were always signing *.dylib files for macOS. We're now doing the same
  thing for all platforms.
* We're now always signing *.framework directories for all platforms (like we
  do for *.dylib files), since frameworks are pretty much like dylibs anyways.

I've verified that this works both by running the submission tests and running
and launching a sample project on device from Windows.

This PR might be easier to review commit-by-commit, because the diff turns out weird otherwise.

### CODE REVIEW

**Review by emaf — APPROVED** [review]

**Comment by emaf** [comment]
@rolfbjarne this looks good to me, but the only thing that worries me from Windows is copying empty files to the Mac. I was looking into the Codesign task and that one is not copying any files to the Mac. I think this is because at the point this is executed, all the needed files exist in the Mac and no extra files are needed (https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks/Tasks/Codesign.cs#L20).

**Review by dalexsoto — APPROVED** [review]
wow 👍

**Comment by rolfbjarne** [comment]
@emaf 

> @rolfbjarne this looks good to me, but the only thing that worries me from Windows is copying empty files to the Mac. I was looking into the Codesign task and that one is not copying any files to the Mac. I think this is because at the point this is executed, all the needed files exist in the Mac and no extra files are needed (https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks/Tasks/Codesign.cs#L20).

That's correct, everything needed for the Codesign task should already be on the mac.

Are you saying that the new `ComputeCodesignItems` should do the same thing?

**Review by mauroa — APPROVED** [review]

**Comment by emaf** [comment]
@rolfbjarne Yeah, so we make sure we don't copy any empty files from Windows.

If you implement ITaskCallback I'd also return false for `ShouldCreateOutputFile` so we don't create output files in Windows, since this new task is not really changing any of the files, but computing what needs to be signed, right?

**Comment by rolfbjarne** [comment]
> If you implement ITaskCallback I'd also return false for `ShouldCreateOutputFile` so we don't create output files in Windows, since this new task is not really changing any of the files, but computing what needs to be signed, right?

Correct, this new task is not creating or changing any files, it's just computing stuff.

**Comment by suihanhbr** [comment]
I got this error when I build my project today.
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error MSB4018: The "ComputeCodesignItems" task failed unexpectedly.
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
  at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x00073] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:1626 
  at System.String.Substring (System.Int32 startIndex) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:1592 
  at Xamarin.MacDev.Tasks.ComputeCodesignItemsTaskBase.Execute () [0x00249] in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeCodesignItemsTaskBase.cs:107 
  at Xamarin.MacDev.Tasks.ComputeCodesignItems.Execute () [0x0002a] in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeCodesignItems.cs:15 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:578 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:807  (MSB4018) (SuiHanIME.iOS)
```

**Comment by chamons** [comment]
@suihanhbr - Please [file and issue](https://github.com/xamarin/xamarin-macios/issues/new) with steps to reproduce/sample so we can look into this.

A stack trace in a PR comment thread is insufficient for us to track down any potential bug.

**Pull request merged**
