### PR TITLE
Merge remote-tracking branch 'origin/master' into xcode8

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
msbuild failure started wth @jstedfast https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=1381&host_id=243&revision_id=777582

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
