### PR TITLE
Changes to build in VSTS

### PR DESCRIPTION
**Pull request by joewstroman**
VSTS doesn't really support multiple checkouts, so I thought it would be easiest to add the package targets and other build scripts here (instead of release-scripts). Also VSTS doesn't allow the use of sudo, so I copied the system-dependencies file. It seemed like less of a hassle.

### CODE REVIEW

**Comment by spouliot** [comment]
@joewstroman we have limited bots capacity. Please make sure it builds locally before doing PR. Thanks!

**Comment by joewstroman** [comment]
I'm not sure why this failed. It hangs for 20 minutes while running tests, but none of these changes touch any xamarin.mac or xamarin.ios code.

**Comment by rolfbjarne** [comment]
The changes to system-dependencies.sh are fine, but I don't understand why you can't just clone release-scripts manually executing "git clone ..." in VSTS? Copied files always end up stale one day.

**Comment by joewstroman** [comment]
I saw that the Jenkins PR's use that script, so I assumed that's the way it should continue happening. I can clone release-scripts, but I believe we're moving away from that repo for VSTS? @duncanmak ?

**Pull request closed without merging**
