### PR TITLE
[arkit] Update to Xcode 10 beta 2

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by VincentDondain** [comment]
Known issue, XML is empty/invalid -> xamarin/maccore#827

**Comment by VincentDondain** [comment]
Breaking change warning:

```
Type Changed: ARKit.ARReferenceImage

Removed interface:

	Foundation.INSCopying
Removed method:

	public virtual Foundation.NSObject Copy (Foundation.NSZone zone);
```

**Comment by spouliot** [comment]
`ARReferenceImage` is not new in Xcode 10 so it's a breaking change
Might be a mistake from Apple since intro did not complain (so it does conform)

**Comment by VincentDondain** [comment]
@spouliot yea just realized it's an actual breaking change. So //radar?

**Comment by spouliot** [comment]
@VincentDondain yes :)

**Comment by VincentDondain** [comment]
Radar: https://trello.com/c/F7bjcplW

Closing this PR hoping they revisit the protocol conformance. Note: I also added the radar to https://github.com/xamarin/xamarin-macios/issues/4189.

**Pull request closed without merging**
