### PR TITLE
[tests] Use the local .NET for running unit tests.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This hopefully solves a few problems on M1, where we'd want to execute with
.NET 5 (last stable .NET release), but that version only supports x86_64, and
then if an ARM64 version of .NET 6 was also installed, things would break in
mysterious ways.

This way we have full control over what happens, and also a consistent
environment across all machines.

### CODE REVIEW

**Review by chamons — CHANGES_REQUESTED** [review]
I think you need to bump [this](https://github.com/xamarin/xamarin-macios/blob/main/tests/dotnet/UnitTests/DotNetUnitTests.csproj#L3) to net6.0 for this to work. 

Without it I got:

```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.1 at [/Users/donblas/Programming/xamarin-macios/builds/downloads/dotnet-sdk-6.0.200-preview.22063.5-osx-x64/shared/Microsoft.NETCore.App]
```

When I tried this locally.

**Comment by spouliot** [comment]
> .NET 5 (last stable .NET release)

@rolfbjarne The latest stable should be 6 (not 5) now right ? If so is there any reason why net5 should be used anywhere ?

I'm using this locally (not quite ok for `arch` on x86-64 systems) so `dotnet` commands runs as `Apple` and not `Intel` while building on M1. That makes my builds a bit faster - but `mono-sgen64` is still an x86_64 process 😢 

```diff
diff --git a/builds/Makefile b/builds/Makefile
index 781bb5491..4f0449dde 100644
--- a/builds/Makefile
+++ b/builds/Makefile
@@ -74,7 +74,7 @@ downloads/%: downloads/%.nupkg

 downloads/$(basename $(basename $(DOTNET6_TARBALL_NAME))): dotnet-install.sh
        $(Q) echo "Downloading and installing .NET $(DOTNET6_VERSION) into $@..."
-       $(Q) ./dotnet-install.sh --install-dir "$@.tmp" --version "$(DOTNET6_VERSION)" --architecture x64 --no-path $$DOTNET_INSTALL_EXTRA_ARGS
+       $(Q) ./dotnet-install.sh --install-dir "$@.tmp" --version "$(DOTNET6_VERSION)" --architecture `arch` --no-path $$DOTNET_INSTALL_EXTRA_ARGS
        $(Q) rm -Rf "$@"
        $(Q) mv "$@.tmp" "$@"
        $(Q) echo "Downloaded and installed .NET $(DOTNET6_VERSION) into $@."
diff --git a/global.json b/global.json
index f40f4903a..e52d340bc 100644
--- a/global.json
+++ b/global.json
@@ -1,5 +1,5 @@
 {
   "sdk": {
-    "version": "5.0.200"
+    "version": "6.0.101"
   }
 }
diff --git a/system-dependencies.sh b/system-dependencies.sh
index 1193f6d0f..f996f18c7 100755
--- a/system-dependencies.sh
+++ b/system-dependencies.sh
@@ -1024,11 +1024,16 @@ function check_dotnet ()
        DOTNET_VERSION=$(grep "^DOTNET_VERSION=" dotnet.config | sed 's/.*=//')
        URL=https://dotnetcli.azureedge.net/dotnet/Sdk/"$DOTNET_VERSION"/dotnet-sdk-"$DOTNET_VERSION"-osx-x64.pkg
        INSTALL_DIR=/usr/local/share/dotnet/sdk/"$DOTNET_VERSION"
+       INSTALL_X64_DIR=/usr/local/share/dotnet/x64/sdk/"$DOTNET_VERSION"

        if test -d "$INSTALL_DIR"; then
                ok "Found dotnet $DOTNET_VERSION in $INSTALL_DIR (exactly $DOTNET_VERSION is required)."
                return
        fi
+       if test -d "$INSTALL_X64_DIR"; then
+               ok "Found dotnet (x64) $DOTNET_VERSION in $INSTALL_X64_DIR (exactly $DOTNET_VERSION is required)."
+               return
+       fi
        if test -z "$PROVISION_DOTNET"; then
                fail "You must install dotnet $DOTNET_VERSION. You can download it from ${COLOR_BLUE}$URL${COLOR_RESET}."
                fail "Alternatively you can ${COLOR_MAGENTA}export IGNORE_DOTNET=1${COLOR_RED} to skip this check."
@@ -1072,6 +1077,7 @@ check_dotnet ""
 if test -z "$IGNORE_DOTNET"; then
        ok "Installed .NET SDKs:"
        (IFS=$'\n'; for i in $(/usr/local/share/dotnet/dotnet --list-sdks); do log "$i"; done)
+       (IFS=$'\n'; for i in $(/usr/local/share/dotnet/x64/dotnet --list-sdks); do log "$i"; done)
 fi

 if test -z $FAIL; then
```

**Comment by rolfbjarne** [comment]
> @rolfbjarne The latest stable should be 6 (not 5) now right ?

Correct, my head hasn't quite caught up yet.

> If so is there any reason why net5 should be used anywhere ?

No, none.

**Review by tj-devel709 — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@chamons we need your +1

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Red test is unrelated (https://github.com/xamarin/maccore/issues/2451).

**Review by chamons — APPROVED** [review]

**Pull request merged**
