### PR TITLE
[gamekit] Update for iOS 10 beta 2

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by spouliot** [comment]
LGTM, check test results and, if all green, merge!

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by VincentDondain** [comment]
Weird `introspection-mac` fail. I did not and still don't see that locally...

```
***** ApiSelectorTest.InstanceMethods
[FAIL] Selector not found for ModelIO.MDLTransform : copyWithZone:
[FAIL] Selector not found for NetworkExtension.NWEndpoint : copyWithZone:
[FAIL] Selector not found for NetworkExtension.NWEndpoint : encodeWithCoder:
[FAIL] Selector not found for Contacts.CNContactFetchRequest : encodeWithCoder:
[FAIL] Selector not found for GameplayKit.GKBehavior : copyWithZone:
[FAIL] Selector not found for GameplayKit.GKEntity : encodeWithCoder:
[FAIL] Selector not found for GameplayKit.GKPolygonObstacle : encodeWithCoder:
[FAIL] Selector not found for GameplayKit.GKComponent : encodeWithCoder:
[FAIL] Selector not found for GameplayKit.GKGraph : copyWithZone:
[FAIL] Selector not found for GameplayKit.GKGraph : encodeWithCoder:
[FAIL] Selector not found for GameplayKit.GKGraphNode : encodeWithCoder:
```

**Comment by spouliot** [comment]
@VincentDondain are you running on macOS 10.12 ?

If so it's normal since the conformance was added in this version. However the bots runs on 10.11 and you'll have to adjust the tests to deal with this (there are several example, grep for the selectors).

**Comment by spouliot** [comment]
nm, it's due to @chamons earlier commit - which you likely don't have pulled. all good :)

**Pull request merged**
