### PR TITLE
[main] Updated Xamarin.Messaging to 1.9.59

### PR DESCRIPTION
**Pull request by mauroa**
Includes latest fixes like support for retry and reconnect, new telemetry, bug fixing, etc.

Also added Merq.Core.dll to dotnet/Workloads/SignList.xml because now it comes as part of Xamarin.Messaging

### CODE REVIEW

**Comment by mauroa** [comment]
@dalexsoto @rolfbjarne this is the bump that we need for 17.6 Preview 2. I did the backport for xcode14.2 and release/7.0.2xx.

**Comment by mauroa** [comment]
Backports:

https://github.com/xamarin/xamarin-macios/pull/17647

https://github.com/xamarin/xamarin-macios/pull/17648

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2138).

**Pull request merged**
