### PR TITLE
Bump to mono/2018-04

### PR DESCRIPTION
**Pull request by luhenry**
This cannot land before dev15.8 is branched

### CODE REVIEW

**Comment by rolfbjarne** [comment]
The build hung (https://github.com/xamarin/maccore/issues/762)

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
I've looked at the device tests, and they're fine, no failures that I haven't seen already (or that aren't also happening in the test run on Jenkins).

**Comment by alexischr** [comment]
@marek-safar 
```
/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs(806,10): error CS0103: The name 'TypeNameParser' does not exist in the current context
```

Looks like `TypeNameParser` is not in any reference assemblies

**Comment by alexischr** [comment]
Nevermind, that was a reference to a new linker type, not a corlib type. Fixed with https://github.com/xamarin/xamarin-macios/pull/3856/commits/5b1482e3921e9df828dedac03bfd05997e66863f

**Comment by rolfbjarne** [comment]
I've added the `skip-api-comparison` label since it won't work in this PR (due to internal API break between the BCL and product assemblies causing build failures).

**Comment by alexischr** [comment]
Remaining test failures are due to https://github.com/xamarin/maccore/issues/647

**Comment by marek-safar** [comment]
@spouliot @rolfbjarne please review and let me know if there is anything else to be done from our side

**Comment by rolfbjarne** [comment]
I'll have a look at the device tests tomorrow.

**Comment by rolfbjarne** [comment]
Device tests:

* All the interpreter tests crashed, for both mini and monotouch-test. Example stack trace ([crash-report](https://gist.github.com/rolfbjarne/0b4c776b0fd269559e1033322bf58304)):

```
* Assertion at ../../../../../mono/mini/aot-runtime.c:5270, condition `amodule' not met

0   monotouchtest                       0x000000010016531c mono_handle_native_crash + 224
1   libsystem_platform.dylib            0x000000018245931c _sigtramp + 52
2   libsystem_pthread.dylib             0x000000018245f264 pthread_kill + 112
3   libsystem_c.dylib                   0x00000001823099c4 abort + 140
4   monotouchtest                       0x000000010028283c mono_log_write_asl + 192
5   monotouchtest                       0x00000001002929b8 monoeg_g_logv + 100
6   monotouchtest                       0x0000000100292bcc monoeg_assertion_message + 72
7   monotouchtest                       0x0000000100138984 mono_aot_create_specific_trampoline + 0
8   monotouchtest                       0x0000000100161e6c mono_exceptions_init + 40
9   monotouchtest                       0x0000000100172208 mini_init + 1148
10  monotouchtest                       0x00000001002ad440 xamarin_main + 1828
11  monotouchtest                       0x000000010011231c main + 96
12  libdyld.dylib                       0x000000018228559c <redacted> + 4
```

* System
    * `[FAIL] HttpListenerRequestTest.HttpRequestIsLocal : System.Net.Sockets.SocketException : Connection timed out`: This is a consistent test failure, causing all variants of the System tests to fail.
    * `[FAIL] UdpClientTest.JoinMulticastGroup3_IPv4 : System.Net.Sockets.SocketException : Not enough buffer space is available`
    * `[FAIL] UdpClientTest.JoinMulticastGroupWithLocal : System.Net.Sockets.SocketException : Not enough buffer space is available`: These two are random (happened once), but I've also seen them before (with master), so this is not a new failure (it would still be nice to get it fixed :smile:)

**Comment by marek-safar** [comment]
@rolfbjarne thanks for the report. I'll try to see if we can get UdpClientTest issues resolved in next integration.

@lewurm could you please investigate the interpreter issues ASAP.

**Comment by spouliot** [comment]
The two watchOS failures are due to invalid XML -> https://github.com/xamarin/maccore/issues/827 (PR to fix this in progress)

**Pull request merged**
