### PR TITLE
Remove the tvos cross compiler, use the normal ios cross compiler ins…

### PR DESCRIPTION
**Pull request by vargaz**
…tead, they are the same.

### CODE REVIEW

**Comment by spouliot** [comment]
we'll need to re-run this with the labels applied (then remove the do-not-merge tag)

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
fail due to disk space, RE should be _liberated_ a few older Xcode so the time should be good...

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* mscorlib/iOS 32bit: [iOS 32-bit sim: TimeZoneTest.TestCtors (D02) fails](https://github.com/xamarin/maccore/issues/629)
* MTouch tests: [MTouch tests: Xamarin.MTouch.RebuildTest_WithExtensions failure](https://github.com/xamarin/maccore/issues/641)

**Pull request merged**
