### PR TITLE
Bump mono to 5.10.99 (same as VSMac)

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by spouliot** [comment]
no, that will be done once we bump/merge 2017-12
you can still use this locally to report issues - but we need consistent results from the bots
Not closing right now (bots have started so we can at least see what they have to say, if anything)

**Comment by VincentDondain** [comment]
Ah sorry, I was pretty sure there was a comment in the code asking to commit the bump if it worked locally (couldn't find that anymore so maybe I dreamed).

**Comment by spouliot** [comment]
iirc that message was for the VS4M requirement, since it's not much used for building what we ship (maybe T4 ?)

**Comment by rolfbjarne** [comment]
This message: https://github.com/xamarin/xamarin-macios/blob/6d73e7634b7fb6670fba9fecf07884496a9fce47/system-dependencies.sh#L438-L441

At the time that was written I thought it would be fine to bump master to any mono hash (as long as it worked locally for someone), but we've later learnt that it can be tricky and confusing when things start failing apparently randomly due to different mono versions installed.

**Comment by VincentDondain** [comment]
Aaaaaaaah I knew I wasn't crazy, couldn't find that message anymore, I didn't do a full grep I was sure it was a comment in Make.config.

@rolfbjarne let's update it then, otherwise you won't be able to tell me I'm wrong (;

**Pull request closed without merging**
