### PR TITLE
Update API diff references with xcode92 data

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
The above `build` is to check bots results, since other PR have weird results running all tests

**Comment by spouliot** [comment]
All platforms/config failed with `MonoTests.System.IO.Compression.FileSystem.ZipArchiveTests.ZipCreateFromEntryChangeTimestamp: Expected: 13 But was: 14` which is unrelated to this PR - and different from the mono bump PR.

@mandel-macaque ^ ever got this one ?

**Comment by mandel-macaque** [comment]
@spouliot that is new to me, let me take a look at the output and the test itself

**Pull request merged**
