### PR TITLE
[d16-7] Rename master to main.

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Fix links that point to master to point to main instead.
* Implement support in the sample tester for specifying the default branch for
  each sample repo.
* Fix various text / documentation to say 'main' instead of 'master.'
* Push to 'main' instead of 'master' in xamarin-macios-data.
* Fix xharness to make 'main' the special branch with regards to documentation tests as opposed to 'master'.
* Fix various CI to use 'main' instead of 'master'.

This is a backport of PR #8851.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9561/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9561/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Install Provisioning Profiles' 🔥 : hudson.AbortException: script returned exit code 104

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9561/1//console)
✅ Packages: 
* [xamarin.ios-13.20.2.4.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9561/1c7cc579d170f672e77955e71a53f1df83723bad/1/package/xamarin.ios-13.20.2.4.pkg)
* [xamarin.mac-6.20.2.4.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9561/1c7cc579d170f672e77955e71a53f1df83723bad/1/package/xamarin.mac-6.20.2.4.pkg)

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9561/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9561/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9561/2//console)
✅ Packages: 
* [xamarin.ios-13.20.2.6.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/package/xamarin.ios-13.20.2.6.pkg)
* [xamarin.mac-6.20.2.6.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/package/xamarin.mac-6.20.2.6.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-9561/ab77e4bf501fc8f06ff7724ea3f1879807785861/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>6 tests failed, 179 tests passed.</summary>

## Failed tests

 * mscorlib/Mac Full/Debug: Failed (Test run failed.)
 * mscorlib/Mac Modern/Debug: Failed (Test run failed.)
 * mscorlib Part 2/iOS Unified 32-bits - simulator/Debug: Failed
 * mscorlib Part 2/iOS Unified 64-bits - simulator/Debug: Failed
 * mscorlib Part 2/tvOS - simulator/Debug: Failed
 * mscorlib Part 2/watchOS 32-bits - simulator/Debug: Failed
</details>

**Comment by rolfbjarne** [comment]
Test failures are all unrelated (all due to https://github.com/xamarin/maccore/issues/2296).

**Comment by rolfbjarne** [comment]
@spouliot 

> I'm guessing #9557 needs to go in first ?

Yes, I merged d16-7 into this PR after #9557 went in, and everything is green now.

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-7-xcode11.7

**Comment by dalexsoto** [comment]
@monojenkins backport xcode12

**Pull request merged**
