### PR TITLE
[ARKit] Fix compiler error.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This fails on my mono, and the code looks wrong, so I'm not sure how it compiles anywhere.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failures are unrelated:

* linkall/watchOS: bug #[55719](https://bugzilla.xamarin.com/show_bug.cgi?id=55719)
* monotouch-test/watchOS: bug #[57762](https://bugzilla.xamarin.com/show_bug.cgi?id=57762)

**Comment by rolfbjarne** [comment]
I use mono 5.2.0.189, and the bots use 5.2.0.90, so the bug has been fixed (i.e. no need for a bug report afaict).

**Comment by VincentDondain** [comment]
@rolfbjarne I completely missed this PR (independence day).

1. I do not get any error if I don't have `unsafe` with Mono 5.2.0.220. 
2. "and the code looks wrong" > can you explain? I don't think there's a bug assigned to me to fix it (:

**Comment by rolfbjarne** [comment]
@VincentDondain yeah, it's an mcs bug (mcs should show an error, but doesn't/didn't). And it's already fixed, so no need for a bug :smile:

**Pull request merged**
