### PR TITLE
[appkit/uikit] Add NSAttributedString Xcode 9 fields

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by dalexsoto** [comment]
Maybe you want to add these new keys to this StrongDictionary

`xamarin-macios/src/AppKit/NSStringAttributes.cs`

**Comment by VincentDondain** [comment]
@dalexsoto (and others) not sure if I should add the new keys to the Strong Dictionary in:

`src/AppKit/NSStringAttributes.cs` and `src/UIKit/UIStringAttributes.cs` (let's not forget about iOS).

or

`src/Foundation/NSAttributedString.mac.cs` and `src/Foundation/NSAttributedString.iOS.cs`.

Pretty confusing.

**Comment by VincentDondain** [comment]
Before addressing Alex's request and merge this, let figure out https://bugzilla.xamarin.com/show_bug.cgi?id=59317.
Those are not critical fields to be added.

**Comment by VincentDondain** [comment]
Closing this PR as it's now outdated and required a much larger code cleanup effort.

_Note: those particular fields have not been requested by customers._

**Pull request closed without merging**
