### PR TITLE
Bump for Xcode 11.2 beta 2

### PR DESCRIPTION
**Pull request by VincentDondain**
- Ignore `CreateReadyWithPacketDescriptions` test because 
```
figAudioSampleBufferCreateWithPacketDescriptionsCallbackOrHandler signalled err=-12731
```
Filed [issue](https://github.com/xamarin/maccore/issues/2023) for it

### CODE REVIEW

**Comment by VincentDondain** [comment]
FYI `AVAudioRecorder` also fails on device (:

**Comment by VincentDondain** [comment]
6 known [BCL tests issues](https://github.com/xamarin/maccore/issues/2021) + 1 [HE0038](https://github.com/xamarin/maccore/issues/581)

However monotouch-test static registrar issue might be legit. @rolfbjarne have you seen that during monitoring?

**Comment by rolfbjarne** [comment]
> However monotouch-test static registrar issue might be legit. 

Yes, it's a block-related crash: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/11558/Test_20Report/monotouch-test/202/stdout-20191011_222558.log

> @rolfbjarne have you seen that during monitoring?

I haven't seen anything like it though, so it could be that Apple changed something in Xcode 11.2 that's causing things to fail. My guess would be that it's not directly related to the static registrar, but that it's a random issue that just happened to hit that particular test run. Can you repro locally (try running all the monotouch-test simulator tests)?

**Comment by VincentDondain** [comment]
Yes I can reproduce that locally https://gist.github.com/VincentDondain/c00c44cb2585dda249c477f7875b376e

**Comment by mandel-macaque** [comment]
The ignored test is not the culprit, that test had those message already, sample successful  build can be found here: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/11542/Test_20Report/ from https://github.com/xamarin/xamarin-macios/pull/7196

**Comment by VincentDondain** [comment]
Yea, I updated the issue https://github.com/xamarin/maccore/issues/2023, will re-enable the test when I find something to ignore that fixed monotouch-test

**Comment by VincentDondain** [comment]
So this looks like a random failure, I'm getting the tests to work, it also sounds like this might not be related to Xcode 11.2 beta 2

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
The test if fixed here: https://github.com/xamarin/xamarin-macios/pull/7214 nothing to do with the Xcode bump.

**Comment by VincentDondain** [comment]
Merging since the 8th issue: https://github.com/xamarin/maccore/issues/2023 is fixed in an other PR.

**Pull request merged**
