### PR TITLE
[dotnet] Package the workloads in a Windows installer (.msi) as well.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Create, upload and publish a Windows installer (.msi) for each workload.

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
👏

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
I have to upload msi files now?? /me needs to pay a vacation to @rolfbjarne

**Comment by rolfbjarne** [comment]
> I have to upload msi files now?? /me needs to pay a vacation to @rolfbjarne

:smile:

These are just temporary until more pieces are in place, we'll eventually stop creating MSIs (I hope...)

**Review by tj-devel709 — APPROVED** [review]

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9979/3/display/redirect) (on internal Jenkins) succeeded

✅ [Provisioning succeeded](https://jenkins.internalx.com/job/macios/job/PR-9979/3//console)
✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9979/3//console)
✅ Packages built successfully
<details><summary>View packages</summary>

* [xamarin.ios-14.7.0.191.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/xamarin.ios-14.7.0.191.pkg)
* [Microsoft.iOS.Ref.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Ref.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Runtime.ios-arm.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Runtime.ios-arm64.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.iOS.Runtime.ios-x64.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Runtime.ios-x64.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.iOS.Runtime.ios-x86.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Runtime.ios-x86.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.iOS.Sdk.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Sdk.14.1.100-ci.pr.gh9979.29+sha.52762bd03.nupkg)
* [Microsoft.macOS.Ref.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.macOS.Ref.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.macOS.Runtime.osx-x64.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg)
* [Microsoft.macOS.Sdk.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.macOS.Sdk.10.15.100-ci.pr.gh9979.1314+sha.52762bd03.nupkg)
* [Microsoft.tvOS.Ref.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.tvOS.Ref.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.tvOS.Runtime.tvos-arm64.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.tvOS.Runtime.tvos-x64.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.tvOS.Runtime.tvos-x64.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.tvOS.Sdk.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.tvOS.Sdk.14.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.watchOS.Ref.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.watchOS.Ref.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.watchOS.Runtime.watchos-arm.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.watchOS.Runtime.watchos-arm.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.watchOS.Runtime.watchos-x86.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.watchOS.Runtime.watchos-x86.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.watchOS.Sdk.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.watchOS.Sdk.7.0.100-ci.pr.gh9979.690+sha.52762bd03.nupkg)
* [Microsoft.iOS.Bundle.14.1.100-ci.pr.gh9979.29.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.iOS.Bundle.14.1.100-ci.pr.gh9979.29.pkg)
* [Microsoft.macOS.Bundle.10.15.100-ci.pr.gh9979.1314.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.macOS.Bundle.10.15.100-ci.pr.gh9979.1314.pkg)
* [Microsoft.tvOS.Bundle.14.0.100-ci.pr.gh9979.690.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.tvOS.Bundle.14.0.100-ci.pr.gh9979.690.pkg)
* [Microsoft.watchOS.Bundle.7.0.100-ci.pr.gh9979.690.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.watchOS.Bundle.7.0.100-ci.pr.gh9979.690.pkg)
* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/delete-xma-build-host.pkg)
* [Microsoft.NET.Workload.iOS.14.1.100-ci.pr.gh9979.29.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.NET.Workload.iOS.14.1.100-ci.pr.gh9979.29.msi)
* [Microsoft.NET.Workload.macOS.10.15.100-ci.pr.gh9979.1314.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.NET.Workload.macOS.10.15.100-ci.pr.gh9979.1314.msi)
* [Microsoft.NET.Workload.tvOS.14.0.100-ci.pr.gh9979.690.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.NET.Workload.tvOS.14.0.100-ci.pr.gh9979.690.msi)
* [Microsoft.NET.Workload.watchOS.7.0.100-ci.pr.gh9979.690.msi](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/package/Microsoft.NET.Workload.watchOS.7.0.100-ci.pr.gh9979.690.msi)

</details>

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-9979/52762bd0397b0440d49a1fbc5464193c4395dfe4/3/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Pull request merged**
