### PR TITLE
[d16-5-xcode11.4] Sample tester needs Catalina pool

### PR DESCRIPTION
**Pull request by dalexsoto**
Xcode 11.4 needs Catalina

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8115/1/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8115/1//console)
✅ Packages: 
* [xamarin.ios-13.16.0.1.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/7acb4710a8c86a6dc1345f46893e6a9b0df57721/1/package/xamarin.ios-13.16.0.1.pkg)
* [xamarin.mac-6.16.0.1.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/7acb4710a8c86a6dc1345f46893e6a9b0df57721/1/package/xamarin.mac-6.16.0.1.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/7acb4710a8c86a6dc1345f46893e6a9b0df57721/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/7acb4710a8c86a6dc1345f46893e6a9b0df57721/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/7acb4710a8c86a6dc1345f46893e6a9b0df57721/1/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8115/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8115/2//console)
✅ Packages: 
* [xamarin.ios-13.16.0.1.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/9f3357758d1392e3f177e41b50f62491dcf00543/2/package/xamarin.ios-13.16.0.1.pkg)
* [xamarin.mac-6.16.0.1.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/9f3357758d1392e3f177e41b50f62491dcf00543/2/package/xamarin.mac-6.16.0.1.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/9f3357758d1392e3f177e41b50f62491dcf00543/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/9f3357758d1392e3f177e41b50f62491dcf00543/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/9f3357758d1392e3f177e41b50f62491dcf00543/2/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by dalexsoto** [comment]
Not yet, will look into those later today

**Comment by dalexsoto** [comment]
From a quick glance most (if not all) errors look like this

```
1) Failed : Samples.MacIosSampleTester.BuildSample(ExceptionMarshaling.IOS: Debug|iPhone)
  build failed (unexpected exit code)
	[Summary of errors from the build output below]
	03:39:39.0600100: lipo : error : sh -c '/Applications/Xcode114-beta3.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode114-beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find lipo 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory) [/Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/bin/Debug/repositories/mac-ios-samples/ExceptionMarshaling/iOS/ExceptionMarshaling.IOS.csproj]
	03:39:39.3123950: MTOUCH : error MT5306: Failed to create the a fat library. Please review the build log. [/Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/bin/Debug/repositories/mac-ios-samples/ExceptionMarshaling/iOS/ExceptionMarshaling.IOS.csproj]
	03:39:40.9850780:   lipo : error : sh -c '/Applications/Xcode114-beta3.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode114-beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find lipo 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory) [/Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/bin/Debug/repositories/mac-ios-samples/ExceptionMarshaling/iOS/ExceptionMarshaling.IOS.csproj]
	03:39:40.9851120:   MTOUCH : error MT5306: Failed to create the a fat library. Please review the build log. [/Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/bin/Debug/repositories/mac-ios-samples/ExceptionMarshaling/iOS/ExceptionMarshaling.IOS.csproj]
  Expected: 0
  But was:  1
  at ProcessHelper.AssertRunProcess (System.String filename, System.String[] arguments, System.TimeSpan timeout, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] environment_variables, System.String message, System.String& logfile) [0x001ee] in /Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/ProcessHelper.cs:75 
  at ProcessHelper.BuildSolution (System.String solution, System.String platform, System.String configuration, System.Collections.Generic.Dictionary`2[TKey,TValue] environment_variables, System.TimeSpan timeout, System.String target, System.String codesignKey) [0x0020a] in /Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/ProcessHelper.cs:121 
  at Samples.SampleTester.BuildSample (Samples.SampleTestData sampleTestData) [0x003ce] in /Users/runner/runners/2.165.2/work/1/s/xamarin-macios/tests/sampletester/SampleTester.cs:177 
```

Will have a deeper look on what is going on

**Comment by spouliot** [comment]
@rolfbjarne is the error pasted by @dalexsoto the same one you recently investigated (and fixed) for appcenter ? (the situation does look a bit similar too)

**Comment by rolfbjarne** [comment]
@spouliot looks similar, in which case #8121 should fix it.

**Comment by dalexsoto** [comment]
Yup will wait for https://github.com/xamarin/xamarin-macios/pull/8121 to go in and then bring that to his branch and see how it goes

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8115/3/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8115/3//console)
✅ Packages: 
* [xamarin.ios-13.16.0.2.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/e9a0741736bc04daf3c153069fdabb85aa1b1272/3/package/xamarin.ios-13.16.0.2.pkg)
* [xamarin.mac-6.16.0.2.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8115/e9a0741736bc04daf3c153069fdabb85aa1b1272/3/package/xamarin.mac-6.16.0.2.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/e9a0741736bc04daf3c153069fdabb85aa1b1272/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/e9a0741736bc04daf3c153069fdabb85aa1b1272/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8115/e9a0741736bc04daf3c153069fdabb85aa1b1272/3/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by dalexsoto** [comment]
Error unrelated to the PR changes and we already have a full green build of the same changes on https://github.com/xamarin/xamarin-macios/pull/8128#commitcomment-37893290

> We stopped hearing from agent Azure Pipelines 48. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610 

The error on https://github.com/xamarin/xamarin-macios/pull/8115/checks?check_run_id=516908815 looks like a network related one.

**Pull request merged**
