### PR TITLE
[mtouch] Allow code sharing assemblies from multiple locations if they're identical. Fixes #56513.

### PR DESCRIPTION
**Pull request by rolfbjarne**
We disallow code sharing when the same assembly (based on name) is referenced
from multiple paths, but poke a hole in this logic by allowing the same
assembly from multiple paths when those assemblies are 100% identical, since
that should be 100% safe.

https://bugzilla.xamarin.com/show_bug.cgi?id=56513

### CODE REVIEW

**Comment by rolfbjarne** [comment]
build

**Comment by zippo227** [comment]
I tried building a project using this branch and it failed with can't lipo directories. I've pulled from master into this branch and am testing now to see if it fixes the issue.

**Comment by zippo227** [comment]
I'm getting the cannot lipo directories because of the crashlytics framework error.

**Comment by zippo227** [comment]
I'm deleting my earlier comments because I was wrong. Sorry for the false information. The MessagesCodeSharing branch compiles perfectly when using my test project: https://github.com/zippo227/ios-samples/tree/master/ios10/MessageCodeSharing   with my https://github.com/zippo227/xamarin-macios/tree/bug56498 which has the latest master merged into the @rolfbjarne  branch bug56498 .

**Comment by rolfbjarne** [comment]
build

**Pull request merged**
