### PR TITLE
[CI] The DropsPAT was removed, change it to a new one.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Review by mjbond-msft — APPROVED** [review]
👍

**Review by rolfbjarne — APPROVED** [review]

**Review by haritha-mohan — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by rolfbjarne** [comment]
The test failures are unrelated, the only important part is that the windows integration passed (which it did: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7380927&view=logs&s=eaa41d3e-3292-5e1c-f4d9-86fcc0d36c2b).

**Pull request merged**
