### PR TITLE
[main][watchOS] Add x86_64 simulator support

### PR DESCRIPTION
**Pull request by dalexsoto**
* Bumps mono binaries to include x86_64 watchOS support
* Build runtime/registrar x86_64 slices
* Produce a 64 bit version of Xamarin.WatchOS.dll
* Allow building x86_64 for watch simulators in mtouch
* Let xharness know about x86_64

New commits in mono/mono:

* mono/mono@ac596375c76 Add support for OP_FCONV_TO_I to mini-arm64.c. (#20548)
* mono/mono@392fe5b87b2 [2020-02][watchOS] Add simwatch64 support (#20552)
* mono/mono@a22ed3f094e Fix potential crash for Encoder.Convert (#20522)
* mono/mono@970783731fc Bump to F# 5.0 (#20511)
* mono/mono@32ab5066f72 Bump msbuild to fix a build issue
* mono/mono@93a7fe77e8e Ensure special static slots respect alignment. (#20506)
* mono/mono@3db5b358413 [debugger] Switch to GC Unsafe in signal handler callbacks (#20495)
* mono/mono@af315f44c40 [2020-02][corlib] ThreadAbortException protection for ArraySortHelper (#20468)

Diff: https://github.com/mono/mono/compare/ca11fb0fd819a1e32565b0d626506f66fb9fd272..ac596375c762c6b8dbe3c802f0ce626004eab51c

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by dalexsoto** [comment]
build

**Review by rolfbjarne — APPROVED** [review]
This looks great! It also looks like mtouch didn't need many changes to support fat watch simulator apps!

**Comment by rolfbjarne** [comment]
> Native linking failed, undefined Objective-C class: FrameworkTest. The symbol '_OBJC_CLASS_$_FrameworkTest' could not be found in any of the libraries or frameworks linked with your application.

This is because you have to add a x86_64 build of our test libraries in tests/test-libraries

**Review by tj-devel709 — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

**Comment by rolfbjarne** [comment]
build

**Comment by dalexsoto** [comment]
build

**Comment by dalexsoto** [comment]
Fake green aka gred 🤥 

⚠️ Build test/test-libraries failed ⚠️

**Comment by dalexsoto** [comment]
Fake green aka gred 🤥 

⚠️ [Build test/test-libraries failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15808/Test_20Report/build-test-libraries.log) ⚠️

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
@dalexsoto it seems that merging `main` disabled the watch simulator tests again, which is why the PR turned greenish.

**Pull request merged**
