### PR TITLE
[xcode14] Bump to beta 4

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
@mandel-macaque something funny is going on on CI this class is bound in @chamons Foundation PR but is not here in the bump PR and xtro is complaining about it and I can't get it to repro locally. Something is smelly.

```
SupportsSecureCoding: Foundation.ObjCException : Objective-C exception thrown. Name: NSInvalidArgumentException Reason: *** -supportsSecureCoding cannot be sent to an abstract object of class NSInflectionRule: Create a concrete instance!
Native stack trace:
    0 CoreFoundation 0x00007ff80f94d7b3 __exceptionPreprocess + 242
    1 libobjc.A.dylib 0x00007ff80f6adbc3 objc_exception_throw + 48
    2 Foundation 0x00007ff8109b74f0 NSRequestConcreteImplementation + 138
    3 Foundation 0x00007ff810935225 +[NSInflectionRule supportsSecureCoding] + 32
    4 introspection 0x0000000106a13799 xamarin_dyn_objc_msgSend + 217
    5 ??? 0x0000000155ec3ff6 0x0 + 5736513526
    6 ??? 0x0000000155ec3bdb 0x0 + 5736512475
```

**Comment by chamons** [comment]
Just for those playing at home, we can not reproduce these xtro/intro failures locally, so are expecting CI trickery.

**Comment by chamons** [comment]
We have seen this on other PRs so landing despite failures with @dalexsoto approval.

@mandel-macaque will dig into this offline.

**Pull request merged**
