### PR TITLE
Bump xharness to a version without an async change.

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Comment by dalexsoto** [comment]
# 🎉 All 48 tests passed 🎉

Nope Nope Nope

**Comment by premun** [comment]
@dalexsoto that's right, @mandel-macaque owes me a beer 😂

**Review by dalexsoto — CHANGES_REQUESTED** [review]
@premun not sure about the bet between you two but this is the message I expect to see :) 

# 🎉 All 182 tests passed 🎉

We are missing 134 heh

**Comment by premun** [comment]
@dalexsoto yeah, I'm on it!

**Comment by mandel-macaque** [comment]
Dammed.. @premun I do own you one 🍺

**Comment by dalexsoto** [comment]
@mandel-macaque we can share the cost of the 🍺 for @premun or buy him two! Thank you :)

**Review by dalexsoto — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

**Pull request merged**
