### PR TITLE
Bump to head of mono 2018-02 which includes the removal of Span<T>

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by chamons** [comment]
Filed https://github.com/xamarin/xamarin-macios/issues/4125 to track those TODOs

**Comment by spouliot** [comment]
@rolfbjarne my guess is that the failure is normal since the "previous build" logic does not rebuild mono (with the previous hash)

**Comment by rolfbjarne** [comment]
@spouliot you're correct, this is an expected failure for the api/generator diff.

**Comment by spouliot** [comment]
Thanks! Merging without opening an issue since https://github.com/xamarin/xamarin-macios/pull/4127 will not report this anymore

**Pull request merged**
