### PR TITLE
Add XM Modern to BCL test suite

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Comment by chamons** [comment]
A first pass to see what the test damage looks like.

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
BCL tests didn't run because the bot ran into a GitHub API rate limitation when fetching the labels 😒

**Comment by rolfbjarne** [comment]
build

**Comment by mandel-macaque** [comment]
Will this branch affect in any way the tests that I have been landing in mono-2017-10? Should be back port it there once it lands?

**Comment by chamons** [comment]
@mandel-macaque In theory no, assuming all tests work both in Modern and Full. The only issue would be you adding test X, and X works in Full but fails in Modern. That's be useful to catch, but we'd catch it in merge (if you run bcl test).

I lean towards cherry pick.

**Pull request merged**
