### PR TITLE
Fix inverted null check in MobileCoreServices

### PR DESCRIPTION
**Pull request by chamons**
https://bugzilla.xamarin.com/show_bug.cgi?id=51299

### CODE REVIEW

**Comment by chamons** [comment]
History shows @spouliot was person who first added file, so if for some crazy reason this was intended he'd likely know.

**Comment by spouliot** [comment]
@chamons typo (mostly likely) or local refactoring (before committing). Please backport for `cycle9`

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
Test failure unrelated (obviously).

**Comment by mandel-macaque** [comment]
@chamons I triggered a rebuild, will look at the output to see if we are ok to land it and will ensure that it does not happen again (the unrelated failure).

**Pull request merged**
