### PR TITLE
Update to mono 2017-04 branch

### PR DESCRIPTION
**Pull request by xmcclure**

### CODE REVIEW

**Comment by xmcclure** [comment]
build

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by rolfbjarne** [comment]
The test failure is not a major issue, I can fix that after merging if needed.

**Pull request merged**
