### PR TITLE
[xcode11.4] Sample tester needs Catalina pool

### PR DESCRIPTION
**Pull request by dalexsoto**
Xcode 11.4 needs Catalina

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8068/1/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8068/1//console)
✅ Packages: 
* [xamarin.ios-13.10.1.41.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/package/xamarin.ios-13.10.1.41.pkg)
* [xamarin.mac-6.10.1.41.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/package/xamarin.mac-6.10.1.41.pkg)
* [xamarin.ios-13.10.1.41.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/package/notarized/xamarin.ios-13.10.1.41.pkg)
* [xamarin.mac-6.10.1.41.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/package/notarized/xamarin.mac-6.10.1.41.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/222f6ffbe54bbdf69b35a76429159748772a5390/1/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8068/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8068/2//console)
✅ Packages: 
* [xamarin.ios-13.10.1.42.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/package/xamarin.ios-13.10.1.42.pkg)
* [xamarin.mac-6.10.1.42.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/package/xamarin.mac-6.10.1.42.pkg)
* [xamarin.ios-13.10.1.42.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/package/notarized/xamarin.ios-13.10.1.42.pkg)
* [xamarin.mac-6.10.1.42.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/package/notarized/xamarin.mac-6.10.1.42.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/a9e805d3df728c72c4c3f27b4b6ad62581df373d/2/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8068/3/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8068/3//console)
✅ Packages: 
* [xamarin.ios-13.10.1.43.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/package/xamarin.ios-13.10.1.43.pkg)
* [xamarin.mac-6.10.1.43.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/package/xamarin.mac-6.10.1.43.pkg)
* [xamarin.ios-13.10.1.43.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/package/notarized/xamarin.ios-13.10.1.43.pkg)
* [xamarin.mac-6.10.1.43.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/package/notarized/xamarin.mac-6.10.1.43.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/98e5d503862f5d33499e5c9275e0989537fe2e2d/3/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by dalexsoto** [comment]
@rolfbjarne hopefully this one will do it 😁

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8068/4/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-8068/4//console)
✅ Packages: 
* [xamarin.ios-13.10.1.44.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/package/xamarin.ios-13.10.1.44.pkg)
* [xamarin.mac-6.10.1.44.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/package/xamarin.mac-6.10.1.44.pkg)
* [xamarin.ios-13.10.1.44.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/package/notarized/xamarin.ios-13.10.1.44.pkg)
* [xamarin.mac-6.10.1.44.pkg (Notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/package/notarized/xamarin.mac-6.10.1.44.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-8068/ba89c6fbd20c025d06518d6552cc4595b0d4d666/4/jenkins-results/generator-diff/index.html) (no change)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by dalexsoto** [comment]
Closed in favor of https://github.com/xamarin/xamarin-macios/pull/8113

**Pull request closed without merging**
