### PR TITLE
[dotnet] Moves tasks to the Windows project

### PR DESCRIPTION
**Pull request by emaf**
This enables adding tasks that require using Messaging to the Windows specific project. 

- All messaging dependencies are now merged into Xamarin.Messaging.dll, and it could be reused from both macOS and Windows packs. 
- The ResolveUniversalTypeIdentifiers and VerifyXcodeVersion tasks were moved to the Windows Tasks project since those can only be run from Windows.

### CODE REVIEW

**Comment by spouliot** [comment]
@emaf Most (maybe all) builds are failing with

```14:46:13.2560930 MSBUILD : error MSB4062: The "Xamarin.MacDev.Tasks.FindItemWithLogicalName" task could not be loaded from the assembly /Users/builder/azdo/_work/1/s/xamarin-macios/_mac-build/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Tasks.dll. Could not load file or assembly 'Xamarin.Messaging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/tmp-test-dir/dont link-mac/dont link-mac.csproj] 
```

**Comment by emaf** [comment]
> @emaf Most (maybe all) builds are failing with

I forgot to push the changes on the Makefile 🤦

**Review by spouliot — APPROVED** [review]

**Comment by rolfbjarne** [comment]
The build fails with:

> make[1]: *** No rule to make target `/Users/builder/azdo/_work/1/s/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/msbuild/iOS/Xamarin.Messaging.dll', needed by `all-ios'.  Stop.

**Review by rolfbjarne — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by emaf** [comment]
@rolfbjarne is anything else missing to merge this? All tests passed but the GH status checks should the build was canceled at some point

**Review by mauroa — APPROVED** [review]

**Pull request merged**
