### PR TITLE
[ci] Use nuget-msi-convert/job/v3.yml

### PR DESCRIPTION
**Pull request by pjcollins**
Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195

Updates the build to the latest MSI generation template.  The `v3`
template uses the latest changes from arcade which include a large
refactoring and support for workload pack group MSIs.

The generation of workload pack group MSIs is enabled by default.  The
tooling will now generate a single MSI for each workload declared in our
WorkloadManifest.json file.  This should improve MSI based installation
scenarios as it dramatically reduces the number of MSIs that we ship.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
This probably needs to be back ported once merged to our release/6.0.4xx branch

**Comment by pjcollins** [comment]
>  This probably needs to be back ported once merged to our release/6.0.4xx branch

We're fine to only use this for net7.0+ packs, it's not needed on older branches.

**Comment by pjcollins** [comment]
Let's wait to merge this for the time being, I think we'll need a change in dotnet/arcade that will handle our approach for supporting .NET 6 projects in .NET 7.

**Pull request closed without merging**
