### PR TITLE
[tests] Fix many watchOS tests issues.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
Results are unclear as watchOS tests where ignored on the bot

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by rolfbjarne** [comment]
There's a wrench lane for this branch: https://wrench.internalx.com/Wrench/ViewTable.aspx?lane_id=3404&host_id=243

**Pull request merged**
