### PR TITLE
[spritekit] Update for Xcode 8.3 beta 1 - part 2

### PR DESCRIPTION
**Pull request by VincentDondain**
This is part 2 of https://github.com/xamarin/xamarin-macios/pull/1628:
"[spritekit] Update for iOS 10.3 beta 1"

Thanks Tim for spotting these issues.

### CODE REVIEW

**Comment by spouliot** [comment]
build

**Comment by spouliot** [comment]
This only covers part of 
```
!missing-selector! SKEffectNode::attributeValues not bound
!missing-selector! SKEffectNode::setAttributeValues: not bound
!missing-selector! SKEffectNode::setValue:forAttributeNamed: not bound
!missing-selector! SKEffectNode::valueForAttributeNamed: not bound
!missing-selector! SKEmitterNode::attributeValues not bound
!missing-selector! SKEmitterNode::setAttributeValues: not bound
!missing-selector! SKEmitterNode::setValue:forAttributeNamed: not bound
!missing-selector! SKEmitterNode::valueForAttributeNamed: not bound
!missing-selector! SKShapeNode::attributeValues not bound
!missing-selector! SKShapeNode::setAttributeValues: not bound
!missing-selector! SKShapeNode::setValue:forAttributeNamed: not bound
!missing-selector! SKShapeNode::valueForAttributeNamed: not bound
!missing-selector! SKSpriteNode::attributeValues not bound
!missing-selector! SKSpriteNode::setAttributeValues: not bound
!missing-selector! SKSpriteNode::setValue:forAttributeNamed: not bound
!missing-selector! SKSpriteNode::valueForAttributeNamed: not bound
!missing-selector! SKTileMapNode::attributeValues not bound
!missing-selector! SKTileMapNode::setAttributeValues: not bound
!missing-selector! SKTileMapNode::setValue:forAttributeNamed: not bound
!missing-selector! SKTileMapNode::valueForAttributeNamed: not bound
```

Double-check the documentation but it seems that exposing the `*:: attributeValues` properties covers all cases. If that's the case then please update `common.ignore` for the rest. thanks!

**Comment by VincentDondain** [comment]
https://github.com/xamarin/xamarin-macios/pull/1694#issuecomment-279895874 – all gone.

I think we should expose `*::setValue:forAttributeNamed:` and `*::valueForAttributeNamed:`, see commit message.

**Comment by VincentDondain** [comment]
Unrelated test failures:
iOS Unified 32 bit - https://bugzilla.xamarin.com/show_bug.cgi?id=52162

**Pull request merged**
