### PR TITLE
[msbuild] remove {GAC} from $(AssemblySearchPaths)

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://developercommunity.visualstudio.com/content/problem/788505/xamarin-found-conflicts-between-different-versions.html
Fixes: http://work.azdo.io/1008385
Context: https://github.com/xamarin/xamarin-android/blob/73b93c2dc94d4af166415634b40695fa2be8c371/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L337-L341

On Windows only, Xamarin.Forms projects hit the build warning:

    Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Numerics" that could not be resolved.
    These reference conflicts are listed in the build log when log verbosity is set to detailed.

The difference appears to be the `{GAC}` search path is used on
Windows, but not Mac.

In fact, the output of `<ResolveAssemblyReference/>` on Mac reports:

    Unused locations
        {CandidateAssemblyFiles}
        {HintPathFromItem}
        {Registry:Software/Microsoft/Xamarin.iOS,v1.0,AssemblyFoldersEx}
        {AssemblyFolders}
        {GAC}
        bin/iPhoneSimulator/Debug/
    Used locations
        {TargetFrameworkDirectory}
        {RawFileName}

Compared to Windows:

    Used locations
        {TargetFrameworkDirectory}
        {GAC}
        {RawFileName}

For now, we should just remove `{GAC}` from the list as the safest fix.

Xamarin.Mac is already doing this:

https://github.com/xamarin/xamarin-macios/blob/f85556c1e5bee7a0faf3bf7ade709c3f5f260f11/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props#L121-L125

Down the road, we could specify only the paths needed for performance
reasons. We have done this recently in Xamarin.Android:

https://github.com/xamarin/xamarin-android/blob/5945e9a77988a01ceb062dcc82bda6c6bf407e14/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L382-L386

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@spouliot none of the tests run on Windows, do they?

This makes Xamarin.Mac and Xamarin.iOS do the same now.

**Comment by chamons** [comment]
The logic now matches XM: https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props#L122 except XM had an escape value (due to internal users needing the old behavior)

XM has a test: https://github.com/xamarin/xamarin-macios/blob/master/tests/mmptest/src/AssemblyReferencesTests.cs#L72

**Comment by spouliot** [comment]
@jonathanpeppers right, our whole repo is Mac only. XVS has their own.

**Comment by jonathanpeppers** [comment]
@monojenkins backport to d16-6

**Pull request merged**
