### PR TITLE
Bump Xcode to beta 4 to run tests against the newest toolchain and SDKs

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
It's a **false** success as the simulators could not be loaded an the tests were ignored (so it's mostly only the macOS tests that were executed).

```
Launching /var/folders/wm/s_3npz453hjccvhy16rcy7zm0000gn/T/mlaunch/mlaunch --sdkroot /Applications/Xcode8-beta4.app --listsim /var/folders/wm/s_3npz453hjccvhy16rcy7zm0000gn/T/tmp2f5fa307.tmp
/var/folders/wm/s_3npz453hjccvhy16rcy7zm0000gn/T/mlaunch/mlaunch --sdkroot /Applications/Xcode8-beta4.app --listsim /var/folders/wm/s_3npz453hjccvhy16rcy7zm0000gn/T/tmp2f5fa307.tmp
error HE0004: Could not load the framework 'DVTDocumentation' (path: /Applications/Xcode8-beta4.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation): dlopen(/Applications/Xcode8-beta4.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation, 1): Library not loaded: @rpath/libswiftos.dylib
  Referenced from: /Applications/Xcode8-beta4.app/Contents/SharedFrameworks/libswiftFoundation.dylib
  Reason: image not found
```

@rolfbjarne ^ can this be changed into a failure

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@dalexsoto even if merged earlier (to unblock the pipeline) please double-check the changes to intents and callkit before updating the bindings to beta 4. thanks!

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
The `mlaunch` used on the bots has the issue and the tests won't run until it's updated in it's azure location.

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
