### PR TITLE
[coop][runtime] Default to GC unsafe mode, switch to GC safe when necessary

### PR DESCRIPTION
**Pull request by luhenry**
cc @rolfbjarne

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
@rolfbjarne should that be merged before with branch C8 ?

**Comment by rolfbjarne** [comment]
@spouliot maybe parts of it, I'll have to review it.

**Comment by luhenry** [comment]
@rolfbjarne is this still up for merging? I can work on resolving the conflict if that's the case, otherwise we can just close it.

**Comment by rolfbjarne** [comment]
@luhenry I'm review our runtime code again now.

One question: is there any limitation on the next state transition after `MONO_ENTER_GC_SAFE_UNBALANCED` is called?

I'm wondering if something like this would be a problem:

    void a ()
    {
        MONO_ENTER_GC_SAFE;
        @try {
            b ();
         } @catch {
             mono_set_pending_exception (...);
         }
        MONO_EXIT_GC_SAFE;
    }
    void b ()
    {
        MONO_ENTER_GC_UNSAFE;
        c ();
        MONO_EXIT_GC_UNSAFE;
    }
    void c ()
    {
        MONO_ENTER_GC_SAFE_UNBALANCED;
        @throw "some exception";
        MONO_EXIT_GC_SAFE_UNBALANCED; // never called
    }

in this case the state transition sequence would be:

1. MONO_ENTER_GC_SAFE;
2. MONO_ENTER_GC_UNSAFE;
3. MONO_ENTER_GC_SAFE_UNBALANCED;
4. MONO_EXIT_GC_SAFE;

Neither MONO_EXIT_SAFE_UNBALANCED in c nor MONO_EXIT_GC_UNSAFE in b are called.

**Comment by rolfbjarne** [comment]
The problem is the `xamarin_process_managed_exception` function, you're changing it to be unsafe at entry, but the caller might do things like this:

    MONO_THREAD_ATTACH;
    xamarin_process_managed_exception (); // this may do "@throw ..."
    MONO_THREAD_DETACH; // this may never be executed. Ops.

So I think the only sane approach here is to keep make `xamarin_process_managed_exception` be safe at entry (and exit).

**Comment by luhenry** [comment]
@rolf regarding your first comment, the state transitions should be fine, but checked build is going to complain about it, because of the steps 2 and 3. The solution for that specific problem is to use the `*_UNBALANCED` versions, as they do not check if the transitions are balanced.

Regarding `MONO_THREAD_ATTACH` and `MONO_THREAD_DETACH` it's not made to be unbalanced, and I think it's going to break if it is.

**Comment by rolfbjarne** [comment]
@luhenry the problem with _UNBALANCED is that although it's expected that the EXIT version won't be called, you don't know what's else further up the stack (which won't be called either). In my first comment that's exactly the problem, since I'm using the _UNBALANCED versions.

The second comment is just a variation of the first, where further up the stack you have ATTACH/DETACH instead of ENTER/EXIT.

**Comment by luhenry** [comment]
@rolf on the _UNBALANCED matter, it should be fine, as you expect to throw and catch the exception in Obj-C code, that is not considered part of the runtimes (mono or xamarin-macios). 

For the MONO_THREAD_ATTACHE/DETACH, I think we can add a _UNBALANCED version. What happens on MONO_THREAD_DETACH is:
 - in coop: we switch to blocking (GC SAFE) mode, and unset the domain
 - in non-coop: nothing, it's literally a no-op

So the problematic case might come in coop, but we already switched to GC SAFE when calling `MONO_ENTER_GC_SAFE_UNBALANCED`, and I don't think we care about the value of the domain, as we are in blocking (GC SAFE) mode.

**Pull request closed without merging**
