### PR TITLE
[msbuild] Repack all iOS Task assemblies into Xamarin.iOS.Tasks.dll

### PR DESCRIPTION
**Pull request by jstedfast**
This is the back-port of https://github.com/xamarin/xamarin-macios/pull/3168 to the 15.6 branch

### CODE REVIEW

**Comment by spouliot** [comment]
```MMP: error MM0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
				System.InvalidOperationException: Operation is not valid due to the current state of the object.
				  at Mono.Cecil.ModuleDefinition.ReadSymbols (Mono.Cecil.Cil.ISymbolReader reader) [0x0002f] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x0004a] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Mono.Cecil.ModuleReader.CreateModule (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00081] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000d] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in <44082a1a5784414bb4abb85f6bdc2d21>:0 
				  at Xamarin.Bundler.MonoMacResolver.AddAssembly (System.String fileName) [0x00031] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/resolver.cs:73 
				  at Xamarin.Bundler.Driver.AddAssemblyPathToResolver (System.String path) [0x00013] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/driver.cs:1915 
				  at Xamarin.Bundler.Driver.GatherAssemblies () [0x00018] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/driver.cs:1880 
				  at Xamarin.Bundler.Driver.Pack (System.Collections.Generic.IList`1[T] unprocessed) [0x00460] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/driver.cs:780 
				  at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x0105b] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/driver.cs:514 
				  at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tools/mmp/driver.cs:220 
```

**Comment by spouliot** [comment]
build

**Comment by jstedfast** [comment]
-xammac tests (BuildFailure; Succeeded)
-Mac (BuildFailure; Succeeded)
-Debug (BuildFailure)
Project file: /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xammac_tests/xammac_tests.csproj 
Platform: AnyCPU Configuration: Debug 
Build duration: 00:00:11.1676855 
Run duration: 00:01:51.1286118 
Main log
Build log
MMP: error MM0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com

**Comment by jstedfast** [comment]
oh, hah, spouliot already looked into it :)

**Comment by spouliot** [comment]
first error seems random and was filed

**Pull request merged**
