### PR TITLE
[watch4] set right min version for arm64_32 based watch devices

### PR DESCRIPTION
**Pull request by lewurm**
Fixes the confusion around `libmono-native*` (see for example https://github.com/xamarin/xamarin-macios/commit/ce5ba1e41d526eddd9b61f68fae22a747831e9f2#commitcomment-33834491 ) when building with `MONO_BUILD_FROM_SOURCE=1`.

Not exactly happy with the naming, but at least it's consistently bad with the Mono SDK.

### CODE REVIEW

**Comment by lewurm** [comment]
My vote is for `MIN_WATCHOS64_32_SDK_VERSION`.

I'll change the name in Mono SDK as well once we settled for a naming here (want to wait for @rolfbjarne ).

**Comment by mandel-macaque** [comment]
+1 on what said, also, 5 reads like an S if the font is not good.

**Comment by lewurm** [comment]
Thanks for voting! 🙂 will merge it into `mono-2019-06` and follow up there when the Mono SDK fix has landed.

**Comment by lewurm** [comment]
https://github.com/mono/mono/pull/15202

**Pull request merged**
