### PR TITLE
[Fix] Reorder the enum to the correct order

### PR DESCRIPTION
**Pull request by tj-devel709**
In response to: https://github.com/xamarin/xamarin-macios/issues/15445

The order of the enums for UNNotificationInterruptionLevel in Xcode is currently different to the order we have in Xamarin.iOS.
This PR should make it so the enums are matched!

### CODE REVIEW

**Comment by chamons** [comment]
For reviewers:

```
typedef NS_ENUM(NSUInteger, UNNotificationInterruptionLevel) {
    UNNotificationInterruptionLevelPassive,
    UNNotificationInterruptionLevelActive,
    UNNotificationInterruptionLevelTimeSensitive,
    UNNotificationInterruptionLevelCritical,
}
```

**Review by chamons — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by spouliot** [comment]
That's a breaking change. It requires re-compiling assemblies that refers to this `enum` since they will bake the integral value into their own binaries. That also make it a _minor_ breaking change since it won't change break at compile, nor runtime.

**Review by dalexsoto — CHANGES_REQUESTED** [review]
@tj-devel709 let's fix it the right way, @spouliot is right we have to Create new enum values and obsolete the old ones.

https://github.com/xamarin/xamarin-macios/pull/14301/files

**Comment by tj-devel709** [comment]
@dalexsoto @spouliot Okay how does this look now?

**Review by spouliot — APPROVED** [review]
👍

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Pull request merged**
