### PR TITLE
Fix wrong cast to IList

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes https://github.com/mono/mono/issues/14729

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Why is that an invalid cast if the C# compiler accepts it?

**Comment by BrzVlad** [comment]
I meant incorrect. An IEnumerable is not necessarily an IList so an exception can be thrown here

**Comment by Therzok** [comment]
@BrzVlad Why not modify the signature of [TestRunner.Run](https://github.com/xamarin/xamarin-macios/blob/26a33946237ea0d9434687a03fb637ab90682445/tests/bcl-test/templates/common/TestRunner.Core/TestRunner.cs#L9) to take an IEnumerable? Don't see IList members being used.

**Comment by rolfbjarne** [comment]
@BrzVlad 

> I meant incorrect. An IEnumerable is not necessarily an IList so an exception can be thrown here

That still doesn't explain why it only fails with the interpreter.

**Comment by Therzok** [comment]
Can't repro the problem with Mac and Console apps, but can repro it not throwing on iOS debug builds.

**Comment by Therzok** [comment]
I think [this](https://github.com/mono/mono/issues/14729#issuecomment-499306330) is why.

**Comment by mandel-macaque** [comment]
Failures are due to issues with the simulators in the bots after the upgrade to Xcode 11. I have fixed the bots, will retrigger a build and everything should be back to normal.

**Comment by mandel-macaque** [comment]
Mac failure is already known: https://github.com/xamarin/maccore/issues/1685 and the watchOS failures are due to https://github.com/xamarin/maccore/issues/581

Looks good to merge.

**Comment by mandel-macaque** [comment]
API diff issue can also be ignored.

**Pull request merged**
