### PR TITLE
Match Xcode's app path to the provisionator.

### PR DESCRIPTION
**Pull request by rolfbjarne**
To see if this fixes https://github.com/xamarin/maccore/issues/2327.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9950/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9950/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Install Provisioning Profiles' 🔥 : hudson.AbortException: script returned exit code 104

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9950/1//console)
✅ Packages: 
* [xamarin.ios-14.3.1.79.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9950/e80b8e59224702368bca7e1742666b3a65da5245/1/package/xamarin.ios-14.3.1.79.pkg)
* [xamarin.mac-6.99.2.79.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9950/e80b8e59224702368bca7e1742666b3a65da5245/1/package/xamarin.mac-6.99.2.79.pkg)

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
Wait what?? when did that change... I 💭 we were in compliance with the naming already...

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
That made the sample tests work: there are now 26/3599 failing sample tests (much better than 3016/3599 failing tests). A very brief look at the remaining ones seems to indicate these are legitimate failures.

**Comment by rolfbjarne** [comment]
This isn't needed anymore, the provisionator was updated to use the Xcode name we expect.

**Pull request closed without merging**
