### PR TITLE
[DRAFT]: Getting mono from source to work

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7364/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7364/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7364/1//console)
    ⚠️ Mono built from source

**Comment by baulig** [comment]
Next step: https://github.com/mono/mono/pull/17700#issuecomment-549634128

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7364/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7364/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7364/2//console)
    ⚠️ Mono built from source

**Comment by baulig** [comment]
@monojenkins build pkg

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7364/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7364/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Build' 🔥 : hudson.AbortException: script returned exit code 2

🔥 [Build failed](https://jenkins.internalx.com/job/macios/job/PR-7364/3//console) 🔥

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-7364/4/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-7364/4/display/redirect) (on internal Jenkins) failed in stage(s) 'Packaging' 🔥 : hudson.AbortException: script returned exit code 2

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-7364/4//console)
    ⚠️ Mono built from source

**Comment by mandel-macaque** [comment]
We do not need anymore, @baulig closing it.

**Pull request closed without merging**
