### PR TITLE
[msbuild] Avoid Dictionary clashes in IBToolTask's mapping dictionary

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54914

### CODE REVIEW

**Comment by jstedfast** [comment]
I think it's fairly simple in this case, MyView~ipad.xib should override the generic MyView.xib.

**Comment by rolfbjarne** [comment]
Build failure looks like a parallel make problem in mono.

**Comment by rolfbjarne** [comment]
Build

**Comment by jstedfast** [comment]
ping

**Comment by jstedfast** [comment]
@kzu? @spouliot ?

**Comment by jstedfast** [comment]
Thanks :)

**Pull request merged**
