### PR TITLE
Bump to .NET 6.0.100-alpha.1.21060.3.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This required fixing some of the dotnet command line arguments.

* dotnet build: the project file must be the first argument.
* dotnet build/publish: use the documented verbosity format.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Very interesting, the .net pkg failed installing https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4364774&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=a2589edb-a191-5e88-a86f-b1c1957787f3&l=468

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
The pkg is broken 😒 

https://github.com/dotnet/installer/issues/9369

**Comment by rolfbjarne** [comment]
@mandel-macaque that said, CI shouldn't install the pkg, we're supposed to download the .tar.gz and extract it locally into builds/downloads.

**Review by spouliot — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated: https://github.com/xamarin/maccore/issues/2154

**Pull request merged**
