### PR TITLE
Xcode82 master - Take II

### PR DESCRIPTION
**Pull request by chamons**

### CODE REVIEW

**Comment by chamons** [comment]
Based on https://github.com/xamarin/xamarin-macios/pull/1343 with an additional commit since Sebastien is having network issues.

**Comment by chamons** [comment]
build

**Comment by spouliot** [comment]
`[FAIL] Typo in TYPE: NSSpellCheckerCanidates - Canidates`

^ I wonder if `TypoTest` is considering the availability attributes... it should not.

**Comment by spouliot** [comment]
```
1) ApiSelectorTest.InstanceMethods (Introspection.MacApiSelectorTest.ApiSelectorTest.InstanceMethods)
     2 errors found in 22436 instance selector validated:
Selector not found for Intents.INPerson : relationship
Selector not found for ModelIO.MDLSubmeshTopology : initWithSubmesh:
```

jenkins bots on Sierra are already helpful :)

**Comment by spouliot** [comment]
@chamons `mmptest (TimedOut)`, seems to be recent tests - maybe something else needs some tweaking for 10,12,2 ?

**Comment by chamons** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by chamons** [comment]
@spouliot 👍 'ed the XI test failures so finally landing.

**Pull request merged**
