### PR TITLE
Fix CMSampleBuffer owns: bug introduced in commit e879678.

### PR DESCRIPTION
**Pull request by RogerHardiman**
Note - I'm still working through the process of building and testing, but wanted to get the PR in for this tiny fix that was introduced with a change in Sept 2016.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
I'm not sure you're right here: the `owns` value is passed in as a parameter, and there's a reason for it (and as far as I can see e87967876f5df6310d04d8ea0c06b7cc7a4c1212 didn't change the behavior).

From what I can see the only way to hit this code path is to use the obsolete method here: https://github.com/xamarin/xamarin-macios/blob/fb6c75d515efea85b7de607d412d0605e887e1e7/src/VideoToolbox/VTCompressionSession.cs#L93.

Can you show your code that ends up running into this problem?

**Comment by RogerHardiman** [comment]
I'd not spotted that obsolete method and it is possible I've got this wrong. Currently the PR is from a manual code review rather than building and testing (would prefer to build and test but still working though the build process)

What I did notice from the Sept 2016 commit was this block of code
```
-			var gch = GCHandle.FromIntPtr (outputCallbackClosure);		 +			CompressionCallback (outputCallbackClosure, sourceFrame, status, infoFlags, cmSampleBufferPtr, false);
 -			var func = (VTCompressionOutputCallback) gch.Target;		
 -			using (var sampleBuffer = new CMSampleBuffer (cmSampleBufferPtr, owns: false)) {		
 -				func (sourceFrame, status, infoFlags, sampleBuffer);		
 -			}
```

had an owns: false

It got replaced by a shared function that had `owns: owns`


So from visual inspection I've assumed that was the code path I'd followed.


But I'll do a proper sample for us.
What I see in my iOS app is regular SIGSEGV being generated at the iOS level in the Emit function which triggered the C# callback.

For now I've got a working compression example in C# with a mix of reflection hacks and my own invokes to call the Apple VTCompressionSession code directly, bypassing everything in VTCompressionSession.cs.  That is nice and stable.

**Comment by RogerHardiman** [comment]
Here is my test code pulled from a fresh XamForms project.
There is a CFRetain in the code (in the callback handler).
If I remove it I get a SIGSEGV when running the code.
with the CFRetain added in the code runs fine.
This is what lead me to investigate the owns: on the CMSampleBuffer

```
using System;
using VideoToolbox;
using CoreMedia;
using Xamarin.Forms;
using System.Runtime.InteropServices;

namespace CompressionTest
{
	public class App : Application
	{
	
		long timestamp_ms = 0;
		int width = 640;
		int height = 480;
		VTCompressionSession session;
		System.Timers.Timer timer;
	
		public App ()
		{
			// The root page of your application
			var content = new ContentPage {
				Title = "CompressionTest",
				Content = new StackLayout {
					VerticalOptions = LayoutOptions.Center,
					Children = {
						new Label {
							HorizontalTextAlignment = TextAlignment.Center,
							Text = "Welcome to Xamarin Forms!"
						}
					}
				}
			};

			MainPage = new NavigationPage (content);


			// TEST CODE STARTS HERE

			// No specific encoder specifcation
			VideoToolbox.VTVideoEncoderSpecification encoder_specification = new VideoToolbox.VTVideoEncoderSpecification();
			
			// Source is YUV420 Bi-Planar
			CoreVideo.CVPixelBufferAttributes source_attributes = new CoreVideo.CVPixelBufferAttributes(
														    CoreVideo.CVPixelFormatType.CV420YpCbCr8BiPlanarFullRange,
													    	width,height);
			// Create the Encoder Session
			session = VTCompressionSession.Create(
				width, height,
				CMVideoCodecType.H264,
				HandleVTCompressionOutputCallback,
				encoder_specification,
				source_attributes
				);
			
			// Now create a TIMER to feed video frames into the Encoder

			timer = new System.Timers.Timer();
			timer = new System.Timers.Timer();
			timer.Interval = 40; // time in milli seconds
			timer.AutoReset = true; // restart timer after the time has elapsed
			timer.Elapsed += (object sender, System.Timers.ElapsedEventArgs e) => {
			
				// Create a PixelBuffer
				CoreVideo.CVPixelBuffer imageBuffer = new CoreVideo.CVPixelBuffer(width,height,
													CoreVideo.CVPixelFormatType.CV420YpCbCr8BiPlanarFullRange);
													
				// TODO. Real application would load YUV image into the imageBuffer. May even use the Pool of buffers
				// from the VTCompressionSession
													
				CMTime pts      = new CMTime(timestamp_ms,1);
				CMTime duration = new CMTime(40,1);
				Foundation.NSDictionary frameProperties = new Foundation.NSDictionary();
				VTEncodeInfoFlags infoFlags;
				Console.WriteLine("Encoding for timestamp " + pts.ToString());
				VideoToolbox.VTStatus status = session.EncodeFrame(imageBuffer,pts,duration,frameProperties,
													imageBuffer.Handle, out infoFlags);
				Console.WriteLine("Encode completed. Status="+status.ToString());
				timestamp_ms += 40;
			};
			
			// Start the timer
			timer.Start();

		}



		void HandleVTCompressionOutputCallback (IntPtr sourceFrame, VideoToolbox.VTStatus status,
												VideoToolbox.VTEncodeInfoFlags flags, CoreMedia.CMSampleBuffer buffer)
		{
			Console.WriteLine("H264 - NAL callback with status "+status.ToString());
			if (status != VideoToolbox.VTStatus.Ok) {
				return;
			}

			Console.WriteLine("H264 - pts "+buffer.OutputPresentationTimeStamp.ToString());

			// Real application copies the SPS, PPS and NAL from the CMBlockBuffer which is contained inside
			// the CMSampleBuffer (buffer.GetDataBuffer() function);
			
			// ToDo. Use SourceFrame to 'free' the CVPixelBuffer
			
			// Adding a RETAIN here fixes the SIGSEGV
			// Note the library tells me to use Create(int,int,CMVideoCodecType,VTCompressionOutputCallback,
			// VTVideoEncoderSpecification,CVPixelBufferAttributes) which it says avoids the need for a CFRetain
			// but I am using that variant of Create() already!
			// So either the comment in the Xamarin.iOS library is wrong, or there is a Xamarin bug.

			CFRetain(buffer.Handle);    // <<--- I should not need this. Looks like a library issue.
			
			
		}

		// Import CFRetain
		[DllImport ("/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation")]
		internal static extern IntPtr CFRetain (IntPtr obj);


		protected override void OnStart ()
		{
		}

		protected override void OnSleep ()
		{
		}

		protected override void OnResume ()
		{
		}
	}
}

```

**Comment by rolfbjarne** [comment]
It looks like the attempt to fix the broken (obsolete) API in a backwards compatible way some time ago  [1] wasn't correct, and due to a typo ended up creating a new API which was just as broken as the old API, accidentally fixing (and obsoleting...) the old API.

@RogerHardiman can you try the old API (https://github.com/xamarin/xamarin-macios/blob/fb6c75d515efea85b7de607d412d0605e887e1e7/src/VideoToolbox/VTCompressionSession.cs#L93) and see if you need the CFRetain there as well? If my reading of the current code is correct, you won't need it.

[1] https://github.com/xamarin/maccore/commit/66c50b9a176c6edfa8e633bfd9b54831ebddc9e5 (this is a link to our source code before we made it public, so it's not publicly viewable)

**Comment by RogerHardiman** [comment]
@rolfbjarne - Thanks for the update. I tested the old Create API (where the last parameter is NSDictionary). The sample code runs fine both without the CFRetain (even though the warning message says you need it). It also runs fine with the CFRetain but I expect I'm causing a leak there.

So right now it looks like this
Old API. Warning message tells you to use CFRetain but you don't need to.
New API. No warning message but you need to use CFRetain or it will crash with SIGSEGV.

Thanks for helping.

**Comment by rolfbjarne** [comment]
@RogerHardiman thanks for testing it.

Unfortunately I'm not entirely sure what to do now.

1. It's clear the old [VTCompressionSession.Create](1) overload is now working fine. Although a bug existed, and an [attempt](3) was made to fix the bug in a backwards compatible way (i.e. not change the old VTCompressionSession.Create behavior at all, so that existing code would not go from working fine to leaking), due to a typo this overload's behavior was accidentally fixed. Unfixing this means that new code using this old overload would go from working fine to crashing (which is worse than leaking). IMHO the fix here is to remove the `[Obsolete]` attribute.

2. The real question is now what to do with the new [VTCompressionSession.Create](2) overload. We have two obvious solutions:

    1. Fix it. This will be a behavioral breaking change (working code will become leaking code, and since this code is using a lot of memory not tracked by the GC, it will likely crash soon with OOM conditions). This might sound bad, but we already did exactly this for the old overload, and nobody has run into it yet (at least not reported it - it happened for Xamarin.iOS 9.8).
    2. Not fix it, and add an `[Obsolete]` attribute (like the obsolete attribute on the old overload). The new overload is somewhat nicer (it's using a type-safe dictionary instead of NSDictionary), but we could potentially come up with yet another overload that uses a type-safe dictionary.

3. We need tests :smile:

@spouliot what do you think?

[1]: https://github.com/xamarin/xamarin-macios/blob/fb6c75d515efea85b7de607d412d0605e887e1e7/src/VideoToolbox/VTCompressionSession.cs#L93
[2]: https://github.com/xamarin/xamarin-macios/blob/fb6c75d515efea85b7de607d412d0605e887e1e7/src/VideoToolbox/VTCompressionSession.cs#L144
[3]: https://github.com/xamarin/maccore/commit/66c50b9a176c6edfa8e633bfd9b54831ebddc9e5

**Comment by spouliot** [comment]
@rolfbjarne _It's clear the old VTCompressionSession.Create_ <- bad link and
_Although a bug existed, and an attempt _ <- that link is also bad (or I'm really lost)

@RogerHardiman thanks for work, it's appreciated :)

**Comment by rolfbjarne** [comment]
@spouliot I've fixed the links.

**Comment by RogerHardiman** [comment]
I agree with removing the Obsolete on the old API.
That also gives me something I can use in a release build.
On the new API I would like to see the bug fixed and in the mean time can use the old API to get my project released.

**Comment by glennawatson** [comment]
I originally put this in a email to the MVP email address but never got a reply. @pureween suggested posting the email directly into this PR.

Hi there,
A client of mine wants me to make a screen capture application to be used in a VR application for Mac.
I was using the AVCaptureScreenInput.

The problem is then when I am using the VTCaptureSession, I am passing a clone of the CVPixelBuffer 
into the EncodeFrame.

I spent about 4 days trying to track down a bug where I would get a random SIG FAULT without much debugging information. Using the method marked as Obsolete solved my SIG FAULT problem since the old obsolete version doesn't take over ownership of the CVPixelBuffer.

Was wondering if there is any plans to fix the bug identified in the PR?

Thanks,
Glenn

**Comment by rolfbjarne** [comment]
We're able to do [breaking changes in our .NET support](https://github.com/xamarin/xamarin-macios/issues/13087), so I've created a PR that fixes this issue: #13589. It turned out to be a bit more complicated than this PR.

That leaves this PR redundant, so I'm closing it.

Thanks a lot for the contribution!

**Pull request closed without merging**
