### PR TITLE
[xharness] Backport the xharness changes needed to produce html reports by xtro on bots

### PR DESCRIPTION
**Pull request by spouliot**
Partial backport/adaptation of
https://github.com/xamarin/xamarin-macios/commit/8d854a0f3d

### CODE REVIEW

**Comment by spouliot** [comment]
🤣 we don't run xtro tests if only the harness is updated
@rolfbjarne maybe changes to xharness should test everything ?

**Comment by spouliot** [comment]
build

**Comment by rolfbjarne** [comment]
@spouliot usually you have additional changes in the PR that triggers testing whatever you changed in xharness (your original PR did iirc). Also running all the tests when xharness changes would slow down my xharness PRs (and as far as I can remember I haven't run into this problem before).

**Comment by spouliot** [comment]
xtro report is fine
apitest seems a random failure -> https://github.com/xamarin/maccore/issues/626

**Pull request merged**
