### PR TITLE
[PushKit] Added support for Xcode 14

### PR DESCRIPTION
**Pull request by SotoiGhost**

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Comment by mandel-macaque** [comment]
Approving looks 🐟 that you did not remove a todo file.

**Comment by dalexsoto** [comment]
Also do not forget to update the wiki

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

**Comment by SotoiGhost** [comment]
Ready, sorry folks, I didn't amend the last commit adding the deletion of the todo file

**Comment by mandel-macaque** [comment]
xtro failures are fixed in xcode14 and are related with GameKit so I'm landing this.

**Pull request merged**
