### PR TITLE
[xcode11] Stop building/shipping 32-bit Xamarin.Mac bits. Partial fix for #6300.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This includes:

* 32-bit version of Xamarin.Mac.dll and OpenTK.dll
* XamMac.dll and XamMac.CFNetwork.dll
* 32-bit versions of the runtime libraries (libxammac.a and friends).
* 32-bit version of the partial static library for Xamarin.Mac.
* Classic support in the generator.

We still ship a few Classic files so that Visual Studio for Mac continue to detect that Xamarin.Mac is installed (otherwise VSfM won't open Classic projects, which makes it impossible to use the migration wizard).

This makes our build slightly faster.

Partial fix for #6300.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Looks like I'll have to port the mmp regression tests to Unified as well.

**Comment by spouliot** [comment]
@rolfbjarne mmp regression - https://github.com/xamarin/xamarin-macios/issues/4975

**Comment by chamons** [comment]
We should update:

https://github.com/xamarin/xamarin-macios/blob/master/tools/mmp/driver.cs#L762

to always error now.

**Comment by rolfbjarne** [comment]
build

**Pull request merged**
