### PR TITLE
[msbuild] Create a WatchKitSupport2 directory in the IPA for WatchOS2…

### PR DESCRIPTION
**Pull request by jstedfast**
…+ apps

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=41762

### CODE REVIEW

**Comment by jstedfast** [comment]
@kzu @joj 

I renamed the FindWatchAppBundle task to FindWatchOS1AppExtensionBundle and added a new FindWatchOS2AppBundle task.

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by spouliot** [comment]
LGTM but I might be missing some key elements :-)
@VincentDondain can you also check this, thanks!

**Comment by VincentDondain** [comment]
That looks completely fine to me 👍

**Pull request merged**
