### PR TITLE
[xammac-test/MapKit/PinAnnotationView] Changed assertion of PinTintColor property to work on other language than English

### PR DESCRIPTION
**Pull request by joconte**
Fixes https://github.com/xamarin/xamarin-macios/issues/6462

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Nice catch!

**Comment by rolfbjarne** [comment]
build

**Comment by dalexsoto** [comment]
build

**Comment by mandel-macaque** [comment]
Api diff failure can be ignored.

**Comment by dalexsoto** [comment]
Thanks a bunch @joconte ❤️

**Pull request merged**
