### PR TITLE
Bump to Xcode 8 and corresponding SDK versions.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by rolfbjarne** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
build

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build success

**Pull request merged**
