### PR TITLE
[msbuild] Fix conditional evaluation order warning

### PR DESCRIPTION
**Pull request by chamons**
- Fixes https://github.com/xamarin/xamarin-macios/issues/12499 (hopefully)
- I had trouble re-using my macios build on Windows, which is the only place I can reproduce it, but it seems like a straightforward fix

### CODE REVIEW

**Comment by chamons** [comment]
I didn't write the original line:

<Delete SessionId="$(BuildSessionId)" Condition="(('$(IsMacEnabled)' == 'true' And '$(IsAppExtension)' == 'true') Or '$(_PlatformName)' == 'macOS')" Files="$(DeviceSpecificOutputPath)dsym.items" />

I think this should be read as "If (we're on XVS and building an app extension) OR (we're on a mac)".

I admit the fix is a bit blind, but given I can only reproduce it on Windows I'm not even sure how I could write a test for it...

**Review by mandel-macaque — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by rolfbjarne** [comment]
> I didn't write the original line:

You didn't write the original line, but you fixed this warning already:

https://github.com/xamarin/xamarin-macios/pull/13112#pullrequestreview-789934291

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
This PR isn't needed, because you already fixed the problem: https://github.com/xamarin/xamarin-macios/pull/13112#pullrequestreview-789934291

**Comment by chamons** [comment]
Ok, I thought I had fixed it but I thought that had already gone through (this this is impossible to reproduce locally for me due to Windows).

**Pull request closed without merging**
