### PR TITLE
[runtime] Make coop assertions debug-only.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This will mostly run on user's devices, which means I don't think we'll be able to pinpoint any issues anyway.

If asserts don't trigger in debug, then I think we're better off hoping for the best for release builds than asserting (the assert might be wrong too, in which case we'd be crashing a working app).

**Comment by spouliot** [comment]
Still not sure ;-) Crash reports goes back to developers (and some to us). @vargaz do you think the current behaviour is of any help to you ? if it's not helping anyone then I'm fine with the change.

**Comment by vargaz** [comment]
I think release asserts are fine if they are no slowing down the app/making it too much bigger.

**Comment by rolfbjarne** [comment]
I have sprinkled these asserts around freely thinking they wouldn't affect (slow down) release builds... otoh I have no idea how slow they are.

**Comment by spouliot** [comment]
@rolfbjarne what about the size impact (with and without this PR) on the _release executable_ ? (bitcode does matter a bit since App Store size limit applies to it)

**Comment by rolfbjarne** [comment]
For the armv7k bits of libxamarin.a, the difference is 3984 bytes (of ~2mb).

For dontlink built for release, the difference is 172 bytes (not sure why this is so much lower, but much of the difference might have disappeared in padding in the file format, etc).

**Comment by spouliot** [comment]
Size impact is negligible. Unless we have (or come up) with a runtime performance issue I'd rather not remove code that can help diagnose crashes.

**Comment by rolfbjarne** [comment]
Closing according to the last comment.

**Pull request closed without merging**
