### PR TITLE
Wrap mono_gc_init_finalizer_thread() call with now-needed coop GC state transition

### PR DESCRIPTION
**Pull request by alexischr**
Should fix https://github.com/mono/mono/issues/19372

### CODE REVIEW

**Comment by mandel-macaque** [comment]
We need to test this on a device, is that correct?

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-6
@monojenkins backport d16-5

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8242/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8242/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: script returned exit code 128

**Comment by lewurm** [comment]
I've tested it on watch4 with the `d16-5` branch (actually `d16-5-xcode11.4` FWIW) and this PR fixes the startup crash.

@rolfbjarne did you test on `master`? Unsure if it's the right fix there.

**Comment by rolfbjarne** [comment]
@lewurm yes, I tested on master (I tested this PR, which is targeting master).

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-8242/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-8242/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Checkout' 🔥 : hudson.AbortException: script returned exit code 128

**Comment by dalexsoto** [comment]
@monojenkins backport d16-5-xcode11.4

**Pull request merged**
