### PR TITLE
[registrar] Use the correct parameters when generating category methods. Fixes #42489.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Category methods are exposed like extension methods, and the first parameter
specifies the class, which means we need to skip the first type when generating
the ObjC signature.

https://bugzilla.xamarin.com/show_bug.cgi?id=42489

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
Test fails to build on watchOS
`ObjCRuntime/RegistrarTest.cs(2499,35): error CS0246: The type or namespace name `CALayer' could not be found. Are you missing an assembly reference? `

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
test crash is unrelated

**Pull request merged**
