### PR TITLE
[CI] Enable setting provisionator channel as parameter

### PR DESCRIPTION
**Pull request by cadsit**
This also brings in the latest changes for provisionator; specifically https://github.com/xamarin/provisionator/pull/402 to unblock builds.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]
Approving only if latests works ;)

**Comment by mandel-macaque** [comment]
not yet working :(

**Review by tj-devel709 — APPROVED** [review]

**Comment by cadsit** [comment]
@mandel-macaque The build linked in the status is an older build -- I think this is the one: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4704326&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=c9117ceb-ee46-564f-0d31-c57e59243b74

**Comment by mandel-macaque** [comment]
Works and tests are unrelated, means we can switch to latests.

**Pull request merged**
