### PR TITLE
[src] Quiet the build a bit.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by chamons — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (various network failures).

**Comment by rolfbjarne** [comment]
Test failures are unrelated (various network failures).

**Comment by rolfbjarne** [comment]
Test failures are unrelated (various network failures).

**Comment by rolfbjarne** [comment]
Looks like GitHub has network failures too...

**Comment by rolfbjarne** [comment]
GitHub seems to have problems with this PR, and does not show the UI to merge the PR (tried with multiple browsers, and other PRs work fine), so I've merged it manually.

**Pull request closed without merging**
