### PR TITLE
[foundation] Update up to beta 5

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by spouliot** [comment]
2016-08-12 15:47:55.386 apitest[62099:4036336] *** -[NSKeyedArchiver init]: cannot use -init for initialization

^ `init` is decorated but it's a special case, since AFAIK it's the first time `init` does not match the type itself (for availability) and the test suite needs to consider that too

**Comment by spouliot** [comment]
@chamons can you review this ? both bindings, which will be part of XM, and the test fix - in case the same is needed elsewhere. thanks!

**Comment by xamarin-release-manager** [comment]
Build failure

**Comment by chamons** [comment]
@spouliot Looks reasonable to me. That DelegateAndDataSourceTest test is a bit special in apitest, I can't think of any other obvious ones there that need the fix off the top of my head.

**Pull request merged**
