### PR TITLE
[introspection] Add/fix/remove availability attributes for Mac Catalyst to make introspection's Introduced test pass.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by spouliot** [comment]
intro failures do not happen on macOS 11.x (MacCatalyst 14.x)
but bots are still on 10.15 (MacCatalyst 13.x)
we'll need to have old macOS bots to run those tests (since Xcode 12.5 is forcing us to update our Macs, both locals and bots), c.c. @dalexsoto

**Comment by spouliot** [comment]
Looks like this bot has issues with tvOS simulators
c.c. @mandel-macaque have you seen this before ?

**Comment by spouliot** [comment]
Failure is unrelated to PR -> https://github.com/xamarin/maccore/issues/2411

**Pull request merged**
