### PR TITLE
[Makefile] Call maccore install-symlinks

### PR DESCRIPTION
**Pull request by VincentDondain**
This is required for our **analysis rules** in maccore.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This needs a maccore bump as well, since there's no `install-symlinks` target in $(MACCORE_PATH)/Makefile right now.

**Comment by VincentDondain** [comment]
@rolfbjarne Yea I just pushed https://github.com/xamarin/maccore/pull/517. Guess we can merge it first and I'll add a bump commit to this PR.

**Comment by VincentDondain** [comment]
@rolfbjarne I added the bump.

**Comment by rolfbjarne** [comment]
whitelist

**Pull request merged**
