### PR TITLE
[ci] Add parameter to disable classic signing

### PR DESCRIPTION
**Pull request by pjcollins**
A new parameter has been added to allow the unified pipeline to skip
classic signing jobs.

The jobs that would sign and notarize the custom workload .pkg and .zip
files have been removed, as we do not ship these anywhere and do not
need to wait on signing for them.  The `dotnet-signed` artifact has been
removed as a result, and the `not-signed-package` artifact is used in
its place.

### CODE REVIEW

**Comment by pjcollins** [comment]
This seems to work against the PR build pipeline, but it would be good to also queue an official CI build against this branch to test it further.

**Review by rolfbjarne — APPROVED** [review]
The entire pipeline is yellow - @mandel-macaque is that because the PR was not created from a fork?

**Comment by mandel-macaque** [comment]
@rolfbjarne I already started a conversations with the infra team about that error.

**Review by mandel-macaque — APPROVED** [review]
Looks good, lets wait for the build here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7687398&view=results

**Comment by pjcollins** [comment]
> Looks good, lets wait for the build here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7687398&view=results

I guess this one didn't run the .NET prepare release stage, should we queue another one with that forceInsertion stage parameter set?

**Comment by mandel-macaque** [comment]
Proof that it worked: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7691220&view=results

**Pull request merged**
