### PR TITLE
[XM] Fix "random" crash in introspection tests

### PR DESCRIPTION
**Pull request by chamons**
- Hopefully kill https://bugzilla.xamarin.com/show_bug.cgi?id=42267

### CODE REVIEW

**Comment by chamons** [comment]
Adding a GC.Collect (2) at the bottom of the test made this happen 100% of the time. Instruments was kind enough to find the culprit for me.

**Comment by rolfbjarne** [comment]
I'm just curious, but what did Instruments have to say about `NSColorPanel`?

**Comment by chamons** [comment]
Something like: Zombie message sent to instance X - NSColorPanel

I forget the exact wording, but can dig it up if desired.

**Comment by xamarin-release-manager** [comment]
Build failure

**Pull request merged**
