### PR TITLE
[Fix] Ensure that strong dictionaries can work with templated dictioaries as property types.

### PR DESCRIPTION
**Pull request by mandel-macaque**
This pull request allows the generator to understand the usage of templated NSDictionary classes as the return type of properties in strong dictionaries.

The added test ensures that the strong dict is generated and can be compiled.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by xamarin-release-manager** [comment]
Build success

**Comment by mandel-macaque** [comment]
FYI code before changes is:

```csharp
public NSDictionary<CBUUID, NSData> ServiceData {
            get {
                return Dictionary [AdvertisementDataKeys.ServiceDataKey] as Foundation.NSDictionary`2[CoreBluetooth.CBUUID,Foundation.NSData];
            }
            set {
                SetNativeValue (AdvertisementDataKeys.ServiceDataKey, value);
            }
        }
```

after is:

```csharp
public NSDictionary<CBUUID, NSData> ServiceData {
            get {
                return GetNSDictionary <CoreBluetooth.CBUUID, Foundation.NSData> (AdvertisementDataKeys.ServiceDataKey);
            }
            set {
                SetNativeValue (AdvertisementDataKeys.ServiceDataKey, value);
            }
        }
```

**Comment by chamons** [comment]
LGTM.

**Comment by dalexsoto** [comment]
LGTM too 👍

**Pull request merged**
