### PR TITLE
[msbuild] Set NSAllowArbitraryLoads when debugging watchOS apps.

### PR DESCRIPTION
**Pull request by rolfbjarne**
The only way to have reliable http connections from the watchOS 2 device
to the mac is to set NSAllowArbitraryLoads.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@jstedfast can you review this?

@kzu @joj: FYI this PR adds a new msbuild task.

**Comment by rolfbjarne** [comment]
This PR is required first: https://github.com/xamarin/Xamarin.MacDev/pull/1

**Comment by rolfbjarne** [comment]
The failing test is unrelated to this commit.

**Comment by jstedfast** [comment]
Is the `IsWatchExtension && Debug` conditional really correct?

WatchExtensions for WatchOS1 and WatchOS2 are different, aren't they?

**Comment by rolfbjarne** [comment]
@jstedfast WatchOS1 is dying (Xcode 8 doesn't seem to support them), and in any case adding the key for WatchOS1 extensions won't hurt.

Also the `&& Debug` condition is because we'll only want this in debug builds (the `NSAllowArbitraryLoads` key will cause apps to fail App Store reviews).

**Comment by jstedfast** [comment]
Okay, now that I better understand what this is doing (thanks @rolf!), I can say that this patch looks good to me :)

👍

**Pull request merged**
