### PR TITLE
Enables CoreCompile target for WatchOS App projects

### PR DESCRIPTION
**Pull request by emaf**
The iOS Designer depends on Roslyn Workspace APIs to inspect and get notified of project changes, which needs CoreCompile target to work.

Fixes Bug #41766 (https://bugzilla.xamarin.com/show_bug.cgi?id=41766)

### CODE REVIEW

**Comment by spouliot** [comment]
for some reason Jenkins did not pick up that PR ?!? @duncanmak any clue why ?

build

**Comment by spouliot** [comment]
msbuild tests failed and
all watchos projects failed to build

**Comment by jstedfast** [comment]
This seems to be the error:

```
CSC: error CS2008: No files to compile were specified
```

**Comment by kzu** [comment]
Damn. xbuild fails with no @(Compile), MSBuild doesn't. 

While we wait for the day when MSBuild is the default, we'll add a workaround that includes an empty .cs via the targets.

**Comment by jstedfast** [comment]
Looks like things are working now, so I guess this patch looks ok but we'll need to make sure that it gets installed into the msbuild extensions directory.

Could we just autogenerate the .cs file in the MSBuild targets instead via a FileWrite instead? I think that might be a better approach... what do you guys think?

**Comment by kzu** [comment]
I think it's overkill @jstedfast, since it's a static file, never needs to be cleaned, and it lives alongside the .targets and tasks.

**Comment by jstedfast** [comment]
Okay, that's fine with me.

@rolfbjarne is there anything more that this patch will need in order for it to get installed alongside the targets and dll's?

**Pull request merged**
