### PR TITLE
[macos] Fix test failure in CertificateTest

### PR DESCRIPTION
**Pull request by chamons**
- SecCertificateCopyEmailAddresses behaves differently on macOS than iOS with
 macOS getting the "documented" behavior of returning an empty array and iOS
 returning null.
- Fix the test, as the time we could fix the API is long gone

### CODE REVIEW

**Comment by chamons** [comment]
I had trouble reproducing this locally in C# (wrote small sample in obj-c), so this is more of a blind fix that i'd like.

**Comment by chamons** [comment]
I'm looking into test failures. It appears my fix did not work as expected.

**Comment by chamons** [comment]
Turns out MONOTOUCH is _NOT_ defined when you open monotouch-test.sln for some configurations...

**Comment by chamons** [comment]
@spouliot Select wasn't broken but MONOTOUCH define was. That makes the XI test pass locally (waiting for bot).

**Comment by spouliot** [comment]
@chamons unit tests are _external_ code so `__IOS__` should always be defined - but then you have to consider `__TVOS__` and `__WATCHOS__` and IIRC (there's a bug for this) we don't have a `__MACOS__` yet to invert the condition.

**Comment by chamons** [comment]
Build failure this time is known:

https://bugzilla.xamarin.com/show_bug.cgi?id=52173

**Comment by rolfbjarne** [comment]
Another option is to just change the test to accept either null or 0.

Regarding `MONOTOUCH`: I understand it's inconsistent right now, but I'd rather remove it than use it more (since we have other defines that does the same thing: `__IOS__`, `__TVOS__`, `__WATCHOS__`), but that's really unrelated to what this PR is trying to fix.

**Comment by chamons** [comment]
Rolled back to just accepting 0 and null, reverting the MONOTOUCH changes.

**Pull request merged**
