### PR TITLE
[tests] Clean up Xamarin.MacDev.Tests.

### PR DESCRIPTION
**Pull request by rolfbjarne**
This is a pretty big refactoring, which:

* Always copies the test projects to a temporary directory before running any
 tests that use them.
* Runs all the tests using an out-of-process MSBuild instance.
* Logs to a binlog instead of writing text to stdout.
* Refactors all the code that used the MSBuild assemblies in memory to
  instead:
  * Tests that modified projects in memory now modifies them on disk
    instead. This won't affect the working copy because the tests are always
    working with a copy      of the test projects.
  * Tests that inspected projects in memory afterwards now parses the binlog
    to get the same information.
* Significantly simplified the code to setup the test projects for testing.

This PR is probably best reviewed commit-by-commit.

### CODE REVIEW

**Review by spouliot — APPROVED** [review]
❤️

**Review by tj-devel709 — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
Nice PR number btw ;)

**Comment by rolfbjarne** [comment]
> Nice PR number btw ;)

💯✖️💯😁

**Comment by rolfbjarne** [comment]
build

**Pull request merged**
