### PR TITLE
[test][intro] Check for API parameters that are [Model] and not the [Protocol] interface

### PR DESCRIPTION
**Pull request by spouliot**
- incomplete and will report error (not to be merged yet)

### CODE REVIEW

**Comment by spouliot** [comment]
build - just to make sure there's no additional failures

**Comment by rolfbjarne** [comment]
Random build failure due to bug #[50634](https://bugzilla.xamarin.com/show_bug.cgi?id=50634).

**Comment by rolfbjarne** [comment]
build

**Comment by spouliot** [comment]
link all (Failed; Succeeded; Ignored)
-iOS Unified 32-bits - simulator (Failed)
-> MT1008 -> https://bugzilla.xamarin.com/show_bug.cgi?id=50419

**Pull request merged**
