### PR TITLE
[d15-7][msbuild] Catch ArgumentException if IBToolTask fails to load plist output

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595179

### CODE REVIEW

**Comment by jstedfast** [comment]
This is a back-port of https://github.com/xamarin/xamarin-macios/pull/3905

**Comment by spouliot** [comment]
@jstedfast 15.7 is frozen. This will need justification to get merged this late.

**Comment by jstedfast** [comment]
Thats fine with me, I just submitted in case you deemed it needed for 15.7

**Comment by spouliot** [comment]
@jstedfast it's too late for 15.7 and this already happened in 15.6 (for Xcode 9.3) so most people will have run into this before it's released.

However it could happen for Xcode 9.4 too so could you backport it to `xcode9.4` ? thanks!

**Pull request closed without merging**
