### PR TITLE
Bump for Xcode 11 beta 2

### PR DESCRIPTION
**Pull request by VincentDondain**

### CODE REVIEW

**Comment by VincentDondain** [comment]
Mmh @rolfbjarne I don't know why the GitHub status wasn't updated but it looks like the build / tests completed: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10324//Test_20Report

Reviewing now.

**Comment by rolfbjarne** [comment]
> I don't know why the GitHub status wasn't updated

It looks updated to me (red), what do you see?

**Comment by VincentDondain** [comment]
Now I do... did I not hit refresh? 🤦‍♂

**Comment by VincentDondain** [comment]
1 known issue, 1 new

- https://github.com/xamarin/maccore/issues/1266
- https://github.com/xamarin/maccore/issues/1765

**Pull request merged**
