### PR TITLE
[msbuild] Fixed WatchOS1 WatchApp projects to define __WATCHOS__ instead of __IOS__

### PR DESCRIPTION
**Pull request by jstedfast**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
IMHO this is a breaking (and silent for customers) change, which may surprise them.

It's also only for a dying case (watchOS 1 apps), so I'm not sure it's worth it.

**Comment by jstedfast** [comment]
Yea, I had a similar thought after submitting it.

**Comment by spouliot** [comment]
A nice catch but I agreed with @rolfbjarne. Apple does not allow new watchOS 1.x / watchkit apps so it makes little sense to introduce a breaking change. Let this die _as is_ :)

**Comment by jstedfast** [comment]
Thanks for your thoughts, guys - branch deleted :)

**Pull request closed without merging**
