### PR TITLE
[xharness] Make monotouch-test (all optimization) aware of IncludesiOS32

### PR DESCRIPTION
**Pull request by spouliot**
Only happens on internal Jenkins
ref: https://github.com/xamarin/maccore/issues/2284

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@spouliot failures are due to https://github.com/xamarin/maccore/issues/2289

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9401/1/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9401/1/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9401/1//console)
✅ Packages: 
* [xamarin.ios-13.99.0.195.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/package/xamarin.ios-13.99.0.195.pkg)
* [xamarin.mac-6.99.0.195.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/package/xamarin.mac-6.99.0.195.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/a47f72b1cca79c377ca5de0e1a51d68766e9c74a/1/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 155 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 32-bits - simulator/Debug (all optimizations): TimedOut
 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9401/2/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9401/2/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9401/2//console)
✅ Packages: 
* [xamarin.ios-13.99.0.196.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/package/xamarin.ios-13.99.0.196.pkg)
* [xamarin.mac-6.99.0.196.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/package/xamarin.mac-6.99.0.196.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/ee2cd4c4a4e285714f496fe8876ec143fc4ee77f/2/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>2 tests failed, 155 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 32-bits - simulator/Debug (all optimizations): TimedOut
 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>

**Review by rolfbjarne — APPROVED** [review]

**Comment by xamarin-release-manager** [comment]
❌ [Build was (probably) aborted](https://jenkins.internalx.com/job/macios/job/PR-9401/3/display/redirect)

🔥 [Jenkins job](https://jenkins.internalx.com/job/macios/job/PR-9401/3/display/redirect) (on internal Jenkins) failed in stage(s) 'Test run, Test run' 🔥

✅ [Build succeeded](https://jenkins.internalx.com/job/macios/job/PR-9401/3//console)
✅ Packages: 
* [xamarin.ios-13.99.0.197.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/package/xamarin.ios-13.99.0.197.pkg)
* [xamarin.mac-6.99.0.197.pkg (Not notarized)](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/package/xamarin.mac-6.99.0.197.pkg)

✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/jenkins-results/apicomparison/api-diff.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/jenkins-results/generator-diff/index.html) (no change)
🔥 [Test run failed](http://xamarin-storage/jenkins/xamarin-macios/PR-9401/423f80b6abff02503fecc411a4485aff1074c771/3/jenkins-results/tests/index.html) 🔥

# Test results

<details>
<summary>1 tests failed, 155 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>

**Pull request merged**
