### PR TITLE
[XM] Add 32-bit variants of apitest and introspection and fix bindings

### PR DESCRIPTION
**Pull request by chamons**
- Previous to this we were only running 64-bit tests, which caused us
to make mistakes

### CODE REVIEW

**Comment by spouliot** [comment]
@chamons Build failed, no test output.

```
23:28:20 GEN      xharness.exe
23:28:21 Harness.cs(42,63): error CS0029: Cannot implicitly convert type `System.Collections.Generic.List<xharness.TestProject>' to `System.Collections.Generic.List<xharness.MacTestProject>'
```

**Comment by chamons** [comment]
Cherry pick failure. Fixing.

**Comment by chamons** [comment]
Looks like xharness/Jenkins.cs needs a patch.

**Comment by chamons** [comment]
Ok. Now only failure is a watch test timing out (I believe unrelated).

**Comment by chamons** [comment]
@rolfbjarne Could you review (in particular the xharness changes)?

**Comment by rolfbjarne** [comment]
@chamons it doesn't look like the 32-bit tests ran on Jenkins, imho that should be added too (also will the 32-bit tests run on Wrench as well? It's not obvious from the diff whether the new project will be added to Makefile-mac.inc or not).

**Comment by chamons** [comment]
@rolfbjarne it appears they are added to the makefile but not to the jenkins bits, so they run locally but not on bots.

Let me look at adding that.

In the wrench days, there wasn't such a difference in how things are run, I didn't think to check.

**Comment by rolfbjarne** [comment]
That ended up grouping the tests strangely:

* apitest
* apitest-un
* dontlink-mac
* dontlink-mac-un
* introspection-mac
* introspection-mac-un

**Comment by chamons** [comment]
Closer but not still right:

:08:08 Unexpected exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Sharing violation on path /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/jenkins-results/tests/apitest/build-Mac_Unified.txt
19:08:08   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00335] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.IO/FileStream.cs:282 
19:08:08   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.IO/FileStream.cs:91 
19:08:08   at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
19:08:08   at xharness.LogStream..ctor (System.String description, System.String path) [0x00014] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/Log.cs:147 
19:08:08   at (wrapper remoting-invoke-with-check) xharness.LogStream:.ctor (string,string)
19:08:08   at xharness.Logs.CreateStream (System.String directory, System.String filename, System.String name) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/Log.cs:184 

Jenkins is doing it's own logging thing...

**Comment by chamons** [comment]
@rolfbjarne Think it looks right on Jenkins finally. Thoughts?

**Comment by rolfbjarne** [comment]
👍

**Pull request merged**
